### ISSUE TITLE
Hacker news verification fails with keybase verification

### ISSUE THREAD

**Issue by jdkanani** [blockstack/blockstack-browser#1000]
I have already keybase verification on hacker-news.

**Comment by yknl** [comment]
@jdkanani Can you provide more detail on this? Blockstack's social proof verifications are independent of Keybase verifications.

**Comment by jdkanani** [comment]
@yknl how to get code again? I lost it!

**Comment by yknl** [comment]
@jdkanani you can click on the Edit button on the top left corner of the profile page and then click on the hacker news proof to see the instructions and code again.

**Comment by jdkanani** [comment]
@yknl I think YC takes sometime to update profile page. I will for a bit and check if it's working.

**Comment by jdkanani** [comment]
It takes sometime to work. Thanks!
