### ISSUE TITLE
Log in to empty screen / Gaia Hub issue

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1001]
Log in to empty screen / Gaia Hub issue

@yknl and I discussed this issue on last Friday evening's UX/UI meeting.

When I open the browser for the first time I see the Log in with Gaia Storage pop-up window, I click the window and enter into the browser and land on, what appears to be, a completely blank white screen upon first glance. Then I notice that I am on Settings and that there is navigation.

I feel this is a major issue that must be resolved before users visit the browser.

I have sent @larrysalibra my console log via email.

Screen shot
<img width="1439" alt="screenshot 2017-10-31 06 34 01" src="https://user-images.githubusercontent.com/1711854/32220429-0b6441ae-be08-11e7-8cc4-d874d4b0083d.png">

**Comment by guylepage3** [comment]
@yknl can you please follow up my issue and write more specific details as discussed last Friday evening during our UX/UI meeting. Thank you sir.

**Comment by larrysalibra** [comment]
The blockstack core node either crashed or hasn't started:
```
console.js:8 2017-10-31T06:33:31.442-0400 DEBUG utils/api-utils.js: setCoreStorageConfig: profileSigningKeypair passed? true
console.js:8 2017-10-31T06:33:31.442-0400 DEBUG utils/api-utils.js: setCoreStorageConfig: POSTing to http://localhost:6270/v1/node/drivers/storage/gaia_hub?index=1
:6270/v1/node/ping Failed to load resource: net::ERR_CONNECTION_REFUSED
console.js:8 2017-10-31T06:33:33.454-0400 ERROR utils/api-utils.js: isCoreApiRunning: problem checking http://localhost:6270/v1/node/ping [TypeError: Failed to fetch]
TypeError: Failed to fetch
:6270/v1/wallet/payment_address Failed to load resource: net::ERR_CONNECTION_REFUSED
console.js:8 2017-10-31T06:33:33.464-0400 ERROR utils/api-utils.js: isApiPasswordValid: problem checking http://localhost:6270/v1/wallet/payment_address [TypeError: Failed to fetch]
TypeError: Failed to fetch
console.js:8 2017-10-31T06:33:33.464-0400 DEBUG store/sanity/actions.js: isCoreApiPasswordValid? No!
:6270/v1/node/drivers/storage/gaia_hub?index=1 Failed to load resource: net::ERR_CONNECTION_REFUSED
storage#gaiahub:1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by guylepage3** [comment]
Yeah. That's what @yknl and I discovered and why I mentioned we should have a "Gaia Hub" status widget within the browser so that the user knows when Gaia is not running. But I believe you mentioned somewhere that it's quite difficult to execute this.

**Comment by larrysalibra** [comment]
We've removed core as a requirement for storage so this issue shouldn't happen again. Thanks for reporting @guylepage3 !
