### ISSUE TITLE
The global full width container class has max-width definition

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1002]
The global full width container class has max-width definition. 

`.container` and `.container-fluid` are classes that are to be used consistently within almost all container sets with the exception of columns. http://getbootstrap.com/docs/4.0/layout/overview/

Need to restructure the app so that all pages are utilizing one of the Frameworks variable Grid Container widths.

**Comment by wbobeirne** [comment]
Pretty sure this is no longer an issue.
