### ISSUE TITLE
Add active descriptions to profile completion bar

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1007]
@larrysalibra @yknl we should have “active descriptions” for the profile completion bar
I’m never going to read that sentence below the progress bar

<img width="1438" alt="screenshot 2017-10-31 10 51 04" src="https://user-images.githubusercontent.com/1711854/32230761-3ebf2204-be2a-11e7-9c26-b567e1563a1c.png">

**Comment by wbobeirne** [comment]
Closing as stale.
