### ISSUE TITLE
Linux start script fails with "sensible-browser: command not found"

### ISSUE THREAD

**Issue by skddc** [blockstack/blockstack-browser#1008]
I just downloaded the Linux install/start script from https://blockstack.org/install and ran `pull` and `start`. However, the `sensible-browser` command in that script doesn't exist. It looks to me like there's supposed to be a function with that name, which is missing.

**Comment by dantrevino** [comment]
The easiest thing to do to fix this is 
`sudo apt install sensible-utils`

Assuming you have a browser installed, the script should find your default

**Comment by skddc** [comment]
Thanks.

I'm wondering why it's not just using [xdg-open](https://linux.die.net/man/1/xdg-open) then, same as the protocol handler that is registered in the same script.

**Comment by bjorn** [comment]
On Arch Linux, `sensible-utils` is located in AUR, so you could do for example:
```
yaourt -S sensible-utils
export BROWSER=chromium
```
Before running the start script.

But I agree with @skddc that it would be preferable to use `xdg-open` for opening a URL, which should be available much more widely than `sensible-browser`.

**Comment by sean9999** [comment]
and fedora:

    dnf install sensible-utils
