### ISSUE TITLE
On restore, blockstack IDs show up as incomplete until first refresh

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1009]
We should have some sort of "loading" indicator or message until the first run of "refreshIdentities" completes and the browser determines whether or not the address owns a name, has a profile and has verified identities.

This should happen on both account restore and creating a new blockstack id (because they could potentially already have profiles/names)

**Comment by john-light** [comment]
Does "refreshIdentities" automatically cycle through the keychain to see if any of the addresses own IDs? Right now I have to manually "brute force" and create new IDs in order to find additional IDs my keychain owns each time I open the browser.

**Comment by larrysalibra** [comment]
> Does "refreshIdentities" automatically cycle through the keychain to see if any of the addresses own IDs? Right now I have to manually "brute force" and create new IDs in order to find additional IDs my keychain owns each time I open the browser.

No, it doesn't. This is something we need to implement in the restore process. We don't store the keychain phrase (master secret) in plaintext, so to implement this is `refreshIdentities`, we'd have to prompt users for their password to decrypt the secret each time.

Here's the issue for improving the restore process: https://github.com/blockstack/blockstack-browser/issues/729

**Comment by wbobeirne** [comment]
The original issue has been resolved by #1576. The other issue mentioned is tracked in #1550 now.
