### ISSUE TITLE
On restore, first of two IDs not populating

### ISSUE THREAD

**Issue by delitzer** [blockstack/blockstack-browser#1012]
Installed the browser (0.20.0) on my personal laptop last night and went through the steps to transfer over my ID (delitzer) from OneName. I then added proofs for Twitter, Facebook, LinkedIn, and Github, and added a name and photo. I then also set up a new ID (elitzer).

Today, upgraded from 0.19.1 to 0.20.0 on my work laptop. I recovered the keychain. None of the proofs show up in my browser, despite being visible in the JSON file (https://gaia.blockstack.org/hub/1L71gYNAppuX5qQzAEvwA5CbUcAsR3oACx/0/profile.json).

**Comment by kantai** [comment]
Hi @delitzer, thanks for raising this issue!

The latest release (v0.20.1) should address this issue. Let us know if you're still having problems with the restore functionality.

**Comment by delitzer** [comment]
Nope, it did not address the issue. I just installed the latest version,
rebooted, and I'm still not seeing any of my proofs or even my primary ID
connected.

**Comment by wbobeirne** [comment]
Closing as stale. Please feel free to re-open if this is still a reproducible issue.
