### ISSUE TITLE
MAJOR: Refreshing my browser requires new sign up in browser

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1014]
MAJOR: Refreshing my browser requires new sign up in browser.

With no username registered, I was on my profile, 40% filled out, name and bio, and then i verified my twitter account. and then refreshed my browser on the profile page seconds after verifying twitter and the register popup appeared. [image below]

<img width="1439" alt="screenshot 2017-11-01 15 08 01" src="https://user-images.githubusercontent.com/1711854/32292862-c1fd7498-bf17-11e7-829e-a7e8c6971084.png">

**Comment by john-light** [comment]
I cannot reproduce this error in the Linux 0.21.1 Blockstack Browser. I am only asked to reenter my wallet seed or create a new wallet when I restart the browser, but not on refresh.

**Comment by guylepage3** [comment]
Closing this issue as it was resolved in previous build. 

@john-light feel free to open another issue for your refresh issue.
