### ISSUE TITLE
Should not be able to verify any social accounts' Blockstack ID without a username

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1015]
Should not be able to verify any social accounts' Blockstack ID without a username

<img width="653" alt="screenshot 2017-11-01 15 19 20" src="https://user-images.githubusercontent.com/1711854/32292962-0e7719c8-bf18-11e7-9329-46ba447b2b52.png">

**Comment by yknl** [comment]
I think we decided to allow verifications without usernames. If not please let me know.
