### ISSUE TITLE
Duplicate when creating new ID

### ISSUE THREAD

**Issue by xanbots** [blockstack/blockstack-browser#1016]
Went to create a new ID, generated 2 copies of the same profile

<img width="1116" alt="screen shot 2017-11-01 at 3 38 37 pm" src="https://user-images.githubusercontent.com/31934541/32293904-f5956790-bf1a-11e7-8421-0554aee81e1d.png">

**Comment by guylepage3** [comment]
@xanbots is this the latest browser?

**Comment by xanbots** [comment]
@guylepage3 not sure but it was fixed when I went to the browser today and I wasn't able to replicate. Going to close this out.
