### ISSUE TITLE
Facebook Social Verification failing

### ISSUE THREAD

**Issue by xanbots** [blockstack/blockstack-browser#1017]
Information I have entered in the Blockstack browser to verify identity via my Facebook account has been reviewed by 2 other people and is 100% correct, but it remains "unverified".  A number of other users are also reporting this issue.

**Comment by yknl** [comment]
@xanbots Any chance you can send me the links to some of the proof posts that are failing?

**Comment by xanbots** [comment]
@yknl absolutely - link to post: https://www.facebook.com/xan.ditkoff/posts/10210399256322262

**Comment by yknl** [comment]
@xanbots looks like the verification message isn't in the Facebook post for your specific case. You need to paste the verification message in the body of the post.

**Comment by xanbots** [comment]
@yknl thank you that worked. We may want to make it more clear the message needs to be copied and pasted in the post in addition to what is auto-generated. I thought the "card" the browser generates on facebook when you click on "Post Verification on Facebook" was all that was needed.  Thanks!

**Comment by xanbots** [comment]
Accidentally closed the issue - but updating the copy is definitely necessary. Getting a lot of support requests around this.

**Comment by jcnelson** [comment]
I also have a few users reporting this.

**Comment by cryptocracy** [comment]
This happened to me too.
I had to edit the FB post and include the snipped of text that read as follows (you can copy it from the Copy Option in the Blockstack Browser)
`Verifying my Blockstack ID is secured with the address YOURADDRESS`
Once I did that I was able to get it to verify.
