### ISSUE TITLE
How to stop Localhost service on Windows

### ISSUE THREAD

**Issue by tkemmere** [blockstack/blockstack-browser#1018]
Hi,
I know I could 'kill' the Blockstack-localhost-service using the taskmanager if I'd want to stop it, to free up PC resources.
But is there an official way to do this? I see no end service button in the browser. Right-clicking the shortcut on my desktop makes no sense, neither would it in the start-menu.
Thanks. Thomas.

**Comment by kantai** [comment]
Hi -- there should be a taskbar icon for Blockstack. Windows can sometimes hide ones which don't pop notifications up frequently. But if you right click on that and select "Exit", it will close the service.

**Comment by tkemmere** [comment]
Indeed! Working. Why did I overlook that? Thanks.
