### ISSUE TITLE
allow users to export their backup phrase

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#102]
Would be nice to have an "export back up phrase" button where the user clicks the button chooses the location to save a plain text file with their back up phrase saved into the file.

**Comment by shea256** [comment]
I'm thinking this could either be a .txt file or a .pdf file. The latter would only make sense if we could do it quickly. We could potentially use this: https://github.com/MrRio/jsPDF.

I'm also thinking that we should give the user the following options:

- Download the file
- Print the file
- Write down the passphrase

**Comment by larrysalibra** [comment]
@shea256 I'm concerned that making it easy to download their unencrypted backup phrase is a bad idea. We should nudge them to write it down (on paper or in a password manager) or make it easy for them to print it (i'm not one of those people terribly worried about my printer stealing my blockstack name.

A downloaded file should have the backup phrase encrypted with the user's password (like the onename backup files). I see issue #371 as the solution for that. Thoughts?

**Comment by larrysalibra** [comment]
<img width="344" alt="screen shot 2017-04-20 at 6 17 43 pm" src="https://cloud.githubusercontent.com/assets/597182/25247057/46f1b5c6-263c-11e7-8f67-e5cd2267a83b.png">

@shea256 @guylepage3 1password's backup process is pretty slick

**Comment by guylepage3** [comment]
yeah. it was a great exp for sure.. simple and clean but yet made me pay attention and go through all the steps.

**Comment by guylepage3** [comment]
Notification banner on dashboard to let the user know to download phrase

**Comment by larrysalibra** [comment]
We have an email backup feature and the ability to display the backup phrase.
