### ISSUE TITLE
Trust level right now looks like a button

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1022]
Trust level right now looks like a button. I keep trying to click on it.
<img width="372" alt="screenshot 2017-11-02 14 21 27" src="https://user-images.githubusercontent.com/1711854/32343212-20ce1150-bfd9-11e7-8699-f9a77679d374.png">

**Comment by yknl** [comment]
This issue is duplicated at https://github.com/blockstack/blockstack-browser/issues/1032
