### ISSUE TITLE
Unable to install on OSX El Capitan

### ISSUE THREAD

**Issue by ekkis** [blockstack/blockstack-browser#1026]
I'm not sure I'm posting in the right place.  if there's a better place please advise.

I visited this site: https://blockstack.org/install downloaded the app on my 10.11.6 OSX notebook and found out I cannot install it.  when I open the .dmg, the icon for the app has a X across it and it won't dump into the apps folder

I need to transfer my OneName ID but am unable to do so as I need to install the Blockstack browser first.  please help

**Comment by larrysalibra** [comment]
Sorry about taking so long to get back. Blockstack for macOS only support Sierra 10.12 and higher.
