### ISSUE TITLE
Add checkbox to prevent popup upon quit from happening

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1029]
Add checkbox to prevent popup upon quit from happening as it is quite annoying that when I quit the app I keep getting a popup in my face that is a macOS standard popup.

<img width="492" alt="screenshot 2017-11-03 11 58 05" src="https://user-images.githubusercontent.com/1711854/32383595-caf35856-c08e-11e7-99e3-66aba03ba7a7.png">

I would like to have the option to turn this off by clicking a checkbox in the popup that says, "Prevent this popup from appearing. You can turn this back on by going into your advanced settings"

Then of course adding the ability to turn the popup back on in the advanced settings of the app.

**Comment by guylepage3** [comment]
Which brings me to my next big issue... https://github.com/blockstack/blockstack-browser/issues/1030

**Comment by larrysalibra** [comment]
This is what fantastical does:

<img width="426" alt="screen shot 2018-01-17 at 7 30 40 pm" src="https://user-images.githubusercontent.com/597182/35044556-cf57f3b6-fbcb-11e7-99b6-53bd145c4d2b.png">
