### ISSUE TITLE
Trust Level UI improvement

### ISSUE THREAD

**Issue by kkomaz** [blockstack/blockstack-browser#1031]
At the moment, the trust level on the profile page looks like a button.  Since it looks like a button, I have a natural tendency to want to click it.  Need to figure out a better way to display the trust level without the perception of a button

ID page: (Trust Level is not a Button)
<img width="498" alt="screenshot of google chrome 11-3-17 1-04-24 pm" src="https://user-images.githubusercontent.com/8473884/32386421-85de0c26-c097-11e7-913e-a9a2eddf169a.png">

Wallet Page: (Receive and Send are buttons)

<img width="736" alt="screenshot of google chrome 11-3-17 1-04-39 pm" src="https://user-images.githubusercontent.com/8473884/32386444-9db317d8-c097-11e7-827f-6b4233c7c4c3.png">

**Comment by guylepage3** [comment]
Well first off. let's start on one view port first as there are a lot of goals we need to accomplish on just the one. Closing this issue and moving it over to a more focused item here: https://github.com/blockstack/blockstack-browser/issues/1032
