### ISSUE TITLE
Facebook Verification Steps 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-browser#1037]
Hey @yknl can we make the browser facebook verification instructions as clear as the onename facebook verification instructions? Think these relay the exact steps to user, and would pretty much eliminate need for FAQ 😄 

<img width="297" alt="screen shot 2017-11-06 at 6 56 06 pm" src="https://user-images.githubusercontent.com/30627583/32470155-385ccd18-c324-11e7-9759-bcbadce8cf73.png">

**Comment by GinaAbrams** [comment]
@yknl if you want to chat about this at all, I'm happy to help 😄

**Comment by yknl** [comment]
![image](https://user-images.githubusercontent.com/29081231/32507699-37474466-c3b6-11e7-9d3e-7d2eb17b3f60.png)

**Comment by GinaAbrams** [comment]
nice this looks great!!!

**Comment by guylepage3** [comment]
Feedback from users.... Shouldn't Step 3 & 4 be before Step 2?
