### ISSUE TITLE
Produce new icons for home screen

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1041]
Produce new icons for home screen

https://paper.dropbox.com/doc/New-Apps-tcYCn6TDqRwzFcx2yApm8

Pinning.. 
- https://github.com/blockstack/blockstack-browser/issues/896
- https://github.com/blockstack/blockstack-browser/issues/934

**Comment by guylepage3** [comment]
Postly
www.postly.co/blockstack

![image](https://user-images.githubusercontent.com/1711854/32515208-6fa5ea12-c3cd-11e7-9872-18ffac3782e6.png)

**Comment by guylepage3** [comment]
Arenaplay
https://www.arenaplay.io/start

![image](https://user-images.githubusercontent.com/1711854/32515216-7a86ca64-c3cd-11e7-8725-aa3344edba42.png)

**Comment by guylepage3** [comment]
AMGiving
http://amgiving.io/

![image](https://user-images.githubusercontent.com/1711854/32515229-84b70ba2-c3cd-11e7-8723-c395d22c355a.png)

**Comment by guylepage3** [comment]
Symmitree
https://www.symmitree.com/

![image](https://user-images.githubusercontent.com/1711854/32515242-8fdf9918-c3cd-11e7-8ad3-ecc5b02a6b73.png)

**Comment by guylepage3** [comment]
Eder
www.eder.io

![image](https://user-images.githubusercontent.com/1711854/32515259-9ae2fdaa-c3cd-11e7-8c2a-33d703170fa1.png)

**Comment by guylepage3** [comment]
@xanbots, Does this app have a name and URL?

![image](https://user-images.githubusercontent.com/1711854/32515271-a4084a0c-c3cd-11e7-84d4-6183542870ee.png)

**Comment by xanbots** [comment]
@guylepage3 Name should just be "Encrypted Token Portfolio Bounty" - and Landing page should be the eventbrite for the bounty: https://tokenportfolio.eventbrite.com

**Comment by guylepage3** [comment]
thank you sir. 👍

**Comment by guylepage3** [comment]
@xanbots, the arenaplay logo is not legible. I cannot read the word mark with white on white. Can we ask them for a legible icon?
https://github.com/blockstack/blockstack-browser/issues/1041#issuecomment-342606239

**Comment by xanbots** [comment]
@guylepage3 Just pinged their team, will update when they send me new logo. Thanks.

**Comment by xanbots** [comment]
@guylepage3 here you go: 
![arenaplaylogo 2](https://user-images.githubusercontent.com/31934541/32517942-138bca54-c3d6-11e7-9ca0-4ee705d317f0.png)

**Comment by guylepage3** [comment]
thank you sir

**Comment by guylepage3** [comment]
>@guylepage3 Name should just be "Encrypted Token Portfolio Bounty" - and Landing page should be the eventbrite for the bounty: https://tokenportfolio.eventbrite.com

We will need the title of the app to have less than 14 characters in length or the name will be cutoff.

**Comment by xanbots** [comment]
@guylepage3 
![logo-6-square-corners](https://user-images.githubusercontent.com/31934541/32522352-f6966724-c3e4-11e7-8236-151aa22a23c0.png)

**Comment by xanbots** [comment]
@guylepage3 for name, can we do "Portfolio Bounty"? Spoke w/ Patrick and it's the shortest that makes sense

**Comment by guylepage3** [comment]
![app-icon-amgiving](https://user-images.githubusercontent.com/1711854/32522727-7b7b5674-c3e6-11e7-9df1-d4ac733cbbe0.png)
![app-icon-arenaplay](https://user-images.githubusercontent.com/1711854/32522728-7b8ac726-c3e6-11e7-9e96-39e1a24d2dab.png)
![app-icon-eder](https://user-images.githubusercontent.com/1711854/32522729-7b97d240-c3e6-11e7-9667-1723fa5d6f92.png)
![app-icon-portfolio-bounty](https://user-images.githubusercontent.com/1711854/32522730-7ba3fa34-c3e6-11e7-984c-a3c99541770b.png)
![app-icon-postly](https://user-images.githubusercontent.com/1711854/32522731-7bae450c-c3e6-11e7-83a0-85c8f4265a3f.png)
![app-icon-symmitree](https://user-images.githubusercontent.com/1711854/32522732-7bbd4390-c3e6-11e7-9452-a852fe1e760e.png)

**Comment by guylepage3** [comment]
Adding Souq to this list as well

**Comment by guylepage3** [comment]
Souq
http://beta.cryptocracy.io
![image](https://user-images.githubusercontent.com/1711854/32528227-eaf322a2-c3ff-11e7-8a25-9efccc666c6e.png)

**Comment by guylepage3** [comment]
Reference: [#896: Add Studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)

Studbits
