### ISSUE TITLE
Add 7 new apps to Home Screen

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1042]
Reference: [#1041: Produce new icons for home screen](https://github.com/blockstack/blockstack-browser/issues/1041)

----

Add 7 new apps to Home Screen.
- [x] Postly [[app icon]](https://user-images.githubusercontent.com/1711854/32522731-7bae450c-c3e6-11e7-83a0-85c8f4265a3f.png) – [postly.co/blockstack](http://postly.co/blockstack)
- [x] Arenaplay [[app icon]](https://user-images.githubusercontent.com/1711854/32522728-7b8ac726-c3e6-11e7-9e96-39e1a24d2dab.png) – [arenaplay.io/start](https://arenaplay.io/start)
- [x] AMGiving [[app icon]](https://user-images.githubusercontent.com/1711854/32522727-7b7b5674-c3e6-11e7-9df1-d4ac733cbbe0.png) – [amgiving.io](http://amgiving.io)
- [x] Symmitree [[app icon]](https://user-images.githubusercontent.com/1711854/32522732-7bbd4390-c3e6-11e7-9452-a852fe1e760e.png) – [symmitree.com](http://symmitree.com)
- [x] Eder [[app icon]](https://user-images.githubusercontent.com/1711854/32522729-7b97d240-c3e6-11e7-9667-1723fa5d6f92.png) – [eder.io](http://eder.io)
- [x] Portfolio Bounty [[app icon]](https://user-images.githubusercontent.com/1711854/32522730-7ba3fa34-c3e6-11e7-984c-a3c99541770b.png) – [tokenportfolio.eventbrite.com](https://tokenportfolio.eventbrite.com)
- [x] Souq [[app icon]](https://user-images.githubusercontent.com/1711854/32528468-3007c716-c401-11e7-84e1-d9a57d4ea570.png) – [beta.cryptocracy.io](http://beta.cryptocracy.io)

**Comment by guylepage3** [comment]
@xanbots, we will need the following data on each app in order to add them to the home screen.

We just need the info for each app with the prefix `example_`

```
   {
      name: 'example_DotPodcast',
      displayName: 'example_DotPodcast',
      description: 'example_A software lab for podcasts and blockchains.',
      version: 'example_1.0.0',
      appIcon: {
        small: '',
        large: ''
      },
      website: '',
      launchLink: '',
      developer: 'example_DotPodcast',
      status: ''
    }
```

**Comment by xanbots** [comment]
@guylepage3 for the version you can use 1.0.0 for all of them. Rest of the info is below.

**Postly**
displayName:  'example_Postly',
description:  'example_The best way to share and discover content with friends.',

**Arenaplay**
displayName:  'example_Arenaplay',
description:  'Games where players' time is valued.',

**AMgiving**
displayName:  'example_AMgiving',
description:  'example_Creating transparency in charitable giving.',

**Symmitree**
displayName:  'example_Symmitree',
description:  'example_Providing free connectivity to the displaced and deprived.',

**Eder**
displayName:  'example_Eder',
description:  'example_A decentralized stash for your personal data.',

**Portfolio Bounty**
displayName:  'example_Portfolio Bounty',
description:  'example_https://tokenportfolio.eventbrite.com.',

**Souq**
displayName:  'example_Souq',
description:  'example_Project Management Platform.',

**Comment by guylepage3** [comment]
thank you very much sir.

**Comment by guylepage3** [comment]
complete
