### ISSUE TITLE
Browser repeatedly tries to upload photo

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#1047]
This is causing a number of issues for users uploading photos. Tagging @larrysalibra @kantai and @yknl for more info here

**Comment by dhealy05** [comment]
when changing my photo, new photo was not displayed until refresh, when it was displayed upside down

**Comment by larrysalibra** [comment]
@jackzampolin can you explain this issue and provide steps to reproduce?

**Comment by wbobeirne** [comment]
Closing as stale.
