### ISSUE TITLE
Blockstack IDs without a Name attached do not properly restore

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#1053]
If you create a keychain and do verifications on an ID and then clear `localStroage`, when you restore from your keychain phrase the verifications disappear.

As a user I would like to be able to restore a Blockstack ID and be able to see all of the verifications I did earlier.

**Comment by kantai** [comment]
Verifications disappear, or the whole profile disappears?

Are they on the latest few versions?

**Comment by jackzampolin** [comment]
I'll gather some more info and post it here
