### ISSUE TITLE
macOS bundles old Core version.

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1054]
It looks like the macOS app is running with `blockstack 0.17.0.9` off of pip.

However, the latest blockstack-core version is `0.17.0.11` which includes some hotfixes over `.09`, in particular, it defaults to turning off pre-fetching of zonefiles for subdomain parsing.

**Comment by larrysalibra** [comment]
We'll use 0.17.0.11 in the next release.
