### ISSUE TITLE
Wallet balance doesn't accurately reflect money committed to registrations

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1074]
Wallet balance shows money that will need to be used for registration transactions as part of the available balance. This is confusing for people who are trying to use up all of their money by registering multiple names. What happens is people try to keep registering names until their balance is used up not realizing that this will cause name registrations operations to silently fail.

**Comment by wbobeirne** [comment]
We have a warning about this now when a registration is still processing.
