### ISSUE TITLE
Blank email crashes API

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#108]
Leaving email blank when creating an account shows "Email already taken" and `503` application error on the registration end point.

<img width="658" alt="screen shot 2016-11-11 at 11 37 39 am" src="https://cloud.githubusercontent.com/assets/597182/20203775/3957b0ec-a805-11e6-9354-4894fc9ab21b.png">

<img width="864" alt="screen shot 2016-11-11 at 11 49 26 am" src="https://cloud.githubusercontent.com/assets/597182/20203742/f3f4ede4-a804-11e6-84fc-949bbef09dad.png">

I'm not able to replicate the API error - after responding `503` several times, it starts to respond `403` with the JSON error message of type `email_taken`.

<img width="757" alt="screen shot 2016-11-11 at 11 55 34 am" src="https://cloud.githubusercontent.com/assets/597182/20203862/d5aa1958-a805-11e6-88bd-632a6beeb959.png">

**Comment by shea256** [comment]
This interface is obsolete. Closing the issue.
