### ISSUE TITLE
No visual indicator on restore from backup phrase

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1082]
When you restore from backup phrase, the button that performs the actual restore doesn't provide any indication once you've clicked it that things are happening.

![restore-keychain](https://user-images.githubusercontent.com/1153552/33038919-42cacf1c-ce04-11e7-9684-364331c15c5f.png)

The encryption that is occurring there takes a couple of seconds on my computer, and it's a recent computer. Older machines and mobile devices will take longer.

**Comment by guylepage3** [comment]
Great catch @kantai 

@yknl let's just dim out the button to `background-color: #60B0FF;` and add a progress underline that has a `heght: 6px;`. see example below..

<img width="454" alt="screenshot 2017-11-22 15 55 57" src="https://user-images.githubusercontent.com/1711854/33149440-c0a34d52-cf9d-11e7-8670-336c279c5d69.png">

**Comment by yknl** [comment]
@guylepage3 I already pushed out a fix for this on the latest browser release. It's the same as the visual feedback we have when creating a new keychain.

![image](https://user-images.githubusercontent.com/29081231/33149664-89988bc8-cf9e-11e7-9534-da5ac79392d9.png)

**Comment by guylepage3** [comment]
That works @yknl but I do really like it when an app provides me with a visual progress bar. GoDaddy does something quite nice as well. 

<img width="494" alt="screenshot 2017-11-22 16 14 28" src="https://user-images.githubusercontent.com/1711854/33150144-3f3c666a-cfa0-11e7-99a0-221216c729b9.png">

**Comment by guylepage3** [comment]
I personally do not feel that an ellipsis is enough of an indicator that something is going on.

**Comment by larrysalibra** [comment]
@guylepage3 
The method @yknl implemented is how we've been handling buttons that we don't want to be clicked twice.

We can iterate on these later and improve them in a later sprint. I like your button with progress bar built in idea!

**Comment by larrysalibra** [comment]
I made an issue to improve "in progress" indication on buttons https://github.com/blockstack/blockstack-browser/issues/1098
