### ISSUE TITLE
Linux Install Instruction Improvements

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-browser#1083]
Not sure if this is too broad of an issue - feel free to close. Wanted to track sprint deliverables.

**Comment by jackzampolin** [comment]
There is already an issue for this

**Comment by jackzampolin** [comment]
https://github.com/blockstack/blockstack-browser/issues/1080

**Comment by GinaAbrams** [comment]
thanks @jackzampolin closing! 🙏
