### ISSUE TITLE
Re-enable zone file updates & transfers

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-browser#1086]

**Comment by jackzampolin** [comment]
There is already an issue for this https://github.com/blockstack/blockstack-browser/issues/1051

**Comment by larrysalibra** [comment]
There’s also another issue for this: https://github.com/blockstack/blockstack-browser/issues/845#issuecomment-345955245

**Comment by larrysalibra** [comment]
This should wait until we have in browser transaction generation.

**Comment by mjstroh** [comment]
I am also having this issue: refer to https://github.com/blockstack/blockstack-browser/issues/1178
