### ISSUE TITLE
Wallet form text disappears on blur

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1088]
<img width="774" alt="screen shot 2017-11-21 at 11 29 21 pm" src="https://user-images.githubusercontent.com/597182/33080756-d26d6692-cf13-11e7-9179-cebe8329fdc7.png">

**Comment by larrysalibra** [comment]
I've made a quick change to the color so that wallet is usable in the v0.21.3 release.

<img width="746" alt="screen shot 2017-11-24 at 12 41 29 am" src="https://user-images.githubusercontent.com/597182/33182790-47adc56c-d0b0-11e7-82c2-30ffedf1b80a.png">

**Comment by wbobeirne** [comment]
Can't reproduce.
