### ISSUE TITLE
Error messages break page style

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#109]
When error message displays, text at the bottom of the sign up page is pushed over a white background making it partially unreadable.

See circled area in screenshot:

<img width="786" alt="screen shot 2016-11-11 at 11 59 22 am" src="https://cloud.githubusercontent.com/assets/597182/20203960/8b220c8c-a806-11e6-9524-4b55d057f7b3.png">

**Comment by shea256** [comment]
No longer relevant, closing.
