### ISSUE TITLE
Add warning/explainer with checkbox during name purchase

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1090]
We need to make it clear to users that they are burning bitcoin and racing other users to buy names. They're not buying names from Blockstack PBC or any other entity (this is decentralized after all!)

Let's do this by adding this language with a checkbox to the name registration process:

Proposed language:
```
I understand by registering a name:
* I am racing other users to register this name by burning bitcoin
* If someone registers the name before me, the bitcoin my computer has burnt in this process will still be gone.  
* No bitcoin from this process goes to Blockstack PBC or any other entity.
```

Feel free to improve on this language.

Any pull request for this issue should have corresponding tests.

**Comment by larrysalibra** [comment]
@jackzampolin we have another issue about sending both of those transactions at the same time: https://github.com/blockstack/blockstack-browser/issues/1091

**Comment by kantai** [comment]
My feelings on this are that we should separate our treatment of this into solving two different problems

1. Informing users of the risks of registration (it's a race, and someone can win, and the loser has still burnt bitcoin) and the process (_your_ computer is doing 2 bitcoin transactions with addresses _you_ control, the burnt bitcoin doesn't go to us)

2. Usage agreement - This is a usage policy that seems to be tied to liability for use of the software. this is a legal decision (that probably interacts with software licensing), that I think should probably be consulted with lawyers before we add a lot of legal text to user's interaction with the product.

**Comment by larrysalibra** [comment]
+1 on @kantai 's analysis. particularly consulting lawyers.

**Comment by jackzampolin** [comment]
I would like to +1 this as well. Both of these things need to be done. It will give users more understanding of how the system works (a good thing) and also will give us a firm policy on these type of issues which makes answering queries about it very simple.

**Comment by larrysalibra** [comment]
I updated the issue with some proposed language.

**Comment by vsund** [comment]
Do we still have preorder transactions to circumvent hijacking claim transactions? The message sounds like other people can also claim your name while registering it.

I didn't look over the new claiming process (with only one transaction), but we still have some technique in place to make sure nobody can listen to transactions and also claim these names, right?

Not really sure whether we should expose all this technical stuff to consumers, but wanted to bring this up though. Should we say that nobody can claim your name when you first claimed it?

**Comment by larrysalibra** [comment]
> Do we still have preorder transactions to circumvent hijacking claim transactions? 
Yes we do.

> The message sounds like other people can also claim your name while registering it.
If someone starts registering the same name at around the same time as you, they can get the name first. We've already seen this happen a few times in the real world. Our goal is to better manage user expectations.

**Comment by larrysalibra** [comment]
Would like some feedback on these changes - particularly the wording:

After selecting a name to register the next screen is this:
<img width="660" alt="screen shot 2017-12-22 at 8 31 21 pm" src="https://user-images.githubusercontent.com/597182/34298135-1da1696e-e757-11e7-9de1-b109d0c71ae4.png">

Followed by this: (note "request registration")
<img width="668" alt="screen shot 2017-12-22 at 8 31 28 pm" src="https://user-images.githubusercontent.com/597182/34298136-20533444-e757-11e7-8d0f-307f41e83a2d.png">

**Comment by shea256** [comment]
@larrysalibra The headline "Hope nobody beats you to it!" seems a bit strange. I would just cut that out.

Can we have more context in terms of the sequence of screens? What's the screen that is shown before these two screens?

**Comment by shea256** [comment]
Also could be helpful to bring someone in on the copywriting front for messaging and language across the product cc @GinaAbrams

**Comment by larrysalibra** [comment]
This shipped.
