### ISSUE TITLE
Add profile field for BIP-0047 Reusable Payment Code

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-browser#1094]
BIP-0047 Reusable Payment Codes ("bitcoin payment codes") make it possible to receive bitcoin without allowing people who know the code to know how much bitcoin you have received using it. See [BIP-0047](https://github.com/bitcoin/bips/blob/master/bip-0047.mediawiki) or [this blog post](https://lightco.in/bitcoin-payment-codes/) for more info. With this field in the profile, apps could use the Blockstack ID to resolve to a payment code so users can easily send and receive more discreet payments.

**Comment by guylepage3** [comment]
added to #1097 1095
