### ISSUE TITLE
Add profile field for Ricochet ID

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-browser#1095]
Some Ricochet users do not mind associating their Ricochet ID with other IDs they are using. Letting them link their Ricochet ID to their Blockstack ID will make it easy for people to find their Ricochet ID.  

https://ricochet.im/

**Comment by guylepage3** [comment]
Will add this to the upcoming list of social proofs @john-light. 

Pinning https://github.com/blockstack/blockstack-browser/issues/1097
