### ISSUE TITLE
List of social proofs & accounts to consider adding to the browser

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1097]
### List of social proofs & accounts
  - [x] twitter
  - [x] facebook
  - [x] github
  - [x] instagram
  - [x] linkedin
  - [ ] tumblr
  - [ ] reddit
  - [ ] pinterest
  - [ ] youtube
  - [ ] google-plus
  - [ ] angellist
  - [ ] stack-overflow
  - [ ] hacker-news
  - [ ] openbazaar
  - [ ] snapchat

**Comment by guylepage3** [comment]
Request by @john-light to add Ricochet ID to the list

**Comment by guylepage3** [comment]
Request by @john-light to add BIP-0047 Reusable Payment Code to the list #1094

**Comment by guylepage3** [comment]
Request by @john-light to add Zcash address to the list #1093

**Comment by larrysalibra** [comment]
Thanks for starting a list of these @guylepage3 - nice to have them all in one place!

@yknl @guylepage3 let's talk about which ones we want to add in the next sprint planning meeting!

**Comment by vsund** [comment]
I would like to also bring up PGP proofs (discussed in https://github.com/blockstack/blockstack.js/issues/297) and websites (discussed in https://github.com/blockstack/blockstack-browser/issues/1056) here.

Also, what do you think of a small bounty (e.g. $10) for adding new accounts and proofs to `blockstack.js` / Browser? Would probably help in getting many more accounts implemented :)

**Comment by cponeill** [comment]
I just saw this issue and was thinking that Earn.com would be a great profile to use as well since it they are building a social network. Just a thought.
