### ISSUE TITLE
Improve in progress indications on buttons

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1098]
@guylepage3 brought up a great point our our disabling buttons and changing them to a verb with an ellipse (example: "Restore" changes to "Restoring...") isn't very obvious.

We can definitely improve on this. Some options for this are here: https://github.com/blockstack/blockstack-browser/issues/1082#issuecomment-346470898

**Comment by wbobeirne** [comment]
This has been greatly improved with #1539, enough so that I think this is safe to close. We tend to use a spinner in most places.
