### ISSUE TITLE
Change trust level to something else

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1099]
We call the number of social media account verifications you have your "Trust Level." This is misleading and dangerous in that it doesn't really have anything to do with how trustworthy a Blockstack ID is.

<img width="506" alt="screen shot 2017-11-24 at 12 45 58 am" src="https://user-images.githubusercontent.com/597182/33182953-e7214ee8-d0b0-11e7-9e10-25755104023d.png">

Thanks to @csuwildcat for bringing this to our attention: https://twitter.com/csuwildcat/status/927301417571725313

**Comment by larrysalibra** [comment]
I've changed this to social level for the time being:
<img width="621" alt="screen shot 2017-11-24 at 1 02 37 am" src="https://user-images.githubusercontent.com/597182/33183531-2fe614a4-d0b3-11e7-9af0-3368867e554d.png">

This change will ship in v0.21.3

**Comment by 5kilodope** [comment]
Hi, i wonder if "Social Level" is a good decision.
Reason: i instantly thought of chinas "social credit system".
