### ISSUE TITLE
"Name registration in progress..." was paid-for but appears to be owned by another id

### ISSUE THREAD

**Issue by Jaxo** [blockstack/blockstack-browser#1101]
Two of the names I purchased appear to be stuck in progress, as indicated by the "in progress" icon. When I looked at them in the explorer, they appear to be "owned" by some other id. How do I get this resolved, since I paid for them? Looking at them in the explorer, I do appear to have purchased them before they were purchased by some other id.

**Comment by larrysalibra** [comment]
Hi @Jaxo - i'm sorry to hear this - can you share the names? You can email them to larry at blockstack.com if you aren't comfortable with sharing them here.

**Comment by larrysalibra** [comment]
We looked in to this and it appears someone else won the name registration race.
