### ISSUE TITLE
Propose new App Store

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#1103]
Home is where *my* apps live...but right now the Blockstack Home screen shares the job-to-be done with what would be an "app store". We are approaching a home screen that is cluttered and confusing already with only 20 apps that users never selected themselves.

Can we create a Home Screen that you can add apps to from the App Store, and then build out an app store that includes short description, name of the developer, and eventually rating? cc @guylepage3 @larrysalibra @shea256 

![screen shot 2017-11-27 at 3 51 27 pm](https://user-images.githubusercontent.com/5605552/33288984-fd2e79a8-d38b-11e7-8c10-ca8a27b968fb.png)

**Comment by guylepage3** [comment]
Agreed @pstan26, we should think about this a bit as there are some of us who feel the best experience is to separate out the Home Screen (access to my apps) vs. the App Store (place to discover and learn more about apps).

**Comment by brandonparee** [comment]
With an 'App Store' would it be possible to simplify the process of adding new applications to the Blockstack Browser? I looked around and it seems that right now the process involves putting assets directly into the browser and then deploying a new update. 

Also, I like the idea of having a separate 'Home Screen' as well, where I can keep my favorite apps. 

(Totally off topic, but maybe a potential revenue stream and use for STX could be 'promoted' applications in the browser.)

**Comment by yknl** [comment]
Separating the Home Screen and App Store makes a lot of sense and is definitely something we should do. One thing to consider from the engineering perspective is where we are going to store the user's list of apps. If we store this locally, then the apps won't be there if the user logs in on a different device. And for privacy reasons, we probably don't want to store this in the user's public profile either.

**Comment by wbobeirne** [comment]
Closing as stale.
