### ISSUE TITLE
Add instructions in Github for adding apps to browser

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#1106]
@guylepage3 @larrysalibra y'all cool if we add some instructions in the README for the browser to add apps? Would you just like that to link to a google form or should it go to another Github README where they can do a pull request to add their URL and Logo? Open to suggestions

**Comment by guylepage3** [comment]
@pstan26 let's keep this a manual thing for the time being as it will be changing very soon.

**Comment by guylepage3** [comment]
closing this issue
