### ISSUE TITLE
Possibility to share only some profile fields

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-browser#1107]
I really like the concept of giving out as little as possible data to be able to operate. In our case this would be to give out only the profile fields that the app requested.
Per default (for backwards compatibility) we could say that it requests all profile fields and then let apps restrict themselves to access only what their need.

The first step would be to show the user which profile fields an app wants to read and then later let the user select which he wants to permit (if not permitted filled in with dummy values or even manipulated data from the user (e.g. I don't want to sign in with my default email, but with `tokensale@some-domain.net`)).

This could be part of a bigger permission system (i.e. `app wants read access to email, name, avatar`, `app wants write access to all profile fields`, `app wants access to spend money`).

**Comment by larrysalibra** [comment]
Like the idea of more granular data sharing. Thanks for suggesting.
