### ISSUE TITLE
Add Token Portfolio Apps to browser

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#1108]
@guylepage3 @larrysalibra @yknl Would like to add the following token portfolio apps to the browser before Monday at noon:

**Project Name | Team Captain Name | URL of Project | logo of project**

- [x] Coins | Chase Wackerfuss | http://use.coinsapp.co | https://user-images.githubusercontent.com/1711854/32732078-848a8baa-c859-11e7-926c-5f1330c4273b.png
- [x] Coinfort | Satraj Bambra | http://www.coinfort.io | https://s3.us-east-2.amazonaws.com/coinfort/icon400.png
- [x] Cryptagon | Bernat Fortet Unanue | http://app.cryptagon.io/ | https://drive.google.com/file/d/1uKDMoHlln8BIjl6fxcbH8bjyrUbhMxvZ/view?usp=sharing
- [x] CoinStack | Ben Rogmans | http://www.coinstack.one/ | http://www.coinstack.one/assets/img/coinstack-logo-400x400.png
- [x] Coinbrella | Luciano Leal | http://www.Coinbrella.com | https://imgur.com/a/iexyA
- [x] CoinKitty | Vince DePalma | http://coinkitty.co | http://www.coinkitty.co/mobile-icon.png
- [x] Coinocle | Justin Hunter | http://blockstack.coinocle.com | https://www.dropbox.com/s/reogkf74xol7odh/400x400Coinocle.png?dl=0
- [x] faa.st | Moe Adham | http://faa.st/portfolio | https://faa.st/static/faast-press-kit.zip
- [x] Coinremix | Ben Longstaff | http://coinremix.netlify.com/ | http://coinremix.netlify.com/project-logo.png
- [x] BlockPortfolio | Patrick DeVivo | http://www.blockportfol.io/ | https://www.dropbox.com/s/hsjfibuok5mlxzs/blockportfoliox400.png?dl=0
- [x] worth | Martin Enzinger | http://worth.at | https://worth.at/worth_sl.svg
- [x] Proem | Cole Jorissen | http://proem.io | https://drive.google.com/file/d/1nwgokn2aiZD3AP8zgmqaJlsjSKXUoKuz/view?usp=sharing
- [x] Coindex | Daniel Shijia Wang | http://coindexapp.herokuapp.com | https://drive.google.com/open?id=1iEu8hlghuJoWBgczAjFBri6TSrkayQE2
- [x] Lio | Alec Richter | http://tap-five-lio.herokuapp.com | http://tap-five-lio.herokuapp.com/logo.png
- [x] Peachy Portfolio | Brandon Paree | http://peachyportfolio.com/ | Pending logo

**Comment by guylepage3** [comment]
This is awesome @pstan26. Can we ensure we get all the above icons as square icons 512x512 size? Thank you sir. 👍

**Comment by pstan26** [comment]
Yes.

**Comment by bernatfortet** [comment]
@pstan26 the link for cryptagon.io is incorrect, would you mind editing it to the following:
Cryptagon | Bernat Fortet Unanue | https://app.cryptagon.io

(there's no "www" in it)
Thanks!

**Comment by cwackerfuss-rl** [comment]
@pstan26 can we please also change our URL to our landing page @ https://coinsapp.co

Thank you!

**Comment by nathanielwood** [comment]
Here's the 512x512 logo for faa.st:
https://faa.st/img/faast-logo-512x512.png

**Comment by vinniejames** [comment]
I've updated the icon for CoinKitty http://www.coinkitty.co/mobile-icon.png

![mobile-icon](https://user-images.githubusercontent.com/2112033/33751791-1eeef0e6-db92-11e7-85db-167007ff13d7.png)

**Comment by alecrichter** [comment]
The 512x512 logo for Lio can be found at http://lioapp.io/logo512.png

Also, could you please update the url for Lio (last time, I promise) to http://lioapp.io

**Comment by benrogmans** [comment]
Hey @guylepage3, the brand new CoinStack logo can be found here:

http://www.coinstack.one/assets/img/coinstack-logo-512x512.png

This one above is 512x512 but maybe the margins are a bit big? I have an alternative but it is a bit smaller: http://www.coinstack.one/assets/favicons/apple-touch-icon.png

Thanks & regards

**Comment by jehunter5811** [comment]
512x512 logo for Coinocle here. Thanks!

<img width="256" alt="coinoclelogo" src="https://user-images.githubusercontent.com/10519834/33764989-695415b8-dbdc-11e7-85d7-d5ff1385dda3.png">

**Comment by xanbots** [comment]
512x512 for Coinbrella 
![coinbrella logo](https://user-images.githubusercontent.com/31934541/33786352-ce902f16-dc36-11e7-82a7-af4bd0d637f9.png)

**Comment by xanbots** [comment]
512x512 Coindex logo
![coindex logo](https://user-images.githubusercontent.com/31934541/33786464-4defa17e-dc37-11e7-86df-22d9b048b7ad.jpg)

**Comment by xanbots** [comment]
512x512 Coinremix logo
![coinremix logo](https://user-images.githubusercontent.com/31934541/33786550-93583fb4-dc37-11e7-82ba-03d5d385e067.jpg)

**Comment by xanbots** [comment]
512x512 Cryptagon Logo
![cryptagon logo](https://user-images.githubusercontent.com/31934541/33786601-bd046068-dc37-11e7-8059-277019e6d7e9.jpg)

**Comment by xanbots** [comment]
512x512 Proem logo
![proem logo](https://user-images.githubusercontent.com/31934541/33786687-fff41d64-dc37-11e7-9967-7ee9225ae1d2.jpg)

**Comment by xanbots** [comment]
512x512 worth logo
![worth_logo](https://user-images.githubusercontent.com/31934541/33786995-507c0fc0-dc39-11e7-98cc-a080f1c9070c.jpg)

**Comment by patrickdevivo** [comment]
![app-icon-blockportfolio-512x512](https://user-images.githubusercontent.com/57259/33799023-707ac7ea-dcf1-11e7-8866-3fbc0216ffd0.png)

Blockportfol.io ^^

**Comment by larrysalibra** [comment]
@pstan26 @xanbots just a heads up. i'm not going to be able to add these icons to browser before monday and also finish technical judging of the apps. Guy is on vacation so we shouldn't expect him to do it either. @yknl might be able to do it.

**Comment by vinniejames** [comment]
I don't mind doing it, if you guys point me in the right direction

**Comment by guylepage3** [comment]
@larrysalibra @yknl I will be handling this one tomorrow.

**Comment by larrysalibra** [comment]
> I will be handling this one tomorrow.
Thanks @guylepage3 ! 🥇

**Comment by satbam** [comment]
@guylepage3 @pstan26 @xanbots Here is my updated logo. Also can we remove coinfolio which was what it was called initially before submission and put Coinfort instead? Thank you.
![coinfort512x512](https://user-images.githubusercontent.com/1127325/33811313-c8449dd6-dddf-11e7-8869-a045f4379908.png)

**Comment by xanbots** [comment]
Thanks @satbam, my mistake, didn't realize you were changing logo/name

**Comment by brandonparee** [comment]
Here is the logo for Peachy Porfolio. 

![logo](https://user-images.githubusercontent.com/6785558/33815013-84177e7e-ddeb-11e7-92eb-740b13ba43cc.png)

**Comment by xanbots** [comment]
@guylepage3 Confirming the above apps will be added to the next browser release. Thanks!

**Comment by guylepage3** [comment]
working on this now

**Comment by guylepage3** [comment]
hey @benrogmans, can you get this version over to me at the 512px size?

>This one above is 512x512 but maybe the margins are a bit big? I have an alternative but it is a bit smaller: http://www.coinstack.one/assets/favicons/apple-touch-icon.png

**Comment by guylepage3** [comment]
Adding the apps to the browser now.

**Comment by guylepage3** [comment]
complete.

**Comment by benrogmans** [comment]
Hey Guy,

Here is the bigger logo on a 512x512 canvas:

![coinstack-logo-2-512x512](https://user-images.githubusercontent.com/394374/34156620-4bf95d58-e4be-11e7-8f6e-2032fd63c173.png)

**Comment by guylepage3** [comment]
@benrogmans adding this now

**Comment by guylepage3** [comment]
@yknl I added the new Coinstack app icon to the browser. Can we add that in on this build?

**Comment by yknl** [comment]
will do

**Comment by benrogmans** [comment]
Thanks guys!

2017-12-19 20:45 GMT+01:00 yknl <notifications@github.com>:

**Comment by guylepage3** [comment]
Cool. Thanks @yknl
