### ISSUE TITLE
Unable run browser build in Ubuntu 16.04

### ISSUE THREAD

**Issue by inzig** [blockstack/blockstack-browser#1111]
Ubuntu 16.04
64 bit system.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/inzamam/Documents/blockstack/blockstack-browser/package.json ENOSPC
    at exports._errnoException (util.js:1020:11)
    at FSWatcher.start (fs.js:1451:19)
    at Object.fs.watch (fs.js:1478:11)
    at createFsWatchInstance (/home/inzamam/Documents/blockstack/blockstack-browser/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/inzamam/Documents/blockstack/blockstack-browser/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/inzamam/Documents/blockstack/blockstack-browser/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/inzamam/Documents/blockstack/blockstack-browser/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/inzamam/Documents/blockstack/blockstack-browser/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockstack-browser@0.21.3 dev: `NODE_ENV=development ./node_modules/.bin/gulp dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockstack-browser@0.21.3 dev script 'NODE_ENV=development ./node_modules/.bin/gulp dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockstack-browser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development ./node_modules/.bin/gulp dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockstack-browser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockstack-browser
npm ERR! There is likely additional logging output above.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.12.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle blockstack-browser@0.21.3~predev: blockstack-browser@0.21.3
6 silly lifecycle blockstack-browser@0.21.3~predev: no script for predev, continuing
7 info lifecycle blockstack-browser@0.21.3~dev: blockstack-browser@0.21.3
8 verbose lifecycle blockstack-browser@0.21.3~dev: unsafe-perm in lifecycle true
9 verbose lifecycle blockstack-browser@0.21.3~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/inzamam/Documents/blockstack/blockstack-browser/node_modules/.bin:/home/inzamam/bin:/home/inzamam$
10 verbose lifecycle blockstack-browser@0.21.3~dev: CWD: /home/inzamam/Documents/blockstack/blockstack-browser
11 silly lifecycle blockstack-browser@0.21.3~dev: Args: [ '-c', 'NODE_ENV=development ./node_modules/.bin/gulp dev' ]
12 silly lifecycle blockstack-browser@0.21.3~dev: Returned: code: 1  signal: null
13 info lifecycle blockstack-browser@0.21.3~dev: Failed to exec dev script
14 verbose stack Error: blockstack-browser@0.21.3 dev: `NODE_ENV=development ./node_modules/.bin/gulp dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid blockstack-browser@0.21.3
16 verbose cwd /home/inzamam/Documents/blockstack/blockstack-browser
17 error Linux 4.4.0-101-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
19 error node v6.12.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error blockstack-browser@0.21.3 dev: `NODE_ENV=development ./node_modules/.bin/gulp dev`
22 error Exit status 1
23 error Failed at the blockstack-browser@0.21.3 dev script 'NODE_ENV=development ./node_modules/.bin/gulp dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the blockstack-browser package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=development ./node_modules/.bin/gulp dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs blockstack-browser
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls blockstack-browser
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by larrysalibra** [comment]
@inzig are you still seeing this problem?

**Comment by wbobeirne** [comment]
Closing as stale.
