### ISSUE TITLE
Addresses not generated consistently by browser

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1112]

**Comment by jackzampolin** [comment]
<img width="737" alt="screenshot 2017-12-11 12 21 46" src="https://user-images.githubusercontent.com/7452680/33853273-3b4acac0-de72-11e7-8bf9-3a727451d8ac.png">
<img width="734" alt="screenshot 2017-12-11 12 21 38" src="https://user-images.githubusercontent.com/7452680/33853275-3b686152-de72-11e7-9931-7a543f85edd3.png">

**Comment by locomo** [comment]
i'm getting the same things .. i reset blockstack browser and i expected to see the 3 IDs that I had previously generated but initially only the first address (ID) that I had originally created appeared - but the rest did not reappear on their own 

i clicked "Create New ID" - my 2nd ID appears with the correct address and profile info

click "Create New ID" again .. a new address appears and the profile info for the 3rd ID appears (avatar, name, description) but the username doesn't not appear and it still reads "Add username" and the address is incorrect

if i continue to click "Create New ID" additional addresses are generated but my 3rd {name}.id never appears

**Comment by Esharifov** [comment]
I had the similar issue and currently only have 2 of my 5 ids displaying? 

Would it be better if the user isn't just dependent on UI, and can double verify the ownership of the ids from some other source or claim them by their passphrase or some other solution?

When we purchase the ids, what is it linked to as a primary identifier, is it our account, which we can gain access to with passphrase?

**Comment by larrysalibra** [comment]
> Would it be better if the user isn't just dependent on UI, and can double verify the ownership of the ids from some other source or claim them by their passphrase or some other solution?


You can verify the ids are owned by your identity address by using the blockstack explorer: https://explorer.blockstack.org or spinning up your own full core node.

**Comment by Esharifov** [comment]
Larry I followed same steps as @locomo did, and was able to retrieve all 4 non-default ids.

However when looking into https://explorer.blockstack.org, I noticed that only my default id is populating under my identity, the rest 4 are displaying solo owner and public addresses associated with them.

I guess my question is that, in case BlockStack has issues and doesn't display my info even in the explorer, can I claim these addresses from Bitcoin protocol by entering my passphrase?

**Comment by jackzampolin** [comment]
@Esharifov All of the identity keys for all of those names are derived from your keychain phrase. You can see the details here: https://github.com/blockstack/blockstack-browser/issues/330

**Comment by jackzampolin** [comment]
Closing https://github.com/blockstack/blockstack-browser/issues/1053 in favor of this issue.

**Comment by kantai** [comment]
I'm exploring what's going on here in this branch:
https://github.com/blockstack/blockstack-browser/tree/hotfix/address-index-bug

The first bug discovery is that we're double incrementing indexes:
https://github.com/blockstack/blockstack-browser/blob/hotfix/address-index-bug/app/js/profiles/store/identity/actions.js#L199

This is "consistent" behavior, however, and wouldn't lead to the issues above. Stay tuned.

**Comment by kantai** [comment]
It looks like that's exactly the bug causing your problem @jackzampolin -- your 0th through 7th indexes are:

```
0 ->  '1HDq8cuiL1WVHYW6WWvKQVziC1ysch6DBe'
1 ->  '1DxPKUkGsFW9DBMhgppMWzLcVjkAhA1cXe'
2 ->  '18QifCARcwvw6hUajYwuB1U2NAUU7jt5Jb'
3 ->  '1M5qDQENjzNzgi5e9siDsx5VipDRZTUrx9'
4 ->   '17QimY54KxwKUeP9Qkus9MR5UdJhh5p2GG'
5 ->   '15eVUr5CtuLAcbUEedzHZZK5quKCfQ6cgE'
6 ->   '1NoCPKN7KDpefP9pGh8V53E53PPbqfwQvQ'
7 ->   '1N98n7FMCjz5DRss3YFucwv91fyQENKFao'
```

Browser 1 is correctly progressing through the indexes 0,1,2,3,4.
Browser 2 is progressing through bug-y indexes 0,1,3,5,7.

These are two different browser versions?

**Comment by jackzampolin** [comment]
I likely imported the keychain phrase on 2 different browser versions, but they are currently the same.

**Comment by kantai** [comment]
Interesting. On browser 1, if you add another couple address what addresses do you get?

**Comment by jackzampolin** [comment]
```[
  "1HDq8cuiL1WVHYW6WWvKQVziC1ysch6DBe",
  "1DxPKUkGsFW9DBMhgppMWzLcVjkAhA1cXe",
  "18QifCARcwvw6hUajYwuB1U2NAUU7jt5Jb",
  "1M5qDQENjzNzgi5e9siDsx5VipDRZTUrx9",
  "17QimY54KxwKUeP9Qkus9MR5UdJhh5p2GG",
  "1NoCPKN7KDpefP9pGh8V53E53PPbqfwQvQ",
  "17e3q4w7AzYgr98duUXfoqh47ikFVrnzPR",
  "1H1zF29Di558yBvmW9t9vckY52Usn74pKK",
  "1EtbzQznAeYxMJtqwuWWs8J1JU7aGxXsA",
  "1KjwMYJmC2k9TUVo5tXUKpN1AYLhF4mpC6",
  "1M5LKAgJjsimCDhgimXbYi1STgeaLjzvKC",
  "19wui9cD2hGB1ri67ujiNPjbqdkVWMcHey",
  "19AxdFYk8mdWc4rwhRSUCHqeUUzrsRi6o",
  "19R1qfLhtGTs3voTCfzvMVyHTUYCcyTNG",
  "1LqmCYZTsZV3tkCtji1ubCUAcm1naLexM1"
]```

**Comment by kantai** [comment]
Great -- yeah, that's the bug that you're experiencing.

**Comment by brnltn** [comment]
Hello,
by restoring my keychain on my localhost I don't refind my ID, it opens with a new one created. But, by using the webapp it opens with the good ID and all informations linked.

**Comment by kantai** [comment]
Closing this bug, as this was fixed in #1173, which has since shipped.

**Comment by RSky215** [comment]
I see this bug was closed but I still seem to have issues getting my alternate ID's to populate on my IDs page. When I check the blockstack block explorer I can see that my original default ID-address is listed in the Zone File for the ID's i'm missing. I assume this means I am the owner.

When I click "Add Another ID" I always receive a new ID with no option to restore or recover another ID.

Example: My primary ID address for this profile (ID-1GFyoGQzYjxPvRbrqEivLbMQ5mtRNkvKoL) appears in the zone file for another ID I claimed (russ.id).

<img width="611" alt="screen shot 2018-10-10 at 9 58 56 am" src="https://user-images.githubusercontent.com/9307147/46749650-6ace2400-cc73-11e8-8a40-2cef43ac6978.png">

<img width="977" alt="screen shot 2018-10-10 at 9 59 09 am" src="https://user-images.githubusercontent.com/9307147/46749676-77527c80-cc73-11e8-8a96-94c58bf66ad7.png">

Is there a fix to this issue as well - is it something different entirely? Thanks!!!

**Comment by kantai** [comment]
@RSky215 -- it looks like that ID `russ.id` is the 7th ID in your wallet, which means you'll need to add many new IDs until it finds that ID (this works like an HD wallet -- see this issue: https://github.com/blockstack/blockstack-browser/issues/1550)
