### ISSUE TITLE
Blockstack Auth doesn't work on Github Pages

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#1116]
https://forum.blockstack.org/t/blockchain-authentication-on-github-pages-site-fails/3564

When implementing Blockstack Auth on a site that is hosted on Github Pages the app fails to load after signin due to a long `?authResponse=`. Github returns a `414 - Request URI too large` error

This may be the case with other static site hosting providers.

**Comment by kantai** [comment]
This is really a blockstack.js issue (open issue here https://github.com/blockstack/blockstack.js/issues/300), so I'm closing this, and we can move discussion over there.
