### ISSUE TITLE
Linux protocol handler bug

### ISSUE THREAD

**Issue by skybach** [blockstack/blockstack-browser#1118]
The default protocol handler causes the url token parameter to return with 3 slashes at the beginning.

I made it work by modifiying blockstack.dektop protocol handler to remove the 3 slashes as well 

from
Exec=bash -c 'xdg-open http://localhost:8888/auth?authRequest=$(echo "%u" | sed s/blockstack://)'
to
Exec=bash -c 'xdg-open http://localhost:8888/auth?authRequest=$(echo "%u" | sed s^blockstack:///^^)'

**Comment by larrysalibra** [comment]
Thanks for reporting this @skybach ! We'd love if you could send a pull request!

**Comment by wbobeirne** [comment]
Looks like this was addressed with #715.
