### ISSUE TITLE
Update storage auth paths to take advantage of direct gaia app access

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1119]
The storage auth path in the browser should take advantage of apps which use direct gaia access by:

1. Skipping the datastore setup from core
2. Skipping the core-session-token generation
3. Allowing Windows/Web users to sign in to storage apps with high enough apprequest versions

**Comment by kantai** [comment]
The above tasks are live in the branch [`feature/direct-gaia-app-support`](https://github.com/blockstack/blockstack-browser/tree/feature/direct-gaia-app-support)

Before this gets merged, the changes in `blockstack.js` will need to make it to npm -- it depends on a new semver check from blockstack.js

**Comment by larrysalibra** [comment]
This shipped.
