### ISSUE TITLE
Can't detect blockstack on Brave Browser

### ISSUE THREAD

**Issue by ianq** [blockstack/blockstack-browser#1120]
* Blockstack does not detect the Desktop Application is installed when logging in to apps from Brave Browser
<img width="972" alt="screen shot 2017-12-15 at 5 58 07 pm" src="https://user-images.githubusercontent.com/19857086/34036886-9d9ed0b6-e1c1-11e7-83e0-9518d1893bb0.png">

**Comment by larrysalibra** [comment]
Thanks for reporting this @ianq

**Comment by jsparknz** [comment]
I also have this problem when trying to use Blockstack with Brave browser (0.22.721) on Ubuntu (18.04). Is there any update to this issue or is anything I can do to help fix it?

**Comment by jsparknz** [comment]
I had a hunch that maybe it was because Brave was installed as a Ubuntu snap, so I removed the snap and installed Brave using the Ubuntu PPA repository. I then got the protocol handler permission prompt, accepted it, and now Blockstack login is working. Not sure if this is the root cause or if it was because I had started with a fresh profile again, but it's a possibility.

**Comment by wbobeirne** [comment]
Also experienced this on OSX, so I don't think it's an issue with Ubuntu Snap.

**Comment by wbobeirne** [comment]
Looks like this is a problem with https://github.com/larrysalibra/custom-protocol-detection. For chrome-like browsers (e.g. Brave) it relies on a quirk that is the window "blurring" whenthe prompt for an external application pops up. Unfortunately Brave's UI doesn't blur the window, but simply blocks the request and shows this prompt:

<img width="1299" alt="screen shot 2018-07-03 at 11 09 37 am" src="https://user-images.githubusercontent.com/649992/42229151-c6bd5ab4-7eb3-11e8-9c58-201231a3dafe.png">

However, the prompt goes away after you're redirected to blockstack.org, so you might miss needing to allow it. The only way to get it to work is to always allow blockstack, or to click allow very quickly.
