### ISSUE TITLE
As a user, I would like to know how name registration works when I go to register a name

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1123]
Discussion around wording and action items: https://github.com/blockstack/blockstack-browser/issues/1090

@yknl will do acceptance testing

**Comment by larrysalibra** [comment]
https://github.com/blockstack/blockstack-browser/issues/1090

**Comment by shea256** [comment]
Copy to be used as a jumping off point:

>You're about to submit a registration request for `larry.id`. Hope nobody beats you to it!

**Comment by wbobeirne** [comment]
Closing as stale.
