### ISSUE TITLE
As a web or windows user, I would like to sign in to apps without core

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1125]

**Comment by larrysalibra** [comment]
@kantai can you take this one?  I can do acceptance testing on it.

**Comment by kantai** [comment]
Yep, I'll take this one.

**Comment by larrysalibra** [comment]
This has shipped for windows & linux users. We still need to update the web version.

**Comment by wbobeirne** [comment]
Closing as stale.
