### ISSUE TITLE
Configuration Settings in Blockstack-Browser

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1127]
Per a couple other issues on blockstack-browser, we should clean up the configuration settings in browser.

While we're at it, we should use core.blockstack.org  (a Public core node) whenever we can (like for fetching names owned, which would keep people from appearing to lose their names when their local core endpoint goes down.)

Proposal for settings:
  - Public core node setting: default to core.blockstack.org
  - Private core node setting: default to localhost:6270
  - Private core node password: 

The idea is that we’d eventually (soon!) remove the private core node setting entirely (so there's just 1 core node option)

@larrysalibra do you want to take the lead on this?

**Comment by wbobeirne** [comment]
I'm pretty sure this is no longer an issue.
