### ISSUE TITLE
Restored account, blockstack ID is not there

### ISSUE THREAD

**Issue by oso4** [blockstack/blockstack-browser#1135]
Hello! So, I had to restore my account, and now my blockstack ID isn't linked. I can search for it, and it exists. It's `schmitt.id`.  But, my account has a different default ID. How do I pull the id I bought back into my account? Thank you! 

Tom

**Comment by iam-dev** [comment]
I've the same problem. also after hard reset

**Comment by meteorplus** [comment]
what do you mean? 
How do I pull the id I bought back into my account? 
you meant link back?

**Comment by Aranad** [comment]
You should be able to restore from your 12 word phrase and your ID's will be there again.
