### ISSUE TITLE
Add DevLink to browser

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1139]
Add DevLink to browser

@pstan26 please provide credentials

**Comment by pstan26** [comment]
Hey @guylepage3 what do you mean by credentials? cc @benrogmans who is the app developer there.

**Comment by guylepage3** [comment]
@pstan26 @benrogmans I'm looking for the usual suspects for placing an app on the Blockstack Browser Home Screen.

>Project Name | Team Captain Name | URL of Project | logo of project

Por favor. 😄

**Comment by dantrevino** [comment]
@guylepage3 I can help here.  Is there an icon?  Here are the app fields for placement in the browser along with examples from the ToDo app:
**name**: Todo App
**display name**: To Do List
**description**: A simple todo app build on blockstack.
**version**: 1.0.0
**appIcons**...
**website**: http://blockstack-todos.appartisan.com
**launchlink**: http://blockstack-todos.appartisan.com
**developer**: Larry Salibra
**storage required**: true (false if not using gaia)
**status**: user ready (other option is "in progress")

**Comment by guylepage3** [comment]
@dantrevino, thank you sir. 👍

**Comment by dantrevino** [comment]
@yknl @larrysalibra @hstove fyi, this can be closed.

**Comment by larrysalibra** [comment]
Thanks @dantrevino
