### ISSUE TITLE
500 Internal Server 

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-browser#1140]
getting `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` accopanied by `[2017-12-25 01:58:47,237] [ERROR] [rpc:4005] (46.140584519194368) object of type 'NoneType' has no len()` in api_endpoint.log

running Linux, and Blockstack Browser 0.21.5

**Comment by kantai** [comment]
Sorry that you're seeing this error.

Do you know what request your browser is making? (i.e., what URL returns the 500)

**Comment by dantrevino** [comment]
172.17.0.1 - - [27/Dec/2017 05:23:16] "GET /v1/stores/1Bh3Rxk1uvD2BzW8Fi3B9vKJN47cW1eXzq/files?path=/portfolio.json&idata=1&device_ids=0&device_pubkeys=0362e74dc367c61cff900d0e2d96e55b815b6e14776db7e5b4b307545170835a53&blockchain_id=dantrevino.id HTTP/1.1" 500 -

It appears to be isolated to this specific blockstack id.  I'm not seeing the error with other ids within the same browser.

**Comment by larrysalibra** [comment]
@dantrevino you shouldn't need to proxy storage through core anymore - please let us know if you're having issues with the direct to gaia storage! thanks for bringing this up!
