### ISSUE TITLE
Wallet broken after trying to send an insufficient amount

### ISSUE THREAD

**Issue by Esharifov** [blockstack/blockstack-browser#1146]
Steps:
1. Go to Wallet
2. Send more funds than available balance ( I did this by not having enough for tx fees)
3. Observe the send button

Expected:
1. Error message displayed cautioning user about insufficient funds
2. "Sending" button is reseted to "Send" button is enabled to do another transaction

Actual:
1.  Error is displayed as expected
2. "Sending" string is displayed and disabled, preventing user doing another tx.
 
![image](https://user-images.githubusercontent.com/13299214/34646759-b9ff0a80-f325-11e7-8909-bdc70589842f.png)

[](url)

**Comment by larrysalibra** [comment]
Thanks so much @Esharifov for telling us about this bug! We're in the process of moving all transaction generation into the browser which should give us much better ability to display actionable user errors.
