### ISSUE TITLE
Authentication dialog doesn't tell users which app they're signing in to

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1147]
The problem we're trying to solve: users should know which apps they're authenticating to. 

Our security model is currently based on app origin. Each app origin gets its own private key - data encrypted for that app only works with that origin. Each app origin also gets its own storage bucket.

The eventual plan is to have a blockstack name for each app, but right now we use legacy domain names.

All of the information from our current dialog comes from the manifest file:

<img width="457" alt="screen shot 2018-01-08 at 1 35 46 pm" src="https://user-images.githubusercontent.com/597182/34659875-da1139c0-f478-11e7-9ee2-86051cba5a90.png">

We need to verify that an authentication request is being generated and sent to the same place it is requested for and that this manifest file info isn't being spoofed by a rogue app (issue for this: https://github.com/blockstack/blockstack.js/issues/338) and display the verified app origin in this dialog so that users can make informed decisions when they're deciding to approve or deny an authentication request.

For this issue we need to:
* update the dialog copy to display the verified app origin
* update blockstack.js and use the `verifyAuthRequest` before displaying the authentication request to users

**Comment by larrysalibra** [comment]
This still needs a UI update from me.

**Comment by wbobeirne** [comment]
Looks like this has been fixed.
