### ISSUE TITLE
Regenerating storage authentication token when it becomes stale

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1149]
Currently -- gaia hub authentication tokens use a 'date' timestamp during authentication. Our default provider will `mod` arithmetic this timestamp to simulate a validity time. Of course, this means that storage connections in blockstack browser can become stale.

The application will see this as a '401' unauthenticated write when they try to PUT a file to the hub -- users will experience a silent error when updating their profile.

This can be remedied for a user by loading:

http://localhost:8888/account/storage#gaiahub

However, blockstack browser should be able to either:

1. Detect that a token became stale and generate a new authentication token
2. Generate the token at the time of write, on each write

(2) will be a 1 round-trip slower, but has the benefit of reducing state

**Comment by kantai** [comment]
@benoror reported experiencing this issue (and I think a number of other users have run into it as well).

The smart-profile-writes update actually _sort of_ mitigates this issue, by generating a token when the profile updates (however, writing to old profile locations (i.e., /root-address/x/profile.json) still tries to use the global token).

**Comment by markmhx** [comment]
This should be fixed by upgrading the version of blockstack.js used by the browser to the latest.

**Comment by markmhx** [comment]
@hstove Want to tackle this version upgrade this sprint?

**Comment by hstove** [comment]
Yep, it'll be a very simple fix.

**Comment by kantai** [comment]
I'm pretty sure that this is already implemented in the browser -- I think everywhere the browser uploads a profile (the only writes the browser ever does) it generates a new auth token on the fly.

**Comment by hstove** [comment]
Sorry, updating blockstack.js was actually already done by Thomas, and will be in the release we're about to put out.
