### ISSUE TITLE
Proposal: No Browser

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#1151]
So over the holidays I was spending time on design thinking for the browser, mostly on the home screen and the app store. One thing that has been bothering me quite a bit is that there is that this is a new concept and we are applying it to the old world of a browser. Except this isn't a browser. It still confuses the heck out of people.

I would like to propose getting rid of the word "Browser" as well as getting rid of the traditional "Home Screen" that appears in the user's browser and pulling it all out into a native application. One where we can control the experience on all platforms.

Users would download the "New Blockstack Internet" onto their machines and |would use Blockstack to access their data on the new internet. They can still use their browsers and we can build out a lot of extensions such as a "Mac Menu Bar App" for Mac users, and browser extensions for others..

There may be a "Home Screen" on the new native app but we could encourage users to simply bookmark and navigate to web apps as they currently do. Another discovery mechanism could be "Alias App icons" that appear in a special folder on their desktops called "Blockstack Apps" This would be an alternative to Mac users "Applications" folder.

Please provide thoughts and comments.

cc:ing @shea256, @larrysalibra, @yknl

**Comment by guylepage3** [comment]
One thing I forgot to mention, which is quite important is that the focus for Blockstack would be the creation of the App Store via blockstack.com. More focus on the app store for discovery.

**Comment by BryanG1** [comment]
Could not agree more with this idea. I would like to see the Blockstack ecosystem exist independently of current internet browsers.

**Comment by sunny-g** [comment]
I'm new to this project, and had a similar thought from a different perspective - could `blockstack-browser` be just a browser extension without requiring any application installation? That way, in the future, `blockstack-browser` could be a full-fledged web browser on top of Electron (like Beaker or Brave), but with the core API (aka, the current `blockstack-browser`) embedded into the browser itself (and optionally, an instance of `blockstack-core` as well).

**Comment by ydennisy** [comment]
Why use a new browser when it can be avoided? 
(Sorry I am new to this project so please bear with me)
I have just logged into the graphite app using Chrome @ https://browser.blockstack.org/
Why would you want users to need to download and learn/use a new browser - is there some functionality missing?

Also what is the repo for the web-app accessible via https://browser.blockstack.org/

**Comment by wbobeirne** [comment]
Closing as stale, discussion has moved to the forums.
