### ISSUE TITLE
Automatically recover all registered usernames when restoring from keychain

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1152]
Remove the need to press "Create ID" to recover each previously purchased usernames when restoring identity from keychain.

One way is to just just go through and generate the first X number of addresses when restoring and add the ones that have usernames.

**Comment by shea256** [comment]
Thanks @yknl but I believe this is a duplicate of this issue: https://github.com/blockstack/blockstack-browser/issues/729

**Comment by yknl** [comment]
Duplicate of #729
