### ISSUE TITLE
Ship multi-player storage

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1158]
Current status:

@yknl and I went through a few review-change cycles on the pull requests for multi-player storage for blockstack.js and those were merged into the develop branches on Tuesday.

Remaining:
- [x] testing demo app
- [x] fixing any bugs discovered
- [x] making blockstack.js build
- [x] making browser build
- [ ] writing a blog post to announce the feature and explain how it works and what it enables for developers. (do we want to do this? @pstan26)

**Comment by larrysalibra** [comment]
All that's remaining on this is to announce the new browser build and decide if we want to do a blog post.

**Comment by pstan26** [comment]
Hey just on plane back from Cuba (no internet) -- happy to ghostwrite the
blog post for multi-reader storage.

**Comment by wbobeirne** [comment]
This has long been shipped.
