### ISSUE TITLE
"Sign In With Blockstack" wants to launch Office 2016

### ISSUE THREAD

**Issue by sondreb** [blockstack/blockstack-browser#1167]
The links or mime-type of the "Sign In With Blockstack" is registered to Office 2016 on Windows, at least when running from Google Chrome.

I still works to click accept in the dialog, it will redirect properly in a new tab, but I'm sure it will scare away some users (including myself) from clicking it.

![image](https://user-images.githubusercontent.com/309938/34915022-76ee5670-f91e-11e7-9892-df1f23df6e42.png)

**Comment by kantai** [comment]
This is probably related to the way we register the protocol handler in Windows --

What version of blockstack is installed on your computer?

**Comment by sondreb** [comment]
I have insider build of Windows 10, so the very latest, and Office 2016. I have the latest version of blockstack (I attempted this right after installation and setup). If you need exact version, I'll give it later as I'm not at that computer right now.

**Comment by demarant** [comment]
![graphite-sign-in-with-openstack-ubuntu17](https://user-images.githubusercontent.com/320440/37020579-8343f6b6-211c-11e8-9e32-382e94bff0a5.png)

I get a similar dialog box on on ubuntu 17.10. I am unable to sign in, did I miss anything?

**Comment by mingrui** [comment]
same problem on windows.

@demarant same problem on ubuntu.

**Comment by ddyson** [comment]
Is anyone working on this? I have just hit this problem half way through the Hello BlockStack tutorial. https://blockstack.org/tutorials/hello-blockstack

**Comment by adsri** [comment]
Any update on this issue? It is still coming for windows10.

**Comment by bronoman** [comment]
Issue seems to be tied to Chrome on Windows 10 with MS Office installed. No issues with [Brave](https://brave.com/).

**Comment by hcollin8** [comment]
Issue is not resolved, any updates?

**Comment by moxiegirl** [comment]
@yknl what do you think? I can test it if you are not sure.

**Comment by yknl** [comment]
This issue needs further investigation. Seems to be a problem that affects both Windows and Linux. We'll move this up the priority list for the browser team.

**Comment by zone117x** [comment]
No. But I know what's causing that on Windows and it's pretty easy to fix, maybe a few hours.

**Comment by zone117x** [comment]
This PR https://github.com/blockstack/blockstack-browser/pull/1796 actually has some of the changes needed to fix it

**Comment by markmhx** [comment]
@zone117x Want to tackle this in the new sprint starting today?

**Comment by zone117x** [comment]
@markmhx Yep should be able to fit this in.

**Comment by markmhx** [comment]
This has been addressed and will be released with v0.36.0
