### ISSUE TITLE
Add text explaining why we need user email

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#1168]
From https://github.com/blockstack/blockstack-core/issues/677

Collecting users email and not explaining why leads to some questions. We should add an explainer as to what we are using those emails for, a way to edit the email once it is input, and potentially an opt out.

**Comment by dantrevino** [comment]
Per @jackzampolin last comment, absolutely the email address should be optional

**Comment by MichaelFedora** [comment]
Via #1560 and #1556 (specifically [this comment](https://github.com/blockstack/blockstack-browser/issues/1560#issuecomment-408376284)) it seems as if the email entry is no longer going to be optional, which is a little sad to me as I enjoyed being able to use the Blockstack network without being attached to a particular email.

I suppose it is for reasons such as [this forum thread](https://forum.blockstack.org/t/access-user-email-address-in-login-with-blockstack-integration/4267) -- being able to be an Oauth-like alternative? Why can't a particular app just ask for the email as a secondary login screen?

**Comment by wbobeirne** [comment]
There's currently copy in there that explains it's for recovery purposes.

**Comment by vsund** [comment]
Also would love to see the option to not have to enter an email address (and instead be able to write the recovery down on paper or similar).
