### ISSUE TITLE
Browser Chrome App Tab not moving to top

### ISSUE THREAD

**Issue by ChristopherA** [blockstack/blockstack-browser#1172]
On the Mac, if you use spotlight to open the Blockstack Browser (command-space + "Blockstack") it will properly open the Chrome App, but it will not bring the Blockstack Browser to the top. This does work properly with the Ledger Chrome App and the Green Address Chrome app.

Related, apparently my Blockstack Browser is in one of my many tabs, in one of my many open windows — how do I find it?

**Comment by wbobeirne** [comment]
Blockstack is no longer a Chrome App, closing as stale.
