### ISSUE TITLE
Unable to verify blockstack ID in Mac OSx

### ISSUE THREAD

**Issue by mjstroh** [blockstack/blockstack-browser#1178]
Here is a log of the issues I have had yesterday. It was an incredibly frustrating experience.

========================================
having trouble verifying my blockstack ID stroh.id
Twitter verifies, but not Facebook

okay - it works now but instructions on this are only available in the video help. Would be handy to have it in the main document instead :slightly_smiling_face:

this is very frustrating - I had verified my Twitter, Facebook and GitHub accounts. Then I went to add a photo and all the verifications disappeared. 

I remember doing this a month or so back with no luck either.
There must be a better way to do this, surely. 
Can this be resolved quickly?

Okay - now verified my account again. Moving on…
Initially the wallet is saying I have zero BTC.
That’s not right.

I don’t understand this - now I click on the ID page and all the info I put in before is GONE. IT IS NOT THERE. NOTHING!

When I try to access the To Do List app, I get a continuous loop happening where it asks me to verify my account, I do that, and then I click on the To Do app, and it then asks me to verify it again.

I am using a Mac and just downloaded the latest MacOSx  patch from GitHub.
=======================================

Here are the steps I performed:

- install Blockstack-for-macOS-v0.22.1.dmg
- Open Blockstack browser
- ++++
- the "Getting Started" window appears
- Click on link "restore an existing keychain"
- Typed in keychain and password for stroh.id
- click "restore keychain"
- in new window, enter email address
- click "continue"
- in storage window, click "Use default storage"
- "Complete your ID" page appears
- Add name, bio
- verify Twitter, Facebook and GitHub accounts
- click ToDo app to open it
- go to line marked "++++" above and repeat

These steps repeat in a loop. I have been in that loop at least 5 times yesterday. 

![screen shot 2018-01-20 at 05 14 54](https://user-images.githubusercontent.com/6382967/35165364-34b6e6e0-fda2-11e7-9b73-9e99b1e01337.png)
![screen shot 2018-01-20 at 05 16 19](https://user-images.githubusercontent.com/6382967/35165365-34f10460-fda2-11e7-80fc-fff65309094e.png)
![screen shot 2018-01-20 at 05 19 07](https://user-images.githubusercontent.com/6382967/35165366-352c23b0-fda2-11e7-9463-3fd882e9582f.png)
![screen shot 2018-01-20 at 05 33 45](https://user-images.githubusercontent.com/6382967/35166113-dc57e00a-fda4-11e7-91f0-7fe6a9416754.png)
![screen shot 2018-01-20 at 05 34 13](https://user-images.githubusercontent.com/6382967/35166114-dc93d59c-fda4-11e7-9014-08f651502829.png)
![screen shot 2018-01-20 at 05 34 22](https://user-images.githubusercontent.com/6382967/35166115-dcc9ece0-fda4-11e7-9cb5-7f11ae43595b.png)
![screen shot 2018-01-20 at 05 34 41](https://user-images.githubusercontent.com/6382967/35166116-dd005c30-fda4-11e7-9efd-de52b7bbd880.png)
![screen shot 2018-01-20 at 05 34 59](https://user-images.githubusercontent.com/6382967/35166117-dd34d00a-fda4-11e7-9819-55499d121adb.png)
![screen shot 2018-01-20 at 05 35 47](https://user-images.githubusercontent.com/6382967/35166118-dd6a374a-fda4-11e7-9dab-7e3032573d45.png)
![screen shot 2018-01-20 at 05 35 58](https://user-images.githubusercontent.com/6382967/35166120-dda37a32-fda4-11e7-9953-2bbd02bd173b.png)
![screen shot 2018-01-20 at 05 36 14](https://user-images.githubusercontent.com/6382967/35166121-ddd8fd24-fda4-11e7-845b-2739bd76288d.png)

**Comment by jackzampolin** [comment]
This issue you are running into is because your ID has Dropbox storage that is no longer supported. We need to add the ability to update zonefiles to the browser. There is an open issue to track this:

https://github.com/blockstack/blockstack-browser/issues/1086

Since you have the dropbox storage in your zonefile, this means you were using the version of the browser that stored BTC in the core wallet. If you would like to recover the BTC, navigate to the `localhost:8888/wallet/send-core` and send the funds to your browser wallet.

One question, does [`stroh.id`](https://explorer.blockstack.org/name/stroh.id) appear as your ID?

**Comment by mjstroh** [comment]
yes stroh.id appears - see last screenshot

**Comment by jackzampolin** [comment]
So that means the ID is owned by the browser. Your profile writes are not persisting because the storage is not configured properly.

Please go add a comment to https://github.com/blockstack/blockstack-browser/issues/1086 mentioning that you are running into this issue. I'm going to close this issue as a duplicate.

**Comment by mjstroh** [comment]
hold on one second.
You cannot close this issue until it is resolved.
I am unable to send the BTC. See screenshot.

![screen shot 2018-01-20 at 05 50 01](https://user-images.githubusercontent.com/6382967/35166413-f42d3940-fda5-11e7-918c-9e97807aa71c.png)
