### ISSUE TITLE
I lost password and keychain

### ISSUE THREAD

**Issue by ferrucc-io** [blockstack/blockstack-browser#1180]
I deleted the blockstack app a while ago. But then changed my mind and downloaded it back. Now it's asking me: "Finish updating Blockstack. Enter your password to finish updating Blockstack." 
But:
1) I don't know my password
2) I never saved the keychain as I created an identity just to play around.
There is no option to "logout"/"create new identity" and there is a question mark icon that is not clickable for help.

So:
1) How can I reset my identity and login with a new one?
2) You should consider improving the UX.

**Comment by wbobeirne** [comment]
Closing as stale. If you're still experiencing this, you can manually clear your browser data for `localhost:8888`. The process for that will vary between browsers, so if you're not sure on how to do that, you might need to search around.
