### ISSUE TITLE
Add loading indicator to the keychain restore

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#1183]
The keychain restore is very CPU intensive and can take a while depending on the hardware. Users frequently think that there is something wrong because there is no feedback here.

**Comment by Esharifov** [comment]
I have literally waited about 25 mins. Does it take more than 25 mins?

**Comment by jackzampolin** [comment]
@Esharifov It shouldn't take that long. Can you make sure you are on the latest version of the blockstack browser, hard refresh your browser (chrome, safari, etc...) and try again?

**Comment by wbobeirne** [comment]
Closing as stale. There are a few PRs open that currently enhance this, but the UI has changed a good bit since this was first opened, so I think the issue has been addressed.
