### ISSUE TITLE
Token should be automatically refreshed for Gaia Hub

### ISSUE THREAD

**Issue by benoror** [blockstack/blockstack-browser#1189]
While developing and app with blockstack.js, I repeatedly encounter this issue while persisting a file:

```
Error: Failed to putFile /untitled.asc (errno: 121): Failed to replicate inode data to at least one driver
```

I tried both restarting Blockstack browser (0.22.1) & proxy, and even my Mac laptop.

As pointed by Ken Liao the issue got fixed by visiting http://localhost:8888/account/storage#gaiahub

---

- Operating system and version: `MacOS 10.13.2`
- Browser and version: `Chrome 63`
- Blockstack version: `0.22.1`
- How you installed Blockstack: `DMG`

**Comment by kantai** [comment]
This is the same as issue #1149 -- closing this and will reference it over there.
