### ISSUE TITLE
As a browser user, I should be able to register a domain in regtest mode without using core

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1190]
As a browser user, I should be able to register a domain in regtest mode without using core

**Comment by kantai** [comment]
A good starting point to check out:

https://github.com/blockstack/blockstack.js/blob/feature/blockstack-operations/tests/operationsTests/src/operationsTests.js

This test performs:
1. a preorder
2. a register
3. an update
4. a transfer
5. a renewal

And it _also_ broadcasts the zonefile for those tests (and sets the library to broadcast in 'testnet')

One point about how this will interact with the browser today --- currently the blockstackd regtest server will return _mainnet_ addresses. This means that a lot of code _doesn't_ need to change in the browser to handle regtest. When you perform the name lookups, etc. requests from the browser, the server will respond in mainnet addresses, _however_ the transaction generated must be a regtest transaction (which still means that it needs to be "set" to regtest.

Regarding transaction generation, we will need to have a service which broadcasts the transaction (and zonefile) after a delay (or, optionally, display the second txn's QR to the user so they can broadcast) --- either @jcnelson or I can work on that.

**Comment by yknl** [comment]
Thanks for the detailed write-up @kantai, looking into this now.

**Comment by larrysalibra** [comment]
This should be a user story right? 

As we discussed, this story can be broken down into a number of tasks:

1. Document starting regtest mode in a way that any community member can enable regtest. (We don't want mainnet to be the only way to test this).
2. Product: Proposal to add support for multiple network support to browser. How is this enabled by developers?
3. Engineering: Build out the multiple network support agreed upon in 2.
4. Product: Requirements for transaction & zone file update server. Proposed API.
5. Engineering: Build the server in 4.
6. Engineering: Implement javascript transaction generation.

**Comment by yknl** [comment]
I broke this story down into the 4 issues below:

1. Setup a remote regtest core node with a faucet endpoint 
https://github.com/blockstack/blockstack-core/issues/735
@jackzampolin and @yknl

2. Add support for regtest mode by connecting to remote regtest core
https://github.com/blockstack/blockstack-browser/issues/1200
@yknl or @larrysalibra 

3. Build out transaction generation in browser based on API
https://github.com/blockstack/blockstack-browser/issues/1201
@yknl or @larrysalibra 

4. Build transaction broadcasting service
https://github.com/blockstack/blockstack-browser/issues/1202
@kantai or @jcnelson

**Comment by larrysalibra** [comment]
Additional step: Build out transaction broadcast service javascript api in blockstack.js https://github.com/blockstack/blockstack.js/issues/362

**Comment by kantai** [comment]
This was completed. Even though it's tricky to configure regtest properly in the browser (and I suspect, even trickier now with the subdomain-onboarding), this was how we tested the client-side registration process before shipping it.
