### ISSUE TITLE
Multi-player storage not working

### ISSUE THREAD

**Issue by goldquest** [blockstack/blockstack-browser#1191]
Hi, 
while trying out the multi-player storage for a mail prototype, we are doing, I just couldn't access the public files from other users. It turns out, that the `apps` section wasn't added to the profile, besides adding the `publish_data` scope.

I also tried the working version of the tutorial: http://publik.ykliao.com/ which also didn't work.

- MacOS 10.13.2
- Chrome 63
- Blockstack v0.22.1 (84)
- How you installed Blockstack: Per download on blockstack.org
- Steps to reproduce:

1. Go to http://publik.ykliao.com/
2. Sign In
3. publish a new status
4. go to http://publik.ykliao.com/:username
5. expect seeing your published status

**Comment by yknl** [comment]
@goldquest, there are 2 issues that may cause this behaviour. Both of them results in profile writes to fail which breaks multi-player storage. 

1) Your Gaia token has expired, to refresh it manually, visit: https://localhost:8888/account/storage#gaiahub
2) You are experiencing the address generation bug described here: https://github.com/blockstack/blockstack-browser/issues/1154

You can try editing/saving your profile and see if changes are persisted. Then if you re-authenticate your app, it should work.

**Comment by goldquest** [comment]
Thanks for your help.
I tried editing the Bio, which didn't work, so I tried restarting the Blockstack Browser. The Browser didn't start again and some python process didn't shutdown correctly. I killed it manually, but the Browser still didn't start.
After a complete restart of the Notebook everything works as expected.

**Comment by goldquest** [comment]
My colleague had the same problem, but the gaia token refresh seemed to solve it here.
