### ISSUE TITLE
As an internal browser user, I should be able to use subdomains.

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1192]
* Implement subdomain registrar independent of blockstack-client https://github.com/blockstack/blockstack-core/issues/730
*  Create production-ready subdomain registrar https://github.com/blockstack/blockstack-core/issues/730
* Re-enable subdomain registration support in the browser https://github.com/blockstack/blockstack-browser/issues/1193
* Write tests for blockstack browser that test subdomains
* Write tests for blockstack.js that test subdomains
* Deploy a production-ready subdomain registrar

**Comment by kantai** [comment]
Additionally:
* Move the subdomain DB into blockstackd https://github.com/blockstack/blockstack-core/issues/718

**Comment by larrysalibra** [comment]
@kantai says remaining items:

* Release of core v0.19
* Need to acquired domain name & payment address

**Comment by wbobeirne** [comment]
Closing as stale.
