### ISSUE TITLE
Add support for regtest mode by connecting to remote regtest core

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1200]
Removes the need to perform the current docker setup for reg test and makes it very easy for developers to start testing with Blockstack IDs.

Implement something along the lines of this:

Opt + Click Blockstack Tray Icon → Run in regtest mode

- Opens `http://localhost:8888/start-regtest` or set a flag `&regtest=1`
- Display warning that this will reset all Blockstack data stored on the browser, recommend use of incognito mode (This can be avoided by running the regtest mode browser on a different port)
- Do a `localStorage.clear()`  and start the browser in regtest mode
- Browser will now connect to the remote regtest core node, this can be configured via URL param
- All transactions generated will be regtest transactions

**Comment by larrysalibra** [comment]
This works and is in develop!
