### ISSUE TITLE
Backfill JS Linting

### ISSUE THREAD

**Issue by cwackerfuss** [blockstack/blockstack-browser#1207]
We added the linting task to the js app late in the process, so there are files that are [currently being ignored](https://github.com/blockstack/blockstack-browser/blob/master/.eslintignore) that we have the opportunity to go back and lint.

**Comment by cwackerfuss** [comment]
@larrysalibra and @yknl --

I'm going to take a breather on going through the Linting fixes so that
A) we dont have too many open tickets
B) there's less chance of merge conflicts

Please take a look and review when you can, I know they're technically lower priority tickets but the fact that they touch so much code makes me want to get them reviewed and merged as soon as possible (because conflicts).

**Comment by larrysalibra** [comment]
@cwackerfuss sounds good.

also making a note to add linting coverage to our test suite as well

**Comment by wbobeirne** [comment]
Closing as stale.
