### ISSUE TITLE
app store account creation design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#121]
The blockstack browser portal account creation view is one of the most important views of any application built on blockstack including blockstack id's. If users land on the account creation view and the communications are not clear the user will bounce before they even start using an app.

**Requirements**
- [x] blockstack logo
- [x] headline
- [x] email input - determined that the user's email address is the one item that applications need to capture from users so that applications can attempt to onboard users after the user has left the app.
- [x] create an account button
- [x] already have an account link
- [x] 72x72 icon

**Comment by guylepage3** [comment]
<img width="986" alt="screenshot 2016-12-07 18 30 57" src="https://cloud.githubusercontent.com/assets/1711854/20991242/5a0bc656-bcab-11e6-9b0a-be6cd91b8311.png">

**Comment by guylepage3** [comment]
2.
<img width="1012" alt="screenshot 2016-12-08 11 28 53" src="https://cloud.githubusercontent.com/assets/1711854/21056835/4730e0ba-be05-11e6-98cc-2acd5f14781d.png">

3.
<img width="982" alt="screenshot 2016-12-08 18 04 12" src="https://cloud.githubusercontent.com/assets/1711854/21056857/55f6aa58-be05-11e6-90c9-9f980a170155.png">

4.
<img width="1253" alt="screenshot 2016-12-08 18 44 10" src="https://cloud.githubusercontent.com/assets/1711854/21056875/64dc5d42-be05-11e6-80a0-2db666844578.png">

5.
<img width="1049" alt="screenshot 2016-12-08 19 14 57" src="https://cloud.githubusercontent.com/assets/1711854/21056905/772225ae-be05-11e6-86b6-c34ef9bf92c2.png">

6.
<img width="1070" alt="screenshot 2016-12-09 11 46 34" src="https://cloud.githubusercontent.com/assets/1711854/21056915/81f44430-be05-11e6-83df-970b42285792.png">

**Comment by guylepage3** [comment]
<img width="881" alt="screenshot 2016-12-09 12 27 09" src="https://cloud.githubusercontent.com/assets/1711854/21058199/eb2974f2-be0a-11e6-8b6d-5303b370a585.png">

**Comment by guylepage3** [comment]
<img width="1358" alt="screenshot 2016-12-09 15 20 15" src="https://cloud.githubusercontent.com/assets/1711854/21064011/9b3e2dcc-be26-11e6-8003-dd2410dc9d5d.png">
<img width="1699" alt="screenshot 2016-12-09 15 43 30" src="https://cloud.githubusercontent.com/assets/1711854/21064016/9fe15a16-be26-11e6-894d-e12c75a07fa9.png">

**Comment by guylepage3** [comment]
@shea256 I think we have a winner with that last iteration. Thoughts?

**Comment by shea256** [comment]
Yeah agreed, I like that last one.

**Comment by guylepage3** [comment]
One last cleaner version..

<img width="1853" alt="screenshot 2016-12-09 15 54 18" src="https://cloud.githubusercontent.com/assets/1711854/21064267/e5036142-be27-11e6-8c11-3169ddf73948.png">

**Comment by guylepage3** [comment]
Complete.

**Comment by guylepage3** [comment]
switched out rectangle logo with new oval logo

<img width="1816" alt="screenshot 2016-12-12 11 43 29" src="https://cloud.githubusercontent.com/assets/1711854/21107587/3775cd90-c060-11e6-903b-abaa5cabbdd4.png">

**Comment by guylepage3** [comment]
Complete.

**Comment by guylepage3** [comment]
removed 
- <lead> copy from issue requirements

**Comment by guylepage3** [comment]
Getting closer with an app-like feel to our brand.

@shea256 @muneeb-ali @jcnelson @larrysalibra 

Please have a look at the following 3 layouts
1.
<img width="1724" alt="screenshot 2016-12-14 15 29 28" src="https://cloud.githubusercontent.com/assets/1711854/21199818/12130446-c213-11e6-8188-cb4466ccb4aa.png">

2.
<img width="1724" alt="screenshot 2016-12-14 15 31 38" src="https://cloud.githubusercontent.com/assets/1711854/21199828/1b6372ba-c213-11e6-88c2-c2be1ebb3892.png">

3.
<img width="1724" alt="screenshot 2016-12-14 15 32 18" src="https://cloud.githubusercontent.com/assets/1711854/21199835/21ee1f18-c213-11e6-978b-3acf2ad7b758.png">

**Comment by jcnelson** [comment]
I like the 3rd one the best.  Gives us space in the future to have a top-level panel with e.g. account and user settings.

**Comment by shea256** [comment]
I like #2. Seems more like an app view than a website, which is what I worry about with #3.

**Comment by muneeb-ali** [comment]
No. 2 is more in-line with the recent direction of keeping Blockstack more in the background.

**Comment by jcnelson** [comment]
No. 2 it is then.

**Comment by guylepage3** [comment]
Perfect. Closing this issue.
