### ISSUE TITLE
Decide user-facing name of "subdomains"

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1211]
Subdomains doesn't make sense from users' perspective. 

The user clicks a button that says "add username" and then is told that one of them is a subdomain.

<img width="670" alt="screen shot 2018-02-10 at 3 03 51 am" src="https://user-images.githubusercontent.com/597182/36045245-0c33b1f2-0e10-11e8-847d-91900f71603b.png">

Not going to dive too deeply into this now as this is something our dedicated product person can think about. As a quick and dirty solution, I suggest we call "subdomains" in the identity context as something like "free usernames"

**Comment by guylepage3** [comment]
I really feel that there should be a better more educational warning here guys. The user needs to actually know what they are committing to when we say "...foo.id is a subdomain that is free to register."

**Comment by yknl** [comment]
How about just calling it a free, sponsored Blockstack ID.

**Comment by dantrevino** [comment]
When users go to register for an application/service, they have the expectation that their username is "free" ... calling this out as "free" and/or "sponsored" confuses the issue.  The outlier here is the for-pay blockstack id.  If username search is going to return pay and free usernames, only the usernames that cost money should be identified.

**Comment by guylepage3** [comment]
>When users go to register for an application/service, they have the expectation that their username is "free" ... calling this out as "free" and/or "sponsored" confuses the issue

I personally have been getting feedback suggesting that everything needs to be very explicit in language. There is a bit of an educational process with this and other items. That's just the nature of the beast. It's either every name is a subdomain or if there are two types of names they need to be clearly described for the user. Preferably visually as well as written.

**Comment by dantrevino** [comment]
@guylepage3 fair enough, but why do they need to be differentiated at all?  They're all just "usernames" ... in terms of the legacy internet, your Facebook username and your Google usernames are still just usernames ... are there implications beyond policies of a specific registrar that change the functionality of subdomain usernames vs a blockstack id?

**Comment by guylepage3** [comment]
@dantrevino, I agree that there should only be one type of username. But that fact is that there are two at for the time being. This is something that needs solving for sure. subdomains are absolutely vital to getting the network up and running fast as they're free but they are a but ugly and therefore a bad UX.

**Comment by jcnelson** [comment]
> How about just calling it a free, sponsored Blockstack ID.

I like this descriptor.  It answers the question "why does my name have three parts, instead of two?".  The answer would be "because it is sponsored by another name."  Which is true--the on-chain name needs to propagate transactions for off-chain names.

**Comment by kantai** [comment]
> I like this descriptor. It answers the question "why does my name have three parts, instead of two?". The answer would be "because it is sponsored by another name." Which is true--the on-chain name needs to propagate transactions for off-chain names.

Yeah -- the idea of sponsorship also clues a would-be-subdomain-registrar-operator into the fact that _they_ need to fund those batches.

**Comment by wbobeirne** [comment]
This has been settled as `id.blockstack`
