### ISSUE TITLE
Blockstack Browser home screen does not show owned ID

### ISSUE THREAD

**Issue by plus-x** [blockstack/blockstack-browser#1215]
After purchasing an ID on the .id namespace, using my Blockstack ID / wallet, and waiting a few weeks, it has never shown as connected to my Blockstack account.

Verified ownership of my ID here:
https://explorer.blockstack.org/name/solrac.id

Verified owner ID = My Blockstack wallet ID (see screenshot below)

How to fix this?

**System Info**
- Mac OS X 10.13.2
- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Blockstack version 0.22.1 (installed from official installer package)
- Also tested on earlier Blockstack versions

**Steps to reproduce:**
- Just open your Home screen via Blockstack menubar app
- See screenshot

![no username](https://user-images.githubusercontent.com/6692678/36222882-c0934d26-11d3-11e8-8dd3-bd1f2adbfb4c.png)

**Comment by yknl** [comment]
hey @plus-x, do you see any errors in the javascript console? 

One thing you could try is to do a reset of your browser and restore from your 12 word keychain phrase.

**Comment by plus-x** [comment]
Please close this ticket

There were no JS errors but I restarted my computer, and all is working fine now. Must have been a corrupted browser state, local problem only
