### ISSUE TITLE
As a website visitor, I should be able to submit an app request

### ISSUE THREAD

**Issue by cwackerfuss** [blockstack/blockstack-browser#1219]
We'd like to allow people to submit an idea for an app to be built on Blockstack. This would help us gauge interest in ideas and point us in the right direction for future bounties.

Here's a mock showing where the user would click from the homepage to request an app:
<img width="1260" alt="screen shot 2018-02-20 at 11 26 21 am" src="https://user-images.githubusercontent.com/4405356/36439021-3c496caa-1631-11e8-9a51-cfe77c216417.png">

The button on the right "Request an app," should lead to a Google Form as a first iteration.

@patrickdevivo @xanbots would one of you mind making a quick form with the fields you think we should capture and then paste a link here so I can send users to the form when they click on this button?

**Comment by larrysalibra** [comment]
@cwackerfuss Does this belong on the blockstack.org repo? https://github.com/blockstack/blockstack.org/issues

**Comment by cwackerfuss** [comment]
Good call, still getting used to the names of these repos, thanks @larrysalibra. Closed.
