### ISSUE TITLE
Add SSH keys as a key option in the key manager in the profile editor

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#122]

**Comment by shea256** [comment]
I tagged @larrysalibra to take a look at this.

We already have PGP keys and Bitcoin addresses so adding SSH keys should be a simple update.

**Comment by larrysalibra** [comment]
Good idea. SSH keys more useful than PGP keys.

**Comment by larrysalibra** [comment]
SSH keys proofs aren't validated at add time, but neither are others. We can consider adding this in future: https://github.com/blockstack/blockstack-browser/issues/124
