### ISSUE TITLE
buildBlockstackVenvForMac.js depends on a hard path to python

### ISSUE THREAD

**Issue by nsipplswezey** [blockstack/blockstack-browser#1230]
https://github.com/blockstack/blockstack-browser/blob/4878a2a0e1c2768adac77297c6858bf985801438/native/macos/build_blockstack_virtualenv.sh#L25

https://github.com/blockstack/blockstack-browser/blob/4878a2a0e1c2768adac77297c6858bf985801438/gulp/tasks/buildBlockstackVenvForMac.js#L1-L7

If a new users python2.7 exists at a different path, setup breaks. New developer then needs to go in and edit the path to build. Proposed improvement in https://github.com/blockstack/blockstack-browser/pull/1226 assumes that users machine has a python aliased to `python2.7`. There's probably some more specific comprehensive handling for this issue, but this seemed like a small improvement that would have made things quicker for me.

**Comment by wbobeirne** [comment]
This gulp task no longer exists
