### ISSUE TITLE
Build blockstack-browser with blockstack-core v0.18.0

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1231]
This will allow MacOS and Linux clients (using the docker scripts) to _display_ subdomains in the user's identities.

I think, because we are limited on testing bandwidth, we probably want to do this release without merging what's currently in `develop`, but I'll defer to @larrysalibra and @yknl on that decision.

**Comment by larrysalibra** [comment]
It looks like besides subdomain support most of the changes in develop vs master are app icon updates. We can make a new release of of develop and disable subdomain registration support.

**Comment by larrysalibra** [comment]
We shipped this in v0.25.0
