### ISSUE TITLE
Browser not remembering keychain on home page load

### ISSUE THREAD

**Issue by CamJohnson26** [blockstack/blockstack-browser#1235]
- Operating system and version: Windows 10, latest update
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser): Firefox Developer Edition, latest update. With Privacy badger, uBlock origin and https everywhere enabled. Disabling the addons does not fix the issue
- Blockstack version: 0.25 latest
- How you installed Blockstack: Ran the msi installer
- Steps to reproduce: Open blockstack browser. Site asks if you want to restore the keychain. Follow the steps to restore the keychain. Close the page and reopen it. The browser doesn't remember the keychain you restored and asks to restore the keychain again. Can't login to blockstack apps because of this.
- Screenshots or videos: None
- Logs: None

**Comment by kantai** [comment]
Hi @CamJohnson26 ---

Blockstack browser stores the keychain in the browser's `localStorage` -- so it might have been cleared or something along those lines between page views.

Do you see any errors in the browser's javascript console after setting up the keychain?

**Comment by CamJohnson26** [comment]
Hey only error looks like it's related to validating my email. Just tried on my mac and it's the same problem, but I'm using synced browsers on both devices so must be some Firefox setting. Main weird thing I have is that I delete cookies when closing the browser, but blockstack forgets me even if I just try to open the same address in a new tab.

I'm happy to help debug this so just send over any steps.

![untitled](https://user-images.githubusercontent.com/5420592/37008864-ccda2908-20a9-11e8-99c3-a4ab037a503c.png)

**Comment by wbobeirne** [comment]
Closing as stale, please open if you're still experiencing issues. This is likely a browser issue with localStorage, possibly caused by a security focused plugin. There's nothing the browser can do about this unless it's allowed to save data locally, so I'd suggest seeing if you can whitelist it from any of these plugins. Alternatively you could try in another browser.
