### ISSUE TITLE
Replace `Isotach` with newer version `Diffuse`

### ISSUE THREAD

**Issue by icidasset** [blockstack/blockstack-browser#1237]
Sorry folks, I know you just changed it recently,
but this is the final name and it now has a proper logo.

The new info is:
- Name: **Diffuse**
- Url: **[https://diffuse.sh/](https://diffuse.sh/)**

You can find the app icon at:
http://diffuse.sh/images/icon-square.svg

And again, please let me know if I can do this work myself.
Thanks!

**Comment by larrysalibra** [comment]
Great @icidasset! got this changed thanks to @dantrevino 's pull request. Sorry about the slow turnaround time! Will be in the next build.

**Comment by icidasset** [comment]
Thanks @dantrevino and @larrysalibra !
