### ISSUE TITLE
Client-side Bitcoin Transactions

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1239]
The last pieces of the blockstack-browser which rely on a local core endpoint are:

1. Bitcoin transactions (really just spends from `/wallet/send`)
2. Legacy application signins / name lookups (at some point, when we stop shipping the local core endpoint, these are going to have to break)

Doing client-side bitcoin transactions can either be implemented in `blockstack.js` (it'd be pretty simple, the code in `txbuild` basically does everything that would be necessary) or in `blockstack-browser` using `bitcoinjs-lib` directly. I think it's a _little_ strange to add bitcoin transaction logic to a library whose primary concern is `blockstack` operations/lookups, but the logic is already mostly there, and implementing this in blockstack-browser would probably end up being more difficult.

Thoughts on which direction to pursue @yknl @larrysalibra ?

**Comment by yknl** [comment]
I think it makes more sense to put it in `blockstack-browser`. But what do you think about putting the bitcoin transaction logic in its own library?

**Comment by larrysalibra** [comment]
Long-term we're going to have payments functionality for stacks as well - it would be nice to have a consistent api for that with a driver model. If we started that payment api with bitcoin, it would give us a head start in coming up with the right payments api for stacks as well.

Based on that, I think it belongs in blockstack.js.

**Comment by kantai** [comment]
> Long-term we're going to have payments functionality for  stacks as well - it would be nice to have a consistent api for that with  a driver model. If we started that payment api with bitcoin, it would  give us a head start in coming up with the right payments api for stacks  as well. Based on that, I think it belongs in blockstack.js.

Yeah, I agree.

**Comment by kantai** [comment]
This is going to need to be implemented for #1242

**Comment by kantai** [comment]
PR: https://github.com/blockstack/blockstack.js/pull/393

**Comment by kantai** [comment]
This has shipped
