### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by nsipplswezey** [blockstack/blockstack-browser#1241]
Looks like theres an issue in the Sparkle updater.
Not much information, besides that it seems I'm already running v0.25.0 when the auto update is triggered, and indicates that I'm running some version < 0.25(I'll screenshot it next chance I get) and then after attempting to install the update(seemingly unnecessarily) the updater seems to fail... 

![image](https://user-images.githubusercontent.com/7946707/37229153-e7009600-2397-11e8-94c3-cb4c9dcea56b.png)

![image](https://user-images.githubusercontent.com/7946707/37229409-b9d8e7da-2398-11e8-9f3e-4759ca37d538.png)

![image](https://user-images.githubusercontent.com/7946707/37229412-bda942d8-2398-11e8-9d9d-3df857f8d805.png)

I'll put any more info I find here.

**Comment by nsipplswezey** [comment]
Also, actually, it would be nice to have an "About Blockstack" or "Check for Updates" option in the top-bar dropdown menu, so I could check versions and trigger updates. I'd be willing to open a PR for that if someone thought it were useful.

**Comment by wbobeirne** [comment]
Closing as stale. Unfortunately now that we're ~13 releases ahead of this, it's hard to know what went wrong. If you can still reproduce, please re-open.
