### ISSUE TITLE
As a new user to the browser that has not added a username, I should be able to use my own gaia hub

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1244]

**Comment by jcnelson** [comment]
Is this already achieved with the Gaia hub settings page?

**Comment by wbobeirne** [comment]
Closing as I think Jude is right. Re-open if this is still actionable.

**Comment by kantai** [comment]
There's a bug that prevents the config option from working, and there's this PR to address it: 

https://github.com/blockstack/blockstack-browser/pull/1491
