### ISSUE TITLE
Error pulling docker image (v0.25.0) from quay.io

### ISSUE THREAD

**Issue by mkvaghani** [blockstack/blockstack-browser#1245]
FATA[0014] Error pulling image (v0.25.0) from quay.io/blockstack/blockstack-browser, Untar exit status 1 chmod /usr/bin/corsproxy: no such file or directory 

NPM Package `npm install -g corsproxy-https` already installed

**Comment by kantai** [comment]
Hi @mkvaghani --

I'm sorry you're having issues with the docker container.

Can you run the command:

```bash
$ docker pull  quay.io/blockstack/blockstack-browser:v0.25.0
```

**Comment by mkvaghani** [comment]
Yes I also tried that, 
`docker pull  quay.io/blockstack/blockstack-browser:v0.25.0`
Same ERROR, can not pull the image.

**Comment by kantai** [comment]
What version of docker are you using?

```
$ docker -v
```

**Comment by mkvaghani** [comment]
It shows me 

Docker version 1.13.1, build 092cba3

**Comment by mkvaghani** [comment]
I've upgraded docker to 12.0
Now it's working. 

I think you have to change the docket install command here, 
https://forum.blockstack.org/t/linux-walkthrough/2495

**Comment by kantai** [comment]
I'm not sure where the error was coming from @mkvaghani --

I have the same version of docker, and it is able to pull down that container without issue. I think there may have been a temporary network issue or issue with the container repository.

**Comment by mkvaghani** [comment]
I've upgraded docker to 12.0
Now it's working.

I think you have to change the docket install command here,
https://forum.blockstack.org/t/linux-walkthrough/2495

**Comment by mkvaghani** [comment]
No problem, now it's working with docker 12.0
