### ISSUE TITLE
Remove devLink from home page

### ISSUE THREAD

**Issue by xanbots** [blockstack/blockstack-browser#1246]
@yknl @larrysalibra Removing devLink from the home screen on the next browser build.

**Comment by cwackerfuss** [comment]
I can take care of this too, I'll jump on it now.

**Comment by xanbots** [comment]
Thanks @cwackerfuss !

**Comment by cwackerfuss** [comment]
Devlink was already removed in a previous update!

**Comment by dantrevino** [comment]
related: #1139 I assume can be closed.
