### ISSUE TITLE
Registering names in other namespaces

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-browser#1247]
Right now, the browser only registers names in `.id`.  However, the developers at [Dotpodcast](https://dotpodcast.co) are looking for a way to register names in `.podcast`---the idea being that independent podcast creators can register their podcasts on their own.  [blockstack.js](https://github.com/blockstack/blockstack.js) already supports registering names in any namespaces, but the browser UI does not.

**Comment by prabhaav** [comment]
+1 for .stealthy

**Comment by jcnelson** [comment]
Just to be clear about the requirements for this feature, the only thing I'm proposing is making it so that when the user goes to buy a name, they can choose which namespace to register it in.  From the engineering meeting today, it does not sound like this should affect applications, the authentication flow, or blockstack.js.  It would only entail altering the UI for selecting a name---the user would additionally have to select a namespace.

Also, per the discussion today, the value of this feature is that it would allow users and app developers to experiment with this aspect of the platform.  One feature we touted in the last hard-fork was the pay-to-namespace-creator namespace type, whereby a developer could register a namespace and collect name-registration fees on it for the first year.  It would be interesting to see if this feature gains any traction if users were able to register names in different namespaces.

**Comment by jcnelson** [comment]
Engineering meeting notes: https://forum.blockstack.org/t/2018-03-22-engineering-meeting/4558/2

**Comment by kantai** [comment]
Closing this in favor of this issue: https://github.com/blockstack/blockstack-browser/issues/1197, which is identical.
