### ISSUE TITLE
As a user, I should be able to view the chat app bounty winners in the Blockstack browser app store

### ISSUE THREAD

**Issue by cwackerfuss** [blockstack/blockstack-browser#1249]
The main question here is where should the chat apps live? In an existing section or in their own new section? Discuss!

**Comment by cwackerfuss** [comment]
Cc @yknl @shea256 @jeffdomke @larrysalibra

**Comment by yknl** [comment]
I vote for a new section

**Comment by cwackerfuss** [comment]
Making a new section unless @shea256 @jeffdomke @pstan26 @larrysalibra @xanbots object

**Comment by jw2013** [comment]
@cwackerfuss shall we close this issue as https://github.com/blockstack/blockstack-browser/pull/1250 is merged? :)

**Comment by wbobeirne** [comment]
We shall!
