### ISSUE TITLE
Git dependencies should use https not git+ssh

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#125]
See https://forum.blockstack.org/t/npm-install-fails-with-permission-denied-while-cloning-from-github/424/2?u=larry

**Comment by vsund** [comment]
I tried to replace "git+ssh://git@github.com" with "git+https://github.com" to see if it fixes the issue (partially worked), but then there were additional repositories which got cloned and their installation called "git+ssh://" too.
So you might want to go through the other repositories too ;)

Rel: https://forum.blockstack.org/t/npm-install-fails-with-permission-denied-while-cloning-from-github/424

**Comment by larrysalibra** [comment]
This issue is happening again:

Fixed one of our packages: https://github.com/blockstack/blockstack-profiles-js/issues/17

Will need to update the version in browser once @shea256 pushes the new build to npm.

**Comment by shea256** [comment]
@larrysalibra Just merged and published.

**Comment by shea256** [comment]
Closing this issue.
