### ISSUE TITLE
Login redirecting from private browser instance to normal

### ISSUE THREAD

**Issue by informartin** [blockstack/blockstack-browser#1252]
Testing Blockstack using regtest and firefox on MacOS shows some weird behaviour.

The tuturial suggests to use a private browser window for testing, but when opening an app and clicking the login button, I get redirected to the normal browser instance and asked to confirm with the blockstack account available there. This account is different to the one I use in the private window and is registered on the mainnet rather than regtest.

For a greater testing experience it would be great if the redirect stays wihtin the private browser instance.

**Comment by wbobeirne** [comment]
This behaves correctly in Chrome, so if this is still an issue, I think it's a problem that Firefox would have to resolve.
