### ISSUE TITLE
Still logged into Apps after resetting browser

### ISSUE THREAD

**Issue by informartin** [blockstack/blockstack-browser#1253]
I reset my blockstack browser in firefox on MacOS and created a new account using regtest.

When trying to use the new account for Apps I realized that I was still logged in to those Apps with the old account. From my point of view, this is a serious security issue. Probably a caching issue, could anyone please check on that?

**Comment by kantai** [comment]
Hi @martinwesterkamp --

Blockstack applications, once authenticated, operate independently of the blockstack-browser. They have their own local storage, etc., which means that resetting the browser itself won't have any effect on logged in apps.
