### ISSUE TITLE
Support for STACKs wallet balances

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-browser#1257]
In the near future, it will be possible to buy names with STACKs tokens.  Blockstack.js will soon have support for registering and renewing names in STACKs (https://github.com/blockstack/blockstack.js/issues/394), and will soon have support for getting the balances of all token types a user holds (since the STACKs blockchain will support app-specific tokens).  However, the Browser will need to show users their token balances as well as their Bitcoin balance.

Most of the engineering complexity is captured in the blockstack.js API call.  However, the Browser wallet UI needs to be modified to display each type of token the user owns, and how many they own.  In addition, the name registration UI needs to indicate to the user which token type will be spent to register the name.

This was a topic in today's engineering meeting: https://forum.blockstack.org/t/2018-03-22-engineering-meeting/4558/2

**Comment by wbobeirne** [comment]
I'm going to close this as we're still a ways off from this, and I think it would be better serviced by a more up-to-date issue for it when the time comes.
