### ISSUE TITLE
Triple slash added to auth request on Ubuntu

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1264]
On ubuntu, a developer at the NYC Blockchain Hackathon gets 3 slashes `///` prepended to the authentication request token.

<img width="336" alt="screen shot 2018-04-01 at 1 08 16 am" src="https://user-images.githubusercontent.com/597182/38165639-31924c1e-3549-11e8-80de-306d94833242.png">

This is the contents of his `blockstack.desktop` file which we modified to use port 3000 because the docker images weren't working.

```
[Desktop Entry]
Type=Application
Terminal=false
Exec=bash -c 'xdg-open http://localhost:3000/auth?authRequest=$(echo "%u" | sed s/blockstack://)'
Name=Blockstack-Browser
```

**Comment by kantai** [comment]
This is addressed in this change:

https://github.com/blockstack/packaging/commit/6609ac598d455fc9edd0bc4a9b9cafd13d2b2240

Should be fixed in the next release's handler script.

**Comment by larrysalibra** [comment]
Thanks to taking care of this!
