### ISSUE TITLE
Test coreless builds of browser

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1267]
We need to test the coreless builds of the browser.

That means testing builds on:

- [ ] macOS
- [ ] linux -> [right-click and save-as](https://gist.githubusercontent.com/kantai/42fc3b3da3b6ffd14f8f81979a01a194/raw/0023f8522ba5f6e5082b815a34f95510f9fbf0e9/Blockstack-for-Linux-v0.28.0-test.sh)
- [ ] windows -> [msi](http://aaron.blankstein.com/stuff/Blockstack-for-Windows-v0.28.0-rc-0.msi)
- [ ] webapp -> [netlified deploy](https://deploy-preview-1256--reporter-beaver-73821.netlify.com/)

I will link to builds on these platforms.

**Comment by kantai** [comment]
Tagging would be testers (@larrysalibra @cwackerfuss @jcnelson @jackzampolin) on the team for updates on how their tests have gone for them.

**Comment by dantrevino** [comment]
Linux works on a clean install.  Brave Browser (Linux) now works (yay), however, after logging into an app it also asks to open an external application, and then opens the existing protocol handler.
![image](https://user-images.githubusercontent.com/7738/38340749-d93daf7a-3829-11e8-9e23-7f0de52dae5d.png)

Will there be a howto for cleaning up existing installs and or change protocol handlers?

**Comment by dantrevino** [comment]
When taking the build to an existing install logging into applications hang at "Signing in..." looking for local core 
![image](https://user-images.githubusercontent.com/7738/38347879-0999f2b8-3853-11e8-8dd7-7cd8ce07fb4b.png)
![image](https://user-images.githubusercontent.com/7738/38347898-27f567ba-3853-11e8-8b18-569849eba0b5.png)

**Comment by dantrevino** [comment]
Also, social verifications went to "unverified" 

![image](https://user-images.githubusercontent.com/7738/38347940-72dc37e0-3853-11e8-807f-7ef619799ac0.png)

**Comment by dantrevino** [comment]
@kantai I let it auto-migrate.

**Comment by kantai** [comment]
@dantrevino -- I've added a patch which should do this automatically during the migration -- if you can pull down the latest and try it again, that'd be much appreciated.


> Will there be a howto for cleaning up existing installs and or change protocol handlers?

The old protocol handler should continue to work -- it opens at `http://localhost:8888/auth?...` right? Or did it open to a bad page?

**Comment by dantrevino** [comment]
@kantai will check in my lunchtime/evening ... two things:

- Please confirm that this procedure makes sense: 
1. localstorage.clear()
2. start 0.26.2, and restore keychain, validate everything is working
3. stop 0.26.2
4. start 0.28-test (link above) (existing identities in place still)
5. validate everything is working

- I said "protocol handler" but what I meant was references to the core/api node ... I still saw errors with things looking for localhost:6270 ... all of the API settings remained in place.. my understanding is that those should be 'core.blockstack.org' after upgrade, correct?

**Comment by kantai** [comment]
Yep -- that's the right procedure.

> I said "protocol handler" but what I meant was references to the core/api node ... I still saw errors with things looking for localhost:6270 ... all of the API settings remained in place.. my understanding is that those should be 'core.blockstack.org' after upgrade, correct?

Yep -- that's correct. The latest commits should ensure that after the upgrade those URLs will get migrated.

**Comment by dantrevino** [comment]
Linux testing .... Still hanging at signin after migrating from 0.26.2 -> 0.28-test (latest).
![image](https://user-images.githubusercontent.com/7738/38386536-cb653396-38c9-11e8-8c25-1db7c8983d0c.png)
![image](https://user-images.githubusercontent.com/7738/38386579-e35b43fa-38c9-11e8-88da-f859f27b8850.png)

**Comment by kantai** [comment]
Can you run 
```
docker images | grep feature_enable-reg-webapp
```
as well?

**Comment by kantai** [comment]
Okay, I think the migration path still needs some work then. Thanks for testing this out @dantrevino -- really appreciate it.

**Comment by kantai** [comment]
Migration should be fixed by commit 96bacdd5f7ac30488b5e3d86f05bbb9fb9e0e90a --
needed to be a little bit better with my redux state.

**Comment by dantrevino** [comment]
confirmed.... I didnt pull the CORS changes, but the API urls all point correctly now and I was able to confirm login to several apps

**Comment by larrysalibra** [comment]
I've tested a bitcoin transaction on my production wallet with build on mac - the fee seems like it might be a bit low and it hasn't confirmed yet.

**Comment by kantai** [comment]
Want to start an issue for that on `blockstack.js` @larrysalibra? That's where the fee is calculated.

**Comment by larrysalibra** [comment]
> Want to start an issue for that on blockstack.js @larrysalibra? That's where the fee is calculated.

Going to wait to see if & when it confirms yet.

**Comment by larrysalibra** [comment]
It confirmed!

**Comment by kantai** [comment]
Can you share the txid so I can inspect it for a low fee, even if it did
eventually confirm?

**Comment by larrysalibra** [comment]
I tried to register lawrencesalibra.id and this bug prevented my in progress registration from being "saved" in the browser - waiting to see if it gets processed: https://github.com/blockstack/blockstack-browser/issues/208#issuecomment-379532869

**Comment by larrysalibra** [comment]
It worked! https://explorer.blockstack.org/name/lawrencesalibra.id

**Comment by kantai** [comment]
Awesome!

It looks like the fee for your transactions is okay (10 satoshis / byte)
for all of them. That's the current recommended fee at
https://bitcoinfees.earn.com/api/v1/fees/recommended

**Comment by kantai** [comment]
This has shipped, thanks everyone for testing!
