### ISSUE TITLE
Error when authenticating an app without a username

### ISSUE THREAD

**Issue by cwackerfuss** [blockstack/blockstack-browser#1274]
An app developer is running into an issue where they can't authenticate when an identity doesn't have a username. I believe this is just a bug that happens sometimes, but may have to do with specific configurations.

<img width="989" alt="screen shot 2018-04-09 at 12 43 59 pm" src="https://user-images.githubusercontent.com/4405356/38513388-b9da5c28-3bf3-11e8-829d-4b5a5cc5f453.png">

**Comment by kantai** [comment]
Thanks for creating an issue for this @cwackerfuss -- I think a couple of others have encountered this issue as well. I have a fix for this, will test and then we can hopefully include this in the upcoming release.

**Comment by aulneau** [comment]
+1 I have run into this, too

**Comment by kantai** [comment]
This is fixed in the latest release (0.28)
