### ISSUE TITLE
Linux install script (Blockstack-for-Linux-v0.28.0.sh) must execute with bash

### ISSUE THREAD

**Issue by artusvranken** [blockstack/blockstack-browser#1279]
- OS: 4.9.0-6-amd64 Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux (stretch)
- Blockstack version: v0.28.0
- Steps to reproduce:
```
$ sh ./Blockstack-for-Linux-v0.28.0.sh
./Blockstack-for-Linux-v0.28.0.sh: 34: [: unexpected operator
./Blockstack-for-Linux-v0.28.0.sh: 45: ./Blockstack-for-Linux-v0.28.0.sh: Syntax error: Bad function name
```
I tried to fix the error myself but I have no clue why it throws it in the first place. The bash-script looks correct.

This is the if-clause causing the first error:
```bash
if [ "$WIN_HYPERV" == '1' ]; then
    prefix='winpty'
else
    prefix=''
fi
```

**Comment by artusvranken** [comment]
Changing the function names that use `-` (dash) in the name to use `_` (lowercase) fixes the script.

I also just noticed that the program is meant to be run in `bash`, not in `sh`, my bad.

**Comment by kantai** [comment]
Glad you worked this out, closing this as solved.
