### ISSUE TITLE
Linux/Docker Install fails on non-amd64 compatible architectures

### ISSUE THREAD

**Issue by hoschi-it** [blockstack/blockstack-browser#1280]
# My Environment
- Linux Mint, 32bit
- Docker version 1.13.1, build 092cba3
- Firefox 59.0.2

# What I did to install blockstack browser
1. downloaded installation script from Github (version 0.28.0)
1. made script executable
1. ran as docker-privileged user without errors:

        $  ./Blockstack-for-Linux.sh pull
        $  ./Blockstack-for-Linux.sh install-protocol-handler

1. ran `$  ./Blockstack-for-Linux.sh start` as the same user. 

# The Problem I ran into
After that, a new webpage opened automatically. The URI was "http://localhost:8888/#coreAPIPassword=0" and it said (translated to english) "Error loading page - connection failed".

There were no docker containers running, but they were both created.

If I forgot to mention some details, please ask!

Thank you very much!!!

**Comment by kantai** [comment]
Hey -- thanks for reporting this.

Can you run the following command to see if there's any logging for the docker container:

```
$ docker logs blockstack-browser-static
```

**Comment by hoschi-it** [comment]
$ docker logs blockstack-browser-static
     standard_init_linux.go:178: exec user process caused "exec format error"
     standard_init_linux.go:178: exec user process caused "exec format error"
     standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by kantai** [comment]
AMD64:

```
$ docker inspect quay.io/blockstack/blockstack-browser:v0.28.0 | grep Architecture
        "Architecture": "amd64"
```

**Comment by hoschi-it** [comment]
That's it. I'm running on i686, so it doesn't fit.
Could someone build a message about the architecture into the script or the documentation for docker installation?

**Comment by markmhx** [comment]
@moxiegirl is this info you'd like to add to the documentation?
