### ISSUE TITLE
Blockstack Browser shows the same Id twice

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-browser#1284]
- Operating system and version
macOS 10.12.6
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Chrome 65.0.3325.181
- Blockstack version
Blockstack Browser 0.28.0(94)
- How you installed Blockstack
Via dmg file from blockstack.org/browser.  Upgraded previous instance of 0.26.2

- Steps to reproduce
1. Clean install or 'Reset Browser' from settings on version 0.26.2.
2. Restore id (dantrevino.id).  Add account twice for other ids (portland.id, device.id) owned by this id.
3. Note that I saw 500 errors for localhost:6270, the IDs were not updated in the UI, and at this point I realized I was still on 0.26.2
4. Quit Blockstack by clicking the icon in the top bar (ie. command-q)
4. Install dmg file from blockstack.org/install.  Choose "Replace".
5. Navigate to IDs

- Screenshots or videos
<img width="757" alt="screen shot 2018-04-18 at 9 25 18 am" src="https://user-images.githubusercontent.com/7738/38946417-3da4a558-42ee-11e8-9643-c61b984b0700.png">

- Logs
Lemme know what you need.

**Comment by kantai** [comment]
I think this is probably related to #1278 -- if you add another ID after `dantrevino.id` is it `ID-1DY24d..` again?

**Comment by kantai** [comment]
Thanks for reporting this @dantrevino -- will close this in favor of #1278
