### ISSUE TITLE
Disable remote logging & Remove log server from macOS app

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1288]
We have a log server in the macOS app that listens on port 8333 for log entries from the javascript app.

Given the large amount of personal data that's in macOS's logs, that turned out to be poor way for users to share their logs with developers.

1. disable remote logging in the javascript app - this can be as simple as removing the following block of code: 

```
if (portNumber > 1024 && portNumber <= 65535) {
    remoteLoggingEnabled = true
}
```

and associated appenders.

2. remove the log server from the macOS app

@aulneau mentioned he has a better solution than log4js - let's start a new issue to discuss the replacement and work it into our sprint schedule!

**Comment by markmhx** [comment]
I'm closing this out since it appears resolved by the above PR: https://app.zenhub.com/workspace/o/blockstack/blockstack-browser/issues/1291
