### ISSUE TITLE
Add Bitcoin wallet support

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#129]
Relevant pages:

- DepositPage.js
- WithdrawPage.js

*Note: there are already pages for depositing and withdrawing bitcoins, but they are hidden from the dashboard and they are not yet functional.*

Already built out wallet services to look into:

- Copay (https://github.com/bitpay/copay/blob/master/src/js/services/walletService.js)

**Comment by shea256** [comment]
@larrysalibra should we move this to 0.3?

**Comment by larrysalibra** [comment]
Basic bitcoin wallet: single address, deposit & withdraw all funds is working. 

Here are some additional features we might consider in the future: #167 #168 #169 #170 #171
