### ISSUE TITLE
Replace log4js with something else

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1291]
Regarding https://github.com/blockstack/blockstack-browser/issues/1288, we're looking to remove the logging server from the macOS client. I've looked at implementing webpack in place of gulp/browserify so that we could implement things like HMR and other newer frontend workflows into the browser, and the issues I ran into were related to log4js and its incompatibility with webpack.

In order to figure out what we should replace it with, I think we need to ask the question: why do we have logging in the first place? Is it for users to be able to share with us errors? If that is the case, then maybe rather than using logs to do this, we should think about implementing better error handling throughout the application. With react 16+ there are now [error boundaries](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html) we can use. 

I think in addition to better error handling in general, we can use things like redux logger and console.log for logging everything we need. (or if console.log) will not run in the macOS/other OS clients, do we need to have logging on those?

**Comment by wbobeirne** [comment]
We've pretty much done this with our webpack config redirecting log4js imports to app/js/logger.js
