### ISSUE TITLE
account problem and web app and mac app

### ISSUE THREAD

**Issue by yoga1314** [blockstack/blockstack-browser#1300]
- Mac os 10.13.4 beta
- Chrome
- Blockstack 0.28.0
- GitHub download

mac app problem:
in my Mac app menu ，no account but have ids，
I follow the steps on github, but after npm install, there is no core api but log server api, after running npm run dev, the browser will directly enter the get started interface. There is no account registration interface.
web app problem:
I get a id, and validated with github,but the id is not useful in mac app.

**Comment by moxiegirl** [comment]
@yoga1314 Apologies for the delay in response. Can you provide a screenshot of where you see the problem?  I suspect this might just be part of our terminology, we are looking at trying to improve.

**Comment by wbobeirne** [comment]
Closing as stale.
