### ISSUE TITLE
Remove complexity around state and redux persist in browser

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1304]
Currently we're using redux-persist more like a database than anything else. There have been some reports of bugs directly related to the way we're dealing with state in the browser eg https://github.com/blockstack/blockstack-browser/issues/1278

We should take a look at what really needs to be persisted, if anything, and also outline our goals with regards to the general state mangement of the browser and then remove anything we don't need.

**Comment by wbobeirne** [comment]
Closing to consolidate with #1553 since there's some recent discussion in there.
