### ISSUE TITLE
Profile Looks Different

### ISSUE THREAD

**Issue by xanbots** [blockstack/blockstack-browser#1305]
When using apps, my profile looks different than it should. My picture does not show up.
<img width="555" alt="screen shot 2018-04-25 at 9 37 10 am" src="https://user-images.githubusercontent.com/31934541/39249281-5023ddd8-486c-11e8-996f-1e89d72d82e4.png">

**Comment by yknl** [comment]
Hey @xanbots this is probably an issue with the app. Let us know if this happens with every app you use.

**Comment by moxiegirl** [comment]
@xanbots Is this still happening?

**Comment by wbobeirne** [comment]
This was fixed #1613.
