### ISSUE TITLE
Shorten the encrypted seed string

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1310]

**Comment by jcnelson** [comment]
I can take a crack at this.  What source file(s) are relevant?

**Comment by yknl** [comment]
thanks @jcnelson, here's the relevant code: https://github.com/blockstack/blockstack-browser/blob/master/app/js/utils/encryption-utils.js

**Comment by jcnelson** [comment]
Is this guaranteed to only be called on 12-word mnemonics?  Or is it meant as a general encryption method in the Browser?

**Comment by jeffdomke** [comment]
@yknl @aulneau you want some new tickets for updating use of this string in generation, restoration, and emails? LMK.

**Comment by jcnelson** [comment]
Submitted as a PR: https://github.com/blockstack/blockstack-browser/pull/1346
