### ISSUE TITLE
Figure out how to let users get instant and free unique ID's without registering names

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#132]
Some ideas:

- Allow unique IDs to either be Blockstack names or Bitcoin addresses
- Start letting users register subdomains instantly (using dynamic zone file updates)

**Comment by shea256** [comment]
OK what if we created a string field that is globally unique, but with multiple possible formats?

We can use the DID system and do something like this:

- "did:bitcoin:17bWfXcFNNhG8Nu6KZopT17KZGPXxjiA9n"
- "did:blockstack:ryan.id"

Both would be considered valid globally unique IDs.

**Comment by shea256** [comment]
This method would also future proof the unique ID ^

**Comment by shea256** [comment]
If we allow users to register free subdomains initially, we could nudge users into buying full domains with a Stripe window.

**Comment by shea256** [comment]
One more idea:

To apps, globally unique user IDs could be assumed to be addresses.

Then, usernames could be optionally revealed as a bonus.

**Comment by shea256** [comment]
Larry and I were discussing that we can decide to make our long-lived unique ideas equivalent to Bitcoin addresses. Here, if you don't have a name you still have a unique ID. But if you register a name to an address, your unique ID can now resolve to and correspond to your name. If you transfer your name to a new address, you still get to keep the original Bitcoin address as a long-lived ID. It doesn't matter if the original address gets compromised because it's just a historical ID and not an authenticating ID. Each bitcoin address can resolve to multiple names, so we can append an index to the end of the unique ID, where the index corresponds to a position in the list of all names that were ever owned by the address.

Example format:

```
B-<address>-<index>
```

Example ID:

```
B-19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk-0
```

**Comment by v6** [comment]
// , Thanks for the presentation & demonstration at Construct 2017. 

It looks like this system has a lot more thought and effort put into it than many others in the space, and I was glad to see that it works with IPFS. 

However, ways to resolve this without hurting users would depend on how wide you expect future adoption to be, no?

**Comment by shea256** [comment]
We mentioned this in a forum thread here:

https://forum.blockstack.org/t/why-do-blockstacks-use-of-jwt-diverge-from-standards/445/13?u=ryan

**Comment by shea256** [comment]
Hey @v6 thanks! Would love to answer your questions in further detail. Would you mind moving this to a thread on the forum (https://forum.blockstack.org)?

**Comment by guylepage3** [comment]
@larrysalibra @shea256 i found this issue in the "Done" column. Should I close this out?

**Comment by shea256** [comment]
@guylepage3 No I removed it from the milestone. Let's keep it open.

**Comment by v6** [comment]
// , I have commented on some of the implications of this issue here: 

https://forum.blockstack.org/t/how-do-you-reconcile-easy-access-for-new-users-with-namespace-land-rushes-what-if-i-just-register-all-the-top-names-of-celebrities-businesses-i-can-afford/698
