### ISSUE TITLE
On-boarding issues from testing with Android SDK example app

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1324]
Tried out new on-boarding on Android:

Video: https://www.dropbox.com/s/lpbexkv5r26jlo8/2018-05-08%20-%20blockstack-android-onboarding%20-%201.m4v?dl=0

It worked for me on the first try! Great to see!

Collecting some issues I saw in this run through in this issue: (we can divide this into separate issues)

* text entered in the username field is automatically capitalized
* username field accepts a capitalized username (this is an invalid username)
* The blue go button on the android keyboard deletes the email instead of submitting it - this might be caused by implementing the email form and  "continue" button as something other than an html form with a submit button.

Pages are generally too tall to see entry fields on a Pixel 2 without scrolling - I didn't realize i needed to scroll to see the continue button and kept pressing the blue android keyboard button to continue without success.

<img width="475" alt="screen shot 2018-05-08 at 8 23 05 pm" src="https://user-images.githubusercontent.com/597182/39756955-e320e720-52fd-11e8-83d4-97098174e087.png">

Auto-capitalized name:

<img width="487" alt="screen shot 2018-05-08 at 8 23 50 pm" src="https://user-images.githubusercontent.com/597182/39756961-e602cf80-52fd-11e8-8fcd-234bd0ba0188.png">

**Comment by jeffdomke** [comment]
Awesome thx. Most of these are known and should be fixed with update Thomas is working on. The others I'll break into individual tickets. Video is very helpful. 🙏

**Comment by jeffdomke** [comment]
Closing this ticket. Opened: #1326, #1336, #1335, #1337
