### ISSUE TITLE
Names aren't successfully creating on .test-personal.id I was able to create same ID twice

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1327]

**Comment by jeffdomke** [comment]
Just tested a second time. Was able to create `Pizzzzzzzzzzzzzzzzza01` twice in 5 minutes

**Comment by hstove** [comment]
`https://registrar.blockstack.org/v1/names/Pizzzzzzzzzzzzzzzzza01.personal.id` returns `{status: available}`. So either it isn't ever registering subdomains, or there is some error related to the lookup.

**Comment by hstove** [comment]
I think our main takeaway from the conversation this morning is that we need to validate the format of usernames to be only lowercase letters and numbers. Otherwise it seems to be working
