### ISSUE TITLE
As a user viewing my key immediately after creating ID (and entering password), I shouldn't have to enter password a second time, so I can quickly record my seed

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1328]
![Screen Shot 2018-05-08 at 2:45 PM](http://marker.screenshots.prod.s3.amazonaws.com/d8b17ab9b88c4932bc2390b657a44276-1525790714836.png)

https://deploy-preview-1268--reporter-beaver-73821.netlify.com/seed

---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/seed](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/seed)

<table><tr><td><strong>Browser</strong></td><td>Chrome 66.0.3359.139</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1394 x 1076</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by aulneau** [comment]
It would be great if @hstove or @yknl could take this one!

**Comment by jeffdomke** [comment]
Thought it relates to the routes @aulneau setup? Also thought it was working a couple weeks back?

**Comment by aulneau** [comment]
This is fixed in https://github.com/blockstack/blockstack-browser/commit/76d283d8a1ce811b1defae20956c046af27c5dfd
