### ISSUE TITLE
App shows as insecure on Chrome 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#133]
From https://forum.blockstack.org/t/connections-to-web-app-blockstack-names-will-display-as-insecure/427?u=larry

> Chrome shows connections without https as insecure. Since our app will be running on localhost without a valid SSL cert, it and connections to Blockstack IDs (which resolve to 127.0.0.1) will also be marked as insecure.

<img width="421" alt="screen shot 2016-12-21 at 10 32 52 pm" src="https://cloud.githubusercontent.com/assets/597182/21393017/8f3abcf6-c7cd-11e6-912a-e963b87a1b88.png">

**Comment by shea256** [comment]
@larrysalibra What do you think are the ways we can address this issue?

Can we have the installer generate a certificate and have that applied to the locally running process?

@jcnelson @muneeb-ali thoughts on this?

We could also push this issue off. What are the attack vectors here we're most worried about in the short term?

**Comment by muneeb-ali** [comment]
Yeah, we can generate a self-signed certificate. The only issue is that some browsers now show a warning for a self-signed certificate as well (I'm trying to remember if this happened with my self-signed certificate on the resolver and then we had to switch over to let's encrypt). 

Using let's encrypt can be the other option but that's a much bigger dependency and there might be issues for people behind NATs.

**Comment by shea256** [comment]
With Let's Encrypt, we'd need to prove we have access to a given domain and tie the certificate to that domain. Not sure this route is possible for us here, unless I'm missing something.

Is there a way we could use a self-signed certificate and then use root access to trick Chrome into thinking it's not actually self-signed?

Is there a way we can create a throwaway CA and then add it to the OS's trusted ring? This may be a really bad idea haha but I'm just trying to explore the idea space.

**Comment by shea256** [comment]
@mfreed Any thoughts on the best course of action here?

**Comment by muneeb-ali** [comment]
Yes, correct. Let's encrypt asks for a publicly routable domain so this won't work. Self-signed certs can be tied to an IP address or localhost (but the browsers might still complain, depending on the browser).

**Comment by shea256** [comment]
I tossed this question over to a friend and he said the following:

> Chrome has an internal flag that’ll tell it to not validate certs for localhost:
chrome://flags/#allow-insecure-localhost
>
> That’ll let you generate a self-signed cert at install time.

**Comment by mfreed** [comment]
This might require that the user manually change Chrome's configuration, though?

Alternatively, is the URL interface you want something like:

    mfreed.id

or

     blockstack.org/mfreed.id

If the latter, then you might be able to avoid self-signed certificates (never a great sign for security!) but configure local dns service to map blockstack.org to 127.0.0.1 (or the machine's public-facing IP address).

Two questions remains, though:

1. will Chrome accept a local IP address (esp. if accompanied by a good certificate).

2. Does Chrome support DNS SRV records?  If so, you can return the port of your local proxy (3000) in the DNS query, as opposed to just an IP address.

**Comment by shea256** [comment]
@mfreed wrote:

> This might require that the user manually change Chrome's configuration, though?

If our installer has root access then we should be able to change the configuration automatically.

**Comment by shea256** [comment]
@mfreed wrote:

> Alternatively, is the URL interface you want something like:
> mfreed.id
> or
> blockstack.org/mfreed.id

We'd want something like this:

```
blockstack.home
```

I'm specifically referring to the dashboard for managing identity and storage on localhost.

See this screenshot:

![screen shot 2017-01-25 at 5 30 18 pm](https://cloud.githubusercontent.com/assets/994646/22312049/4c2e41fe-e324-11e6-85ae-d815edb41694.png)

We can map `blockstack.home` to `localhost` and then serve the dashboard on port 80 instead of port 8888.

**Comment by larrysalibra** [comment]
> If our installer has root access then we should be able to change the configuration automatically.

Chrome isn't the only problem. Firefox does this as well ->

<img width="452" alt="screen shot 2017-01-26 at 7 11 34 pm" src="https://cloud.githubusercontent.com/assets/597182/22330957/616fe46e-e3fb-11e6-900e-e26d337f784b.png">

@shea256 said  
> Can we have the installer generate a certificate and have that applied to the locally running process?

Don't see why not. It should work on the 3 major desktop platforms. 

@muneeb-ali said 
> Yeah, we can generate a self-signed certificate. The only issue is that some browsers now show a warning for a self-signed certificate as well (I'm trying to remember if this happened with my self-signed certificate on the resolver and then we had to switch over to let's encrypt).

We should be able to generate a local CA, sign the self generated cert with the local CA,  add the local CA to the operating system and/or browser trust stores so that everything trusts it.

I believe IE/Edge/Safari use the OS list of root CAs. I think Firefox uses its own list on all platforms. Chrome might as well - not sure. Potentially lots of combinations and edge cases to handle.

**Comment by larrysalibra** [comment]
@shea256 
> We could also push this issue off. What are the attack vectors here we're most worried about in the short term?

This is more of a UX issue than an attack vector issue. As of Jan 1, 2017, chrome will put the words "not secure" next to the address bar whenever our localhost app has password fields, etc. It's going to confuse ppl.

I think we can push it off for now but should keep it in mind.

**Comment by shea256** [comment]
Just found this on StackOverflow:

http://stackoverflow.com/questions/8169999/how-can-i-create-a-self-signed-cert-for-localhost

> In Keychain Access, double-click on this new localhost cert. Expand the arrow next to "Trust" and choose to "Always trust". Chrome and Safari should now trust this cert.

**Comment by larrysalibra** [comment]
This will be resolved when we move the browser to a native app window: https://github.com/blockstack/blockstack-browser/issues/599
