### ISSUE TITLE
Confirm your key step – not implemented

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1330]
![Screen Shot 2018-05-08 at 2:50 PM](http://marker.screenshots.prod.s3.amazonaws.com/d3b76c3d940a4c19ba4a21987323a27f-1525791051985.png)
---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/seed](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/seed)

<table><tr><td><strong>Browser</strong></td><td>Chrome 66.0.3359.139</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1394 x 1076</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by jeffdomke** [comment]
UI for this is changing to selecting words from buttons, but still need to generate the random request for two words and then validate the user has selected the correct two words in any order.

**Comment by wbobeirne** [comment]
This has been implemented correctly.
