### ISSUE TITLE
Confirm keyboard submit buttons properly fire on desktop, iOS, android

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1335]

**Comment by aulneau** [comment]
Fixed in https://github.com/blockstack/blockstack-browser/commit/76d283d8a1ce811b1defae20956c046af27c5dfd, but now there is a new bug where sometimes if you are focused in a field, you have to leave the field and then hit the button (can't hit the button while focused in a field) cc @hstove
