### ISSUE TITLE
Username/ID capitalization suppression

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1336]

**Comment by jeffdomke** [comment]
@larrysalibra brought this up. Should we suppress caps in the UI?

**Comment by larrysalibra** [comment]
One thing we should do is set autocorrect to false in the input component

**Comment by hstove** [comment]
Yeah, we should do both.

**Comment by aulneau** [comment]
So I've spent some hours trying to remove autocomplete from these forms but it seems as though in the latest Chrome, there is currently no way to disable autocomplete. I've tried every method I've been able to find. @hstove if you have some time I'd love some help on this
