### ISSUE TITLE
registrar setup for blockstack.id

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1338]

**Comment by aulneau** [comment]
@jcnelson do you know the status of this?

**Comment by jcnelson** [comment]
No--I need to find out where the keys are for `blockstack.id` (I don't have them, since I'm not the one who registered it).

**Comment by aulneau** [comment]
cc @muneeb-ali @shea256

**Comment by shea256** [comment]
I actually don't think I have it. Are there other options we have?

**Comment by kantai** [comment]
`bsk.id` ?

**Comment by jeffdomke** [comment]
A couple other options were tested. They were all junked in favor of that one. We should dig for it. Anyway to find out who owns? Can we just ask the community?

**Comment by jeffdomke** [comment]
Sounds like this is borked. Closing.
