### ISSUE TITLE
Browser.Blockstack.com ID app login loop

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1341]
![stuck in browser loop](https://user-images.githubusercontent.com/767828/39835249-9e7159de-539d-11e8-9aee-46db34edbc91.gif)

**Comment by jeffdomke** [comment]
I've just created an ID in browser.blockstack.com. Then I want to access an app. Tries to redirect me to browser, or web app, when I do it asks me to download browser. Stuck in a loop.

**Comment by wbobeirne** [comment]
Looks like your original request came from a test deploy site, which didn't have the same credentials as `browser.blockstack.org`.
