### ISSUE TITLE
Email capture checkbox – both for community and developer news placed in email sent check screen

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack-browser#1345]
Eventually this could help tailor the information given and resources provided, but really is just meant to get a more accurate view of number of developers starting to use Blockstack. As everyone's first step is the browser, this would make it easy to quickly understand the nature of new signups. For non-devs we can help them along with more basic content and promote apps to them if they choose to stay on the email list. I think everyone will appreciate getting information most relevant to them.

**Comment by hstove** [comment]
I think the main question here is where we store that data

**Comment by larrysalibra** [comment]
From an implementation perspective adding a field to mailchimp shouldn't be an issue.

However, this is really a product issue so looping in @jeffdomke on this.

He's spent a lot of time looking at and fine tuning the on-boarding process and is in the best position to think about whether or not this makes sense.
