### ISSUE TITLE
Desktop — update designs to be optimized for non-mobile conditions: Desktop web and blockstack browser.

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1348]

**Comment by aulneau** [comment]
Implemented in https://github.com/blockstack/blockstack-browser/commit/76d283d8a1ce811b1defae20956c046af27c5dfd, however we'll need to decide on what kind of content/copy we want to show

![screen shot 2018-05-16 at 5 45 34 pm](https://user-images.githubusercontent.com/11803153/40148084-d8feeb86-5931-11e8-9f63-8b4e2b72adb5.png)


I had imagined this content being educational and would change on the various screens you navigate between.
