### ISSUE TITLE
Human-readable ID: The data associated with my Blockstack ID seems to have been lost

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack-browser#1350]
Blockstack Bug Report - unfortunately this person did not leave an email address.
--
**What kind of issue did you encounter?:** Bug

**Describe the issue you encountered**
When going through process of acquiring a human-readable ID the data associated with my Blockstack ID seems to have been lost, specifically my proofs. After a couple hours it seems the human-readable ID is now associated with my BSID, but the proofs are still gone. Seems like there might be a data loss bug somewhere in the workflow. | 2018-05-08 17:06:38 | Bug | When going through process of acquiring a human-readable ID the data associated with my Blockstack ID seems to have been lost, specifically my proofs. After a couple hours it seems the human-readable ID is now associated with my BSID, but the proofs are still gone. Seems like there might be a data loss bug somewhere in the workflow.

**Comment by wbobeirne** [comment]
I'm pretty sure this is fixed with #1538.
