### ISSUE TITLE
Implement short code in emails and in restore UI

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1356]

**Comment by aulneau** [comment]
Someone needs to review and approve this PR to be able to implement shorter codes -> https://github.com/blockstack/blockstack-browser/pull/1346

**Comment by jeffdomke** [comment]
Still getting long codes in emails?

**Comment by aulneau** [comment]
I did not implement this but I am getting short codes:

Most recent registration:
![screen shot 2018-05-23 at 11 43 27 am](https://user-images.githubusercontent.com/11803153/40438797-a2b37784-5e7e-11e8-8a52-72c7b2e463fd.png)

Older registration:
![screen shot 2018-05-23 at 11 43 53 am](https://user-images.githubusercontent.com/11803153/40438801-a44c9044-5e7e-11e8-828e-c919fa316aeb.png)

**Comment by yknl** [comment]
@jeffdomke Does the 160 character recovery code work? It's at the maximum char length of an SMS message.
