### ISSUE TITLE
Explore Permission Types

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#136]
Here's a table of permission types that may be commonly used. A table of commonly used types will need to be maintained so that they can be translated and displayed in a way the user can understand.

### Permission Types

| Display Name | API Path |
| ------ | ---- |
| - | /stores/helloblockstack.com |
| Your profile | /profile |
| Your email address | /profile/email |
| Your phone number | /profile/telephone |
| Your physical address | /profile/address |
| Your address book | /collections/schema.org:Person |
| Your messages | /collections/schema.org:Message |
| Your images | /collections/schema.org:ImageObject |
| Your audio files | /collections/schema.org:AudioObject |
| Your videos | /collections/schema.org:VideoObject |
| Your notes | /collections/schema.org:DigitalDocument |
| Your calendar | /collections/schema.org:Event |

**Comment by csuwildcat** [comment]
In talking with @shea256, I am of the view that we should not bake fixed nouns into the `/profile` area of the REST API. The major issue here is that there will be many things in the world that have identities, and the present proposal bakes in the assumption that the profile is for a person. Following on to that is the fact the object at the `/profile` endpoint may be of any object type from a wide array of schemas, so promoting properties into the REST path enters a dragon's den of cross-schema noun conflicts and countless considerations of non-human property promotion into the path.

One option is to encode subvalues in the Profile object that require permissions as ID'd pointers to objects in the user's `/collections` where the data lives and can be accessed (assuming the requesting entity is permitted to do so)

**Comment by guylepage3** [comment]
@shea256 will coordinate with @jcnelson on this for Portal and Core.

**Comment by larrysalibra** [comment]
This issue doesn't belong in the browser repo - it probably belongs in the Gaia hub repo: https://github.com/blockstack/gaia
