### ISSUE TITLE
"Copy to clipboard" –> "Copy 12 words"

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1361]

**Comment by jeffdomke** [comment]
Seems like this should have some kind of feedback. "Copied" or some kind of visual confirmation that something happened.

**Comment by aulneau** [comment]
This issue is only referencing the changing of the words, not the functionality of the button. Please refer to this issue for the functional aspect of the copy button -> https://github.com/blockstack/blockstack-browser/issues/1329 (marked still in progress)
