### ISSUE TITLE
/seed confirm step: This is currently gameable, user can simply click all pills until a valid state exists. Needs to be setup where user can fail when attempting.

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1362]

**Comment by aulneau** [comment]
Some questions related to this:

- When they fail what should we do? some of my ideas:
   - re-order their words
   - change which words we want them to find
   - Do we send them back to their words with a message like 'better double check your phrase'?
- Also to what degree does this matter? (as it's just for their own account security, if they game it, so be it?)

**Comment by jeffdomke** [comment]
My suggestion: Prompt users for two words (A and B) from the randomized list. User can tap two words then they automatically 'submit'. If they select A and B in either order, test passes. If they fail, an error flashes, and the test resets. Upon reset, the A and B words in the prompt change. 

I wouldn't send them back that seems disorienting.

**Comment by jeffdomke** [comment]
I can't get past the "Unlocking seed" step. Just hangs. 

```Uncaught (in promise) Error: bad header; couldn't find a good version (got 4147674983)
    at Decryptor.read_header (main.js:252829)
    at main.js:252933
    at Decryptor.run (main.js:252938)
    at main.js:253135
    at Object.decrypt (main.js:253149)
    at main.js:24396
    at new Promise (<anonymous>)
    at main.js:24395```

**Comment by yknl** [comment]
@aulneau yes, I changed it to `base64` because it wasn't able to decrypt the seed from the recovery link.

**Comment by jeffdomke** [comment]
Looking good. Seems to be an exception. To reproduce: 
1. Go to test screen
2. Find one of the words
3. Tap that one word twice. 
4. Submit. 
5. Test passes.

**Comment by aulneau** [comment]
fixed in https://github.com/blockstack/blockstack-browser/commit/3ecfe0ced6595deb1eb03b67da5faf39cd86457c#diff-046828c3173f114654d88fd5327e1432R125
