### ISSUE TITLE
Onboarding identity creation broken

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1365]
Looks like the identity wasn't properly generated during onboarding
`ID-undefined`
![image](https://user-images.githubusercontent.com/29081231/40196574-eb4966ce-59de-11e8-8607-77879e0d6bb3.png)

**Comment by aulneau** [comment]
Yeah I saw that. However it does show up after some time, just not immediately (i am not sure why)

![screen shot 2018-05-17 at 3 01 52 pm](https://user-images.githubusercontent.com/11803153/40200947-4719be50-59e3-11e8-928a-c798f0ba5709.png)
