### ISSUE TITLE
Replace Diffuse icon with a more colorful version

### ISSUE THREAD

**Issue by icidasset** [blockstack/blockstack-browser#1368]
Hey folks,

I made a more colorful version of the icon:

<img src="https://diffuse.sh/images/icon-square-ws.png" width="128" />

Would it be possible to replace the icon on the homescreen?
Thanks!

**Comment by icidasset** [comment]
Friendly bump 😀 
Can make a PR if that's more convenient.

**Comment by icidasset** [comment]
Sounds great @aulneau ! `app.co` is also using the old icon, but I've sent an email to `hello@app.co` with links to the new icons.

**Comment by markmhx** [comment]
I'm closing this issue since I believe this PR should resolve it once released soon: https://github.com/blockstack/blockstack-browser/pull/1823
