### ISSUE TITLE
Replace logger with something webpack compatible

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1373]
In relation to https://github.com/blockstack/blockstack-browser/issues/1347, the main thing preventing us from using webpack is the logger.

**Comment by hstove** [comment]
Would [this workaround](https://github.com/log4js-node/log4js-node/blob/master/docs/webpack.md) possibly help?

**Comment by aulneau** [comment]
I had played around with a webpack branch and found that workaround and it did not work. If you have time/want to try it out, please do! I'll take a look at webpack stuff after the onboarding has been shipped!

**Comment by wbobeirne** [comment]
Webpack is in now, we've worked around the logger.
