### ISSUE TITLE
Successful restore fails. Not sure what is happening. This was from correct code and password

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1380]
![Screen Shot 2018-05-24 at 4:44 PM](http://marker.screenshots.prod.s3.amazonaws.com/d5548c733b514e7fb026636244519305-1527180253191.png)
---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in)

**Comment by aulneau** [comment]
see https://github.com/blockstack/blockstack-browser/issues/1371 restore is being fixed today
