### ISSUE TITLE
Enter name, remove, still looks valid

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1382]
![Screen Shot 2018-05-24 at 4:49 PM](http://marker.screenshots.prod.s3.amazonaws.com/5f4ebca395ad44bcbe120d45f1c79034-1527180596072.png)
---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-up?redirect=%2F](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-up?redirect=%2F)

**Comment by aulneau** [comment]
We are no longer validating on blur because of this bug https://github.com/blockstack/blockstack-browser/issues/1360, which would result in possible edge cases such as this. cc @yknl

**Comment by yknl** [comment]
We should reset the error message in the onChange event
