### ISSUE TITLE
Encrypted seed email alignment issues

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1393]
the "Larry9 - Encrypted Seed: Save this email forever" email is misaligned in my email client

Apple Mail Version 11.3 (3445.6.18)

<img width="992" alt="screen shot 2018-05-25 at 11 05 54 pm" src="https://user-images.githubusercontent.com/597182/40551665-3527d536-6070-11e8-8875-b6a7e5122a9e.png">

**Comment by jeffdomke** [comment]
![img_0123](https://user-images.githubusercontent.com/767828/40781112-bda19bcc-64a8-11e8-8d65-c977db8d06f9.PNG)

Still getting the same thing on Spark email client. Seems like this is due to the code. I wonder if there is some way to force it to wrap.

**Comment by larrysalibra** [comment]
This might work: https://stackoverflow.com/questions/499137/css-how-can-i-force-a-long-string-without-any-blank-to-be-wrapped-in-xul-and#499154
