### ISSUE TITLE
Verify recovery phrase screen functionality incorrect/broken

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1396]
By randomly tapping on the words I can successfully "verify" that i've written down the phrase.

The user doesn't need to have written down the phrase to pass this screen. It also doesn't appear to verify correct ordering. 

Also, because "invalid" word choices don't do anything, it appears to the user that the page is broken.

The bitcoin wallet app Copay has a pretty good implementation of this. See notes and screenshots on how to implement this here: https://github.com/blockstack/blockstack-browser/issues/622

Another issue here is that the screen asks me select words 1 (pizza) and 8 (step) but only lets me select words 3 (cycle) and 8 (step).

For video see ~2:59 in video: https://drive.google.com/file/d/1O8M4AQReIoN6ktLS12Nb9duxKOgJAche/view?usp=sharing

**Comment by aulneau** [comment]
yeah this page is currently not fully functional, cc @yknl
