### ISSUE TITLE
Username capitalized in on-boarding screens

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1397]
My username "larry9.test-personal.id" is capitalized as "Larry9.test-personal.id"

Capital letters aren't allowed in Blockstack ID usernames.

![img_5270](https://user-images.githubusercontent.com/597182/40552930-c230002c-6073-11e8-86cb-7ed5897a3a4d.jpg)

**Comment by larrysalibra** [comment]
I'm still seeing this problem both on the screen above and the new authentication screen

**Comment by larrysalibra** [comment]
Still seeing this problem

![img_6263 2](https://user-images.githubusercontent.com/597182/41530799-d3399bae-7323-11e8-9ccd-c8b83333e0b9.jpg)

**Comment by larrysalibra** [comment]
This looks fixed for me on desktop but still happens on mobile.

**Comment by aulneau** [comment]
please refer to https://github.com/blockstack/blockstack-browser/pull/1473 for this issue, should be fixed with any new username after this PR is merged

**Comment by wbobeirne** [comment]
This was indeed resolved in #1473.
