### ISSUE TITLE
Back buttons on android break flow and return user to start even when ID successfully created

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1398]

**Comment by timstackblock** [comment]
The web app works as expected I tested this on my Galaxy 9 handheld device. Then I ran a test with a cloud device both worked exactly the same. Creating a new account then selecting the back button after the password is entered but before the email is entered still allows the user to visit a valid blockstack ID account page. You will have to reload the page to refresh the browser but your ID is created correctly.


See a video of the test below
https://screencast-o-matic.com/watch/cqfobBZr0Y

**Comment by timstackblock** [comment]
TEST RUN 1
Google Pixel 3 XL
Release2018, November
OSAndroid 9.0
BrowserChrome
Screen Size6.3 in - 2.76 x 5.67 in
Resolution1440 x 2960 px
Viewport412 x 846 dp
Aspect Ratio18.5 : 9

TEST RUN 2
Samsung Galaxy S9 Plus
Release2018, March
OSAndroid, v9
BrowserChrome
Screen Size6.2 in - 6.2 x 2.9 in
Resolution1440 x 2960 px
Viewport412 x 740 dp
Aspect Ratio18.5 : 9

TEST RUN 3
Samsung Galaxy Note 9
Release2018, August
OSAndroid, v8.1
BrowserChrome
Screen Size6.37 in - 3.01 x 6.37 in
Resolution1440 x 2960 px
Viewport414 x 846 dp
Aspect Ratio18.5 : 9

TEST RUN 4
Google Nexus 6P
eptember
OSAndroid 7
BrowserChrome
Screen Size5.7 in - 2.8 x 5.0 in
Resolution1440 x 2560 px
Viewport411 x 731 dp
Aspect Ratio16 : 9

TEST RUN 5
Google Nexus 6
Release2014, November
OSAndroid, v5
BrowserChrome
Screen Size6.0 in - 2.9 x 5.2 in
Resolution1440 x 2560 px
Viewport411 x 731 dp
Aspect Ratio16 : 9

TEST RUN 6
Samsung Galaxy S9 Plus
Release2018, March
OSAndroid, v9
BrowserFirefox
Screen Size6.2 in - 6.2 x 2.9 in
Resolution1440 x 2960 px
Viewport412 x 740 dp
Aspect Ratio18.5 : 9

**Comment by timstackblock** [comment]
This also worked in Android studio I think we can close this issue, I believe it may have been with an older android phone and OS.
