### ISSUE TITLE
12 word restore – enter step is misleading, this is a set step

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1401]
![Screen Shot 2018-05-25 at 7:48 PM](http://marker.screenshots.prod.s3.amazonaws.com/24e17aa7cb864d7db62357115d5b802d-1527277684368.png)
---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in)

**Comment by jeffdomke** [comment]
@aulneau shouldn't this step be a double password same as the password creation step in the main flow. This is also the way the current browser works.

**Comment by aulneau** [comment]
oh sure yeah that makes sense
