### ISSUE TITLE
Link from email hangs after password

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1405]
https://deploy-preview-1268--reporter-beaver-73821.netlify.com/seed?encrypted=7465e95adc0a61d0ab8306125451ac0b6b5536967ec6dcaae25be23835dd063a9ad0fe44972ebe212cb2a103c136843c62b06ed7cfe4e86e70374c477f0b2f46bc7c0d8c41528980e049da85b526e6e5

1. Open Secret Key Email
2. Click link
3. Link loads, enter correct password
4. Hangs forever

**Comment by jeffdomke** [comment]
<img width="1474" alt="screen shot 2018-05-25 at 5 53 07 pm" src="https://user-images.githubusercontent.com/767828/40567704-805fa30c-6044-11e8-9afe-7438469279e8.png">

**Comment by yknl** [comment]
All the previous email links no longer work because we changed the encoding on the magic codes. If you try with a newly sent email it should work.
