### ISSUE TITLE
How do I recover an ID? This is why there was an interstitial first screen with no focus in the mockups

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1406]
![Screen Shot 2018-05-25 at 10:22 PM](http://marker.screenshots.prod.s3.amazonaws.com/f981141b554044e98af46029cd38d304-1527286968638.png)

Worried 90% of users wouldn't scroll down and find the thing they need. Add another state or screen or no focus. 

---
### More Info

**Source URL**: [https://www.dropbox.com/preview/Public/IMG_0118.PNG?role=personal](https://www.dropbox.com/preview/Public/IMG_0118.PNG?role=personal)

**Comment by aulneau** [comment]
Can you elaborate on scrolling? Or elaborate more in general on what this means
