### ISSUE TITLE
Focus state messed up on iOS chrome

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1407]
![Screen Shot 2018-05-25 at 10:24 PM](http://marker.screenshots.prod.s3.amazonaws.com/0df9c874bd0846449ddb4e3a4308fba2-1527287044997.png)

Keyboard should be up but it isn't. Field thinks it is. To reproduce just load the URL in chrome. 

---
### More Info

**Source URL**: [https://www.dropbox.com/preview/Public/IMG_0117.PNG?role=personal](https://www.dropbox.com/preview/Public/IMG_0117.PNG?role=personal)

**Comment by aulneau** [comment]
I think this is an autofocus bug with the browser, not with our code. I've seen this and tried to debug with no solution other than to disable autofocus.
