### ISSUE TITLE
Accessing key in iOS chrome hangs

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1409]
![Screen Shot 2018-05-25 at 10:26 PM](http://marker.screenshots.prod.s3.amazonaws.com/e118686cc8864bdaafe855511dc999ba-1527287210014.png)
---
### More Info

**Source URL**: [https://www.dropbox.com/preview/Public/IMG_0122.PNG?role=personal](https://www.dropbox.com/preview/Public/IMG_0122.PNG?role=personal)

**Comment by aulneau** [comment]
Can you confirm this is not an old id (with non base64 encodings)?

**Comment by aulneau** [comment]
cc @jeffdomke can you confirm this still happens with a fresh account?

**Comment by aulneau** [comment]
I'm going to move this to delivered @jeffdomke
