### ISSUE TITLE
Email storage copy 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1411]
“Your email is only for delivering recovery instructions. Blockstack does not store emails.”

I believe we do store email addresses. Copy needs to be adjusted to be consistent with this.

**Comment by aulneau** [comment]
I agree -- technically though I haven't included the function that adds in the email to mailchimp, so currently we don't store any emails with this new build. cc @yknl @jeffdomke 

I'll add it back in, but we'll need new copy, and I'll be adding in the checkbox to opt in.

**Comment by larrysalibra** [comment]
New copy "Your email is needed for critical recovery instructions." is much better!
