### ISSUE TITLE
Sign-in with a new test-personal.id subdomain restarts the onboard flow

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-browser#1415]
What happens:

* I complete the onboard flow with a new subdomain
* I try to sign into an app
* I get redirected to the Blockstack Browser
* The Blockstack Browser prompts me to begin the onboarding process, despite having just done so.

What I expect to happen:

* I get directed to sign in with an ID.

**Comment by aulneau** [comment]
hmm I just went through the process from the browser homepage, and then signed up, and then went back to the home page, opened an app, and then went to sign in and my account was there and worked as expected. Can you try again (with the latest build/links) and see if it happens? 

Can you also keep an eye on the console and report anything that looks relevant back? Thanks!

**Comment by aulneau** [comment]
I have not been able to reproduce this. I'm going to close this if I don't hear back from @jcnelson or someone else reporting the same bug cc @yknl

**Comment by yknl** [comment]
Using the latest version in the `feature/onboarding-flow` branch I was able to onboarding and sign in to both a desktop app and an iOS app using the iOS SDK.

**Comment by jcnelson** [comment]
The problem happens when I'm using an incognito Chrome window, and I try to open an app.  The app opens in my normal Chrome window, and the login gets stuck.  When I copy the URL into my incognito window, I still get prompted to enter my private key password.  I'm told that I'm up-to-date, and I get sent to the Blockstack home page.

**Comment by aulneau** [comment]
So you have an ID that you have restored in your incognito instance, and when you log into an app, eg from stealthy, you're saying the new tab opens in a non-incognito chrome window, and so you copy the url, eg localhost:3000/auth?authResponse={code}, paste it in, and then you're no longer logged in?

if you could write the exact steps you took to encounter this issue, that would be great! I tried to log into stealthy with an incognito window and it never left, so I could not recreate this issue.
