### ISSUE TITLE
Tapping back while confirming username navigation issues

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1417]
Tapping the back link after confirming username registration, while it is still processing takes the user back to the "create password" page. After 5-10 seconds (presumably when the username registration finishes), it jumps to the "your ID is ready and secure" page.

I tried this a second time around and made a video and I ended up at the enter email address after tapping back a couple times because it wasn't responding at first.

Video (see around ~1:20) https://drive.google.com/file/d/1LlCHRbvDwlvpP4xqKGkl50ZQghCyBWYv/view?usp=sharing

**Comment by aulneau** [comment]
We should disable that back action when it's processing. The user should not be able to go back once they have confirmed a username.
