### ISSUE TITLE
"Back to <app>" link on auth page doesn't really make sense on mobile

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1420]
In my view, "Back to < app >" doesn't really make sense on mobile when used with our mobile SDKs:

![img_5313](https://user-images.githubusercontent.com/597182/40716134-8655d714-643a-11e8-9de2-cf45db44138d.jpg)

From the user's point of view they haven't really "left" the native app - they're still "inside" of it.

There are also a number of other interface options to achieve the same ends: 

* an option to "deny" (maybe this could read cancel?)
* a chrome-provided "X" to close the sign in dialog
* an android-provided android button at the bottom of the screen

Don't see this as a blocker for a release but something that can be refined in a future iteration.

**Comment by larrysalibra** [comment]
iOS also provides a cancel button:

![img_5316](https://user-images.githubusercontent.com/597182/40719713-f26ffa72-6446-11e8-90a0-8af14637154b.jpg)

**Comment by yknl** [comment]
The "Back to <app>" button has been removed in the latest version on `feature/onboarding-flow`
