### ISSUE TITLE
Authentication page select ID button unclear

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1424]
Buttons should indicate to the user what will happen when she taps or clicks it.

When I load the authentication page, my eyes are immediately drawn to the large purple button. I'm then confused because the button doesn't have any text on it that tells me what I can do. The only immediately visible action available is the "deny" button. I am confused until I go back and read the less prominent copy at the top of the page.

![img_5316](https://user-images.githubusercontent.com/597182/40717887-930e72a8-6440-11e8-8bc0-9372953ae273.jpg)

Info on how buttons should be labeled:

From [Apple's Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/controls/buttons/):
"Use verbs in titles. An action-specific title shows that a button is interactive and says what happens when you tap it."

From [Android's Material Design guidelines](https://material.io/design/components/buttons.html#text-button):
"A button’s text label is the most important element on a button, as it communicates the action that will be performed when the user touches it."

**Comment by aulneau** [comment]
I would argue that we don't need a button on here to say 'Sign in with this ID'

take a look at the oAuth page from google: (emails have been greyed out)
![group](https://user-images.githubusercontent.com/11803153/40735776-ac830d78-6401-11e8-9b15-ac91544f8ca7.png)

I totally agree with you about needing to be very explicit regarding button labels, but I think this leans more towards the direction that Google has taken (along with other oAuth pages). You're selecting an ID.

The rationale behind why we chose to display the usernames/ids and have that be a selection when you click on it versus selecting an ID and then hitting a button that says 'approve' or 'continue' is that we thought it added an extra step. When I click on an account to auth with via google, that is my selection, I don't have to click another button.

**Comment by larrysalibra** [comment]
> The rationale behind why we chose to display the usernames/ids and have that be a selection when you click on it versus selecting an ID and then hitting a button that says 'approve' or 'continue' is that we thought it added an extra step. When I click on an account to auth with via google, that is my selection, I don't have to click another button.

Totally agree with the rationale - I'm 100% on-board with it.

The google screenshot you shared is a great example because doesn't have the problem I was describing.

In our browser, the accounts are big, bright purple buttons (which look delicious btw) - when I see that screen, my eyes immediately jump to the big purple button.



If I go back to the top and read the page, I see: 

* "back to hello, blockstack"
* "Select an ID"
* and then "hello, blockstack wants to and read your basic data" (just noticed there's a typo in that copy)

Nothing on the page tells me why I'm selecting an ID.

In contrast, with the google example, my eyes are first drawn to the colorful google logo at the top of screen where it says "sign in with Google". I immediately know what I'm doing on this page: I'm signing in with google.  If I continue reading, I'm reminded again what I'm doing by the words "choose an account to continue to dribble.com". Finally, I'm presented with a list of accounts.

To rephrase, the problems I see are: 

1.) the bright colorful button pulls my eye away from everything above it so it doesn't get read until i'm already confused
2.) The copy on the page doesn't say anything about what's action is being performed when I tap the purple button.

**Comment by markmhx** [comment]
I'm closing this issue out in favor of https://github.com/blockstack/blockstack-browser/issues/1424, though I've linked to it from there to capture the above input and conversation.
