### ISSUE TITLE
Photo upload support for Blockstack-provided hosting

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#143]
The upload endpoint for Blockstack-provided hosting, `https://api.onename.com/v1/upload` expects JSON. We need an API endpoint for uploading photos to support photo upload with this hosting option.

In the meantime, trying to upload photos with Blockstack-provided hosting will result in an exception being thrown.

**Comment by shea256** [comment]
Moved this milestone to v0.3.

Let's get this working with the new Blockstack Core integration.
