### ISSUE TITLE
Forgot password and no seed route

### ISSUE THREAD

**Issue by stackatron** [blockstack/blockstack-browser#1432]
Information re recovering with local unencrypted

**Comment by aulneau** [comment]
Currently the seed is never stored locally unencrypted. It always requires a password to see/use/restore, etc.

**Comment by jeffdomke** [comment]
Larger conversation and something Ryan wants

**Comment by moxiegirl** [comment]
@jeffdomke what is a seed route?

**Comment by aulneau** [comment]
@jeffdomke when should we have the convo about this? currently it is not possible from my current understanding of how everything works.
