### ISSUE TITLE
Migration copy change

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1435]

**Comment by jeffdomke** [comment]
![img_d1043ed51012-1](https://user-images.githubusercontent.com/767828/40804835-6f346fcc-64ea-11e8-9b66-60530ce4b41c.jpeg)

**Comment by jeffdomke** [comment]
Had a discussion with Ryan about this. He couldn't understand that the browser was trying to migrate and needed his permission. He was asking if it could just be more plain spoken about is going on. 

Very least, at the top = "Upgrading browser" 

Bigger solution an interstitial/first screen that says "We've updated the Blockstack browser and need to migrate your identity." 

Or open to other ideas.

**Comment by yknl** [comment]
How about this?
![image](https://user-images.githubusercontent.com/29081231/40806936-ee39c24e-64f0-11e8-80a0-8121eed5dda7.png)

**Comment by aulneau** [comment]
or this?

![screen shot 2018-05-31 at 3 56 57 pm](https://user-images.githubusercontent.com/11803153/40807947-4c8e2d86-64eb-11e8-9baf-6319b09d6e86.png)

**Comment by jeffdomke** [comment]
Probably the second one Thomas posted.

**Comment by yknl** [comment]
+1 Go with your version @aulneau
