### ISSUE TITLE
[Bug] Specifically Requiring `react-spring.umd` Instead of the Module Itself

### ISSUE THREAD

**Issue by MichaelFedora** [blockstack/blockstack-browser#1439]
https://github.com/blockstack/blockstack-browser/blob/4b90a3a894e4f61768f89ad1fe2aba7aad23b2e0/app/js/components/ui/components/shell/index.js#L2

https://github.com/blockstack/blockstack-browser/blob/4b90a3a894e4f61768f89ad1fe2aba7aad23b2e0/app/js/components/ui/containers/shell-parent.js#L6

Should be `import { animated } from 'react-spring'` and `import { Transition } from 'react-spring'` respectively. In newer versions of the `react-spring` library the `.umd` file is renamed, so this is somewhat important.

**Comment by aulneau** [comment]
Thanks for this! Feel free to create a branch, eg `feature/update-react-spring-import` and PR to fix this. We're currently not using `react-spring` but it's included because the new onboarding (and other parts of the app) will make use of it in a future release!

**Comment by yknl** [comment]
Fixed in https://github.com/blockstack/blockstack-browser/commit/2484488bdfbf7665359a6462c716523cb37406e2
