### ISSUE TITLE
Make the Build Process More Cross-Platform Compatible

### ISSUE THREAD

**Issue by MichaelFedora** [blockstack/blockstack-browser#1440]
Certain items (specifically the `package.json` scripts as well as the `clean` gulp task) make it so the build process only works on a system with Bash, and has certain things that only relate to macOS.

---

First off, it would be great to move all of the `package.json` scripts under [`cross-env`](https://www.npmjs.com/package/cross-env) so it would work under other OS's (*cough* Windows), like so:

```javascript
{
  ...
  "scripts": {
    "dev": "cross-env NODE_ENV=development ./node_modules/.bin/gulp dev",
    "dev-proxy": "cross-env NODE_ENV=development ./node_modules/.bin/gulp proxy",
    ...
    "test": "cross-env NODE_ENV=test npm run lint && npm run flow && ./node_modules/.bin/gulp test",
    "web": "cross-env NODE_ENV=production ./node_modules/.bin/gulp prod"
  }
}
```

Secondly, putting these items

https://github.com/blockstack/blockstack-browser/blob/4b90a3a894e4f61768f89ad1fe2aba7aad23b2e0/gulp/tasks/clean.js#L9-L12

within a `if(process.platform === 'darwin') { /* ... */ }` would be *fantastic*, because these only apply to the macOS anyways.

---

While these small changes don't fix everything with building on Windows (that requires quite a bit of dep upgrades), these changes are a big step in making the browser a lot more cross-platform compatible building-wise, and help future proof it.

**Comment by aulneau** [comment]
Thanks for this! we will be updating the build processes of this project in an upcoming release and will take these suggestions under consideration. We're most likely going to move away from gulp and use npm/yarn/webpack to handle most of these tasks.

**Comment by markmhx** [comment]
@aulneau Any updates since re: moving away from gulp, etc?

@zone117x you might find this issue interesting

**Comment by zone117x** [comment]
@aulneau fixed this some time ago
