### ISSUE TITLE
A dependency's dependency requires GitHub account

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#145]
Reported on slack:

<img width="603" alt="screen shot 2016-12-27 at 10 49 38 pm" src="https://cloud.githubusercontent.com/assets/597182/21501907/c8b8e3dc-cc86-11e6-9ed4-266d012c13e4.png">

Confirmed on my machine that an `npm install` fails without GitHub ssh credentials.

We shouldn't be including NPM dependencies that include dependencies that require users to have specific accounts (in this case, a GitHub account) to check out. Will try to track down the offending package.

**Comment by larrysalibra** [comment]
Offending dependencies:
https://github.com/blockstack/blockstack-keychains-js
https://github.com/blockstack/blockstack-profiles-js

**Comment by larrysalibra** [comment]
@shea256 can you take a look at these at your convenience?
https://github.com/blockstack/blockstack-keychains-js/pull/5 
https://github.com/blockstack/blockstack-auth-js/pull/7

**Comment by shea256** [comment]
Ah @larrysalibra yes sure thing. I'll make the updates to those packages.

**Comment by MIGUELWAXX** [comment]
cheers

**Comment by shea256** [comment]
Hey @larrysalibra, both of these packages have been updated. Closing this issue out.

**Comment by larrysalibra** [comment]
We haven't updated these pages in browser yet. Re-opening.

**Comment by larrysalibra** [comment]
Updated!
