### ISSUE TITLE
Blockstack Browser does not set usernames after user recovers their ID's

### ISSUE THREAD

**Issue by prabhaav** [blockstack/blockstack-browser#1452]
- Operating system and version: Mac OS X
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Blockstack version: 0.29.1
- How you installed Blockstack: yes
- Steps to reproduce: see attached video

[blockstack_browser_recovery_bug.zip](https://github.com/blockstack/blockstack-browser/files/2077125/blockstack_browser_recovery_bug.zip)

**Comment by yknl** [comment]
Just a clarification, this issue exists for usernames that have been confirmed. The problem goes away after clicking on the IDs page. Most likely the browser hasn't updated the username yet before the auth screen is shown.

**Comment by dantrevino** [comment]
@yknl I'm seeing this consistently each app ... i.e. its not going away.  Tried logging into multiple apps multiple times.  Same OS/versions as @prabhaav

**Comment by yknl** [comment]
@dantrevino what's the username that you're seeing this issue for? Is it a username that you registered within the last couple of hours?

**Comment by dantrevino** [comment]
@yknl  This happens with old IDs.  dantrevino.id

**Comment by yknl** [comment]
Thanks @dantrevino, this problem goes away after you visit the ID's page correct?

**Comment by aulneau** [comment]
should be fixed with https://github.com/blockstack/blockstack-browser/commit/7cdbc12d1892f7a53c4637092f6906d33cd944e9
