### ISSUE TITLE
CORS proxy breaks account registration 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#146]
It looks like the registration endpoint is replying with a redirect. 

<img width="463" alt="485ff7d8-cc5f-11e6-9512-82233ac079f5" src="https://cloud.githubusercontent.com/assets/597182/21526010/1b15d1c8-cd5c-11e6-942b-62b77aff3e9d.png">

Thanks to @shea256 for reporting on pull request #144 

I'll look into this.

**Comment by larrysalibra** [comment]
I can't replicate this error on my computer with the CORS proxy:

<img width="706" alt="screen shot 2017-01-03 at 6 54 11 pm" src="https://cloud.githubusercontent.com/assets/597182/21605782/41ab2b88-d1e6-11e6-9369-a7a675d4e527.png">
<img width="706" alt="screen shot 2017-01-03 at 6 54 55 pm" src="https://cloud.githubusercontent.com/assets/597182/21605784/456be8e8-d1e6-11e6-90d7-2707f43a2a6a.png">

@shea256 Can you take a look at the request that's failing on your side and see why it's redirecting for you?

**Comment by shea256** [comment]
@larrysalibra I haven't had issues lately. What did you do to fix this?

**Comment by larrysalibra** [comment]
@shea256 I didn't do anything. I was never to reproduce the problem. Could have been an intermittent problem with the API during the CORS preflight that was sending a redirect. Either way, let's close this unless the issue reappears.

**Comment by shea256** [comment]
I'm having this issue again.

**Comment by larrysalibra** [comment]
@shea256 Okay. I see you disabled proxy fetch here: https://github.com/blockstack/blockstack-browser/commit/44761a02d505f1289289015255d65a65c7066df0

Was your problem was with proxy fetch interfering with a request to local localhost:5000?  

If so, I added a commit yesterday that skips proxy fetch for localhost: https://github.com/blockstack/blockstack-browser/commit/15147ea98bdca64b7b4d5a46ebf166bdd2db01d4

Did you have this problem after you merged in this commit?

**Comment by larrysalibra** [comment]
Disabling proxy fetch breaks our ability to resolve profiles from servers that don't have CORS headers set properly (like blockstack's s3).
<img width="731" alt="screen shot 2017-02-01 at 4 12 40 pm" src="https://cloud.githubusercontent.com/assets/597182/22501148/15f55232-e89a-11e6-808a-211f23597ddf.png">

**Comment by larrysalibra** [comment]
I've re-enabled proxy fetch to fix the fetching profile problem. https://github.com/blockstack/blockstack-browser/commit/bb42753c4aff9fe5fe74be58f079cb63c47357b4

**Comment by larrysalibra** [comment]
Registration now happens on localhost (with core rest api) and skips the CORS proxy.
