### ISSUE TITLE
Message is confusing. Possibly remove

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1463]
![Screen Shot 2018-06-18 at 8:08 PM](http://marker.screenshots.prod.s3.amazonaws.com/0b401d18cb394c6eb25198191154dc51-1529352537410.png)

https://forum.blockstack.org/t/recover-password/5498/1

Consider moving to the second step, where the password is needed. There is already language there. 

---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in)

**Comment by mrjmd** [comment]
Rolled a quick PR at #1464, let me know if I should add some of this messaging to the next step or not (IMO it's not necessary to add back elsewhere).
