### ISSUE TITLE
Recursive browser loop signing up for browser.blockstack.org

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1469]
Tested this a while back, not sure if it still is possible. 

Spotted by @muneeb-ali 

![stuck in browser loop](https://user-images.githubusercontent.com/767828/41680708-67abb434-74a0-11e8-8ead-ae554ed7fa49.gif)

**Comment by yknl** [comment]
In the gif, it looks like you're logged into the build preview browser webapp and then trying to sign in via browser.blockstack.org. Since they're on different websites, they won't share storage.

**Comment by aulneau** [comment]
Yeah that's what I see too, also if you are talking about differences between `browser.blockstack.org` and the browser application, they do not share storage, so there would be no shared state between the two. If you could elaborate @jeffdomke we can try to dig in and see if there is really a bug or if it's just the nature of how the application currently works.

**Comment by jeffdomke** [comment]
The storage thing wasn't it. Can't remember why I did the gif like that, I recorded it a month ago when Muneeb mentioned the bug and it was a legit issue. Anyway, good news is I just tried it again and the new onbording seems to not have this issue.
