### ISSUE TITLE
Secret recovery phrase should be written left to right, top to bottom

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1470]
In English, we read right to left, top to bottom.

The secret recovery phrase is displayed top to bottom, left to right instead left to right, top to bottom.  While it has numbers which reduces the chance of confusion but feels incredibly awkward to read/write down.

<img width="973" alt="screen shot 2018-06-21 at 11 41 50 am" src="https://user-images.githubusercontent.com/597182/41711502-8715677c-7548-11e8-9dd9-9f7764410015.png">

**Comment by aulneau** [comment]
> In English, we read right to left, top to bottom.

Do you mean left to right?

I agree -- do you think:

```
1    2
3    4
... etc
```
Would work better?

**Comment by aulneau** [comment]
<img width="503" alt="screen shot 2018-06-21 at 11 08 08 am" src="https://user-images.githubusercontent.com/11803153/41731238-79a4c722-7543-11e8-861d-aa73baba72f8.png">

fixed with https://github.com/blockstack/blockstack-browser/commit/bb13b044d517e9b50abbe17fb0e7e8e4fb642a65

**Comment by jeffdomke** [comment]
Not a fan of this. I don't think the statement Larry made would hold up under user testing. I remember we debated the display a ton in the design phase. Maybe any amount of trying to help people is wrong, maybe we should just display the words with spaces exactly as they should be stored and re-entered in the recovery step. It will make the next step a little harder, but maybe worth it. Thoughts on that solution?

**Comment by larrysalibra** [comment]
Yeah left to right.

Agree that doesn’t look much better. It feels too narrow. 

I like Jeff’s proposal.
