### ISSUE TITLE
UI/Keyboard display bugs in Safari

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1475]

**Comment by jeffdomke** [comment]
![image_from_ios-3](https://user-images.githubusercontent.com/767828/41873531-3eacec32-7893-11e8-81b3-18d25028cff2.png)
![image_from_ios-2](https://user-images.githubusercontent.com/767828/41873532-3ec5a1f0-7893-11e8-9632-25ab2288b4f3.png)
![image_from_ios-1](https://user-images.githubusercontent.com/767828/41873533-3ee2d27a-7893-11e8-93f5-b32eb8b43262.png)
![image_from_ios](https://user-images.githubusercontent.com/767828/41873534-3f044fae-7893-11e8-9083-e4789c67df89.png)

**Comment by jeffdomke** [comment]
@aulneau these look pretty bad. Can you please test and get a fix out ASAP.

**Comment by aulneau** [comment]
Can you give more details as to how to recreate this issue?
