### ISSUE TITLE
Social Proofs unverified all of a sudden

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-browser#1477]
Social proofs unverified, but "Social Level" is 5.

- Operating system and version: macOS Sierra 10.12.6
- Browser and version: Chrome  67.0.3396.87 (Official Build) (64-bit)
- Blockstack version: browser.blockstack.org
- How you installed Blockstack: no local install
- Steps to reproduce: visit my profile page
- Screenshots or videos
![screen shot 2018-06-26 at 9 55 42 am](https://user-images.githubusercontent.com/7738/41927737-e1041818-7927-11e8-8d07-082982b6d2b4.png)

**Comment by yknl** [comment]
Thanks for raising this one @dantrevino, looking into this!

**Comment by sebdunkel** [comment]
@yknl I was able to reproduce this as well. 

MacOS Sierra 10.13.5 
Chrome Version 67.0.3396.87 (Official Build) (64-bit)
Blockstack Version 0.29.2 and browser.blockstack.org

Social proofs in the browser show as both verified and unverified (social level remains the same). The explorer still shows them as verified. 

<img width="660" alt="screen shot 2018-06-26 at 12 30 24 pm" src="https://user-images.githubusercontent.com/10814372/41931253-8bc8cda2-794b-11e8-82d2-4661fe5d7758.png">

<img width="633" alt="screen shot 2018-06-26 at 12 30 41 pm" src="https://user-images.githubusercontent.com/10814372/41931247-87b73776-794b-11e8-9d94-326f6402a5f3.png">

**Comment by aulneau** [comment]
fixed with #1478 :)
