### ISSUE TITLE
On slow networks authentication appears broken

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1482]
On a slow network, the browser code will load and the black "help" button will appear with an otherwise white screen for a long period of time before the blockstack id sign in buttons actually appear.  

I suspect this happens while the browser is trying to load the app's manifest.json file in the background, but I haven't had a chance to further investigate. This happened for me when the android device I was testing on had a very poor LTE connection.

Wanted to make a note of it so that someone can investigate further.

If this issue can replicated, we might want to add a loading indicator of some sort.

**Comment by wbobeirne** [comment]
This should be fixed thanks to @aulneau's fancy loader.
