### ISSUE TITLE
Typo in recovery email

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1483]
Blockstack is spelled wrong...see highlighted text

<img width="898" alt="screen shot 2018-06-27 at 12 37 41 am" src="https://user-images.githubusercontent.com/597182/41943099-6733e5ce-79a2-11e8-855d-4070635c6d8e.png">

**Comment by wbobeirne** [comment]
Moving to `blockstack-browser-server` repo since that's what sources the email
