### ISSUE TITLE
Profile page error due to Avatar component

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1486]
The Avatar component causes the profile page to be blank because `stringToColor()` throws an exception when the `id` prop is undefined.

![image](https://user-images.githubusercontent.com/29081231/41998054-c98a044e-7a27-11e8-8fab-a5f7bd95637d.png)

**Comment by aulneau** [comment]
When does the profile page ever have an undefined ID?

**Comment by yknl** [comment]
Not sure.. could be another bug. I came across this using the browser with an existing account.

**Comment by aulneau** [comment]
https://github.com/blockstack/blockstack-browser/pull/1487 should fix it!
