### ISSUE TITLE
The Gaia read URLs in the profile apps object are ignored

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-browser#1488]
A profile has an `apps` entry that maps each application origin to a Gaia URL prefix for reading its data, as follows:
```
    "apps": {
      "https://app.graphitedocs.com": "https://gaia.blockstack.org/hub/16YzkXKsYWZKypRcXk6vn4ETu1GBzoiZLw/",
      "https://www.chat.hihermes.co": "https://gaia.blockstack.org/hub/16wcVWogB3U3GAaHMVRXgWX68mGdN25Xkp/",
      "https://www.stealthy.im": "https://gaia.blockstack.org/hub/1ERc9KRMnpG7x4v8mN8e2WW7viEVbZnpvr/",
      "http://publik.ykliao.com": "https://gaia.blockstack.org/hub/1GzmHhQuUP4aKmnwXLCEEyJ2Won4gZkpJP/",
      "https://blockx-socialapp.herokuapp.com": "https://gaia.blockstack.org/hub/17sZ9xyRQzgiTW1N9RX41BGVdGA2UyDSQr/",
      "https://chat.postly.co": "https://gaia.blockstack.org/hub/1FfmXZ243RaEx4ShvaXSxSjyxoTqX1QMtT/",
      "https://blkbreakout.herokuapp.com": "https://gaia.blockstack.org/hub/1DBd33VtZd8wzHv6ReUnfij3Gwn2TEqL88/",
      "http://app.travelstack.club": "https://gaia.blockstack.org/hub/18KE1m4Y3f5ohLQoiMshLwvx9MGuNDKp9q/",
      "https://testnet.misthos.io": "https://gaia.blockstack.org/hub/1LRQGqYbXV8iZcutEkgBhWkTug3YRrgvMX/"
    }
```

Today, this gets used primarily for multi-reader storage---Alice reads Bob's data using these URLs. 
 However, when Alice signs in and *writes* data, the Browser doesn't give her the matching write URL.  Instead, it passes the one from the settings page.

Ideally, the `apps` object tells the Browser which Gaia hub to write to on sign-in, so the user can (1) specify this on a per-app basis, and (2) we can offload state from the Browser to the user's profile (which I consider to be more authoritative than the Browser settings).

Thoughts? @larrysalibra @yknl @kantai

**Comment by jcnelson** [comment]
This is fixed in the CLI authenticator.

**Comment by markmhx** [comment]
@jcnelson do you know if this is still an outstanding bug?

**Comment by jcnelson** [comment]
Yes, this is fixed.
