### ISSUE TITLE
issue building mac app

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#149]
Hey @larrysalibra I tried building the mac app but I ran into a problem.

It says there's no signing identity present.

I don't have the logs with me right now but I can re-try and post them here.

**Comment by shea256** [comment]
Alternatively, @larrysalibra can you build the app and submit a release to the releases page under the code name "Burgundy": https://github.com/blockstack/blockstack-browser/releases

**Comment by larrysalibra** [comment]
I made a build and submitted it here -> https://github.com/blockstack/blockstack-browser/releases/tag/v0.2.0

Re no signing identity present. The short answer is the signing team ID is stored in the project file, so you'll might need to open xcode and adjust the code signing setting to use your team's certificate.

Find those here:

<img width="962" alt="screen shot 2017-01-20 at 7 40 45 pm" src="https://cloud.githubusercontent.com/assets/597182/22148393/ce0fa594-df48-11e6-8ff6-dfb4b87d92df.png">

Next week, I'll go through the steps on a new macOS user account (that doesn't have my Apple Developer Program signing credentials hanging around the keychain) and document the steps users need to take to use their own signing credentials and update the README accordingly.

**Comment by larrysalibra** [comment]
I've added instructions for building a release here: https://github.com/blockstack/blockstack-browser/tree/dae0e031c63833c6bfea51262cf6baa63124f7cc#building-a-macos-release-for-distribution

**Comment by larrysalibra** [comment]
@shea256 Take a look at the instructions - I'm going to close. Please reopen if instructions are unclear.
