### ISSUE TITLE
Allow free ID registrations after sign in

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1499]

**Comment by wbobeirne** [comment]
Having looked into this a bit, it really bugs me that those two flows have entirely different looks to them:

### Regular Username
![default](https://user-images.githubusercontent.com/649992/42392862-4f5eb370-8122-11e8-8ea9-689dbd8863de.png)

### Subdomain Username
![subdomain](https://user-images.githubusercontent.com/649992/42392874-5670ea16-8122-11e8-837e-b3f2b4fafa1b.png)

It would be great to unify these views into one common use component that looks like the latter, where the only thing that changes is the suffix in the view (".id" or ".id.blockstack")

cc @jeffdomke if you have any thoughts

**Comment by yknl** [comment]
The flows look different because we only updated the onboarding screens and not the regular name registration screens. We should definitely work on making them consistent. When I brought this up I was thinking that we can just re-enable the sponsored name registration code and then look at a full design later on.

**Comment by jeffdomke** [comment]
Yeah completely agree. We just haven't had the bandwidth. I imagine @aulneau also has some thoughts on how to use components to do this in a lean way. We also would need some additional communication and design work to signal the free/sponsored and switching between them. And, it feels confusing to allow ID generation without a name attached like we do now. Separating this one task from the larger systemic implications seems very tricky.

**Comment by wbobeirne** [comment]
The sponsored name screen is deeply embedded into the onboarding code. To reuse that code to work outside of onboarding would require a refactor anyhow, so I see two ways of going about this:

### 1) The Quick Fix

Just add the free subdomain in on top of the existing flow, keeping their implementations entirely separate (Moving some of it out into util functions, of course.) Something like:

![subdomain-old](https://user-images.githubusercontent.com/649992/42395950-b30135e6-812d-11e8-9494-bdd9500a8cb7.png)

### 2) Repurpose Onboarding

Repurpose the onboarding UI to work elsewhere and with multiple options, something like:

![subdomain-new](https://user-images.githubusercontent.com/649992/42396590-4ba2d794-8130-11e8-9515-bce5c3ca6cf2.png)

**Comment by yknl** [comment]
@wbobeirne We had something like this before which we disabled. The quick fix could just be to add this back in. https://github.com/blockstack/blockstack-browser/pull/1204

**Comment by wbobeirne** [comment]
Oh, that totally explains why the flow feels odd, it was meant to check multiple TLDs already! And here I thought I was being clever with my quick fix mockup. Thanks for putting me on the right track, it's up in #1511.
