### ISSUE TITLE
Update take over loaders in onboarding/recovery steps

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1500]

**Comment by wbobeirne** [comment]
@jeffdomke is this good enough of an improvement from the current text-only version, or do you want a more radical change?

![loader](https://user-images.githubusercontent.com/649992/42349564-2b415fe4-807b-11e8-94ba-b75cc6d4e1fe.gif)

**Comment by jeffdomke** [comment]
@wbobeirne yeah, I think that should cover it. Thx!
