### ISSUE TITLE
Move mnemonic decryption to web worker

### ISSUE THREAD

**Issue by wbobeirne** [blockstack/blockstack-browser#1507]
Right now decryption blocks the main thread, causing the whole page to freeze for 2-5 seconds. Moving this over to a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) that takes in a phrase and returns a decrypted key should allow the page to stay responsive during decryption. [Support for web workers is exceptional](https://caniuse.com/#feat=webworkers), so there's little to worry about with incompatibility.

**Comment by aulneau** [comment]
I've been wanting to use this for a while -> https://github.com/developit/workerize-loader

**Comment by wbobeirne** [comment]
We used `worker-loader` (seems nearly identical to `workerize-loader`) on MyCrypto to offload decryption to a worker thread similarly, so there's kind of a reference implementation here:

* The worker - https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/web-workers/workers/fromV3.worker.ts
* The module that manages the worker - https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/web-workers/fromV3.ts
* Actually being called - https://github.com/MyCryptoHQ/MyCrypto/blob/e761b9d1fbeb33ad548f39d68365fd531ea003ae/common/libs/wallet/non-deterministic/wallets.ts#L22-L27

**Comment by wbobeirne** [comment]
Closed via #1539.
