### ISSUE TITLE
Only seeing option to sign into dApps with a previous id instead of new id even after resetting browser and restoring new id

### ISSUE THREAD

**Issue by petec029** [blockstack/blockstack-browser#1514]
After creating a new id on safari when I try to sign into other dApps like Stealthy the only option I see if to sign in with a previously created id.  I even tried resetting the browser and restoring the new id but get the same result.

<img width="458" alt="screen shot 2018-07-05 at 10 18 06 am" src="https://user-images.githubusercontent.com/519271/42403949-2201823c-8153-11e8-8cda-0d58b00bb747.png">

This is the new id I was expecting to appear

<img width="735" alt="screen shot 2018-07-05 at 5 29 32 pm" src="https://user-images.githubusercontent.com/519271/42403971-46c0f026-8153-11e8-85bb-9d4fded9eb72.png">

**Comment by aulneau** [comment]
Hey Peter! Thanks for the issue. When you are loading up from stealthy, is it opening in the blockstack browser, or is it opening in Safari? (or is it in another browser such as chrome or firefox?)

**Comment by petec029** [comment]
I am starting at the home page in https://browser.blockstack.org.  Clicking on the stealthy icon on home page which opens up another safari tab of https://www.stealthy.im.  Then I click on login in blockstack in the upper right corner which takes then opens up another tab in safari with a ulr that starts with http://localhost:8888/auth?

**Comment by wbobeirne** [comment]
@petec029 you'll need to go through the recovery process on http://localhost:8888 with your recovery code from https://browser.blockstack.org. Right now you have different accounts associated with those two clients.
