### ISSUE TITLE
Building native apps should be easier

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1516]
Currently other engineers/community members cannot build the app natively to test. The main blocker is related to our certifications that we use to sign the macOS app (I haven't started debugging windows builds yet).

I think we should automate and abstract away some of the building processes. I've heard very positive things about `fastlane` for building and deploying native apps. see https://fastlane.tools/ and https://github.com/fastlane/fastlane (it might only be for iOS and android, still looking into if we can use it for the macOS app)

I think we would benefit a lot from sinking some time into exploring using fastlane. fastlane also has a tool for certification management -> https://docs.fastlane.tools/actions/sigh/ where you can set things up like production/dev certs and delegate who/how they're used.

cc @yknl @wbobeirne @larrysalibra

**Comment by zone117x** [comment]
@aulneau I think we are pretty good with this now with proper building on Windows and macOS, on local machines and CI. What do you think?

**Comment by hstove** [comment]
Yes, this is much improved. It's quite easy to build the native app now without a cert. I'm going to close it out.
