### ISSUE TITLE
Suggestion: Improve UX of the initial create/restore screen

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-browser#1520]
The font choice on this screen confuses precedence and order. Also, the use of dual buttons and their positioning could be clarified:

![image](https://user-images.githubusercontent.com/1347209/42532523-295ff0ea-8455-11e8-87d8-e9c1641a19b5.png)

Since the recovery sequence is entirely different, using a link in help text is a good way to indicate to the user that recovery is alternate choice and, more importantly, an entirely different flow.  Also, keeping the question label secondary to the dialog should clarify what this dialog is about. Suggested changes:

![image](https://user-images.githubusercontent.com/1347209/42532533-3213b9ce-8455-11e8-9981-9a8e7167939b.png)

**Comment by petec029** [comment]
I like what @moxiegirl is suggesting.  End users are not going to be familiar with the term restore blockstack id. I think 'use an existing blockstack id' is going to make more sense to end users.

I think there is an opportunity to improve the UI/UX design of this screen beyond what @moxiegirl mocked up.

**Comment by wbobeirne** [comment]
This was changed with #1535.
