### ISSUE TITLE
Onboarding doesn't handle subdomain registration errors

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1524]
Errors can be returned by the subdomain registrar. Currently the onboarding flow simply ignores those errors and continues onboarding the user. For example:

* A user may have signed up for too many names already with a given IP.
* The submitted username may have invalid characters -- it seems this happens on mobile, because the mobile keyboard autocorrects the name to capitalized
* The server may be broken

Those errors should be manifested to the end user.

**Comment by wbobeirne** [comment]
Also worth noting the same issues exist with emails, as mentioned in #1506. I don't think either of these failures should be hard stops for users, but they should definitely be aware of them and told how to do these things later.

**Comment by wbobeirne** [comment]
^ Use of that library is blocked by #1479 as it needs a way to handle the imported styles for its theming, which gulp cannot do.

**Comment by wbobeirne** [comment]
I was able to work around this by vendoring the module's theme temporarily. It'll be easy to undo once webpack has landed.
