### ISSUE TITLE
Restore ambiguous result after entering fake key

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-browser#1533]
Before opening an issue:

When reporting a bug, include as much information as possible including:

- Operating system and version: Mac OSX, High Sierra 10.13.4
- Browser and version Chrome: 67.0.3396.99 (Official Build) (64-bit)
- Blockstack version: Webapp --- can't see the version but it is 7/17
- Steps to reproduce:

1.  Save the 12 word passphrase in a text document. Mine was in Atom.
2. When prompted for the passphrase, cut and paste from a the text document.

**What happened**: System prompted me for a password 

This looks like a bug as I am pasting an entirely made up sequence. The system should tell me the phrase is bad, not pass me through to a password prompt.

![2018-07-18_13-36-41](https://user-images.githubusercontent.com/1347209/42906718-c77d8eae-8a90-11e8-8e2a-5b48dd7ea274.gif)

I actually make it through to this:

![image](https://user-images.githubusercontent.com/1347209/42907080-a8317014-8a91-11e8-86de-b261be9af4ca.png)

which actually doesn't look like an error on my part.

**Comment by aulneau** [comment]
> This looks like a bug as I am pasting an entirely made up sequence. The system should tell me the phrase is bad, not pass me through to a password prompt.

There's no way for the system to know if a 12 word phrase is fake or not. (as far as I am aware) cc @jcnelson 

Also your gif does not show a 'password' prompt, it shows an email prompt.

**Comment by aulneau** [comment]
I also don't think users will be making up random 12 word phrases with the hopes that they would work.

However I do think we have a lot to do regarding the handling of errors with the onboarding process.

**Comment by aulneau** [comment]
Okay so I asked @yknl and if a user used their own `BIP39` generator and generated 12 words, it would work the same as if they would be restoring one generated through blockstack

**Comment by wbobeirne** [comment]
`bip39.validateMnemonic` should ensure each word is valid.
