### ISSUE TITLE
Add instructions to user and validation error that account for the new subdomain ID limitations

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1542]
Per the discussion here: 

https://forum.blockstack.org/t/people-are-spamming-id-blockstack-what-can-we-do/5743/52

Seems like we need a short note on the field with the limit. And an error that it is too long. We should probably show a "username not available" message on the dictionary words. Just a suggestion, maybe there are better solutions.

**Comment by yknl** [comment]
Implemented in https://github.com/blockstack/blockstack-browser/pull/1541
