### ISSUE TITLE
Testing on nameless users

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1547]

**Comment by markmhx** [comment]
@jeffdomke I'm not really sure how to interpret this issue. Want to revise it a bit for clarity, or best to close out given its age?

**Comment by moxiegirl** [comment]
@markmhx I think Pete one of evangelists is running into this issue --- hard to tell from the description what prompted it.  He posted in channel Wednesday.

**Comment by markmhx** [comment]
@moxiegirl Got a link handy to his post? I'll take a look. We may want to create a new issue that maps more directly and clearly to his concerns since this one is pretty old and sparse.

**Comment by moxiegirl** [comment]
@markmhx https://blockstack.slack.com/archives/GADLAAFGB/p1552057323032700

**Comment by markmhx** [comment]
@moxiegirl Hmm I'm unable to view that message for some reason, mind checking the link?

<img width="647" alt="Screen Shot 2019-03-12 at 10 54 59" src="https://user-images.githubusercontent.com/28991/54191026-5fe31e00-44b5-11e9-8b26-654fe5629742.png">

**Comment by moxiegirl** [comment]
@markmhx worked for me. the link is to Evangelist official in the open Slack. Looks like you were not in that channel. Invite sent
