### ISSUE TITLE
Automatic multiple ID recovery on restore — discuss proposal on forum and decide

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1549]

**Comment by MichaelFedora** [comment]
Is there a link to the proposal/forum thread that you could put in the OP?

Additionally, you could just put the number of ID's in the profile.json, unecrypted or otherwise. Easy enough to do.

**Comment by wbobeirne** [comment]
Closing in favor of #1550, where most of the discussion is.
