### ISSUE TITLE
design new browser portal profiles landing view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#155]
Design a new Blockstack Browser Portal Profiles landing view

**Requirements**
- [ ] Search bar
- [ ] Personas
- [ ] Register button
- [ ] Import button

**Comment by guylepage3** [comment]
<img width="1250" alt="screenshot 2017-01-25 21 36 15" src="https://cloud.githubusercontent.com/assets/1711854/22318151/5235c4ba-e346-11e6-920b-5614d8b5e132.png">

**Comment by guylepage3** [comment]
@shea256 on the dashboard view of the browser portal we are calling the "Profiles," Profiles. But once the user clicks on the app and enters it, they currently see "Personas."

Should we change Personas to Profiles?

**Comment by guylepage3** [comment]
@shea256 I feel we should add a simple one line of instructions for the user, telling them to register or import their profile and maybe why? Thoughts?

**Comment by shea256** [comment]
@guylepage3 wrote:

> @shea256 on the dashboard view of the browser portal we are calling the "Profiles," Profiles. But once the user clicks on the app and enters it, they currently see "Personas."
>
> Should we change Personas to Profiles?

Yes, let's change it to "Profiles". I feel like it's easier to understand.

@guylepage3 wrote:

> @shea256 I feel we should add a simple one line of instructions for the user, telling them to register or import their profile and maybe why? Thoughts?

Yes, I can work on making the copy a little clearer for the user.

**Comment by guylepage3** [comment]
@shea256 I was thinking we may want to apply the same "app icon" concept to the the profiles view as we will be applying to the dashboard. thoughts?

<img width="1920" alt="screenshot 2017-01-26 11 54 32" src="https://cloud.githubusercontent.com/assets/1711854/22341308/5a76c8ea-e3be-11e6-9d9b-430a7d89164b.png">

**Comment by shea256** [comment]
OK you don't think that would be confusing?

**Comment by shea256** [comment]
I thought this was an interesting UI that Vida put together:

![screen shot 2017-01-26 at 11 57 23 am](https://cloud.githubusercontent.com/assets/994646/22341404/afe1e454-e3be-11e6-8c5e-bb0f03f6e737.png)

Not focusing on the details but more saying that generally a vertical list might be appropriate.

**Comment by guylepage3** [comment]
Well, we are not a vertical viewport at the beginning here. We are launching with desktop. So it will need to be a) responsive b) non-floating. The problem with going vertical is that the user may have to scroll which is a UX loss imo.

Unless we are thinking most users will not have more than 5-6 profiles?

**Comment by shea256** [comment]
Most will not have more than 5-6, that is correct. Most will probably have 1-3.

And I was thinking that we could have a vertical list as an inner div. It doesn't have to be in mobile form but can pop into the mobile list format when the screen shrinks.

**Comment by guylepage3** [comment]
I feel a better layout for desktop might be something along the lines of this.. The reason being is that it allows the user to quickly access the profile they'd like but utilizes the entire screen. I feel this would be a better experience.

This is not the design but a wireframe/concept for the layout

<img width="1478" alt="screenshot 2017-01-26 12 39 29" src="https://cloud.githubusercontent.com/assets/1711854/22343017/7f9d8f90-e3c4-11e6-9026-d55d7ce8734c.png">

**Comment by shea256** [comment]
OK I like that.

But how about we get rid of "Register" and "Import" and just add a "+" button at the end, which takes you to a page that let's you create a new profile?

As far as importing goes, we can insert that in the registration page as an option that let's you switch over. Importing will be much less common than registration.

**Comment by jeffkaplan88** [comment]
My 2 cents is:

(a) Go with "Profiles" throughout - as @shea256 said it's intuitively easier for people to understand
(b) Definitely add a short, simple explanation for both why and how to register/import. A simple value prop and guidance goes a long way for adoption.

- Jeff

shea256 commented an hour ago
@guylepage3 wrote:

@shea256 on the dashboard view of the browser portal we are calling the "Profiles," Profiles. But once the user clicks on the app and enters it, they currently see "Personas."

Should we change Personas to Profiles?
Yes, let's change it to "Profiles". I feel like it's easier to understand.

@guylepage3 wrote:

@shea256 I feel we should add a simple one line of instructions for the user, telling them to register or import their profile and maybe why? Thoughts?
Yes, I can work on making the copy a little clearer for the user.

**Comment by shea256** [comment]
Thanks for jumping in @jeffkaplan88!

Agree with "profiles" and the short, simple explanation.

**Comment by guylepage3** [comment]
Definitely.. Thanks for the feedback @jeffkaplan88.

The more people who jump in the better. 😄 

Here's the v1 final design.. Moving on to the build.. 

<img width="1478" alt="screenshot 2017-01-26 18 03 59" src="https://cloud.githubusercontent.com/assets/1711854/22354150/15f22a3c-e3f2-11e6-85f3-24632acfc0f0.png">

**Comment by guylepage3** [comment]
Here's the v1 final final design.. Moving on to the build.. 

![profiles-desktop](https://cloud.githubusercontent.com/assets/1711854/22384219/6041a280-e49b-11e6-8c0e-2aa8dfd17f30.png)
![profiles-tablet](https://cloud.githubusercontent.com/assets/1711854/22384227/6455f22c-e49b-11e6-8e56-51ddd0772ac7.png)
![profiles-mobile](https://cloud.githubusercontent.com/assets/1711854/22384233/6761c8ce-e49b-11e6-8e70-514e5ab82c3f.png)

**Comment by shea256** [comment]
Awesome! Only thing I think that's needed is a section title that says "My Profiles" or something like that. This is so the user doesn't think the section is for bookmarked profiles of other people.

**Comment by guylepage3** [comment]
**Browser (Desktop)** - InVision link
https://invis.io/N2A7UM1X7#/216416027_05-Profiles-Desktop

**Browser (iPad)** - InVision link
https://invis.io/P6A7UR6RJ#/216417115_05-Profiles-Tablet

**Browser (iOS)** - InVision link
https://invis.io/XBA7URQV6#/216417519_05-Profiles-Mobile

**Comment by guylepage3** [comment]
>Awesome! Only thing I think that's needed is a section title that says "My Profiles" or something like that. This is so the user doesn't think the section is for bookmarked profiles of other people.

Added. See InVision links above

**Comment by shea256** [comment]
Oh hell yeah, this is beauty.
