### ISSUE TITLE
Requesting email scope doesn't actually provide email

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1556]
Requesting the email scope during authentication displays the user interface message about "reading your email", but the response doesn't actually include the email.

The auth response token is below.

I erased my browser and created a new account to make sure there hadn't been some state change and found the same issue.

I'm using Chrome 67.0.3396.87 on Android 8.1.0 on a Pixel 2.

This problem happens on the currently deployed browser.blockstack.org commit: 
https://github.com/blockstack/blockstack-browser/commit/5836e17181e7e0d68a712a75e01f1df1c2f4643f

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJqdGkiOiJjMzZkM2U0Mi1jMDU0LTRhZjMtYjk5MS02ZGM4NmUxZDE4ZmUiLCJpYXQiOjE1MzI1OTA0MTcsImV4cCI6MTUzNTI2ODgxNywiaXNzIjoiZGlkOmJ0Yy1hZGRyOjFQNlhMYzVGRWh6SjlnZVVEWmlQUEJ3MnRBaEFYU01DVnciLCJwcml2YXRlX2tleSI6IjdiMjI2OTc2MjIzYTIyMzk2MTYxNjYzMTY2MzQzMTMxNjQzNTM3Mzg2NDY1MzIzMDM5NjI2MjY2MzY2NjM4NjYzOTYxMzI2NDMxNjEzMjIyMmMyMjY1NzA2ODY1NmQ2NTcyNjE2YzUwNGIyMjNhMjIzMDMzNjUzNTM3MzIzNDM0NjEzNTM4MzQzODM5MzIzODM0MzQzNDMxNjMzOTMzMzUzMTMyNjYzMjMwMzYzMDY2MzY2NjMxMzQzMTY2MzkzMTM4MzgzNjYzMzA2MjY0MzY2MzYxMzkzMDY2NjQzODM3NjIzNjY1MzY2MzYzMzEzMjY2MzgyMjJjMjI2MzY5NzA2ODY1NzI1NDY1Nzg3NDIyM2EyMjM4NjIzNzY0NjE2MzY1NjQ2NTM1Mzg2MjMxMzk2NjMzMzYzNzY1MzI2NjMxNjEzMzM2MzU2NTMyNjY2NDM5NjMzOTMzMzkzMTYzMzA2MjYzMzEzNjM3MzI2NTM5NjQzMzYzNjY2NTY2MzgzMTM1MzgzMDM1MzU2MzM2Mzc2MTMzMzMzMDM0MzAzMTM3NjIzODY1NjUzNzM4MzYzNjM0NjEzOTM0MzgzMzYyMzUzMzMxMzgzODM1NjMzMzMxMzk2NTM1NjIzODM0NjYzODY0NjQzNTM0MzMzMTM5NjU2MzM1MzMzNTM1NjMzNDMyMzIzMTMwMzgzNzYxMzc2NDM4MzczOTMwMzYzMDYyMzI2NDY2Mzg2MzM0Mzc2NjM1MzUzNTM5MzM2MTY1MzgzOTY2MzY2MzY1MzEzNzM0NjUzMDMyMjIyYzIyNmQ2MTYzMjIzYTIyNjI2MTM4MzAzMDM5MzczODY0MzM2MTM4NjIzNzYyNjQ2MzY0NjE2MjMxMzYzMjM3MzkzNzY2MzIzNTM3NjYzNDYzNjE2MzMzMzIzOTM1MzYzNjM4MzkzMDMxMzIzMTYzMzAzMTYzMzc2MTYxMzMzMTM2NjM2MTYzMzgzNzMxMzYyMjJjMjI3NzYxNzM1Mzc0NzI2OTZlNjcyMjNhNzQ3Mjc1NjU3ZCIsInB1YmxpY19rZXlzIjpbIjAzMWU3YTJkYmZkOGI1M2UyNDllMGEwNzRlNGVhNDBiYjMxYTgzZDI2MWU4YTliODczNDFmNDQ0YmU5MTNkMTMyNCJdLCJwcm9maWxlIjpudWxsLCJ1c2VybmFtZSI6bnVsbCwiY29yZV90b2tlbiI6bnVsbCwiZW1haWwiOm51bGwsInByb2ZpbGVfdXJsIjoiaHR0cHM6Ly9nYWlhLmJsb2Nrc3RhY2sub3JnL2h1Yi8xUDZYTGM1RkVoeko5Z2VVRFppUFBCdzJ0QWhBWFNNQ1Z3L3Byb2ZpbGUuanNvbiIsImh1YlVybCI6Imh0dHBzOi8vaHViLmJsb2Nrc3RhY2sub3JnIiwidmVyc2lvbiI6IjEuMi4wIn0.aqVynC28oeJQMsuioWuAPrvfOiG5mdItMaIi6UG9rd7w7HLcGI7tb2rBVT9l9XF7BX7wNbbZTao44a6XfVMnDA
```

**Comment by wbobeirne** [comment]
Can confirm this is happening. However, there's a silver lining here. This means that currently, no apps are _actually_ relying on the email permission. There's been a lot of discussion about whether to keep email as a part of onboarding (#1560), so maybe this gives us the perfect opportunity to remove it since we won't be breaking existing integrations.

We should probably figure out the future of emails in Blockstack before fixing this. In the mean time though, I'd suggest we remove the scope from blockstack.js' documentation.

**Comment by wbobeirne** [comment]
So I just tested this in blockstack.js by adding an email to [this line](https://github.com/blockstack/blockstack.js/blob/master/tests/unitTests/src/unitTestsAuth.js#L304), and didn't get it as a part of the response in the promise. As far as I can tell, this never worked, and may very not work for other metadata options as well. Would definitely like someone more well versed in blockstack.js to confirm this though.

**Comment by markmhx** [comment]
I've created an epic issue here to investigate the proper solution for this further: https://github.com/blockstack/blockstack-browser/issues/1780

As @wbobeirne mentions, removing it from the docs may be the most immediate action, unless we decide to implement it fully instead.

**Comment by friedger** [comment]
The code looks like it is working. https://github.com/blockstack/blockstack-browser/blob/6805a07fcde2e611b5e728534d0a587acc8bc551/app/js/auth/index.js#L504
Using 18.3.0 I managed to receive the email address of the user in the auth response token.

**Comment by hstove** [comment]
Closing this since @zone117x fixed it!
