### ISSUE TITLE
Restoring from seed phrase freezes UI for a few seconds and Nameless User flashes for a second

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1570]

**Comment by wbobeirne** [comment]
#1507 will resolve the freezing UI. I've looked into the flash of nameless user, and it'll just require a bit of refactoring on [this block of code](https://github.com/blockstack/blockstack-browser/blob/master/app/js/sign-in/index.js#L206-L213) to make sure that `refreshIdentities` finishes before we move to the success view. I see that we use some redux actions as promises, e.g. `initializeWallet` in the `createAccount` function, same file. Is that something that redux-thunk typically supports, or should we wait for a `componentWillReceiveProps` change?

**Comment by yknl** [comment]
I think promises are easier, more intuitive to use and won't confused new developers. Also `componentWillReceiveProps` is often overlooked when we make changes and is harder to debug.

**Comment by wbobeirne** [comment]
Closed via #1576.
