### ISSUE TITLE
Improve display of apps on homepage

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1571]
The home screen on the browser is very outdated. We should replace it with a Blockstack specific page on app.co after the redesign is released.

**Comment by wbobeirne** [comment]
This might result in a very... empty and boring homepage. I agree though, the hardcoded list is not the way to go. However, I'd suggest some alternatives:

1. Use some app.co API to get a list of the highest ranked applications and show those in-browser, though still link out to see more.
2. Show only apps the user has already auth'd with, with a link to see more from app.co.
3. A combination of 1 & 2.

Either way, I think this warrants some design love, cc @jeffdomke

**Comment by aulneau** [comment]
@markmhx Yeah I think this is a good idea. I've wanted to spend some time on this kinda thing for a while, I think it's just been unclear as to where this lies with regard to priority. Additionally I think we should talk generally about how we'd want it to work, eg if we want it to link to the app.co profile vs the direct app link. I am also not sure if the app.co response contains the link to the app itself vs the app marketing site.

**Comment by markmhx** [comment]
Yea I'm not sure what App.co provides either, though by default all apps should at least have profiles on App.co. So I'm kind of presuming that linking to App.co profiles may be the best first way to go to keep things simple?

It would be great to link more directly to the destination of choice for a user (e.g. mobile download, web app access) but I think that requires something like https://github.com/blockstack/app.co/issues/215.

**Comment by aulneau** [comment]
Yeah, my only initial hesitation with linking to the app.co profile is that it might be confusing. As a user in an app store, I'd expect to stay within the app store or go directly to the app, not go to this new place I might not know about.

**Comment by markmhx** [comment]
Yea as a user, I'll definitely be a bit peeved if I get sent to yet another page for viewing the app instead of the app itself. I guess I view it as a short-term solution to unlock the main change we want to make to this page, even though we want to provide direct link(s) per app later.

**Comment by GInxh** [comment]
I don't think we should pull the apps at all. 

1. night theme 

2. add all apps in new categories so they are presented by category not earnings or lifetime. 

1. productivity 2. storage 3. social 4. wallets 5. games! etc

3. Have a place to browse apps, and a place to pin apps I use as my own personal blockstack "home screen" So maybe an "apps" tab as shown by Mark's mockup, but also a "Home" tab where it is my own personally pinned dashboard. 

Accomplishing the following will really create user engagement for 

a. discovery of apps 

b. keeping users coming back by having a homepage of apps they know they want to log into everyday. For example, I use the speed dial plugin in my other browsers to pin website I navigate to everyday so I can speed through my usual morning browsing routine.

Enabling this for users would really be a win for us and cement in this idea that they have this growing set of experiences and apps they can return to as a home base.

**Comment by markmhx** [comment]
I'd like to keep this particular issue relatively simple, and while I think some of these ideas are promising (e.g. it'd be handy to see the apps you've already used in one place), I'd like to break them off into separate issues.

I would also encourage us to think of the browser as providing only the functionality that can't be supported elsewhere (as linked from the browser perhaps). App.co and web browsers may be the best places, for example, to categorize apps and bookmark frequently visited ones.

This particular issue is trying to solve one specific problem with the current display of apps: they grow outdated (in terms of both inclusion and ordering) very easily since the list is statically programmed, not dynamically generated.

If this were a clean-slate effort, I'd suggest not listing apps for discovery in the browser at all (per the above point of keeping it specialized). However, we don't want to disappoint developers with their removal, so they've been grandfathered of sorts.

**Comment by jeffdomke** [comment]
We should prioritize the quick fix here. Display list of apps from App.co. The users will have to take a round trip to the app website, but that is probably better than the current state of affairs. cc @GinaAbrams

**Comment by markmhx** [comment]
@jeffdomke I'm adding this to the next sprint that begins on Monday with the proposal that @aulneau tackles it then.

@aulneau I'll put 15 minutes on the calendar for early next week so we can decide on a design direction here.

**Comment by GInxh** [comment]
> We should prioritize the quick fix here. Display list of apps from App.co. The users will have to take a round trip to the app website, but that is probably better than the current state of affairs. cc @GinaAbrams

 clarify, we are removing apps from the browser profile? Can we not just keep the existing design and import the new apps? Do we have any data points to show that users will stay engaged if all the engagement opportunities imported into their onboarding flow and default sign in landing if all those points of engagement dissappear? This is seems like a bad idea and multiple other engineers on this thread agree with me. Are we overriding the feedback of all of the engineers feedback? 

Should we ask people on the forum? This decision making process seems incongruent from how we make all other data based decisions with a huge emphasis on user feedback and measurement points when it comes to user interaction.

**Comment by aulneau** [comment]
> To clarify, we are removing apps from the browser profile?

From my understanding that is not what we're talking about. I think what we will do is just use the app.co api to fetch all blockstack apps, and then display them on the browser homepage in a very similar way as it is currently.

However, I think the biggest issue right now is that the apps aren't super organized currently. They have categories etc, but I think we'll have to play around with fine tuning the order. I can pick this up on Monday and have a pretty quick example thrown together of what we could do. Additionally, because we'll be fetching data, there will be a new state of loading apps that hasn't existed before in the browser.

**Comment by markmhx** [comment]
We're definitely not removing the apps from the browser homepage as part of this issue's implementation.

For this issue, we mainly want to ensure that the apps are dynamically generated and therefore always up-to-date.

And while we introduce dynamic generation, we probably want to list them out in a useful way – either by ordering a single list of apps by a useful criterion (e.g. App Mining ranking, or anything else indicating quality). Or perhaps by categorizing them, if there's a straightforward way to do so.

**Comment by markmhx** [comment]
Some related recommendations have been provided by Kitsana on the forum here: https://forum.blockstack.org/t/dotpodcast-app-mining-thoughts/7316

**Comment by russwfranklin** [comment]
I think it would be neat to only have choice apps located on your personal homepage (like how downloaded apps display on your mobile phone). You would "download" new apps from app.co to be located here...

![image](https://user-images.githubusercontent.com/21110565/52882043-70ada780-3134-11e9-8dc9-9212227a1f3f.png)

app.co would then mimic the google play store.

**Comment by aulneau** [comment]
This issue has been addressed (to a certain degree) with the merging of this pr -> https://github.com/blockstack/blockstack-browser/pull/1823 and those changes should be released in the next version of the browser. If there are any new concerns or topics for discussion related to these changes, please feel free to open a new issue once we've released these changes. :)

![screen shot 2019-02-21 at 9 56 00 am](https://user-images.githubusercontent.com/11803153/53182663-91a44b80-35bf-11e9-88f6-9305903c80a2.png)

**Comment by markmhx** [comment]
I've created the two issues referenced immediately above to keep tracking the other suggestions made in this issue's comment thread so we can consider them outside the scope of this particular issue.
