### ISSUE TITLE
Restore screen UI glitch in iOS safari

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1573]
![image](https://user-images.githubusercontent.com/29081231/43696209-f667f8b6-990a-11e8-9185-4dcaddb02781.png)

**Comment by jeffdomke** [comment]
I believe it was reported this weekend by Stealthy. Wonder if you can search Slack for the file name and track it down that way :)

**Comment by yknl** [comment]
I wasn't able to reproduce this either. The screenshot looks very out dated.

**Comment by yknl** [comment]
Closing as not reproducible
