### ISSUE TITLE
Short term fix in UI explaining the restore process

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1577]

**Comment by jeffdomke** [comment]
![screen shot 2018-08-06 at 3 41 46 pm](https://user-images.githubusercontent.com/767828/43737440-40df4de8-998f-11e8-9ad9-50dcd3d39c98.png)

Something along these lines, although I think the copy needs to some work since this is tricky.

**Comment by jeffdomke** [comment]
This is great. I feel like the first paragraph is not needed. And would get rid of "recently" this could be discovered much later.

**Comment by yknl** [comment]
Looks fine to me. Though we used secret recovery key and magic recovery phrase in the onboarding, we should be consistent here to avoid ambiguity.

**Comment by wbobeirne** [comment]
> I feel like the first paragraph is not needed.

Couldn't resist the chance at a teaching moment, but right on, I'll change this.

> secret recovery key and magic recovery phrase

Just checked, it's "Secret Recovery Key" for mnemonic phrase and "Magic Recovery Code" for encrypted phrase. But we also call it "Keychain Phrase" in settings. Either way, going to remove that line.

**Comment by moxiegirl** [comment]
Some comments here for your review. I think the choices aren't clear. Use the same mechanism, a button, for each choice is very clear. 

The consensus from AP and other guidelines is the lowercase internet, even with the adjective new. Also, we want to standardize so probably want to avoid capitalizing New Internet in all our writings. 

![image](https://user-images.githubusercontent.com/1347209/43783567-e1be5038-9a16-11e8-8247-774701274bd2.png)

Also, are we doing sentence casing on buttons or title casing? I think sentence casing is more modern...

Finally, this is an opportunity to establish terminology around the id hierarchy which is confusing.  Our "account" format has an "id" attached to it so hard to argue it is not an id.  So, I'd call this account id and account for short works. Then, the others can be secondary IDs -- that way your "add more ids" makes sense with your use of the word account as well.

I don't know that I'd remove any teaching language from our GUI. It helps to remind people if we can do it in a more compact manner. The bigger issue is consistency in language, so the text doesn't inject confusion maybe:

> Secondary IDs use the same password and secret recovery key as your primary account ID, so you won't need to remember additional information.  Secondary IDs cannot be deleted, but if you recently restored and are missing IDs you must add them back using the **IDs > Add another ID**  dialog.

Also in the text, the " just adds characters and are hard to see, bold is easier to catch in scanning.

I'm confused, they can't be deleted, but they can go missing?
