### ISSUE TITLE
Integrate the API calls with the Blockstack core REST API

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#158]
The browser uses the legacy onename API. Switch to using the REST API provided by Blockstack core. Ship a copy of blockstack with every browser.

**Comment by larrysalibra** [comment]
I've created a server that mocks the blockstack core REST API using blockstack cli until the real API is ready to ship. see #159

**Comment by larrysalibra** [comment]
I've integrated all the of the API endpoints we discussed in: https://github.com/blockstack/blockstack-core/issues/279#issuecomment-278745814 except for:

*  `GET /v1/wallet/payment_address` - I'll integrate this once we decide where to display this. 
* `GET /v1/wallet/owner_address` - We don't need this.
* `GET /v1/blockchain/bitcoin/pending` - Right now, new names are marked as pending upon registration. We might not need to use this call either. Will investigate more tomorrow.

Next up is testing integration with the real core api & updating the mac app to start the api on startup once @jcnelson is finished with his changes.

**Comment by shea256** [comment]
Awesome!

**Comment by shea256** [comment]
Awesome, great work @larrysalibra!

**Comment by larrysalibra** [comment]
This is complete.  Everything should work as intended once fixes for issues listed [here](https://github.com/blockstack/blockstack-browser/issues/185#issuecomment-279227514) with core api are resolved.
