### ISSUE TITLE
Update react router

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1594]
The version of react router we're using is pretty old. Updating to the new version will require a little bit of refactor. Thoughts @wbobeirne @yknl?

**Comment by wbobeirne** [comment]
I'd say if it ain't broke, don't fix it. If there aren't any features, bug fixes, or vulnerabilities we want out of the new version, I don't think it's worth upgrading.

**Comment by yknl** [comment]
Yup, if we're not gaining anything from upgrading to the newest version then the time spent isn't justified.

**Comment by aulneau** [comment]
Cool sounds good to me!
