### ISSUE TITLE
Email screen copy in restore flow is inaccurate

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1599]
The email capture copy in the restore flow is inaccurate, no recovery instructions are sent on restores.
![image](https://user-images.githubusercontent.com/29081231/43936713-d98fd6f8-9c27-11e8-843a-ab975ff9ef09.png)

**Comment by wbobeirne** [comment]
Should we re-email them if they entered the mnemonic phrase? The encrypted key will be different if they used a different password.

**Comment by yknl** [comment]
I think it would be confusing to send another email here. The user could just be signing into an additional device. cc @jeffdomke

**Comment by wbobeirne** [comment]
I think normally people will do encrypted seed + password for new devices which is no problem, since they'll have the same encrypted seed. However then you have the dishonest copy problem. But I was only considering if they do the raw bip39 phrase for another email.

**Comment by jeffdomke** [comment]
I would remove the "email is needed copy" we shouldn't email another copy it will be a mess. There was a long discussion about this at the this shipped.

**Comment by wbobeirne** [comment]
<img width="477" alt="screen shot 2018-08-22 at 4 39 16 pm" src="https://user-images.githubusercontent.com/649992/44489671-166ed680-a62a-11e8-88b6-2773c35eabc4.png">

Is this the desired change? Do we want to have any accompanying copy here?

**Comment by wbobeirne** [comment]
I'd definitely like to add some copy there for recovery, something to the tune of

> Blockstack doesn’t store your email on a server, so we need to ask for it when you recover. 

that explains why they have to re-enter, and hopefully adds a little good will from the user about the email. It would also be nice to add a "We don't store your email" notice when you first enter it too.
