### ISSUE TITLE
Restore copy change

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1601]
![Screen Shot 2018-08-10 at 6:57 PM](http://marker.screenshots.prod.s3.amazonaws.com/5d39789fc9be4864bc8318baae7561f3-1533927472050.png)
---
### More Info

**Source URL**: [https://browser.blockstack.org/sign-up?redirect=%2F%23coreAPIPassword%3DPretendPasswordAPI%26logServerPort%3D](https://browser.blockstack.org/sign-up?redirect=%2F%23coreAPIPassword%3DPretendPasswordAPI%26logServerPort%3D)

**Comment by jeffdomke** [comment]
Based on the latest user testing this change is critical, please get it into the next release.

**Comment by jeffdomke** [comment]
We can also do "Sign in with Existing ID"

**Comment by wbobeirne** [comment]
Closed via #1605.
