### ISSUE TITLE
Confirm redux stores work the same in dev + prod environments

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1603]
With the merge of the webpack PR we will now be releasing production code whereas before we were only shipping development code. There are some differences for the redux store between dev and prod, we should confirm there are no regressions from shipping prod code.

**Comment by wbobeirne** [comment]
I think we should get rid of this multi-file paradigm, and use conditionals in one file to have the different behavior. The current methodology seems prone to forgetting to update both.

**Comment by aulneau** [comment]
+1
