### ISSUE TITLE
Profile data always null

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1607]
The current release of the browser always calls `makeAuthResponse` with a `null` profile data.

This results in the default "Nameless person" profile being returned to apps.

https://github.com/blockstack/blockstack-browser/blob/540867d8e5ddd4b9e76a414ae2ff3d68c806573a/app/js/auth/index.js#L368

**Comment by larrysalibra** [comment]
This happens to me on both larry.id and lsalibra.id

**Comment by larrysalibra** [comment]
I tested this by added `console.log(profileResponseData)` above the call to `makeAuthResponse` and it was always `null` when i tried to sign in. Seems like a problem retrieving profile data.

**Comment by larrysalibra** [comment]
Happens for me in Safari Version 11.1.2 (13605.3.8)

**Comment by wbobeirne** [comment]
I've been unable to replicate in both Chrome 67 and Safari 11.0.2 with my existing profile, nor with a freshly created profile for testing this out. My guess at the moment is that there must be something problematic in certain legacy profiles.

**Comment by jehunter5811** [comment]
Definitely seems to be tied to older IDs. Not sure what's considered a legacy profile, though. I experience this on jehunter5811.id, but not on justin.personal.id or on admin.graphite.

**Comment by jcnelson** [comment]
I might have noticed a pattern:  all these old IDs have a profile URL format with an ID index.  For example:

`https://gaia.blockstack.org/hub/16KyUebBPPXgQLvA1f51bpsne3gL7Emdrc/0/profile.json`

This was true for `lsalibra.id`, `larry.id`, `naval.id`, `jehunter5811.id`, and `judecnelson.id`, but not for `justin.personal.id` or `admin.graphite`.

**Comment by jcnelson** [comment]
There was also an observation from the Stealthy team that it only appeared to affect netlify-hosted apps.

**Comment by larrysalibra** [comment]
The browser appears to be returning the wrong `profile_url` for my name `lsalibra.id`

It is returning `https://gaia.blockstack.org/hub/1GBLCrGLATRcLXS8V81RbzyCQPaSv4ATby/profile.json` in the auth response token instead of `https://gaia.blockstack.org/hub/1GBLCrGLATRcLXS8V81RbzyCQPaSv4ATby/0/profile.json`

**Comment by larrysalibra** [comment]
The problem is in this function

https://github.com/blockstack/blockstack-browser/blob/540867d8e5ddd4b9e76a414ae2ff3d68c806573a/app/js/utils/profile-utils.js#L116

It searches through a bunch of locations looking for a valid profile - a profile signed by the proper signing key. If i recall correctly this was to make the browser work when a user doesn't have a name.


However, when there is a username associated with a Blockstack ID, it should return the profile that is pointed to by the username's zonefile and not simply the first valid profile it finds.

In the case of `lsalibra.id` at some point a bug probably resulted a valid profile being written to a few other locations, so it finds the valid profile found in that location which is not the profile that's actually pointed to by the name.

```
2018-08-15T00:26:06.924+0800 DEBUG utils/profile-utils.js: Found valid profile at https://gaia.blockstack.org/hub/1GBLCrGLATRcLXS8V81RbzyCQPaSv4ATby/profile.json
VM22 main.js:270917 2018-08-15T00:26:06.927+0800 DEBUG auth/components/AuthModal.js: profileUrl: https://gaia.blockstack.org/hub/1GBLCrGLATRcLXS8V81RbzyCQPaSv4ATby/profile.json
```

**Comment by kantai** [comment]
As mentioned in the PR #1613 -- this seems to be caused by the zoneFile parsing instructions, rather than `fetchProfileLocations` (which shouldn't be called when a zoneFile exists).

**Comment by larrysalibra** [comment]
Fixed in 
https://github.com/blockstack/blockstack-browser/releases/tag/v0.31.1
