### ISSUE TITLE
Social level went back to 0 and twitter account is now unverified

### ISSUE THREAD

**Issue by petec029** [blockstack/blockstack-browser#1629]
After updating to the latest Blockstack browser my twitter account is now unverified and my social level is 0. I am running Blockstack on Safari Version 11.1.2 from my MacBook Pro

<img width="733" alt="screenshot 2018-08-22 08 09 47" src="https://user-images.githubusercontent.com/519271/44462858-e43a8600-a5e3-11e8-81d4-49bb18250dc8.png">

**Comment by hoschi-it** [comment]
same issue here with twitter and github account using Blockstack-for-win10-v0.32.2.msi and google chrome

**Comment by petec029** [comment]
So I just tried verifying my twitter account again.  I followed the steps and added the twitter url of https://twitter.com/petec029/status/1046406720589897729 and nothing happened.

**Comment by yknl** [comment]
Hey @petec029 are you still experiencing this issue? We've made several bug fixes that should have addressed this.

**Comment by petec029** [comment]
Hi @yknl I have not run into this problem again
