### ISSUE TITLE
Clear auth page loads indefinitely

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-browser#1632]
@petec029 reported this: https://github.com/blockstack/blockstack-ios/issues/50#issuecomment-415018182

I have the same issue when I navigate to https://browser.blockstack.org/clear-auth on desktop Chrome or iphone.

**Comment by wbobeirne** [comment]
Looks like the page loads fine, it just doesn't remove the loader, so it's just covering the content. Should be an easy fix. Sorry for the hassle @shreyasthiagaraj.

**Comment by wbobeirne** [comment]
Closed via #1633.
