### ISSUE TITLE
Fix help button on screen during authentication

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1645]
When I try using the little gray help button (a circle with the "?" character in it) on desktop during authentication with my locally installed browser, it doesn't do anything:

<img width="1083" alt="screen shot 2018-09-04 at 10 17 45" src="https://user-images.githubusercontent.com/28991/45019235-1f997380-b02c-11e8-9048-8203d7ebbe75.png">

It seems this is a simple div that should be clickable:

<img width="469" alt="screen shot 2018-09-04 at 10 19 33" src="https://user-images.githubusercontent.com/28991/45019251-288a4500-b02c-11e8-86f1-2c82799dcc54.png">

**Comment by moxiegirl** [comment]
@markmhx @yknl Looks like this was done.  I can't find this in the code, though there is a new SupportButton.  Reopen If I am closing this in error.
