### ISSUE TITLE
Create username updates

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1653]
![Screen Shot 2018-09-06 at 7:33 PM](http://marker.screenshots.prod.s3.amazonaws.com/8228f97a990247ffb7b43f1fadfaf7ff-1536262398755.png)

Copy change and fix misalign on the input. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.22%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.22%20PM.png)

**Comment by jeffdomke** [comment]
![screen shot 2018-09-21 at 10 38 33 am](https://user-images.githubusercontent.com/767828/45887783-88058600-bd8a-11e8-82d6-f8735284f9af.png)

**Comment by aulneau** [comment]
@jeffdomke fixed with https://github.com/blockstack/blockstack-browser/commit/f6fb56c1eced2e75889ba543d27ac880a58d24ac
