### ISSUE TITLE
Save your Secret Recovery Key – Copy and button updates

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1657]
![Screen Shot 2018-09-06 at 7:45 PM](http://marker.screenshots.prod.s3.amazonaws.com/c98a0d6d90d04f56afba74e5613a94db-1536263137882.png)

Copy updates and removing the button at the bottom

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.41%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.41%20PM.png)

**Comment by jeffdomke** [comment]
Button CTA should read "Secret Recovery Key"

**Comment by aulneau** [comment]
fixed in https://github.com/blockstack/blockstack-browser/pull/1674/commits/4f406146db58c0f1da0e5a64d2703af783eea991
