### ISSUE TITLE
Seed screen – copy and layout changes

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1658]
![Screen Shot 2018-09-06 at 7:46 PM](http://marker.screenshots.prod.s3.amazonaws.com/9957914021734847b82b6a8966c80e09-1536263218800.png)
---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.46%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.46%20PM.png)

**Comment by jeffdomke** [comment]
Observed two problems: 
– The feedback that the words copied no longer shows (but it functions). 
– Two the output shows up with commas, for example: `trumpet,valve,shock...`

**Comment by aulneau** [comment]
@jeffdomke both should be fixed with https://github.com/blockstack/blockstack-browser/commit/9e6eaf3cf360dd8aaf8201cc6de2045a68da25f5
