### ISSUE TITLE
Verify seed screen

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1659]
![Screen Shot 2018-09-06 at 7:47 PM](http://marker.screenshots.prod.s3.amazonaws.com/8168f23c2bb14c40b3f92bedcd33ca4f-1536263258093.png)
---

Behavior of screen needs to be updated. There is no confirm button. Tapping any two words should trigger submission. If incorrect, turn the words/buttons red, show shaking animation to convey an incorrect answer then reset test (ask for different #s). 

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.49%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.49%20PM.png)

**Comment by aulneau** [comment]
I didn't know that there was clarity on this. In my mind we left it as something we would play around with (which I have not gotten to quite yet). I can remove the confirm button, but it might take more time to add in shaking animations and have the whole thing work well.

**Comment by jeffdomke** [comment]
OK, new ticket next round of work.
