### ISSUE TITLE
Start recovery – copy button updates

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1661]
![Screen Shot 2018-09-06 at 7:53 PM](http://marker.screenshots.prod.s3.amazonaws.com/547e2b884c434b62b8883999a6f0085a-1536263611395.png)
---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.58%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.21.58%20PM.png)

**Comment by jeffdomke** [comment]
Cancel button please. Trying to remove the number of large CTAs.

**Comment by aulneau** [comment]
@jeffdomke fixed with https://github.com/blockstack/blockstack-browser/commit/c13eed1a1e305a76cff510b09abe5d8478f9a643
