### ISSUE TITLE
Restoring spinner – copy update, small fixes

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1663]
![Screen Shot 2018-09-06 at 7:56 PM](http://marker.screenshots.prod.s3.amazonaws.com/d635149bcf0147518177fbee38bdfc1d-1536263810986.png)
---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.24.55%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.24.55%20PM.png)

**Comment by aulneau** [comment]
should be fixed with https://github.com/blockstack/blockstack-browser/commit/16b8948ae8b8458115aedf0a871ebf1425db72f3 and https://github.com/blockstack/blockstack-browser/commit/706afe7c64ff8743cb0f30f12262a65aa95d8f45

**Comment by jeffdomke** [comment]
I see the nav junk removed. Still seeing the old copy.

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack-browser/commit/e19dfade629f7fe057582774651a0b71ccf8be2f

there were multiple places with this copy, missed this one before.
