### ISSUE TITLE
ID creation emails – consolidate

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1664]
![Screen Shot 2018-09-06 at 7:59 PM](http://marker.screenshots.prod.s3.amazonaws.com/6cb15d6422ae4ea1b4732fcce7e4ca9e-1536263991709.png)

Subject = `jeff.id.blockstack — Save this email`

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.25.06%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-06%20at%203.25.06%20PM.png)

**Comment by jeffdomke** [comment]
@yknl 

Can we change the subject `jeff.id.blockstack - Save this email: Recovery info`

Also: The name of this email account reads as `hello` <hello@blockstack.org> – can we update to `Blockstack`

**Comment by yknl** [comment]
Updated
