### ISSUE TITLE
Password creation screen copy

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1678]
Mobile focus will probably cause confusion here. Put 8 character min in the validation message:
"Your password is too short" --> "Too short. 8 characters minimum."

Also suggest adding to the front of the of the instructions:
"Please record your password, Blockstack cannot reset this password for you."
-->
"8 characters minimum. Please record your password, Blockstack cannot reset this password for you."

**Comment by jeffdomke** [comment]
The placeholder text of the first field should still contain that instruction. Seems to be removed. 
"New password" ---> "New Password (8 characters min)

**Comment by aulneau** [comment]
@jeffdomke fixed with https://github.com/blockstack/blockstack-browser/commit/1e7a6efe442cdcddd391c15c65d9e1807a799abd
