### ISSUE TITLE
Enable testing name registrations

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1679]
When we are working on / updating functionality / ui work for the onboarding, we tend to make a new account each time we have to go through the flow. This ends up being not a small number of new(fake) accounts. 

I suggest we have a flag env that we pass when we're testing, eg `process.env.STAGE` or something to that effect which would switch out the registrar url for another name, eg `*.test-blockstack.id`. @kantai we have a test registrar set up already, correct? if so what is that url?

cc @yknl

**Comment by yknl** [comment]
Yes there is a test registrar setup, the url is in the settings defaults:
https://github.com/blockstack/blockstack-browser/blob/master/app/js/account/store/settings/default.js#L42

I've been creating a large number of testing ID's on the id.blockstack registrar as well. I don't think it has any significant negative effects. But if it does I'm on board with using the test registrar. 

There is also the problem of running into rate limiting on the registrar when registering too many test usernames. We can get around this by setting an authorization header with an API key in the registration request. `Authorization: bearer <secret>`

I propose we add a URL param to indicate that it should run in testing mode and pass in the API key. (The automated end-to-end browser tests will also benefit from this) `https://browser.blockstack.org/?testMode=true&registrarApiKey=secretkey`

**Comment by aulneau** [comment]
Nice, thanks.

I think a negative side effect of this is that it could change the metrics around new user sign ups.

**Comment by aulneau** [comment]
@yknl do you have availability to work on this?

**Comment by yknl** [comment]
I may be able to get this next week.

**Comment by markmhx** [comment]
@yknl were you able to address this after all?

**Comment by hstove** [comment]
Matt has implemented a flag you can set to use the test registrar. It requires you to use the JavaScript console, but since this is really just for internal use, that seems fine to me

**Comment by markmhx** [comment]
@hstove Cool, is this issue good to close out then?

**Comment by hstove** [comment]
Yes, I think so.
