### ISSUE TITLE
Recovery email capture – field not in focus on load

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1682]
![Screen Shot 2018-09-25 at 9:45 PM](http://marker.screenshots.prod.s3.amazonaws.com/a96911703253440a9ad7b4332fb29469-1537911943769.png)
---
### More Info

**Source URL**: [file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.45.01%20PM.png](file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.45.01%20PM.png)

**Comment by aulneau** [comment]
https://github.com/blockstack/blockstack-browser/commit/484577049b655103dfef2be90a17f4faaad8e5d0 fixed this
