### ISSUE TITLE
Restore not fetching photos properly

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1683]
![Screen Shot 2018-09-25 at 9:47 PM](http://marker.screenshots.prod.s3.amazonaws.com/566db95a2c064d959c6e6fa0674bfeaa-1537912036507.png)

Confirmed this ID has a photo

---
### More Info

**Source URL**: [file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.46.23%20PM.png](file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.46.23%20PM.png)

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack-browser/commit/a31605fbc889e180f8ac54847fe5dc9c0cf29f47
