### ISSUE TITLE
Email capture on new ID creation – not in focus on load

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1684]
![Screen Shot 2018-09-25 at 9:50 PM](http://marker.screenshots.prod.s3.amazonaws.com/c4685f319525458bb26bb76e81e49511-1537912217936.png)
---
### More Info

**Source URL**: [file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.49.21%20PM.png](file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.49.21%20PM.png)

**Comment by aulneau** [comment]
fixed in https://github.com/blockstack/blockstack-browser/commit/484577049b655103dfef2be90a17f4faaad8e5d0

all autofocus broke somehow, they should all work now
