### ISSUE TITLE
Email capture on new ID creation – copy

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1685]
![Screen Shot 2018-09-25 at 9:53 PM](http://marker.screenshots.prod.s3.amazonaws.com/b404535872134b828a977a70e59c9abb-1537912384411.png)

Think we should ditch the "we do not store this". 1) just sounds a bit strange wording wise. 2) We are in a time loop on this. Several months ago I had almost the same copy in there and Ken and a couple other people insisted it wasn't correct and should be corrected. 

---
### More Info

**Source URL**: [file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.49.21%20PM.png](file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.49.21%20PM.png)

**Comment by aulneau** [comment]
fixed in https://github.com/blockstack/blockstack-browser/commit/484577049b655103dfef2be90a17f4faaad8e5d0
