### ISSUE TITLE
Recovery email failure screen – copy

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1686]
![Screen Shot 2018-09-25 at 9:55 PM](http://marker.screenshots.prod.s3.amazonaws.com/4fbe0b63f18f450cabb86e1143aa0639-1537912554724.png)
---
### More Info

**Source URL**: [file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.54.44%20PM.png](file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-09-25%20at%205.54.44%20PM.png)

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack-browser/commit/20e79584f39ce89d49ad1c76f73935dd1113cabf
