### ISSUE TITLE
Browser help button thing showing up on iOS chrome

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1688]

**Comment by jeffdomke** [comment]
![screen shot 2018-09-25 at 5 59 46 pm](https://user-images.githubusercontent.com/767828/46045876-0183d800-c0ed-11e8-96bc-6ed6e2366de8.png)
![screen shot 2018-09-25 at 5 59 59 pm](https://user-images.githubusercontent.com/767828/46045878-0183d800-c0ed-11e8-92bd-86a50937a658.png)
![screen shot 2018-09-25 at 6 00 17 pm](https://user-images.githubusercontent.com/767828/46045879-0183d800-c0ed-11e8-8bb3-06114c11230e.png)

**Comment by aulneau** [comment]
maybe fixed with this? https://github.com/blockstack/blockstack-browser/commit/85855c15b4e36a9984b67deef6a728579056cd8d will do further testing, having a hard time recreating this bug

**Comment by aulneau** [comment]
okay I think I've got this fixed, I don't have an ios device on hand to test in real life, but it looks good on browserstack. @jeffdomke if you could check this, that'd be great!
