### ISSUE TITLE
Recovery with 12 words – adding one space or return to the words causes the UI to treat that input as a magic code.

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1691]
Feels brittle. I'm not sure how the current rules are implemented but assume it should be able to handle one extra space. When I copy and paste the seed from other docs I notice frequent spaces attached or returns.

**Comment by markmhx** [comment]
I'm closing this issue since it appears resolved by https://github.com/blockstack/blockstack-browser/pull/1694. @aulneau please re-open if that's not actually the case.
