### ISSUE TITLE
Question bubble showing on iOS safari

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1695]
![Screen Shot 2018-09-27 at 8:12 PM](http://marker.screenshots.prod.s3.amazonaws.com/20931dbc7a7b473984e31182f2af66a0-1538079155127.png)

This has something to do with scrolling. I can create this affect by scrolling on any screen. Same things happens on chrome but when you scroll that way the "white edge" seems to correct it or expand to always hide it. On Safari that seems to not be working. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-27%20at%203.26.52%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-27%20at%203.26.52%20PM.png)

**Comment by aulneau** [comment]
This is a known issue that happens across many devices and browsers. When an element takes up the viewport size, when the address bar moves and adjusts, the element sometimes does or does not. I will continue to look into this but might need to punt it.

**Comment by yknl** [comment]
We should just remove it. It's no longer useful after the token sale period.
