### ISSUE TITLE
Unlocking hangs – iOS safari

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1697]
![Screen Shot 2018-09-27 at 8:17 PM](http://marker.screenshots.prod.s3.amazonaws.com/8e10421cdd2e4302af1021ca3f5a9bd4-1538079436104.png)

Was able to reproduce this a couple times: 

Just go to any step to unlock the Secret Recovery Key and it will hang forever. 

Browserstack. Latest iOS on Safari. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-27%20at%204.15.31%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-27%20at%204.15.31%20PM.png)

**Comment by aulneau** [comment]
@jeffdomke can you test this on your local device?

**Comment by aulneau** [comment]
I am not able to recreate this bug @jeffdomke

**Comment by jeffdomke** [comment]
Yeah, just tried it. Can't recreate on my device. Might have just been some thing with browserstack.

**Comment by aulneau** [comment]
Yeah they say they are real devices but time and time again I run into small inconsistencies like this _shrug_
