### ISSUE TITLE
Edge Browser – cannot get any buttons to work

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1698]
To test just use browserstack and latest edge and try to create an ID or restore.

**Comment by aulneau** [comment]
I think we should punt this and do a larger audit of functionality across browsers.

**Comment by zone117x** [comment]
So far only problem I'm seeing in Edge is a bug when trying to get past the "enter email" screen. 
I'm currently testing Edge support for the protocol handler detection so going to assign to myself. 
This issue also fits in an important KR for this quarter.

**Comment by markmhx** [comment]
@zone117x Want to tackle this in the new sprint starting today?

**Comment by zone117x** [comment]
Let's try to get this done this sprint, but debugging these Edge issues can be quite a time sink. So I'd punt this if it started looking like a multi-day debugging session.
