### ISSUE TITLE
Create a username unable to check – small display bug

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1701]
![Screen Shot 2018-09-27 at 8:27 PM](http://marker.screenshots.prod.s3.amazonaws.com/06d06b43cde948e1b3ab56df2dc74466-1538080033723.png)
---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-09-27%20at%204.26.11%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-09-27%20at%204.26.11%20PM.png)

**Comment by aulneau** [comment]
this should be fixed with https://github.com/blockstack/blockstack-browser/commit/1ffaea0ea03a36bebceee7af9f71c21696521e25
