### ISSUE TITLE
Improve UX format of the registration failure state

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1702]
Design, formatting and display of this message just diverges from all other errors. On mobile it blocks the user from the next step even though there is nothing to change or do now or retry, it is just a notice. 
![screen shot 2018-09-27 at 4 38 30 pm](https://user-images.githubusercontent.com/767828/46173460-52720880-c274-11e8-8670-1885e3b283b5.png)
![screen shot 2018-09-27 at 4 38 42 pm](https://user-images.githubusercontent.com/767828/46173461-52720880-c274-11e8-90f7-da84ac83f556.png)

How to test and such is here: https://github.com/blockstack/blockstack-browser/pull/1583

**Comment by jeffdomke** [comment]
Think we can punt on this for a while but wanted to capture.

**Comment by markmhx** [comment]
@aulneau I think we discussed addressing this in the new sprint, so I'm assigning it as such. But please let me know if you'd prefer to hold off until a future sprint.

**Comment by markmhx** [comment]
This appears to be addressed by https://github.com/blockstack/blockstack-browser/pull/1898
