### ISSUE TITLE
Lastpass did not save password

### ISSUE THREAD

**Issue by nickjam** [blockstack/blockstack-browser#1711]
setup an id on my android device. Lastpass did not save password during setup so I don't have original password. Went to my welcome email to recover my password using my secret key phrase but to view my secret key phrase for the first time I need my original password that I do not have. pls help. (I'm still logged in on my android device chrome browser, if that is useful)

**Comment by yknl** [comment]
Unfortunately your secret key isn't stored anywhere in plain text. You will need your original password to decrypt and view your secret key again.

**Comment by moxiegirl** [comment]
@nickjam If you lose both your secret key and your origin password, your id becomes estranged. Meaning, you can't access it. Neither can anyone else.  If you haven't deleted the email Blockstack sent you when you created this ID, you may still be able to get back to your ID. Have you searched your inbox, spam, and trash folders?

Documentation for your reference.
https://docs.blockstack.org/browser/ids-introduction.html

**Comment by moxiegirl** [comment]
I'm closing this as it is expected behavior. Please reopen if you feel it was closed in error.
