### ISSUE TITLE
Footer needs correction

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-browser#1713]
> The Blockstack Tokens are a crypto asset that is currently being developed by
Blockstack Token LLC, a Delaware limited liability company, whose website can be
found at www.blockstack.com. The website you are currently visiting
www.blockstack.org is sponsored by Blockstack PBC, an affiliate of Blockstack
Token LLC, and should not be viewed as an offer or sale of securities.

"whose website an be found at www.blockstack.com" is the issue. It just redirects to www.blockstack.org

**Comment by krtb** [comment]
Hi! Can you assign this issue to me if it's still available?

**Comment by moxiegirl** [comment]
I can't assign it to you as you are not on the org list.  That won't stop you from forking and doing a PR back with a fix tho. This is a public repo.  We'd appreciate the help @krtb !

**Comment by krtb** [comment]
sounds great! @moxiegirl, could I ask where this file i located? Was trying to look in app/public/index.html and none of the other docs looked correct for finding this. Also, should I attempt to get on the org list?

**Comment by moxiegirl** [comment]
@krtb I'm sorry. I dropped this on the wrong repo. I'll close this issue and reopen on the other. That should help you out @krtb

**Comment by moxiegirl** [comment]
@krtb if you prefer to work on the browser, here is a list of the good first issues: 

https://github.com/blockstack/blockstack-browser/labels/good%20first%20issue

**Comment by krtb** [comment]
@moxiegirl no preference at all! Blockstack is such a sweet idea that I would want to help out in any way possible!
