### ISSUE TITLE
Proofs in  Web App trying to use CORS-proxy

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#1714]
Proofs in the web version of the browser are trying to use the CORS proxy. I don't know what's up, but I'd guess the culprit is near here:

https://github.com/blockstack/blockstack-browser/blob/f02a31e2627c509300669512ae425871eb36b721/app/js/profiles/store/identity/actions.js#L29

If that `isWebAppBuild` is false, it won't make requests to `proofs.blockstack.org`:

![proofs-erros-web-hosted](https://user-images.githubusercontent.com/1153552/46961372-3f2dae00-d066-11e8-9e7b-d072184a2a83.png)

**Comment by aulneau** [comment]
@kantai -> https://github.com/blockstack/blockstack-browser/pull/1703

**Comment by kantai** [comment]
Oops, sorry about that, I had thought that was fixed.
