### ISSUE TITLE
Magic recovery code for 24 word seed phrases appear as invalid for recovery

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1719]

**Comment by markmhx** [comment]
@yknl can you recreate this bug now that a few months have passed? Not sure if it's still a bug.

**Comment by yknl** [comment]
yes this is still a bug

**Comment by markmhx** [comment]
@yknl Thanks for the confirmation. Should this issue get prioritized since it's a bug? I presume it affects all users with 24-word seeds that try to auth these days?

**Comment by yknl** [comment]
This bug has been fixed in https://github.com/blockstack/blockstack-browser/pull/1850.
