### ISSUE TITLE
start-containers: not a valid identifier

### ISSUE THREAD

**Issue by plutext** [blockstack/blockstack-browser#1721]
Trying to run the installer on manjaro

$ sh Blockstack-for-Linux-v0.34.1.sh 
Blockstack-for-Linux-v0.34.1.sh: line 71: `start-containers': not a valid identifier

It should suggest you make it executable and run it that way, since that works

**Comment by moxiegirl** [comment]
@plutext Thank you for the issue.  We will add instructions for users that download the executables to make sure they add executable permissions before running it.
