### ISSUE TITLE
User enters email into username and no validation shows

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1725]
![Screen Shot 2018-11-20 at 7:53 PM](http://marker.screenshots.prod.s3.amazonaws.com/17887e137bb2473ca1ec873fb6a4d39c-1542743584776.png)

Edge
32
Intel(R) Celeron(R) CPU N3350 @ 1.10GHz
3324.7 MB
1013.91 MB
Windows 10 Home 10.0
1366 x 768

3936.28 MB

---
### More Info

**Source URL**: [file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-11-20%20at%202.51.20%20PM.png](file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-11-20%20at%202.51.20%20PM.png)

**Comment by markmhx** [comment]
@zone117x Has this issue's solution been completely reviewed and as such can be closed in anticipation of release?
