### ISSUE TITLE
Next button with email does not move on in Microsoft Edge

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-browser#1730]
Unable to move through the entire onboarding process in IE.  When I got to entering the email, I could press Next but the dialog just 

![image](https://user-images.githubusercontent.com/1347209/49023620-79519b80-f14c-11e8-9980-23339c32b655.png)

Version:

![image](https://user-images.githubusercontent.com/1347209/49025659-fb43c380-f150-11e8-92ce-7037abb3b3ea.png)

![image](https://user-images.githubusercontent.com/1347209/49025780-3940e780-f151-11e8-9ee7-3371e71deb5e.png)

**Comment by markmhx** [comment]
@zone117x Has this issue's solution been completely reviewed and as such can be closed in anticipation of release?
