### ISSUE TITLE
Add Gaia hub URL choice to onboarding flow

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-browser#1735]

**Comment by markmhx** [comment]
- [ZenHub board](https://app.zenhub.com/workspaces/blockstack-engineering-582a2234b399ebbf18315399/boards?epics=47580020_1735&repos=26510718,22058375,47580020)

**Comment by markmhx** [comment]
@jehunter5811 Are you able to load the ZenHub board with the above link? I'm not sure if we've properly set up public access, but we definitely want everyone to see progress on this project / erpic as we're tracking it in ZenHub.

**Comment by jehunter5811** [comment]
@markmhx Yep, the link works for me. Appreciate you making it public!

**Comment by moxiegirl** [comment]
I've moved the documentation issues to the later Epic for the gaia hub. Removing my ownership of this.

**Comment by markmhx** [comment]
@moxiegirl Sounds good, think it'd be best that we close out this epic? If we're completing the above documentation under the other epic (and since we don't have any more plans for adding more choice during onboarding at the moment), closing out seems appropriate to me.

**Comment by moxiegirl** [comment]
@markmhx sure thing. I'll do that.
