### ISSUE TITLE
Bug: Browser Wallet Balance Shows 0 BTC On Mobile

### ISSUE THREAD

**Issue by laytond** [blockstack/blockstack-browser#1737]
Reposting this from https://forum.blockstack.org/t/browser-wallet-balance-shows-0-btc-on-mobile/6867 per Jeff's request.

<hr>

I recently restored my Blockstack ID from my recovery key on two different mobile devices. Everything seems :+1:except that my wallet balance is showing 0 BTC when it should have a small balance in there. Also of interest is that the balance that does appear on my MacBook doesn’t appear to be accurate: https://live.blockcypher.com/btc/address/1Ax7mUj1kVr9D5TeyQfJBfVcJP3yuyTwoV/ .

Please see some screenshots below. (I couldn’t attach more than one image in a post as a newbie here _[on the Blockstack forum, not GitHub]_, so I just put them all in one).

![screenshots-blockstack-browser](https://user-images.githubusercontent.com/10748468/49545324-25ecf500-f892-11e8-8d03-7c87849e314c.jpg)

Image 1: Brave Browser on macOS Mojave
Image 2: Brave Browser on Android 9
Image 3: Safari Browser on iOS 12.1

I haven’t attempted to move any funds around yet, but happy to try if that helps troubleshoot the issue.

**Comment by moxiegirl** [comment]
@laytond hey, we will take a look and prioritize this. Thanks for posting this and then throwing it over here.

**Comment by laytond** [comment]
@moxiegirl yeah no problem! Let me know if I can test anything else from my end.

**Comment by hstove** [comment]
We fixed some issues here in our recent browser versions. I'm going to close this - let me know if it's still an issue. Thanks!
