### ISSUE TITLE
Correct recommended Gaia hub modal header

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1741]
The header here should say "[App name] recommends..." without the "Hello," part:

![Screen Shot 2018-12-06 at 18.53.51.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/37998d50-298c-4206-a27e-3168ce8541ca)

**Comment by hstove** [comment]
Haha! I finally realized what the cause of this 'bug' is. The app's name is "Hello, Blockstack". So, it's all good :)
