### ISSUE TITLE
UI Issue on Browser Update Page

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/blockstack-browser#1757]
See screenshot coming...

**Comment by jehunter5811** [comment]
<img width="689" alt="screen shot 2018-12-21 at 5 43 51 am" src="https://user-images.githubusercontent.com/10519834/50341196-8eb7ac80-04e3-11e9-8388-e05c10db097e.png">

**Comment by aulneau** [comment]
Interesting, thanks for posting this. Can you please provide some info about your system, browser, native vs browser.blockstack.org, etc?

Thanks!

**Comment by jehunter5811** [comment]
System: Mac OS High Sierra
Browser: Brave and Chrome (saw it in both)
Happens at browser.blockstack.org

**Comment by jehunter5811** [comment]
A separate issue I'm opening is that after updating the browser, usernames are not populated. The user would have to stop the auth flow, go to the IDs page, refresh, then go back to the app and log in again to have their username come through after a browser update.

**Comment by markmhx** [comment]
This bug is especially problematic on mobile since the button flies mostly off the screen:

![f366d8ee-9c86-4ab9-8d21-807408c37f07](https://user-images.githubusercontent.com/28991/50541649-40bd3b80-0baa-11e9-9a79-597997fac419.png)

**Comment by markmhx** [comment]
This appears fixed for me with the latest browser release:

<img width="671" alt="screen shot 2019-01-03 at 15 41 49" src="https://user-images.githubusercontent.com/28991/50643359-24384f00-0f6e-11e9-9bf3-74dd0e2b432b.png">
<img width="413" alt="screen shot 2019-01-03 at 15 41 55" src="https://user-images.githubusercontent.com/28991/50643360-24d0e580-0f6e-11e9-9e05-7035a15b860b.png">
