### ISSUE TITLE
After hosted browser update, usernames don't come through (only IDs)

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/blockstack-browser#1758]
After updating the browser, usernames are not populated. The user would have to stop the auth flow, go to the IDs page, refresh, then go back to the app and log in again to have their username come through after a browser update.

**Comment by jhunter5811** [comment]
Note this is not just on the hosted browser. It's on the local browser as well. No user is going to know that they need to deny an auth request, refresh on the browser home page, double-check their ids, then go log in. This is already breaking experiences for users and people are reporting it across apps.

**Comment by hstove** [comment]
Yeah, we have some code to 'refresh identities', which picks up the username from your addresses. We only have it on a few places, like the 'view more IDs' page. We need to add this to onboarding, and a few other pages that people might run into this issue.

**Comment by jhunter5811** [comment]
Cool. This one is especially bad because every user is required to update the browser when there is an update. There's no opt-out for the hosted browser.

**Comment by jeffdomke** [comment]
@hstove not following your comment. We've pushed maybe 5-10 updates in the past year and this is the first time I remember this reported. Think this is a new bug in the latest build. @jehunter5811 you agree?

**Comment by jehunter5811** [comment]
That’s correct. This specific issue has never happened before as far as I can remember.

**Comment by SouthernWolf95** [comment]
I can confirm that this is also an issue that seems to affect multiple different things. My social links got deleted, as did my username, profile bio, and my profile picture which is now unable to be updated. Some apps, like Graphite, I have to switch around which browsers I use, while others just flat out fail entirely.

**Comment by markmhx** [comment]
@SouthernWolf95 Have you found that your social links, etc. get restored as expected upon reauthentication?

**Comment by yknl** [comment]
The latest release should fix this issue.
https://github.com/blockstack/blockstack-browser/releases/tag/v0.35.2

**Comment by jehunter5811** [comment]
Verified this fix. Thanks @yknl
