### ISSUE TITLE
Updating browser screen – add option to reset browser and start over with recovery key

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1760]
![Screen Shot 2018-12-30 at 7:27 PM](http://marker.screenshots.prod.s3.amazonaws.com/bd61f88a9ac04bf883d74da1b33ad0aa-1546198035272.png)
---
### More Info

**Source URL**: [https://forum.blockstack.org/t/unable-to-log-in-after-browser-update/7079](https://forum.blockstack.org/t/unable-to-log-in-after-browser-update/7079)

**Comment by markmhx** [comment]
@aulneau Could you provide some design guidance here when you have a chance?

**Comment by aulneau** [comment]
Yep I will tomorrow!

**Comment by jeffdomke** [comment]
Think we should prioritize this. The more stuff that breaks the more updates we push the more chances there are for this to frustrate users.
