### ISSUE TITLE
Fix back button to app on initial modal

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1761]
I'm finding that the "Back to [App Name]" button doesn't do anything:

<img width="619" alt="screen shot 2018-12-30 at 20 49 03" src="https://user-images.githubusercontent.com/28991/50550681-387e0280-0c75-11e9-9754-7f853fb8aab7.png">

**Comment by markmhx** [comment]
We discussed this internally and decided to simply remove this back button entirely, both from this modal and the one shown later in the flow upon optionally viewing your seed.

**Comment by hstove** [comment]
This is actually fixed with @aulneau's fix in https://github.com/blockstack/blockstack-browser/pull/1809
