### ISSUE TITLE
Fix recovery email delivery

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1762]
When signing up for a new ID with the hosted browser, I got two "failed to send" errors in a row:

<img width="1440" alt="screen shot 2018-12-30 at 20 50 47" src="https://user-images.githubusercontent.com/28991/50550693-5fd4cf80-0c75-11e9-8eb6-6d80f4b271cc.png">

I'm not sure if it has anything to do with using "+2" in my Gmail address to distinguish it from my other ID's registration (which was my intent).

**Comment by nathanielcook** [comment]
Happened to me as well. No plus signs in my email address.

**Comment by yknl** [comment]
This has been fixed, it was an issue with the email service.
