### ISSUE TITLE
Fix profile.json URL post-signup

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1763]
The URL to my profile appears to be missing a "/" slash after "hub" after signing up for a new ID with the hosted browser:

<img width="681" alt="screen shot 2018-12-30 at 20 53 00" src="https://user-images.githubusercontent.com/28991/50550733-d4a80980-0c75-11e9-9a59-891221372af7.png">

Fortunately core is reporting the right URL so this appears to be handled incorrectly by the browser itself in the client: https://registrar.blockstack.org/v1/names/markmhendrickson2.id.blockstack

**Comment by vinay035** [comment]
We are also facing the same issue. After decoding the auth token generated the profile url is missing / infront of /hub.

**Comment by markmhx** [comment]
@hstove Has this issue's solution been completely reviewed and as such can be closed in anticipation of release?
