### ISSUE TITLE
Fix id.blockstack name registration

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1764]
When I try to register a name for my newly registered ID, I get the following hanging error (shown in console) even when trying different names:

<img width="1353" alt="screen shot 2018-12-30 at 21 10 40" src="https://user-images.githubusercontent.com/28991/50550853-9f9cb680-0c77-11e9-91f6-4eb0c6a7b051.png">

**Comment by yknl** [comment]
@markmhx you've hit the free name registration limit. The error message could be improved though.

**Comment by markmhx** [comment]
@yknl How does the current limit work? (i.e. maximum names, time factor if any)

**Comment by yknl** [comment]
The subdomain registrar limits names registered by IP address. I don't have the number on hand. There's an existing issue to add an admin interface on the registrar to reset the limits here: https://github.com/blockstack/subdomain-registrar/issues/19

**Comment by markmhx** [comment]
@aulneau I've added this to the new sprint with your assignment
