### ISSUE TITLE
email address is passed as null even if it is present in scope

### ISSUE THREAD

**Issue by vinay035** [blockstack/blockstack-browser#1765]
Even if email is asked in the scope while logging in using blockstack.js

Please attached images
<img width="482" alt="screenshot 2019-01-02 at 17 53 34" src="https://user-images.githubusercontent.com/1333378/50592009-48d1ef80-0eb8-11e9-9bfd-e0b02f8e490f.png">

![screenshot_2019-01-02_at_17_56_35](https://user-images.githubusercontent.com/1333378/50592111-b251fe00-0eb8-11e9-9cd6-e87c27be711c.png)

**Comment by markmhx** [comment]
Thanks for reporting this @vinay035! We'll investigate and resolve ASAP.

**Comment by markmhx** [comment]
After discussing internally, it's become clearer to the team that we don't currently provide email scope support even though it's mentioned in the documentation. So this isn't so much a bug as a failure to fulfill expectations set by the docs.

I've created an epic issue here for planning out how to resolve this discrepancy: https://github.com/blockstack/blockstack-browser/issues/1780

**Comment by markmhx** [comment]
@vinay035 We discussed this internally and realized that we don't actually support this functionality, though it's documented.

This is obviously confusing, and we ought to either add the functionality or remove the documentation for it. We've created a separate issue for exploring the right solution here: https://github.com/blockstack/blockstack-browser/issues/1780

Please let us know your thoughts on that issue if you have them! I imagine you may want to petition for us adding this functionality 🙂

I'm closing out this issue in favor of continuing work and conversation regarding the email scope there.
