### ISSUE TITLE
Fix name registrations for .id domain

### ISSUE THREAD

**Issue by sposth** [blockstack/blockstack-browser#1770]
When I try to register a custom user name on the .id domain, I get the following error message: 
“Error submitting name registration”.

Same with latest versions of Chrome and Safari on a localhost “http://localhost:8888”. 

I have enough balance in my wallet and try for a couple of days to claim a custom user name that is still available.

I use the latest release of the blockstack browser: V0.35.2

The Chrome console shows me the following error report: 

![image](https://user-images.githubusercontent.com/14913025/50642458-82affe00-0f6b-11e9-8862-11ffdcba95e0.png)

Thanks for any suggestions how to deal with this issue.

**Comment by markmhx** [comment]
For reference, two users appear to have reported on the forum the same difficulty with registering names for the .id domain:

- [Name registration for *.id always ends in “Error submitting name registration”](https://forum.blockstack.org/t/name-registration-for-id-always-ends-in-error-submitting-name-registration/7088)
- [“Error submitting name registration”](https://forum.blockstack.org/t/error-submitting-name-registration/7092)

**Comment by sposth** [comment]
# Localhost
Blockstack default installation process. Once I open it, the software runs on http://localhost:8888.

# My Steps: 
http://localhost:8888/profiles
> I klick on "Add A Username"

http://localhost:8888/profiles/i/add-username/0/search
> I search for username "XYZ"
> I get result to register "available names": 
a) "Register xyz.id for 0.0005 Bitcoins" 
and 
a) "Get xyz.blockstack.id for free" 
> I choose a), check the terms and enter password. 
> Despite enough balance I get the following result:
http://localhost:8888/profiles/i/add-username/0/select/XYZ.id
"Error submitting name registration"

**Comment by markmhx** [comment]
After discussing this internally yesterday, we're going to try recreating this bug and see if it may have been due to a temporary uptime issue with the broadcast service.

If we can't recreate, we may need to ask those users who have experienced the bug to recreate it so we can check the broadcast service's log for errors.

**Comment by sposth** [comment]
> If we can't recreate, we may need to ask those users who have experienced the bug to recreate it so we can check the broadcast service's log for errors.

Tested again with latest version. Issue still there (just tested 21:54 CET). Let me know if I can be of help.

**Comment by hstove** [comment]
Our devops team fixed the issue with the broadcast server. I've confirmed this works now by registering a new paid name.
