### ISSUE TITLE
Ensure update form works for Firefox users

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1772]
We've received [a report on Twitter](https://twitter.com/seraph_zaho/status/1080943312339652608) that the "We have updated the browser" form wasn't working in Firefox with the user having to switch to Chrome to submit successfully.

<img width="686" alt="screen shot 2019-01-04 at 10 05 31" src="https://user-images.githubusercontent.com/28991/50680527-51394000-1008-11e9-9cc1-5fece58e9381.png">

**Comment by zone117x** [comment]
Just tested on MacOS with latest version of Firefox 64.0 and everything seems to work.

1. Installed old version of Blockstack Browser v0.35.0.
2. Recovered by Blockstack account in a new empty Firefox session.
3. Logged into an app. 
4. Used Blockstack's update prompt to upgrade to current version v0.35.2
5. Firefox opened and prompted "We have updated the browser, Please enter your password to migrate your data to the new version."
6. Entered my password and it worked.
7. Verified I was still signed into an app, then signed and signed back in with no issues.


Can the user check his Firefox console for any error logs?

**Comment by markmhx** [comment]
After discussing these internally, we decided to try reproducing this bug ourselves in Firefox by downloading an older local browser installation, authenticating, then downloading the newest installation.

It would be best to test with a Windows machine as well should we not manage recreating with a Mac.

**Comment by zone117x** [comment]
I performed the same test on Windows. Everything worked.

**Comment by seraph-zaho** [comment]
Hi,
Some comments: 
- Tried to erase Firefox cache, didn't work.
- I used a 3rd app to erase/clean cache for all the system (macOs MOjave 10.14.3 Beta (18D38a)) and now it's working again.

**Comment by markmhx** [comment]
@seraph-zaho That's great to hear! We'll close this out then, at least until we hear it reported by others. Hopefully it had an uncommon root cause.

**Comment by markmhx** [comment]
@simonlayfield Thanks for the report. It's unclear to me that the SSL error you're encountering relates to this update form specifically, and I believe the local Blockstack Browser served at localhost:8888 supports only HTTP, not HTTPS.

Are you accessing it via `https://localhost:8888` or `http://localhost:8888`?
