### ISSUE TITLE
Fix hanging upon authentication when publish_data scope used

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1773]
As [reported in Slack](https://blockstack.slack.com/archives/C07TM0PSM/p1546475104068900), one of our developers is encountering a hanging behavior upon using the "publish_data" scope for his app.

<img width="1178" alt="screen shot 2019-01-04 at 12 26 16" src="https://user-images.githubusercontent.com/28991/50686034-f4e01b80-101b-11e9-9e28-0d210ad66a50.png">

![image](https://user-images.githubusercontent.com/28991/50686035-f7427580-101b-11e9-8a9a-d9c90706655b.png)

**Comment by brycedev** [comment]
This issue can be closed. I've remedied my issue by utilizing redirectToSignInWithAuthRequest() instead of redirectToSignIn() . Thank you!

**Comment by zone117x** [comment]
Thanks for the update @brycedev 
Are you by chance using an editor/IDE that provides code-completion / JSDoc hints?

**Comment by hstove** [comment]
I'm not sure that this is actually fixed. I think this is a persistent issue with multi-party apps.

**Comment by markmhx** [comment]
I'd agree. It's great that @brycedev found a workaround but users of `redirectToSignIn` will presumably still encounter this bug, so I'll re-open.

**Comment by zone117x** [comment]
@brycedev Was this a bug in the `redirectToSignIn` method, or were you needing to use a feature that requires using `redirectToSignInWithAuthRequest`?

**Comment by brycedev** [comment]
Agreed @markmhx . @zone117x I believe there may be a bug in `redirectToSignIn()`. I noticed the main difference between that and `redirectToSignInWithAuthRequest()` was the need to include a private key in the auth request that I created with `makeAuthRequest()`. Does `redirectToSignIn(redirectURI: String, manifestURI: String, scopes: Array): void` send a private key under the hood, and is that key required for the 'publish_data' scope?

**Comment by zone117x** [comment]
@brycedev This is the `redirectToSignIn()` method (from here https://github.com/blockstack/blockstack.js/blob/6f9c71a0692059d60a6bf4c1d03e0d2dc1efbc9e/src/auth/authApp.js#L128)
```js
export function redirectToSignIn(redirectURI: string = `${window.location.origin}/`,
                                 manifestURI: string = `${window.location.origin}/manifest.json`,
                                 scopes: Array<string> = DEFAULT_SCOPE) {
  const authRequest = makeAuthRequest(
    generateAndStoreTransitKey(), redirectURI, manifestURI, scopes
  )
  redirectToSignInWithAuthRequest(authRequest)
}
```

Can you see how your usage of `redirectToSignInWithAuthRequest()` differs?

If there is a bug then I think this issue should be moved to the blockstack.js repo.

**Comment by markmhx** [comment]
I think our suspicion after discussing this internally earlier in the week was that setting `publish_data` with the `redirectToSignIn` method may result in the profile object being written badly (though that's just a suspicion at this point). As such, I don't _think_ this is related to private keys.

@hstove is planning to test for recreation and see what's indeed going on here though.

**Comment by hstove** [comment]
I've done some testing both of public apps and newly created apps, with the `publish_data` scope, using `redirectToSignIn`. I have not been able to reproduce any bad behavior here. I'm going to close this out, but if anyone can find any reproducible steps, please post them here and we'll dig in!
