### ISSUE TITLE
Ensure Blockstack apps work properly across browsers and systems

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-browser#1775]
This issue will represent a Zenhub epic to track all current major Browser issues that we want to fix in the next release.

**Comment by markmhx** [comment]
@hstove I've updated this epic's title to reflect the quarter's [OKR 7.2](https://paper.dropbox.com/doc/Q1-OKR-draft-discussion-XmLsCJiYuTB4P9qkhxg7Y) "Blockstack app works properly on Chrome, Safari, Firefox, Edge, Brave on macOS, Windows, Android and iOS" since beyond squashing urgent bugs, that's the high-level goal we're targeting with this work.

I think that change also better incorporates @zone117x's work on protocol handling improvements since those aren't bugs per se (though they're certainly experienced as such by many).

Please let me know if you prefer a different framing of this work, though.

cc @jeffdomke

**Comment by jeffdomke** [comment]
Here is the summary from the analysis I did from qualitative data about 40 days ago: 

Stuff that caused onboarding problems: 

- Blockstack.js not updated = 47.37%
- User clicks "deny" when app asks for read/write access (gets dumped in browser and is confused) = 10.53%
- Save Password modal pops up in Android on final step and blocks button to continue to app = 3.51%
- User tries to record seed and gets frustrated = 3.51%

As you can tell, stale blockstack.js, and thus old onboarding problems persisting is by far the largest issue.

**Comment by jeffdomke** [comment]
The apps tested are all apps in the App Mining Alpha. It only tests initial onboarding, no restoration or existing users. 

blockstack.js: This is just developers using an older version in their app. So bugs that were previously solved show up, or you get a weird interaction with an updated browser version. Ideally we would identify these as breaking changes, but we don't always account for every way things can go wrong. Usually the end user manifestation of those bugs just the onboarding fails (just hangs forever on a couple screens that tend to have issues).

**Comment by moxiegirl** [comment]
I added this to Milestone 1 since work is being done.  Maybe only a portion will be done. But good to know that it is part of the work going on within the next two weeks.

**Comment by markmhx** [comment]
@jeffdomke I've created and prioritized the following issues to address the top three problems you encountered during testing:

- [Audit versions used by App Mining apps and solicit upgrades](https://github.com/blockstack/blockstack.js/issues/602)
- [Reduce misuse of "Deny" button during onboarding](https://github.com/blockstack/blockstack-browser/issues/1816)
- [Ensure that "save password" modal doesn't block button on Android](https://github.com/blockstack/blockstack-browser/issues/1817)

As for the last one related to seeds, perhaps https://github.com/blockstack/blockstack-browser/issues/1781 is the best issue to track its solution for now, though going seed-only in a more user-friendly way isn't the only way to resolve frustrations with saving it. A solution here is still TBD and contingent on more research (comparing to Lisk, doing more digging, etc).

**Comment by jeffdomke** [comment]
This can be closed correct?

**Comment by markmhx** [comment]
@jeffdomke Yep, there are a couple of outstanding issues under this epic still, but I think we can safely close it out since we've essentially checked the box here for the related Q1 OKR notwithstanding. We'll handle those two issues as non-epic'ed priorities.
