### ISSUE TITLE
Icon in app manifest are not resolved correctly

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-browser#1783]
The specification for app manifests define that `icon.src` can be relative urls to the base url.
However, the browser assume they are absolute urls and then might show the wrong icon or a broken icon like this:

![bildschirmfoto von 2019-01-10 09-42-57](https://user-images.githubusercontent.com/1449049/50956518-2a718280-14bc-11e9-829c-f906a604184f.png)

(in this case using localhost:8888 (the browser base url) instead of the app base url)

**Comment by GInxh** [comment]
Thank you for reporting this. We will get back to you soon.

**Comment by hstove** [comment]
I'm going to move this to the icebox. Not because it isn't valid, but unfortunately I don't think we'd make this a priority for the time being. This could be a good community contribution.
