### ISSUE TITLE
Blockstack Mobile Browser Camera Bug

### ISSUE THREAD

**Issue by prabhaav** [blockstack/blockstack-browser#1790]
When recovering an existing ID, if the user chooses to use the QR code flow, the following error comes up: 
<img width="768" alt="blockstackiosbug" src="https://user-images.githubusercontent.com/11723563/51132069-26a86d80-17e6-11e9-9022-415af1569155.png">

**Comment by markmhx** [comment]
I believe we built this QR code feature only to decide to no longer support it. So we may be able to simply remove it. @jeffdomke Is that indeed the case?

I'm adding this to our current epic for ensuring that Blockstack works across systems and browsers, so we'll get to this ASAP.

**Comment by markmhx** [comment]
@prabhaav We certainly want to unblock you here ASAP. @hstove Is there a quick fix we can get in place for Stealthy (perhaps by detecting user agents for web views like this?) that can resolve their app store need even if we need more time deciding on whether to keep QR codes in general?

**Comment by markmhx** [comment]
Also @shreyasthiagaraj any ideas from our end on how we or they might resolve this with iOS code as a hotfix at least?

**Comment by prabhaav** [comment]
This isn't in our iOS code, this is the Blockstack Auth that comes up before the user is even able to use the app.

**Comment by markmhx** [comment]
@prabhaav Yea understood, just pinging him in case he has a creative solution given the web view context. But I imagine this will be something we resolve in the browser code.

**Comment by hstove** [comment]
When I go to reproduce this, it asks me for permission to use the camera, and I click 'Accept'. Then it works as normal. If you click 'Deny', it shows this error message. Is that not your behavior?

**Comment by prabhaav** [comment]
That question never comes up for me on mobile Safari

**Comment by hstove** [comment]
You may have denied it previously. Go to Settings -> Safari -> Allow Camera & Microphone to see if it's denied

**Comment by prabhaav** [comment]
This is a bug report filed by Apple app review team

**Comment by hstove** [comment]
Yeah, I get that. So, it sounds like the only thing we could improve here is the error message? Unless there really is a bug here, but I wasn't able to reproduce it.

**Comment by prabhaav** [comment]
![img_5b019bd55c2c-1](https://user-images.githubusercontent.com/11723563/51140908-9fb2bf80-17fc-11e9-95f0-f51c2843e35b.jpeg)

I have those settings enabled and I still see the same error

**Comment by shreyasthiagaraj** [comment]
Yea, once the browser is open I don’t think we  have any control from iOS
code. Sounds like it would be a web fix...

**Comment by prabhaav** [comment]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/11723563/51150080-aef43600-1819-11e9-9c8f-a7c0b31cc037.png">

That was the issue they identified with the `No video input devices found`

**Comment by jeffdomke** [comment]
Seems like we should hide the button and entire feature in Safari. @hstove assigning to you.

**Comment by hstove** [comment]
@prabhaav has this ever worked in stealthy? I’m wondering if you have to update your plist file to support the permission dialogue

**Comment by prabhaav** [comment]
@hstove never tried it. This is outside of Stealthy in the Blockstack browser.

**Comment by shreyasthiagaraj** [comment]
Ah, right. We pass in `client: ios_secure` to indicate the special browser
window. I think for the latest version of iOS we may be able to avoid using
`SFAuthenticationSession`, so perhaps I could do something on SDK side to
avoid this. But for certain versions of iOS (I think iOS 11?) this cannot
be avoided. It'll need to be fixed on the browser side then to hide the
button.

**Comment by prabhaav** [comment]
FYI @hstove , I found an issue with the fix. It didn't block us from getting into the app store, but this issue might come up again. See attached video:
[scannerBug.mov.zip](https://github.com/blockstack/blockstack-browser/files/2770235/scannerBug.mov.zip)
