### ISSUE TITLE
Brand URL for local installation

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1798]
Noticed that the casa node has a nice local URL: `Casa-node.local`

Would be nice to have our own version of this: 

Current: `http://localhost:8888/sign-up`

Proposed: `http://blockstack.local/sign-up`

What are the restrictions on what we can do?

**Comment by markmhx** [comment]
I imagine this entails primarily adding a record to the user's host file (e.g. `/etc/hosts`) upon installation of the browser.

@zone117x thoughts on whether that's the case and if it's easy enough to do with our installer?

**Comment by zone117x** [comment]
**Short answer**: We can't do this. It requires sudo/admin permissions on all operating systems which is would have an unacceptable impact on both UX and security. 

**Long answer**: Local network devices use various forms or [zeroconf networking](https://en.wikipedia.org/wiki/Zero-configuration_networking) for the use-case in Jeff's example. Casa node is likely using [mDNS](https://en.wikipedia.org/wiki/.local#mDNS_implementations) broadcasting which some operating systems will use for resolving `{name}.local` DNS queries to a local device IP. Nothing like is applicable to our situation: a device accessing its own locally hosted http server.

**Comment by jeffdomke** [comment]
cwel. so close as no fix yeah?
