### ISSUE TITLE
Improve UX of authentication clearance page

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-browser#1799]
https://browser.blockstack.org/clear-auth

Clicking "Press again to confirm" at the Sign Out screen does nothing on web. On iOS I get this error: "Safari cannot open the page because that address is invalid."

**Comment by markmhx** [comment]
I can confirm on my end, too, that it's not working. Has this broken recently? It seems it was working just a few days ago.

**Comment by markmhx** [comment]
- Add /reset path
- Ensure redirect to /sign-up across all devices upon "Reset My Device" click
- Snazzy up design with standard components

**Comment by markmhx** [comment]
@aulneau Does this issue still seem feasible for the current sprint?
