### ISSUE TITLE
Fix social verification for GitHub account

### ISSUE THREAD

**Issue by thaonguyenle** [blockstack/blockstack-browser#1805]
I am on: http://localhost:8888/profiles
I click on: Prove your Github account
I followed instructions to create a public gist, here: https://gist.github.com/thaonguyenle/b75e39326b0b7d2a8fa825fea32e79d4

I click verify. It takes me back to http://localhost:8888/profiles, without a +1. :(

**Comment by GInxh** [comment]
We will add this as a data point to help resolve the bugs around proving social accounts on Blockstack profiles. Thank you for the feedback!

**Comment by markmhx** [comment]
@thaonguyenle Would you mind trying to verify with GitHub again and see if you can recreate this problem? If so and you're able to recreate, we'll dig into solving it.

**Comment by thaonguyenle** [comment]
Hey,

I can’t even remember this issue. So most likely not. Was this from a long
time ago? Thanks for following up then.

**Comment by markmhx** [comment]
Yep from January. I'll close out then, thanks!
