### ISSUE TITLE
Pass Core API URL into auth response

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-browser#1827]
When signing in, the browser does not pass in the user's preferred Blockstack Core node's API url.  It needs to do so in the call to `makeAuthResponse` in `app/js/auth/index.js`.

**Comment by jcnelson** [comment]
Fixed in https://github.com/blockstack/blockstack-browser/pull/1830

**Comment by markmhx** [comment]
I'm closing this issue since the above PR appears to have resolved it.
