### ISSUE TITLE
add user's real name to profile card list on landing view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#183]
Add user's real name to profile card list on landing view

<img width="419" alt="screenshot 2017-02-06 18 37 17" src="https://cloud.githubusercontent.com/assets/1711854/22671242/4fd317a0-ec9b-11e6-8eed-a7b812ebfa6d.png">

**Comment by guylepage3** [comment]
@shea256 shall we add this as a feature for v0.4.0?

**Comment by shea256** [comment]
Sounds great @guylepage3
