### ISSUE TITLE
Update release checklist doc

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1841]
Update the checklist to reflect the new build process.
https://github.com/blockstack/blockstack-browser/blob/master/maintainers/release-checklist.md

**Comment by markmhx** [comment]
@yknl Is this priority enough to include in the next sprint? And if so, who should we assign?

I'll icebox meanwhile.

**Comment by yknl** [comment]
Yes, it should be included. I assigned myself.

**Comment by hstove** [comment]
@yknl did this, it's been merged.
