### ISSUE TITLE
Add option to delete profile photo

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1845]

**Comment by russwfranklin** [comment]
![image](https://user-images.githubusercontent.com/21110565/53185976-1e560600-35ce-11e9-9937-af5c6953b13e.png)

**Comment by markmhx** [comment]
Thanks @russwfranklin – I'm going to close this out since we've created an issue that subsumes your request here in that it proposes we add the option to delete a number of user data points: https://github.com/blockstack/blockstack-browser/issues/1852
