### ISSUE TITLE
Helloblockstack.org only works with installed version, not via web

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack-browser#1847]
Suggest also updating branding.

I tested this several times, logged in without the Windows install running, wouldn't load, localhost error. When I turned that back on, I could login. It should work with just the browser.

**Comment by hstove** [comment]
Good catch, but I'm gonna close this, because we're completely re-doing the homepage in the next release. We'll only pull apps from app.co, which doesn't include HelloBlockstack.
