### ISSUE TITLE
Linux Sign In Loop

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/blockstack-browser#1848]
I have a Graphite user who needs some help. Posting here and opening a bug in the Blockstack Browser repository. I'm copying and pasting his message to me so you can see the steps he's taking, but basically, he's getting stuck in an endless loop because (maybe) the browser is not providing an auth response? Or not actually restoring his ID? 

1. I start at https://app.graphitedocs.com/ and click on the "Sign in with Blockstack" button. 
2. I get a pop-up and select the "Sign in with an existing ID" button. 
3. I am asked for my "Secret Recovery Key or Magic Recovery Code". I provide my Secret Recovery Key in this case. I get the same result using my Magic Recovery Code but it takes more steps. 
4. I am asked for my password which I provide. 
5. I am asked for my email address which I provide. 
6. I get a "Restoring your Blockstack ID" info screen. 
7. I get a screen informing me that my ID has been restored. I then try to click on "Go to Graphite". 
8. I get a "Select an ID" warning screen that tells me that "Graphite" wants to read my basic info etc. I select my ID in the purple button. At this point I get taken back to the original log-in screen (Step 1). I go through the same steps logging in from Blockstack (https://browser.blockstack.org/) except when I get to Step 7, I get a button to "Go to Blockstack" (see screenshot_09). I then get a menu of Blockstack apps and select "Graphite" (see screenshot_10). Then, I get taken to your website (see screenshot_11) and have to click on "Sign in" in the top-right corner. Then I got through the same merry process I've documented without any success.

**Comment by markmhx** [comment]
This was also cross-posted on the forum at https://forum.blockstack.org/t/linux-sign-in-problems/7542.

@jehunter5811 After we emailed a bit about this user's problem, were you able to track down the problem any more precisely? Or need us to research it?

**Comment by jehunter5811** [comment]
Not sure what I can do to track it down since it seems to be blockstack.js code causing the issue. For example, I just managed to make this happen locally on Graphite Publishing and had console open. Here's the error: 

`Error: Failed to login: Invalid authentication response.`

**Comment by hstove** [comment]
Can you provide reproduction steps and possibly code? What version of blockstack.js?

**Comment by jehunter5811** [comment]
Sure thing! My scenario is different from the user who reported it. I'm on a Mac, not a Linux machine. But I saw it happen a few times with this as my code to handle pending sign-in: 

```
if (isSignInPending()) {
      handlePendingSignIn().then((userData) => {
        window.location = window.location.origin;
      });
    }
```

I stick that in the componentDidMount lifecycle method to catch a pending sign in as soon as a user returns to the app. 

The error doesn't happen all the time, but when it does, it seems very similar to the original report. I land back at the app sign in page with the url including the authResponse. No redirect or authResponse handling occurs. 

This is on blockstack.js 18.3.0.

**Comment by hstove** [comment]
Is there any pattern to if it happens for a new Blockstack user vs. a user already signed into the Browser?

Also, you're using the 'custom Gaia hub onboarding' flow, right?

**Comment by markmhx** [comment]
@jehunter5811 could you provide any more info regarding @hstove's inquiries above so we can track this down better?

**Comment by jehunter5811** [comment]
I can't replicate this anymore. No idea if Linux users are still having a problem because I don't have a Linux machine to test on.

**Comment by markmhx** [comment]
@jehunter5811 thanks for the update. It seems as though the original user was unable to provide us more information to diagnose, so perhaps we ought to close this issue until we hear of more reports. Please let me know, though, if you'd like to keep it open while you follow up with them.
