### ISSUE TITLE
User acceptance test the Blockstack Core API to prepare for the integration

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#185]
@larrysalibra is out tomorrow and won't be able to see the changes to the Blockstack Core REST API until Thursday.

I am going to work with @jcnelson to do user acceptance testing on the Blockstack Core REST API.

There are two items that @larrysalibra has requested:

- Remove the authentication from the API
- Remove the requirement to pick a password for the node

**Comment by larrysalibra** [comment]
@jcnelson and I worked through a bunch of issues earlier - thanks so much to him for staying up so late to help out. 

These are the remaining outstanding core API issues for this release:

https://github.com/blockstack/blockstack-core/issues/298
https://github.com/blockstack/blockstack-core/issues/297
https://github.com/blockstack/blockstack-core/issues/295
https://github.com/blockstack/blockstack-core/issues/294

I've submitted a pull request that should fix two of them: https://github.com/blockstack/blockstack-core/pull/296

**Comment by larrysalibra** [comment]
These are the remaining core API issues outstanding:
https://github.com/blockstack/blockstack-core/issues/298
https://github.com/blockstack/blockstack-core/issues/297

**Comment by shea256** [comment]
@larry @jcnelson can we close 185 and keep these two open until they're addressed?

blockstack/blockstack-core#298
blockstack/blockstack-core#297

cc'ing @guylepage3 on this too

**Comment by guylepage3** [comment]
closing this issue
<img width="149" alt="screenshot 2017-02-13 16 15 37" src="https://cloud.githubusercontent.com/assets/1711854/22903739/abb62122-f207-11e6-9054-921499366ff9.png">

**Comment by shea256** [comment]
@guylepage3 reopened until @larrysalibra and @jcnelson respond

**Comment by jcnelson** [comment]
#298 is addressed.  I don't think we can get to #297 without `blockcypher`'s cooperation.

**Comment by shea256** [comment]
OK cool. Let's close this then and we can revisit blockstack/blockstack-core#297
