### ISSUE TITLE
Improve error message encountered because of rate limiting when registering new ID

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack-browser#1851]
<img width="1440" alt="screen shot 2019-02-26 at 3 02 00 pm" src="https://user-images.githubusercontent.com/25477905/53442833-294ad500-39d8-11e9-8bcc-dd7220bc29d4.png">

- Click `Create new ID`
- Enter username and continue
- Create a password
- Click `Register ID`
- Shows this error

Edit: it's because of rate limiting. The current error message does not convey the cause — it makes it seem like Blockstack is at fault.

**Comment by markmhx** [comment]
I'm labeling this with "bug" since the user perception is that it's a bug since they aren't informed of why there's a failure and what they can do about it.
