### ISSUE TITLE
Add email value to session upon re-authentication

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1853]
Currently we store the user's email address in their session only during the first session as initiated with registration. This issue entails storing it in subsequent sessions as well, using the email value as provided again by the user during the sign-in flow, so that developers with the `email` scope permitted can get the value regardless of when the user's session was created.

This is a hotfix of sorts that resolves a core issue for the following epic: https://github.com/blockstack/blockstack-browser/issues/1780

**Comment by markmhx** [comment]
@yknl Is this an issue you or someone else could pick up mid-sprint this week for fast completion? Or best to resolve going into next sprint? cc @jeffdomke

**Comment by hstove** [comment]
@zone117x fixed this - its in the beta release.
