### ISSUE TITLE
Unexpected string in JSON at position 262

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-browser#1858]
I'm getting the following error during auth flow.

```
[DEBUG] SyntaxError: Unexpected string in JSON at position 262
    at JSON.parse (<anonymous>)
    at https://browser.blockstack.org/static/js/vendors.1b38d2faab448e4b154f.chunk.js:23:238823

```
I tried to run my app in Incognito mode.. I got the same error, but was prompted to create/restore an account, and that process worked, but I was redirected to Blockstack Browser, instead of back to my app.
<img width="1169" alt="screen shot 2019-03-05 at 3 14 08 pm" src="https://user-images.githubusercontent.com/7738/53844267-067d6b00-3f5a-11e9-96d5-563d4c8e4a91.png">

In Incognito mode, after restoring my account, and attempting to log in, I  got the "Failed to fetch information about the app requesting authentication..." error.
<img width="1166" alt="screen shot 2019-03-05 at 3 14 52 pm" src="https://user-images.githubusercontent.com/7738/53844209-df269e00-3f59-11e9-9d05-71b07236994b.png">

**Comment by dantrevino** [comment]
sign-in code 
```
   signIn() {
      let manifest = window.location.origin + "/manifest.json";
      console.log("manifest.json at : " + manifest);
      this.$blockstack.redirectToSignIn(window.location.origin, manifest, [
        "store_write",
        "publish_data"
      ]);
    }
```
manifest
```
{
  "name": "w3b3",
  "short_name": "w3b3",
  "theme_color": "#250E31",
  "background_color": "#FFFFFF",
  "display": "standalone",
  "scope": "/",
  "start_url": "/",
  "icons": [
    {
      "src": "https://infallible-colden-26bcfc.netlify.com/icon.png"
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```

**Comment by markmhx** [comment]
@dantrevino Did you encounter these bugs in production or development? If the former, do you have a URL I can use to try recreating?

In my experience, the "Failed to fetch information about the app requesting authentication" error is always related to CORS or URL structure (e.g. localhost vs 127.0.0.1 in development).

I haven't seen the "Unexpected string in JSON at position 262" error before, if I recall correctly.

**Comment by dantrevino** [comment]
FFS.  Spent over an hour reconfiguring my cors with different servers trying to recreate and it turns out I was missing a comma between icons.src and icons.sizes properties in manifest.json.  EBKAC.  smh.

**Comment by hstove** [comment]
It happens! I should have asked you to paste your `manifest.json`. I know the feeling of being deep in your code and missing what's right in front of you.

**Comment by markmhx** [comment]
The most puzzling bugs are always right in front of you 🙃
