### ISSUE TITLE
finalize the blockstack core installation process in the mac build

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#187]
@larrysalibra said right now we are pip installing blockstack core from pypi.

Before we publish the mac app, we need to have done one of several things:

- Push the changes made to Blockstack Core to pypi
- Change the installation process so Blockstack Core is installed from a GitHub branch

Tagging @jcnelson on this as well so he can be kept in the loop.

**Comment by larrysalibra** [comment]
We're now installing using `pip` from the repo branch: https://github.com/blockstack/blockstack-browser/blob/7a693d198733afc2a9c3d5979aa2c36976bc40f0/native/macos/build_blockstack_virtualenv.sh#L36
