### ISSUE TITLE
Forum login fails using blockstack ID login

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-browser#1915]
**Describe the bug**
Blockstack forum login fails using the Blockstack ID login option. When the user is trying to log into the blockstack browser web app they are NOT taken into the forum as expected but asked to select the forgot your password link and receive an error message. 

**See video of bug here: http://somup.com/cqhjo5naUo**

**To Reproduce**

_USE A VM OR A MACHINE THAT IS NOT SIGNED IN WITH THE BLOCKSTACK APP. THIS SEEMS TO WORK WITH THE BLOCKSTACK APP SO YOU WILL NOT SEE AN ERROR USING YOUR DEV MACHINE._ 

1. Go to forum.blockstack.org select the option to login, then select login with a blockstack ID
2. Click on 'Login with blockstack web app' when prompted
3. Login to the blockstack web app and Restore your ID and when prompted select the "go to blockstack forum" button
4. You will be taken to the blockstack forum and there will be a green error message at the top of the login pop-up that tells you to reset your password to access the forum.
5. Since the user is a new user and has not registered a email / password with the forum and registered using the blockstack ID they will receive a message that says "email not found" 
6. Then they will be prompted to login again and if they select the Blockstack ID option they will go into an endless loop and repeat all the steps above starting at step 2

**Expected behavior**
The user should be able to successfully log into the forum with a Blockstack ID they should not go back to a login screen 

**Screenshots**
<img width="399" alt="Screen Shot 2019-05-08 at 12 17 28 PM" src="https://user-images.githubusercontent.com/49165468/57390885-514e7580-718b-11e9-822b-efcd4e193fd8.png">

<img width="551" alt="Screen Shot 2019-05-08 at 12 08 20 PM" src="https://user-images.githubusercontent.com/49165468/57390692-f3ba2900-718a-11e9-978b-803e523bc408.png">

<img width="454" alt="Screen Shot 2019-05-08 at 12 08 54 PM" src="https://user-images.githubusercontent.com/49165468/57390693-f3ba2900-718a-11e9-8314-1285fdda64a3.png">

**Desktop (please complete the following information):**
 - OS: [iOS 10.14.4]
 - Browser [chrome Version 74.0.3729.131]
 - Version [block stack web app]

**Comment by yknl** [comment]
Thanks @timstackblock, this issue should be added to https://github.com/blockstack/blockstack-ruby

**Comment by timstackblock** [comment]
Moved this issue to  https://github.com/blockstack/blockstack-ruby and closing it in this repo

**Comment by timstackblock** [comment]
I am reopening this ticket this issue is back.

<img width="793" alt="Screen Shot 2019-06-06 at 4 33 29 PM" src="https://user-images.githubusercontent.com/49165468/59064786-18ccb500-8879-11e9-9512-ee6a200bf252.png">

**Comment by timstackblock** [comment]
https://github.com/blockstack/blockstack-ruby/issues/7 wrong repo moving the convo to blockstack-ruby
