### ISSUE TITLE
Error adding custom Blockstack ID

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-browser#1919]
I have been trying to add a custom Blockstack id by navigating to the profile page and clicking on the More button. Unfortunately, the feature doesn’t appear to work. It always results in an error: Error submitting name registration

https://forum.blockstack.org/t/adding-a-custom-blockstack-id/8059

**Comment by lord-aerion** [comment]
I'm experiencing the same issue.

The console logs the following messages:

```
main.6428ee1fae7a8e458387.chunk.js:1 <my-desired-username>.id
main.6428ee1fae7a8e458387.chunk.js:1 <my-desired-username>.id.blockstack
core.blockstack.org/v1/names/<my-desired-username>.id:1 Failed to load resource: the server responded with a status of 404 ()
registrar.blockstack.org/v1/names/<my-desired-username>.id.blockstack:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by HaroldDavis3** [comment]
If I’m not mistaken this is the problem that requires a refresh of the page after entering the session password for the new name. 

Note: This needs to be repeated when resetting your browser as well if you have more than one name attached to one key.

**Comment by bauhouse** [comment]
Thanks, @moxiegirl, for adding this issue on my behalf.

As requested, here are the details of my environment:

- **Browser:** Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- **Platform:** macOS 10.14.5 (18F132)
- **Blockstack ID:** `bauhouse.id.blockstack`

As mentioned in the original forum post, I have been trying to add a custom Blockstack id by navigating to the profile page and clicking on the More button. Unfortunately, the feature doesn’t appear to work. It always results in an error: `Error submitting name registration`.

The console returns the following:

```
Failed to load resource: the server responded with a status of 404 ()
core.blockstack.org/v1/names/<selected-name>.id:1

Failed to load resource: the server responded with a status of 404 ()
registrar.blockstack.org/v1/names/<selected-name>.id.blockstack:1

Unchecked runtime.lastError: The message port closed before a response was received.
```

Forcing a reload of the page results in the same error.

**Comment by lord-aerion** [comment]
Is there any movement on this issue?

I've been trying to register my preferred ID for several weeks now, and it appears to hinge on a simple 404 error; surely this can be fixed in mere minutes?

**Comment by kevins** [comment]
I don't think you can get a custom usernames anymore. The onboarding process only allows you to use the blockstack.id usernames. When I made my account, they made me get a username.blockstack.id name but it didn't add the username to my profile right away. 

They gave me the option to create a custom id by paying bitcoins. After getting an error for a few days, my profile finally updated to show the username I signed up as on my profile (the username.blockstack.id one). 

So I'm assuming that the username you signed up as can't be changed and that's why we get the error.

**Comment by yknl** [comment]
This should be fixed in the latest version v0.36.3. https://github.com/blockstack/blockstack-browser/releases/tag/v0.36.3

**Comment by markmhx** [comment]
@lord-aerion @bauhouse Could you confirm that this bug is now resolved for you?

**Comment by kevins** [comment]
> @lord-aerion @bauhouse Could you confirm that this bug is now resolved for you?

Now when I sign up it doesn't even give me the option to create a "username.id" ID and just makes a "username.blockstack" ID

**Comment by markmhx** [comment]
@kevins That should be expected during sign up, then afterwards you should be able to register more IDs with ".id" through the browser by navigating to the "Identity" tab.

**Comment by kevins** [comment]
@markmhx It works now. Thanks. The price for the custom names went up by a lot though :(

**Comment by markmhx** [comment]
Sorry about that 😞 We're moving to our own blockchain in part because of BTC price concerns.
