### ISSUE TITLE
BUG REPORTED IN FORUM: Error submitting name registration, I have latest version

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-browser#1925]
FORUM POST
https://forum.blockstack.org/t/error-submitting-name-registration-i-have-latest-version/8074

**Describe the bug**
Error submitting name registration, in Windows 10

**To Reproduce**
1. Go to https://browser.blockstack.org/profiles/i/add-username/0/search
2. Enter a valid name and search for it
3. Select the option to register the name when it appears
4. User will see error appear in console when the user selects the option to buy an address with bitcoin
5. User will see the screen freeze if the user selects the option for a free name ending in .blockstack on a windows machine, it does not freeze on a mac

**Expected behavior**
I am seeing a different result in windows than I do on my mac, I would expect both browsers to work exactly the same

**Screenshots**
![may281](https://user-images.githubusercontent.com/49165468/58481237-ff659380-8129-11e9-9f14-e5a61cafb667.jpg)
![may282](https://user-images.githubusercontent.com/49165468/58481238-ff659380-8129-11e9-92f7-6365fffdaac5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by moxiegirl** [comment]
Closed by: https://github.com/blockstack/blockstack-browser/pull/1928
