### ISSUE TITLE
Blockstack token voucher

### ISSUE THREAD

**Issue by spindriftur** [blockstack/blockstack-browser#1930]
Hey, can I still claim this?!
<img width="725" alt="Screen Shot 2019-06-02 at 5 47 37 PM" src="https://user-images.githubusercontent.com/26857602/58767818-b7e26b80-855e-11e9-8bd6-d4ada7fb1d48.png">

**Comment by moxiegirl** [comment]
@spindriftur please send an email to support@stackstoken.com to see about your voucher
