### ISSUE TITLE
Some apps fail to auth in Chrome 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-browser#1946]
This might be a repeat issue, but Blockstack apps have been failing to auth me in via chrome or simply not functioning, but they are working in other browsers. Example below: 
<img width="1362" alt="Screen Shot 2019-08-19 at 9 27 17 AM" src="https://user-images.githubusercontent.com/30627583/63269902-0998b900-c265-11e9-8738-88f8cf4a0ac1.png">

**Comment by jeffdomke** [comment]
@GinaAbrams Ken looked into this a bit and seems like an app server config issue. Have any more context on which app and a status from that app founder?
