### ISSUE TITLE
Profile network requests for ID creation step

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1948]

**Comment by zone117x** [comment]
I ran through the ID creation process while the Chrome profiler was enabled. 

ms | HTTP method | endpoint description
-- | -- | --
107 | get | hub_info
51 | options | store profile
248 | post | store profile
64 | options | register
865 | post | register

totals | -
-- | --
1335 | total time
1220 | time if option requests were properly cached


The total time spent on network requests is around ~1.2 seconds (subtracting the broken cached CORs `HTTP OPTION` request time). 

This was also done on a VPN to avoid the office IP registration rate limits, so the total time is probably closer to less than 1 second.
