### ISSUE TITLE
Add notice to wallet route distinguishing Stacks Wallet

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1964]
Currently, visitors to [the Blockstack Browser's "Wallet" route](https://browser.blockstack.org/wallet/receive) are prone to confuse the Browser's BTC wallet shown there with [the separate Stacks Wallet](https://wallet.blockstack.org/) for STX tokens.

This issue entails adding a notice to the top of this route's view that alerts the user to the distinction and directs all users interested in the Stacks Wallet to its website.

**Comment by markmhx** [comment]
@moxiegirl Could you please provide the content to provide in this notice with any relevant URLs?

**Comment by moxiegirl** [comment]
@markmhx please see the PR fix I made for this: https://github.com/blockstack/blockstack-browser/pull/1965

**Comment by markmhx** [comment]
@moxiegirl I think I saw in Slack that you may want to update this PR before release based on Ryan's feedback – is that the case?

**Comment by moxiegirl** [comment]
Yes.

**Comment by markmhx** [comment]
@moxiegirl Cool. It'd be great to review those latest changes next Tuesday when we meet to discuss this change's inclusion in our next browser release.
