### ISSUE TITLE
change @media 975px breaking point in blockstack-bootstrap

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#197]
Discovered that `blockstack-bootstrap` has an odd breaking point of `@media (min-width: 975px;)` instead of the standard `@media (min-width: 992px;)`. This was causing a lot of breaking issues with the profiles app.

**Comment by jackzampolin** [comment]
Is this issue closed out?

**Comment by guylepage3** [comment]
Complete with bootstrap v4 upgrade.
