### ISSUE TITLE
User report of email entitled "Save this email: Recovery info" was never delivered - shared screenshot from all folders showing it is not there

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#1979]
I have seen this come up off and on, unsure whether its user error or error in mailing

**Comment by timstackblock** [comment]
This is a valid bug, I am able to reproduce

<img width="219" alt="Screen Shot 2019-12-03 at 9 59 36 AM" src="https://user-images.githubusercontent.com/49165468/70062331-d11eb000-15b3-11ea-9aa7-a3ea0c4a81c5.png">

**Comment by hstove** [comment]
We've addressed this - which turned out to be an issue with a 3rd party API. Feel free to re-open if you see this again.
