### ISSUE TITLE
Remove Dappy wallet from dApp list

### ISSUE THREAD

**Issue by eugeneives** [blockstack/blockstack-browser#1986]
Team stopped the app development and Dappy wallet [website](https://dappywallet.com/) is not available now. Dappy' icon in the Blockstack browser is misleading. I think it should be deleted. Also, I found some more broken links in the browser.

Broken links:
- [Dappy Wallet](https://dappywallet.com/)
- [Vyse Auth](https://vyse.in/)
- [Tunzal](https://tunzal.ml/)
- [PusteBucket](https://pastebucket.io/) – broken SSL/https connection
- [MyWhereAbout](http://mywhereabouts.get2getherwith.me/)
- [El Weather](https://elweather.com/)
- [BlockRight](https://blockright.moochain.com/) – broken SSL/https connection
- [BePrivate](https://beprivate.co/)
- [Prism](https://prismreader.app/)
- [Arcane Boards](https://boards.arcane.ac/)
- [Huaren.News](https://huaren.news/) – broken SSL/https connection
- [Ourtopia](https://www.ourtopia.co/)
- [Crowdraise](https://crowdraise.net/)
- [Secure Photo](https://secure-photo.com/)
- [Arcane Darkroom](https://darkroom.arcane.ac/)
- [Aodh](https://aodh.xyz/)
- [Wage](https://wage.pm/) – broken SSL/https connection
- [Foodrover](https://foodrover.info/)
- [Thunderstack](https://thunderstack.id/) – broken SSL/https connection
- [Avicenna](https://avicenna.casa/) – gateway timeout
- [Predicto](https://www.predictoapp.com/)
- [Sensei Chat](https://sensei.chat/)
- [Satoshi Nakamoto Vs The World](https://www.satoshivstheworld.com/)
- [Vermilion](https://vermilion.arcane.ac/)
- [Blockcred](http://www.blockcred.io/)
- [SendFriend](https://www.sendfriend.xyz/)
- [DOKTER](http://dokterapp.tk/) – redirect to webcam models **(Remove it ASAP!)**
- [Arcane Books](https://books.arcane.ac/)
- [Kanstack](https://kanstack.com/)

You need to check these links again and ping the authors. If not, remove the broken applications from the browser.

**Comment by markmhx** [comment]
Thanks @eugeneives! I'm reviewing and removing these now.

**Comment by markmhx** [comment]
I've removed all of the apps in your list except for the following, which load fine for me:

- Vyse Auth
- BePrivate
- Arcane Boards
- Crowdraise
- Arcane Darkroom
- Aodh
- Predicto
- Vermilion
- Blockcred
- Arcane Books

If anyone with a removed app confirms with me (here or elsewhere) that it's back up and running properly with HTTPS, I'll put it back on App.co. None of the associated data was deleted from App.co; I simply removed from listing.

**Comment by njordhov** [comment]
Are these apps also removed from November app mining?
