### ISSUE TITLE
npm install fails: ssh dependency

### ISSUE THREAD

**Issue by cstrangedk** [blockstack/blockstack-browser#199]
**Steps to reproduce:**

`git clone https://github.com/blockstack/blockstack-browser.git`
`npm install`

**Error:** 

`npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Cloning into bare repository '~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494'...
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Permission denied (publickey).
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: fatal: Could not read from remote repository.
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494:
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Please make sure you have the correct access rights
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: and the repository exists`

**Comment by larrysalibra** [comment]
Thanks for the issue! This was fixed in https://github.com/blockstack/blockstack-browser/issues/125 - fixes haven't been merged into master yet. Please try the `web-0.3` branch and re-open if it still happens. Thanks!

**Comment by cstrangedk** [comment]
This is still happening on the `web-0.3` branch.  

**Steps to reproduce:**
`git clone https://github.com/blockstack/blockstack-browser.git -b web-0.3`
`npm install`

**Error:**

`npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Cloning into bare repository '~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494'...
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Permission denied (publickey).
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: fatal: Could not read from remote repository.
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494:
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Please make sure you have the correct access rights
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: and the repository exists.
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) Permission denied (publickey).
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git)
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) and the repository exists.`

**Comment by larrysalibra** [comment]
Thanks! We'll take a look!
