### ISSUE TITLE
Change link included in tweet for Twitter social verification

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#2004]
The Explorer link included in a tweet posted during Twitter social verification should be removed and replaced with a shortened version (e.g. bit.ly) to https://blockstack.org/try-blockstack with the following GET parameters appended for tracking:

- utm_campaign=social-verification
- utm_medium=social-media
- utm_source=twitter

**Comment by markmhx** [comment]
Whoever pushes this change live should also address https://github.com/blockstack/blockstack.org/issues/1009 simultaneously or leave a comment on that issue indicating that we're now driving traffic to https://blockstack.org/try-blockstack via Twitter.

**Comment by hstove** [comment]
Fixed in d5e1ebe
