### ISSUE TITLE
ID is taken after signing up and logging out then back in

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#2009]
This is coming in from a user in support who has been sent a link to this issue to add to. I will add anything else in here that they send to support.

> I created an id
I had to close my browser, which clears cookies and everything
I came back and used my secret recovery key to get back in
It's showing the id with my name and my short bio, but it keeps saying the id.blockstack id is taken

> So, now it won't let me access my listatta.id.blockstack even though I used my secret key, and have the original password and everything...

> I have the recovery info, i used it, and it's still not the correct id? what gives?

**Comment by markmhx** [comment]
Can we get confirmation on just what they're looking at when they say "it keeps saying the id.blockstack id is taken"? Perhaps with a screenshot?
