### ISSUE TITLE
Fix spacing issue on profile editing page

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#201]
<img width="917" alt="screen shot 2017-02-09 at 11 01 28 am" src="https://cloud.githubusercontent.com/assets/994646/22791365/20d088c0-eeb7-11e6-9331-0416d0634b36.png">

**Comment by guylepage3** [comment]
resolved..

<img width="1059" alt="screenshot 2017-02-12 19 27 29" src="https://cloud.githubusercontent.com/assets/1711854/22867609/507f33d8-f159-11e6-9f9c-66aa6f1df4e0.png">
