### ISSUE TITLE
After restoring ID in browser, the username is already taken

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#2012]
This is coming in from a user in support who has been sent a link to this issue to add to. I will add anything else in here that they send to support.

> I take giansalex.id.blockstack in signup, but in restore login, username is missing, can you help me?.

> I see message:

> giansalex.id.blockstack is already taken

**Comment by giansalex** [comment]
Hello @ryanarndtcm, the browser is `Brave (Version 1.1.23)`.
But in this moment, i already have my username `giansalex.id.blockstack`.
![image](https://user-images.githubusercontent.com/14926587/71751554-f2401e00-2e49-11ea-8372-a2ebb75d550c.png)
Thanks!

**Comment by ryanarndtcm** [comment]
Thanks for the update! Sounds like it is resolved then? Sometimes using a browser in Incognito mode will cause an issue like that as well.

**Comment by giansalex** [comment]
Yes, solved.
