### ISSUE TITLE
Recovered account is not showing original ID

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#2013]
This is coming in from a user in support who has been sent a link to this issue to add to. I will add anything else in here that they send to support.

> I registered for an ID today and backed up my Secret Recovery Key. Then I reset my browser and restored with my Secret Recovery Key.

> It didn't show me my Blockstack ID, and instead it told me to create a password again. I did that and I found that while the Secret Recovery Key is the same, the Magic Recovery Code is different and no Blockstack ID exist on my recovered account.

> I reset my browser again and login with my old Magic Recovery Code with the correct password. I logged in successfully, and Secret Recovery Key is still the same. But the Magic Recovery Code I see in settings is different to the one I used to login.

> When I search for my Blockstack ID that is supposed to be linked with this Secret Recovery Key, it is obviously "taken". When I register with a new and available Blockstack ID, it shows error.

> How do I resolve this error, and is it possible to get my original Blockstack ID back?

**Comment by markmhx** [comment]
The description makes me think the user may have inadvertently registered twice with two different Secret Recovery Keys then got mixed up with which corresponded to which Magic Recovery Codes and which had their ID registered to it.

Can we confirm they didn't receive two registration emails with different Magic Recovery Codes, perhaps by asking them to search their inbox?

**Comment by ryanarndtcm** [comment]
I can ask them that yes. Will report back any reply.

**Comment by ryanarndtcm** [comment]
No update from the user whatsoever.

**Comment by hstove** [comment]
What might have happened is that they restored their account before the subdomain was registered on-chain. When you restore your account (with either secret or magic), the Browser makes a call to blockstack-core to say "any usernames registered at this address"? If the subdomain isn't registered yet (which may take hours), then the answer is "no", so we show no username.

Fortunately, we've built some new mechanisms in the new authenticator to actually support this scenario, so you'll see the username you registered, even if it's not on-chain yet. However, it's not feasible to port that functionality back to the Browser.
