### ISSUE TITLE
Identity is not showing

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#2015]
This is coming in from a user in support who has been sent a link to this issue to add to. I will add anything else in here that they send to support.

>I signed back into my blockstack ID calvintran.id and while the recovery phrase got me into the account, it seems the calvintran.id. identity is gone (all I have now is the ID: ID-15VzhsQV2CKKmsNjYBim1TrKDDYaVuEZX3 )  and because of that, none of my apps work for me. 

>I used to be able to access my Dmails and Arcane docs, but now their pages won't load. Any suggestions?

**Comment by ryanarndtcm** [comment]
The user confirms that they are using the Brave browser on Windows 10.

**Comment by ryanarndtcm** [comment]
User is not operating in incognito mode. He sends this "I signed out and in again, and this time, the calvintran.id connected, but the dapps still don't work. Signed out and in again and it still doesn't work."

**Comment by timstackblock** [comment]
Duplicate issue https://github.com/blockstack/blockstack-browser/issues/2017
