### ISSUE TITLE
user enters invalid password an is blocked from re-entering a valid password

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-browser#2016]
During ID renewal is a user enters invalid password an error message appears but once they try a second time to enter the correct password in the text box they are blocked from re-entering a valid password because the submit button are no longer clickable

<img width="939" alt="Screen Shot 2020-01-08 at 9 42 39 AM" src="https://user-images.githubusercontent.com/49165468/71986894-3bea8900-31fb-11ea-9ec0-347ae3fb52ca.png">

http://somup.com/cYVj2gfdl6

**Comment by hstove** [comment]
Fixed in ae913f32
