### ISSUE TITLE
Can not register a new username

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#2026]
This is coming in from a user in support who has been sent a link to this issue to add to. I will add anything else in here that they send to support.

>Hi! I'm trying to create a free username 'devexsoft.id.blockstack' and got an error:
>Something went wrong!
>Sorry, it looks like the blockchain failed to process your name registration. Please contact us at support@blockstack.org for help. Some apps may be unusable until you register an ID.

They also sent a video of the error which I am including as well. It is webm and it is inside .zip as the webm is not supported for upload.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2019.11.webm.zip](https://github.com/blockstack/blockstack-browser/files/4098144/screencast-bpconcjcammlapcogcnnelfmaeghhagj-2019.11.webm.zip)

**Comment by pyoner** [comment]
Hi @ryanarndtcm thank you for the support!
I'm using a Chrome browser (ver. 79.0.3945.130) and Ubuntu 18.04.3 LTS

**Comment by pyoner** [comment]
@ryanarndtcm I tried to register the username again and succeeded

**Comment by ryanarndtcm** [comment]
Ok great thanks! I am going to close this ticket.
