### ISSUE TITLE
Blockstack login is giving Error 520

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#2056]
This is coming in from a user in support who has been sent a link to this issue to add to. I will add anything else in here that they send to support.

>Hi ,

>I have a serious problem. Or app relies on Blockstack login and we get the following error :

![image](https://user-images.githubusercontent.com/52256509/78684370-c14b0b80-78c6-11ea-87b1-6d6a65e00808.png)

**Comment by markmhx** [comment]
@ryanarndtcm could we confirm this is still occurring for the user? It seems like it may have been a temporary outage problem from the looks of it.

**Comment by ryanarndtcm** [comment]
yes. closing.
