### ISSUE TITLE
User images not loading for profiles or apps

### ISSUE THREAD

**Issue by bissisoft** [blockstack/blockstack-browser#2061]
![2020-08-07-06:13:54](https://user-images.githubusercontent.com/68321606/89605407-164b5e00-d876-11ea-96b1-8fd72cf3a001.png)

**Comment by markmhx** [comment]
@hstove I have a faint recollection that we saw this months ago and either squashed it or at least discussed its possible cause. 

As @dantrevino points out with https://github.com/blockstack/blockstack-explorer/issues/225#issuecomment-666644577, this may be related to the double slashes in the asset URL. 

For example:

- [Works](https://gaia.blockstack.org/hub/19AAYhqyS33YH8zrdmyN1PmEez8ZEEPQdT/0/profile.json): https://gaia.blockstack.org/hub/19AAYhqyS33YH8zrdmyN1PmEez8ZEEPQdT/0/avatar-0
- [Doesn't work](https://gaia.blockstack.org/hub/1J6LqoWPHfBx9sNrSBwVfGWphitD8Krftm/profile.json): https://gaia.blockstack.org/hub/1J6LqoWPHfBx9sNrSBwVfGWphitD8Krftm//avatar-0

Does this ring a bell?

**Comment by markmhx** [comment]
Note that this is also affecting apps that use the profile pic, such as [Envelop](https://envelop.app):

<img width="291" alt="Screen Shot 2020-08-20 at 11 15 21" src="https://user-images.githubusercontent.com/28991/90751575-9b9f2b80-e2d6-11ea-94a2-cec62d22c025.png">

**Comment by markmhx** [comment]
@bissisoft mind trying to set your user image again with https://browser.blockstack.org/ and see if it loads properly subsequently? We have a fix in place now and would like to confirm if possible that it works for you.
