### ISSUE TITLE
Loading spinner on selecting profile never stops

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-browser#2062]
A user reported that auth process of pnotes.online never finishes.

The loading spinner when selecting a profile never stops.

**Comment by dantrevino** [comment]
This has been an issue since Saturday for more than just pnotes.  I've seen this behavior with other apps like NoteRiot, as well as just trying to set up my user account on a new browser.

**Comment by dermodmaster** [comment]
A look in the browser console provides a CORS error:
> Access to fetch at 'https://proofs.blockstack.org/validate/' from origin 'https://browser.blockstack.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

This issue should have a very high priority.

**Comment by whoabuddy** [comment]
Tagging @hstove considering this from the readme:

> ⚠️ IMPORTANT: This project has been deprecated in favor of the Blockstack App. It will receive only critical updates by Blockstack PBC going forward.

And

> This repository is maintained by hankstoever.id.

**Comment by whoabuddy** [comment]
## Screenshot of the issue

After trying to log in from https://note.riot.ai/

![2020-08-10 06 05 50 browser blockstack org 5ab6d34bdec2](https://user-images.githubusercontent.com/9038904/89785706-acc68c00-dacf-11ea-8c90-2c1a0b826763.png)

## Console error

I see the same error mentioned above:

`Access to fetch at 'https://proofs.blockstack.org/validate/' from origin 'https://browser.blockstack.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

## Error at subdomain

Accessing https://proofs.blockstack.org/validate/ or the root domain https://proofs.blockstack.org/ returns a `503 - service temporarily unavailable`.

![2020-08-10 06 10 10 proofs blockstack org 875a39b0e533](https://user-images.githubusercontent.com/9038904/89786059-32e2d280-dad0-11ea-9350-bdaca335ca96.png)

**Comment by markmhx** [comment]
PBC DevOps is working to resolve this actively re: https://github.com/blockstackpbc/devops/issues/381. Thanks everyone for the report and my apologies for this outage 🙏

**Comment by wileyj** [comment]
@friedger @dantrevino can you try it now please?

**Comment by whoabuddy** [comment]
@wileyj I can confirm that I am able to log into https://note.riot.ai/ and https://pnotes.online which were both stuck spinning before :+1:

**Comment by dantrevino** [comment]
yup confirmed

**Comment by hstove** [comment]
Thanks all for the reports, the fix, and the confirmations of the fix!
