### ISSUE TITLE
Contributing Docs - missing part of description for "chore" label

### ISSUE THREAD

**Issue by timstarkk** [blockstack/blockstack-browser#2065]
I was perusing the docs to learn how to contribute, and I noticed the following:

[in CONTRIBUTING.md](https://github.com/blockstack/blockstack-browser/blob/master/CONTRIBUTING.md#issues-and-labels)
Under the "**Issues and labels**" section:
One bullet point reads: "chore - Issues that are not"

I can only assume that the description is incomplete.
I would like to fix this myself, the only problem is.... I don't know what it's supposed to say!
Thanks.

**Comment by markmhx** [comment]
I'm not sure either 😆 

If you're looking to contribute, however, I might suggest heading over to https://github.com/blockstack/ux/tree/master/packages/app since the Blockstack Browser repo is now deprecated.

**Comment by timstarkk** [comment]
haha, oof...
I must have missed the ⚠️⚠️⚠️⚠️⚠️ at the top of the readme. 🤦‍♂️

Thanks for pointing me in the right direction.
