### ISSUE TITLE
Hitting browser quota for redux storage

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#208]
Long time use of the browser results in redux storage exceeding the browser local storage quota.

Both @guylepage3 and I have experienced this problem:

<img width="805" alt="screenshot 2017-02-11 17 24 07" src="https://cloud.githubusercontent.com/assets/597182/22858114/cb8ce4c8-f0bc-11e6-806b-e3efb8b5d4d9.png">

**Comment by shea256** [comment]
I applied the fix in this thread: https://github.com/gaearon/redux-devtools/issues/298

You can see my commit above.

@larrysalibra @guylepage3 can you let me know if this addresses the issue for you?

Thanks!

**Comment by larrysalibra** [comment]
We need to test to make sure this works. Easiest way is to re-enable the code that creates a new address on each refresh and then refresh many times.

**Comment by guylepage3** [comment]
@larrysalibra @shea256 should we create a corresponding issue for testing?

**Comment by larrysalibra** [comment]
No need. Looks fine here. We can re-open if this issue comes up for anyone else.

**Comment by larrysalibra** [comment]
I'm seeing this problem again - this time on Safari (Version 11.1 (13605.1.33.1.2))
<img width="1437" alt="screen shot 2018-04-08 at 4 50 06 pm" src="https://user-images.githubusercontent.com/597182/38465348-1ea5045c-3b4d-11e8-9dfd-e1740ee6c26c.png">

**Comment by larrysalibra** [comment]
@cwackerfuss can you take a look at this when you look into improving redux state management?

**Comment by markmhx** [comment]
@larrysalibra We're unsure how you could end up filling 5mb worth in local storage – lots of identities? Or something else?

**Comment by larrysalibra** [comment]
@markmhx Redux was storing multiple copies of state...basically one for each state change. Was probably misconfiguration.

**Comment by markmhx** [comment]
@larrysalibra Cool, we'll keep this closed unless you recreate and want to re-open.
