### ISSUE TITLE
remove #id selectors throughout portal & apps

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#212]
Go through the portal and apps replacing all `#ID`s with `.class` names as IDs are problematic for a few reasons;

1. IDs are completely unique and therefore cannot be reused
1. Classes do everything that ID's do and more
1. IDs have fundamental inheritance issues;
  1.  as they cannot be reused leading to a downward spiral into specificty.
  1. leaving the developer to use the last resort non-inheriting property hack `!important` throughout the styles.
1. Classes are the industry standard. Developers are no longer looking for them and we should adhere to the standard.

**References**
- http://oli.jp/2011/ids/
- http://screwlewse.com/2010/07/dont-use-id-selectors-in-css/

**Comment by jackzampolin** [comment]
Closing as this issue looks dead.
