### ISSUE TITLE
design launch modal

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#214]
Design a new launch screen

**Comment by guylepage3** [comment]
Current view...

<img width="994" alt="screenshot 2017-02-13 08 11 08" src="https://cloud.githubusercontent.com/assets/1711854/22884707/54f86d10-f1c4-11e6-97a1-97e8b20c70a2.png">

**Comment by larrysalibra** [comment]
current restore/create account view:

<img width="370" alt="screen shot 2017-02-17 at 8 07 31 pm" src="https://cloud.githubusercontent.com/assets/597182/23077393/0a948d4e-f54d-11e6-8aec-c2b3de24974c.png">
<img width="366" alt="screen shot 2017-02-17 at 8 07 38 pm" src="https://cloud.githubusercontent.com/assets/597182/23077397/0c83ccfa-f54d-11e6-9d08-d729c83ccf8a.png">
<img width="364" alt="screen shot 2017-02-17 at 8 07 53 pm" src="https://cloud.githubusercontent.com/assets/597182/23077399/0eaae608-f54d-11e6-98d2-377715f87f6e.png">

**Comment by guylepage3** [comment]
<img width="1250" alt="screenshot 2017-02-23 07 41 17" src="https://cloud.githubusercontent.com/assets/1711854/23265173/e7f5890a-f9b1-11e6-937b-c1a8a8c9f69d.png">
<img width="1249" alt="screenshot 2017-02-23 07 41 38" src="https://cloud.githubusercontent.com/assets/1711854/23265172/e7f38f42-f9b1-11e6-9af9-e87dd7541c34.png">

**Comment by guylepage3** [comment]
Complete.
