### ISSUE TITLE
work with Jude to iron out the data authorization requirements

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#219]

**Comment by muneeb-ali** [comment]
Tagging @jcnelson here. He created a task for this in Core. I'm removing that task and tracking it here instead.

**Comment by shea256** [comment]
Pushing this to v0.5 as there's still work to be done on this between @jcnelson and myself.

**Comment by shea256** [comment]
This is an ongoing task that can be closed once we confirm that the data authorization specs have been nailed down. @jcnelson and I will sync up on this upon syncing up on the "Hello Blockstack for the Nth Time" app.

**Comment by jackzampolin** [comment]
Closing as stale
