### ISSUE TITLE
dropbox integration redirects to localhost:3000 in the macOS app instead of localhost:8888

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#222]
Tagging @larrysalibra to take a look at this.

**Comment by shea256** [comment]
Maybe we can do the following:

1. Update the Dropbox app so it supports callbacks for both "localhost:3000" and "localhost:8888"
1. Have a variable that sets the current host at startup and pass that to the Dropbox callback

Also, with the callbacks, can we set them to "localhost:PORT" instead of "localhost:PORT/account/settings"?

There are other places in the app where we have "localhost:3000" hardcoded. We can address the rest of these later.

**Comment by shea256** [comment]
@larrysalibra what do you think of what I said above?

Remember, we have to pass localhost:8888 to the dropbox redirect call.

Here's where we're supplying it: https://github.com/blockstack/blockstack-browser/blob/web-0.3/app/js/pages/account/SettingsPage.js#L94

**Comment by larrysalibra** [comment]
@shea256 should be fixed now. i'm making a new mac build to test. stand by.

**Comment by shea256** [comment]
Sounds good @larrysalibra. Let us know if there's anything else you find or need.

**Comment by larrysalibra** [comment]
@shea256 This should be fixed in the latest build. Please re-open if you still have the problem.
