### ISSUE TITLE
create an issue template for browser issues

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#228]
Create an issue template for Portal issues to encourage easy and fast contributing from the community.

Example:
- [Bootstrap issue template](https://github.com/twbs/bootstrap/issues/new)

**Resources**
- [Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by jackzampolin** [comment]
Is this still something we want to do?

**Comment by larrysalibra** [comment]
I created one:
<img width="995" alt="screen shot 2017-12-30 at 12 48 34 am" src="https://user-images.githubusercontent.com/597182/34442156-394cd87a-ecfb-11e7-9637-3914b88c2b09.png">

Let me know what you think. If everyone thinks it's a good idea, we can make these in all of our repos!

Thanks @guylepage3 for the idea!

**Comment by guylepage3** [comment]
Nicely done @larrysalibra 👍
