### ISSUE TITLE
Improve name registration UI & flow

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#232]
* Name availability (is it available for registration?
* Name price 
* Does the user need to deposit additional bitcoin?
* Order confirmation
* Provide a bitcoin address/QR code for deposit if needed

We discussed a two step process where the user enters the name and then a confirmation modal appears displaying the name price and asking the user to deposit bitcoin or price and confirmation.

**Comment by larrysalibra** [comment]
I feel like completing this task properly is potentially a large project with respect to design. @guylepage3 @shea256 what do you think?

**Comment by shea256** [comment]
Yes this seems somewhat complex. There are many possible states, screens, and messages to display to the user.

**Comment by guylepage3** [comment]
yeah. should we push this to the next sprint?

**Comment by larrysalibra** [comment]
Let's push it.

**Comment by larrysalibra** [comment]
One thing we may need to do as part of this process is prompt users not to turn their computers off or go to sleep after they submit a registration.  Core needs to send 4 name operation transactions over a period of several hours or the name registration could fail. I say this because last night, even though I know this, let my macbook go to sleep twice during that period of time - the first because I needed to move venues and the second when the laptop went to sleep after the power cable got disconnected while I was sleeping.  

We'll also need to work with @jcnelson to come up with a better UX for registration - asking users to keep their devices awake and online for hours at a time is very challenging these days. (Perhaps we can create all the transactions at once and send them to a service that broadcasts them at the right time)

**Comment by guylepage3** [comment]
See https://github.com/blockstack/blockstack-browser/issues/669 & https://github.com/blockstack/blockstack-browser/issues/690
