### ISSUE TITLE
design css transition for opening apps

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#239]
Design a CSS transition animation for when a user opens apps. The goal should be to give the feeling that a user is opening a separate application inside of portal/their browser.

**Comment by larrysalibra** [comment]
Right now, technical constraints mean that apps run in separate tabs. We don't have the ability to control how web browsers display a new tab. Would be really cool if we can figure out how to do this in the future, but for now, I'll close this issue.
