### ISSUE TITLE
ui build support button

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#243]
UI build of the support button design on the Home Screen that links to forum support.

- https://github.com/blockstack/blockstack-browser/issues/710-

**Comment by guylepage3** [comment]
In reference to [this article discussed in slack this morning](https://codewithoutrules.com/2017/02/10/voice-exit-user-retention/), we should think about where this button will take the user. 

Here's a great example of a quick and dirty button:

<img width="430" alt="screenshot 2017-03-03 10 44 24" src="https://cloud.githubusercontent.com/assets/1711854/23561721/6f570f7a-000d-11e7-9c91-bd754721d2b2.png">

That takes the user to a Google Form that they fill out. This might be a good way to handle support initially.
https://docs.google.com/a/papriika.com/forms/d/e/1FAIpQLScCKYMF5m3jHbKBu6_EE7MFDy7rTD7RLPAEzsrF4g_f8iWcDg/viewform

**Comment by shea256** [comment]
We should set up a support system real soon and link to support from the home screen. Thinking we can set up a ZenDesk account and then link to the help desk.

**Comment by guylepage3** [comment]
@shea256 can I get a link to ZenDesk for this? I will be adding this to the Home Screen.

**Comment by guylepage3** [comment]
out of scope for this sprint.

**Comment by larrysalibra** [comment]
We currently have this support button:
<img width="174" alt="screen shot 2017-12-30 at 12 53 32 am" src="https://user-images.githubusercontent.com/597182/34442259-e15e4d96-ecfb-11e7-8ffe-1258d2a204fd.png">
