### ISSUE TITLE
registration confirmation to take user to profiles app list view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#256]
After the user registers a profile, the app shows a "Name preordered! Waiting for registration confirmation." alert view but does not take the user anywhere. After the "Name preordered! Waiting for registration confirmation." alert view appears for 2 seconds, the user should be taken back to the Profiles App List view where they can see their new profile.

<img width="1249" alt="screenshot 2017-02-23 08 45 27" src="https://cloud.githubusercontent.com/assets/1711854/23261788/eff207d4-f9a5-11e6-8cf6-23e28ebbfa9f.png">

**Comment by larrysalibra** [comment]
What about sending them to the edit profile page where they can add name, photo, etc?

**Comment by guylepage3** [comment]
@larrysalibra hm.. i feel like i would rather start using the app upon creation. then come back to editing my profile. @shea256. thoughts?

**Comment by larrysalibra** [comment]
Good point. @guylepage3 

I would think if i'm creating a profile by clicking the button in the profiles app, I'd probably want to fill out my profile.

If i'm sent to the register page as part of an auth flow or an on-boarding process of using another app (not the portal) I'd probably want to skip the profile editing and get straight back to the app.
