### ISSUE TITLE
live design new profiles app register pages

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#258]
Live design new profiles app registration pages. 

Reference: [#230: create a ProfilesApp object that wraps all pages](https://github.com/blockstack/blockstack-portal/issues/230).

<img width="1248" alt="screenshot 2017-02-23 08 44 55" src="https://cloud.githubusercontent.com/assets/1711854/23265864/0ae79816-f9b4-11e6-9653-9aa1fb55d28f.png">
<img width="1248" alt="screenshot 2017-02-23 08 45 13" src="https://cloud.githubusercontent.com/assets/1711854/23265863/0ae45638-f9b4-11e6-8cd1-29dc18c35267.png">

**Comment by jackzampolin** [comment]
Closing as stale
