### ISSUE TITLE
design live search query view inside profiles app

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#259]
Design live search query view inside profiles app

Reference: [#230: create a ProfilesApp object that wraps all pages](https://github.com/blockstack/blockstack-portal/issues/230).

<img width="1249" alt="screenshot 2017-02-23 10 38 07" src="https://cloud.githubusercontent.com/assets/1711854/23266091/ba768846-f9b4-11e6-8e97-eb5cddbf7640.png">

**Comment by jackzampolin** [comment]
This feature has been removed. Closing.
