### ISSUE TITLE
Integrate the export page w/ the Onename API so names can be transferred to other addresses

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#28]

**Comment by shea256** [comment]
@larrysalibra This issue is about the second: transferring names from the browser to other places.

And yes, this list looks good.

We should also talk to @jcnelson to see how best to handle this with the Blockstack Core/CLI localhost REST API. We're no longer relying on api.onename.com or api.blockstack.com.

**Comment by jackzampolin** [comment]
This is being handled in the current sprint. Closing
