### ISSUE TITLE
Upgrade Blockstack Auth to support the passing of the base URL for the user's Blockstack Core node

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#290]

**Comment by shea256** [comment]
This is dependent on how the integration turns out with "Hello, World for the Nth Time", which @jcnelson is working on.

Removing this from v0.5.

**Comment by guylepage3** [comment]
adding the `backlog` label to this issue

**Comment by larrysalibra** [comment]
This is something that will be handled in blockstack.js. See https://github.com/blockstack/blockstack.js/issues/224
