### ISSUE TITLE
Getting portal to work with existing Blockstack installations 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-browser#312]
Feedback from Skorpion7777 on the forum:

> People who are familiar with the Blockstack CLI and already own a wallet. I started my installation journey on a VM with Blockstack CLI and a wallet already installed. But the Browser couldn't deal with it and the instructions given by @larry in the slack haven't really worked for me which was super frustrating since you would think "yeah I already configuered blockstack and everything is fine, browser installation shouldnt take long" ...... Yeah..... Maybe a Docker Image would solve this, I'm not shure

We're focused on the macOS built right now but should start testing for this soon.

**Comment by guylepage3** [comment]
@muneeb-ali I'm labeling this issue `backlog`

**Comment by jackzampolin** [comment]
This is working.
