### ISSUE TITLE
resolve flexbox flow orientation on home screen

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#320]
There seems to be an issue with the flow of the flexbox orientation on the home screen when an even number of app icons appear.

**Comment by guylepage3** [comment]
<img width="838" alt="screenshot 2017-03-17 10 36 17" src="https://cloud.githubusercontent.com/assets/1711854/24047999/dbe5d874-0afd-11e7-9f11-a5c19dec4059.png">

**Comment by matheusml** [comment]
By replacing ```justify-content: space-between``` to ```justify-content: flex-start```, we get this result:

![](http://i.imgur.com/iNJgfUd.png)

Can I send the PR?

**Comment by guylepage3** [comment]
Awesome @matheusmi! Feel free to do a pull request.

**Comment by guylepage3** [comment]
resolved. closing issue.
