### ISSUE TITLE
How to get rid of `localhost:3000` in the address bar

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-browser#321]
There was a discussion about how to get rid of the `localhost:3000` in the browser address bar in Slack and what to do about the port number.

When mapping `blockstack-portal` to (for example) `127.1.2.3` you can let bind the portal to `127.1.2.3:<port>` and use any port you'd like to use (even port 80 which means no port in browsers). The only thing that could interrupt are programs which bind to a port on all network interfaces.

I hope I didn't miss anything there^^

**Comment by guylepage3** [comment]
Pinning this conversation to this issue.

https://blockstack.slack.com/archives/C074LC7RC/p1489605053065640

**Comment by guylepage3** [comment]
@jcnelson & @shea256 came up with a solution for this as well

**Comment by vsund** [comment]
I think this should solve https://github.com/blockstack/blockstack-portal/issues/316 too (when binding to an loopback address != `127.0.0.1`).

**Comment by larrysalibra** [comment]
Moving to native app #599 will solve this.

**Comment by wbobeirne** [comment]
Closing as stale. So long as this runs in a browser, it's going to be this way. If we move to another form factor, this will be addressed as a part of that effort.
