### ISSUE TITLE
Add blockstack: protocol handler to Linux

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#324]
For Ubuntu, to create a `blockstack:` handler, create the following file:

`/usr/share/applications/blockstack.desktop`

With the following contents:
```
[Desktop Entry]
Name=Blockstack
Exec=blockstack.sh %u
Type=Application
NoDisplay=true
Categories=System;
MimeType=x-scheme-handler/blockstack;
```

We'll need to point the `Exec=` to a script that opens the user's default browser with the Portal's authentication path.

**Comment by jcnelson** [comment]
You can find the default browser with `xdg-mime query default text/html`.  This can be fed into the `Exec=` string.  You can use a `.desktop` launcher like `gtk-launch`, or you can grab the command directly from the `.desktop` file with the following:

```
$ cat "/usr/share/applications/$(xdg-mime query default text/html)" | grep "Exec=" | sed -r 's/Exec=([^ ]+) .*/\1/g' | xargs sh -c -
```

**Comment by jcnelson** [comment]
I've gotten this to work on Linux.

My `blockstack.sh`:

```bash
#!/bin/sh

PORTAL_URL="http://localhost:3000"

# logging...
echo "request: $@" >> /tmp/blockstack.log

# expect blockstack:AUTHENTICATION_TOKEN
if [ -z "$1" ]; then 
   exit 1
fi

AUTH_TOKEN="$(echo "$1" | sed -r 's/blockstack://g')"
exec chromium-browser "$PORTAL_URL/auth?authRequest=$AUTH_TOKEN"
```

My .desktop file (in `~/.local/share/applications/blockstack.desktop`):

```
[Desktop Entry]
Name=Blockstack
Exec=blockstack.sh %u
Type=Application
NoDisplay=true
Categories=System;
MimeType=x-scheme-handler/blockstack;
```

**Comment by jackzampolin** [comment]
This is implemented in the `launcher` https://github.com/blockstack/packaging/blob/master/browser-core-docker/launcher#L201
