### ISSUE TITLE
Add a self-hosted alternative for storage providers

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-browser#327]
Would be cool to have a self-hosted alternative for adding storage for not being dependent on the few big cloud companies.

Rel: https://github.com/blockstack/storage-drivers/issues/68

**Comment by larrysalibra** [comment]
I agree this is very important and consistent with our vision/mission.

**Comment by jackzampolin** [comment]
Gaia Hubs are the way we will be implementing this. We would just need to add a `fileDriver` [here](https://github.com/blockstack/gaia/tree/master/hub/server/drivers) and instructions to enable. I'm going to close this as the issue is going to be best discussed over on the `gaia` repo.
