### ISSUE TITLE
Portal can't access Core node

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#353]
@pstan26 is having trouble submitting a name registration.

He's sent me his Blockstack mac app log which shows no problems starting the Core API.
He's also sent me his `api_endpoint.log` which shows a price lookup working fine, but then the log ends.

This is a screenshot he shared:

![screen shot 2017-03-24 at 2 19 55 pm](https://cloud.githubusercontent.com/assets/597182/24309821/4e93cfba-1108-11e7-9977-5866fe04d06a.png)

We've tried to: 1. exit the mac app and restart it. These restarts show up in the `api_endpoint.log`.

**Comment by larrysalibra** [comment]
@pstan26 can you try the following?

1. exit the mac app
2. in the terminal run `rm -Rf /tmp/blockstack-venv/` - this will delete your blockstack core node virtual environment
3. restart the mac app
4. after about ~15 seconds, try to visit `http://localhost:6270/v1/names/muneeb.id` - if your core node is running, you should see some JSON like this:

```JSON
{"status": "registered", "zonefile": "$ORIGIN muneeb.id\n$TTL 3600\n_http._tcp IN URI 10 1 \"https://blockstack.s3.amazonaws.com/muneeb.id\"\n", "expire_block": 489247, "blockchain": "bitcoin", "last_txid": "1edfa419f7b83f33e00830bc9409210da6c6d1db60f99eda10c835aa339cad6b", "address": "1QJQxDas5JhdiXhEbNS14iNjr8auFT96GP", "zonefile_hash": "b100a68235244b012854a95f9114695679002af9"}
```

If that works, try the registration again and let me know what happens.

**Comment by pstan26** [comment]
I tried that and seem to have lost all my bitcoin (at least from the wallet display), but also I can't check price and availability of the name and then there is problem submitting the registration.
![screen shot 2017-03-24 at 3 58 00 pm](https://cloud.githubusercontent.com/assets/5605552/24311490/c9a264ea-10aa-11e7-9b09-b3493b1be795.png)

**Comment by pstan26** [comment]
@larry tried again today, seems like there are less errors?
![screen shot 2017-03-30 at 2 10 32 pm](https://cloud.githubusercontent.com/assets/5605552/24519315/b6e22a46-1552-11e7-8c04-76644fcd50d7.png)

**Comment by oso4** [comment]
I'm having the same persistent issue. Any progress?

**Comment by guylepage3** [comment]
sounds good @oso4. let us know how that works out for you either way. thanks. 😄

**Comment by jackzampolin** [comment]
This is likely fixed by a new release, closing.
