### ISSUE TITLE
macOS: DMG Branding

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#357]
Create background & design layout for our macOS DMG.

<img width="484" alt="screen shot 2017-03-26 at 10 09 56 pm" src="https://cloud.githubusercontent.com/assets/597182/24331981/0b355918-1271-11e7-9afb-c5ac160bc9fc.png">

We can customize the background, icons, and layout. 

See https://github.com/LinusU/node-appdmg#json-input for exactly what is customizable.

**Comment by larrysalibra** [comment]
We can also change this icon:

<img width="100" alt="screen shot 2017-03-26 at 11 03 37 pm" src="https://cloud.githubusercontent.com/assets/597182/24332398/808a9cee-1278-11e7-8740-78492dcda6a5.png">

**Comment by guylepage3** [comment]
This may be a nice little one for @field2 to tackle. @field2 what do you think?

**Comment by field2** [comment]
On it! :)

**Comment by larrysalibra** [comment]
Awesome @field2 ! Any progress on this?

**Comment by field2** [comment]
Sorry, been a bit crazy but should have something by early this week.

**Comment by guylepage3** [comment]
@larrysalibra @field2 I did not see this issue and started a new one here.. https://github.com/blockstack/blockstack-browser/issues/488

@field2 we could go this fancy route as seen by what the folks at InVision did but I am now starting to think we could just do something very simple like what the folks at Slack have done..

**Comment by guylepage3** [comment]
@field2 I'm adding a few more designs as well. As for the Install icon however.. I feel that should be something nice and simple and utilize the Blockstack Icon. Which I am starting to think should become a simple "gray" color instead of purple. Thoughts?

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/34489430-4f6a8be6-efaa-11e7-8d1f-ba3d1340894e.png)

**Comment by guylepage3** [comment]
<img width="1920" alt="screen shot 2018-01-02 at 10 48 53 am" src="https://user-images.githubusercontent.com/1711854/34489502-946c506c-efaa-11e7-89a5-5e8fde78f7f8.png">

**Comment by guylepage3** [comment]
It's interesting to see that a super huge project like Slack doesn't even use an install icon. I am thinking the reason is that it could cause confusion for users to see the browser app icon along side a custom installation icon. I feel we should actually stick with the macOS DMG installation icon.

**Comment by guylepage3** [comment]
Also, here's how Dropbox handles the install icon as well. Same as Slack.

![screen shot 2018-01-02 at 11 18 16 am](https://user-images.githubusercontent.com/1711854/34490922-750e9220-efaf-11e7-9aec-8981dcec951d.png)

**Comment by shea256** [comment]
Further highlighting the importance of this as the other day I watched someone install Blockstack and they didn't know what to do. They've never installed an app by dragging into the Applications folder. We sometimes take this for granted and think it's obvious but it really isn't.

Here's how Exodus does it:

<img width="653" alt="screen shot 2018-01-03 at 4 45 15 pm" src="https://user-images.githubusercontent.com/994646/34541323-bedd4da0-f0a5-11e7-8f4c-e271605f3dec.png">

Good model to follow IMO.

Also good to keep in mind that double-click works for a `.dmg` but dragging is apparently required for a `.app`.

**Comment by shea256** [comment]
I also want to highlight the fact that I watched someone install Google Chrome and they didn't know what to do!

![chrome-dmg-start](https://user-images.githubusercontent.com/994646/34541825-c5370d56-f0a7-11e7-95e6-b2f3851356f9.png)

If you'll notice, there's a visual to indicate dragging but there aren't explicit instructions.

We'll need instructions very similar to what Exodus has.

**Comment by guylepage3** [comment]
>If you'll notice, there's a visual to indicate dragging but there aren't explicit instructions.
>We'll need instructions very similar to what Exodus has.

+1 👍

**Comment by guylepage3** [comment]
This issue is two issues in one. The majority of the comments here are in regards to the "icon design" and not the window design. 

I am reopening #488 and closing this one as we will keep the icon the same so users are not confused as stated in this comment. https://github.com/blockstack/blockstack-browser/issues/357#issuecomment-354797222

Moving the related comments over to #488 as well.
