### ISSUE TITLE
Backup file design

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#371]
This issue is related to creating backup files that can be safely stored in an untrusted location (such as dropbox. The file should be able to be used to restore a user's wallet or move it to a different browser.

It contains an the user's encrypted backup phrase.

Possible format:
```JSON
{
  "comments": "This is your Blockstack wallet backup. It is encrypted with your password. You can import it into Blockstack to restore your wallet.",
  "encrypted-backup-phrase": "encryptedbackupphrasehere",
  "date": "2017-04-23T18:25:43.511Z",
  "version": 1
}
```

**Comment by jackzampolin** [comment]
This has changed since this isuee was opened. Closing.
