### ISSUE TITLE
integrate blockstack.js with blockstack-storage

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#373]

**Comment by shea256** [comment]
We took a detour this sprint to focus on the website (blockstack.org). As a result, I didn't focus on the browser portal as much. I'm now pushing this task to the next sprint: v0.8. I'll be coordinating with @jcnelson on this one for next sprint.

**Comment by jackzampolin** [comment]
This work is ongoing. Closing this as the appropriate repo for this is `blockstack.js` or `blockstack-storage-js`
