### ISSUE TITLE
clean up redux stores

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#377]

**Comment by larrysalibra** [comment]
@shea256 I'll work on this unless you object.

**Comment by larrysalibra** [comment]
Our `account.js` and `identities.js` stores are by far the largest. Let's split these up

**Comment by larrysalibra** [comment]
Taking longer than expected so splitting it into multiple issues:
#434 #435 #436 #437 #438 #439

**Comment by larrysalibra** [comment]
#435 is the remaining task in this containing task. i'm going push this off towards the end of the sprint time remaining and work on other more pressing issues.
