### ISSUE TITLE
figure out the quick, gradual on-boarding process

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#379]

**Comment by shea256** [comment]
For this I'm thinking the following there can be two ways to get started with the Blockstack app:

1. Download the app from the website, then follow the on-boarding process in the app.
2. Sign up at join.blockstack.org and follow the on-boarding process, receive an email, download the app, and paste your backup code from the email.

**Comment by shea256** [comment]
We took a detour this sprint to focus on the website (blockstack.org). As a result, I didn't focus on the browser portal as much. I'm now pushing this task to the next sprint: v0.8.

**Comment by guylepage3** [comment]
duplicate.. https://github.com/blockstack/blockstack-browser/issues/534
