### ISSUE TITLE
Process of transferring names from the Onename app

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-browser#383]
If a user has access to their Onename app account then they can use the transfer feature to send their names to Portal. They'd just need to know the address to which they want to transfer the name. 

There is a subset of users that don't remember their passwords but do have the backup file. It might make sense to enable them to upload that file in Portal vs. implementing that functionality with the Onename app (older code base and might be harder to update).

This is just a discussion issue. Might make sense to mark it with a label "discussion".

**Comment by vmatekole** [comment]
Can you please take a look at #536 ?

**Comment by vmatekole** [comment]
Any update on this?

**Comment by jackzampolin** [comment]
This is being completed in the current sprint. @vmatekole you will be sent an email with some instructions on how to complete the transfer this week.
