### ISSUE TITLE
Host updates on a CDN

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#387]
Updates are currently hosted on github which serves them via a redirect to `https://github-cloud.s3.amazonaws.com/`. US-based `S3` is reallllllllllly slow outside of the USA. (S3 is best used as cheap storage with a CDN product like cloudfront, cloudflare, etc in front it)

When updating through the auto-update mechanism, I'm only getting ~300-400 kb/s on a 1000/1000 mbit line. Typically when updating from Apple, Google, etc it is 10-15 times faster.

**Comment by jackzampolin** [comment]
This is done with the transition to `gaia.blockstack.org`

**Comment by larrysalibra** [comment]
@jackzampolin no it hasn't. we still host updates on github which hosts on standard zone s3.

**Comment by jackzampolin** [comment]
I thought this was for gaia hub! I'll reopen.
