### ISSUE TITLE
Cannot read balance preventing access to create profile

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack-browser#388]
<img width="393" alt="screen shot 2017-04-04 at 3 01 39 pm" src="https://cloud.githubusercontent.com/assets/17515551/24673914/cf03c5aa-1947-11e7-86eb-203dc9c9aa9a.png">

I got this error in the console. 

I just downloaded v0.6 and went to the profiles and clicked on the +Create button and nothing happened.

**Comment by shea256** [comment]
Thanks for reporting @estermer! I'm assigning this to @larrysalibra. I had the same problem and reported it here: https://github.com/blockstack/blockstack-portal/issues/389.

**Comment by larrysalibra** [comment]
This should be fixed in 0.9.0. Please re-open if it isn't!
Thank you again for reporting!
