### ISSUE TITLE
Testing gmp and libffi installation via script 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-browser#416]
I noticed that gmp is installed by the macOS installer script. Noticed that the [library was not loaded](https://github.com/blockstack/blockstack-portal/issues/415#issuecomment-294392702) for Albert:

```
Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
Referenced from: /private/tmp/blockstack-venv/lib/python2.7/site-packages/fastecdsa/curvemath.so
Reason: image not found
```

He is on macOS 10.12. Let's see if we can reproduce this error locally.

**Comment by jackzampolin** [comment]
This has been fixed in recent versions.
