### ISSUE TITLE
Centralize hash reading logic

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#424]
The portal reads the core api password & log server port from the hash portion of the URL. Dropbox SDK does the same. 

We should centralize this logic in one place so that we can remove these parameters from the address bar after they are read.

Previously, we had a problem where clearing the hash portion after reading the core api password & log server ports broke dropbox linking. (https://github.com/blockstack/blockstack-portal/commit/04859ce7a9da07d1778569ed33244cf51c2d1ed3)

**Comment by jackzampolin** [comment]
Is this issue still active?

**Comment by larrysalibra** [comment]
It's something we should work on given time. Putting in backlog

**Comment by larrysalibra** [comment]
Closing this issue since we know handle storage drivers at the gaia hub level.
