### ISSUE TITLE
Explicitly use proxy-fetch and remove from global

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#432]

**Comment by jackzampolin** [comment]
Code for this is in the [`app/js/utils/proxy-fetch.js`](https://github.com/blockstack/blockstack-browser/blob/master/app/js/utils/proxy-fetch.js).  This code could be packaged as a module and called explicity. Called here:

- [`app/js/profiles/store/pgp/actions.js`](https://github.com/blockstack/blockstack-browser/blob/master/app/js/profiles/store/pgp/actions.js#L33)
- [`app/js/utils/zone-utils.js`](https://github.com/blockstack/blockstack-browser/blob/master/app/js/utils/zone-utils.js#L64)

**Comment by jackzampolin** [comment]
Related: https://github.com/blockstack/blockstack-browser/issues/448

**Comment by larrysalibra** [comment]
This used to cause problem but hasn't caused problems for a while.
