### ISSUE TITLE
Design: Display of sanity check results

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#445]
In #417, we added sanity checks to the portal. These check if:
1. the core API endpoint is running
2. the core API password is valid

Currently, the results are recorded in the log.

I also added an `alert` when the core API endpoint isn't running: https://github.com/blockstack/blockstack-portal/commit/9d0b1668ba27ef01c304e686c5ee8727d51d0e30

I did **not** add an alert for incorrect password since there is a chance this could happen on 1st run.

I think we should display these in the portal UI.

One option would be to have a modal similar to the welcome modal that forces users to enter the correct api password. 

Another option is to add a non-invasive message with a link to information of how to resolve the problem in the status bar or another place that is visible from all views in the app.

Since 
1. neither of these options are expected errors and both are errors that the average non-dev user isn't going to be able to fix beyond restarting or reinstalling our app
2. these errors will commonly happen during development

I'm leaning toward the second option.

Thoughts @guylepage3 ? What's better from a design perspective in your view?

**Comment by wbobeirne** [comment]
Closing as stale.
