### ISSUE TITLE
Social network proofs: Failed context type error

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#446]
Encountered this error while fixing #397:

It complains the context props are `undefined`, but they are clearly defined both in the parent and inside the react component. 

<img width="994" alt="screen shot 2017-05-01 at 12 44 44 pm" src="https://cloud.githubusercontent.com/assets/597182/25573085/23322b56-2e6c-11e7-894e-8b47f2e8e90a.png">
<img width="990" alt="screen shot 2017-05-01 at 12 44 51 pm" src="https://cloud.githubusercontent.com/assets/597182/25573089/26414d40-2e6c-11e7-8930-05edb057755f.png">

**Comment by jackzampolin** [comment]
This issue is fixed in later releases.
