### ISSUE TITLE
Upgrade Blockstack S3 file uploader

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#455]
The Blockstack S3 file uploader only supports profile token files. Upgrade it to support photos and possibly arbitrary files. 

Background: We're going to provide every user with an amount of storage space so that users don't have to immediately connect their cloud storage provider. We'll nudge users to connect their own storage, at which point we'll move their assets to their chosen storage and update the zone file to point to the new location. We won't provide a mechanism for users to move back to the Blockstack Inc-provided storage.

The plan is to take the existing http://api.onename.com/v1/upload and expand it to support additional file types.

Who is the best person to coordinate with on this @muneeb-ali or @jcnelson ?

**Comment by jcnelson** [comment]
> We're going to provide every user with an amount of storage space so that users don't have to immediately connect their cloud storage provider. 

I think this is a bad idea.  What I suspect will happen is that 90% of users will simply use our storage provider, and then we're stuck maintaining it indefinitely since they won't want to move.  That puts us into the uncomfortable position of having to build a non-trivial storage gateway that enforces quotas, does authentication, etc., and then has to keep data available and secure.  It also costs us money.

**Comment by larrysalibra** [comment]
>  90% of users will simply use our storage provider, and then we're stuck maintaining it indefinitely since they won't want to move

My guess would be closer to 98% of users.

I think you're right. Even if it was free, vast majority of users will be lazy and not switch providers. When you add the cost of the `NAME_UPDATE` transactions, all but the most motivated will stay.

@shea256 Thoughts?

**Comment by shea256** [comment]
What if we cut them off after a week? The goal of this is to make on-boarding smoother and delay their need to hook up a provider immediately. It's not to make them dependent on our data store.

We can say "sorry your free data store has expired, please connect a storage provider to continue".

**Comment by larrysalibra** [comment]
@shea256 @jcnelson we can also make sure they deposit enough bitcoin for name registration so that there is adequate leftover for the `NAME_UPDATE` transaction.

Re API keys & authentication, I was thinking we could have them sign a message (or jwt) with their identity private key for access control instead of figuring out a method to hand out api keys and manage them.
---
Another thought, what if we stick with the current blockstack s3 upload API and *only* allow storage of profile token files? If they want to write additional data (like an avatar) then we prompt them to connect their own storage.

**Comment by shea256** [comment]
> @shea256 @jcnelson we can also make sure they deposit enough bitcoin for name registration so that there is adequate leftover for the NAME_UPDATE transaction.

Great idea.

> Re API keys & authentication, I was thinking we could have them sign a message (or jwt) with their identity private key for access control instead of figuring out a method to hand out api keys and manage them.

Yes I like this.

> Another thought, what if we stick with the current blockstack s3 upload API and only allow storage of profile token files? If they want to write additional data (like an avatar) then we prompt them to connect their own storage.

This is a good idea but they'll still need to make a NAME_UPDATE transaction.

**Comment by larrysalibra** [comment]
> This is a good idea but they'll still need to make a NAME_UPDATE transaction.

My thinking is that would simplify our work on the upload endpoint since it already allows for a single JSON file upload. We wouldn't need to turn it into a full-fledged storage provider. We could also easily limit file size (if the upload endpoint doesn't do this already) to a few kilobytes reducing the potential for abuse. You're right, it doesn't get rid of the `NAME_UPDATE` transaction - if the user isn't willing to pay for this either from change left over from buying a name or a separate deposit, her identity will be lost we when expire her storage.

**Comment by jcnelson** [comment]
> Another thought, what if we stick with the current blockstack s3 upload API and only allow storage of profile token files? If they want to write additional data (like an avatar) then we prompt them to connect their own storage.

This already exists.  Our servers at `node.blockstack.org` will store a signed profile JWT to S3 from anyone, as long as it's signed by the name who claims to have signed it, the signature matches the key in the zone file (or owner address), and the timestamp is within 30 seconds of the server's clock.  Users get an entry for `node.blockstack.org` in their zone files by default.

I'm much more worried about the `NAME_UPDATE` that will be required to subsequently add their preferred storage providers.

**Comment by larrysalibra** [comment]
We decided not to implement this.

**Comment by meteorplus** [comment]
Here are the link to the [forum post](https://forum.blockstack.org/t/2018-02-01-engineering-meeting/4112/2 ) about file uploads: 
- https://ethereum.stackexchange.com/questions/7842/storing-document-file-in-blockchain and this 
- https://medium.com/blockchain-musings/storing-documents-in-blockchain-1d4d361ca962
