### ISSUE TITLE
Address pull request into blockstack app generator

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#458]
Tracking for: 
https://github.com/blockstack/blockstack-app-generator/pull/6
https://github.com/blockstack/blockstack-app-generator/pull/7

**Comment by larrysalibra** [comment]
Merged https://github.com/blockstack/blockstack-app-generator/pull/7 waiting for a CORS bug fix on blockstack/blockstack-app-generator#6

**Comment by jackzampolin** [comment]
These have been reviewed and merged.
