### ISSUE TITLE
Integrate storage functions in portal

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#459]
This is waiting on:  #457

**Comment by larrysalibra** [comment]
@jcnelson You can add implementation for updating core storage config here -> https://github.com/blockstack/blockstack-browser/commit/2707e6e7e0b3c29eae20baeca604c776b1d9c41e

**Comment by jcnelson** [comment]
Thanks!  Will do

**Comment by larrysalibra** [comment]
Initialization of Gaia works!
