### ISSUE TITLE
empty search results looks like still searching

### ISSUE THREAD

**Issue by dominictarr** [blockstack/blockstack-browser#467]
you can't immediately tell the difference between a slow search and no results, unless you look in the dev tools. If you have slow internet you may expect to be looking at the search for a few seconds so it's not obvious if it's working right.

**Comment by larrysalibra** [comment]
Thanks @dominictarr !

@guylepage3 this great feedback to consider as part of your design of the search view: https://github.com/blockstack/blockstack-portal/issues/259

**Comment by larrysalibra** [comment]
@guylepage3 @shea256 we need some sort of loading indicator to show to users. it would be great to have something like this available to use portal wide whenever a potentially slow request is made.

**Comment by matheusml** [comment]
Can we use a YouTube like loading bar on the top of the page, @guylepage3 ?

**Comment by guylepage3** [comment]
@matheusml can you show me what you mean?

**Comment by matheusml** [comment]
@guylepage3 something like this:

https://milworm.github.io/react-progress-2/example.html

**Comment by guylepage3** [comment]
>it would be great to have something like this available to use portal wide whenever a potentially slow request is made.

This should probably be left up to an app per app basis. Something that we do not control. Also, we should work hard to prevent a slow request from happening in the first place.

>Can we use a YouTube like loading bar on the top of the page, @guylepage3 ?

Ahh.. I see how YouTube does it. Hm.. I feel like we should avoid having a progress bar that stretches the full width of the DOM as it may evoke a feeling of centralization. Like there's something going on behind "the Blockstack Browser." This is something @shea256 and I have discussed in the past that we want to avoid having any "Blockstack" code affecting the DOM as much as possible.

**Comment by jackzampolin** [comment]
Feature removed. Closing.
