### ISSUE TITLE
Integrated App for Linux

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#468]
Per discussion on Monday on getting Portal+Core up and running on Linux, I have some instructions, which are basically just the combination of the install instructions for core and the instructions for portal on Linux.

That's currently in hiding here: https://github.com/kantai/blockstack-core/blob/rc-0.14.2-aaron/docs/setup_core_portal.md

The question is whether or not we want a more integrated setup for Linux (or at the least Ubuntu), where a user can install everything with one command?

Also #428 is related.

**Comment by jackzampolin** [comment]
This is implemented with the launcher for linux. Closing.
