### ISSUE TITLE
Releases only compatible with macOS 10.12+

### ISSUE THREAD

**Issue by addobandre** [blockstack/blockstack-browser#470]
It seems to me that this is a too strict requirement (very annoying to me since I'm one version behind). Maybe go down on the SDK version? This should help adoption in the future (a few days ago, I saw a friend that was still running 10.6.8).

**Comment by larrysalibra** [comment]
Thanks for your feedback!

We're still trying to decide a version support policy so your input is very valuable.

Our current thinking given our timeframe and resources is to support the current version of macOS along with the developer beta of 10.13 that presumably will be announced at WWDC in a couple weeks. 

Once 10.13 is officially released, we'd continue to support 10.12 along with 10.13 (*n* & *n-1*). Next year when 10.14 developer beta is released, we'd support that along with 10.13 and 10.12. 

When 10.14 is released, we'd make a decision based on project resources whether we want to support *n*, *n-1* & *n-2* or just *n* and *n-1*.

@addobandre If you don't mind me asking, why are you one version behind? Is there something that breaks on the current version or you haven't got around to updating or something else? (Not trying to be snarky - just trying to understand what drives user decisions). Thanks!

**Comment by addobandre** [comment]
Nothing will break as far as I know, but I'm in the process of switching to Linux on another computer and automating my OS install setup (auto-install packages, configure zsh...).
I think supporting one or two older versions would be the best option: it gives a nice 2-year update window. Other software projects (I looked specifically at web browsers Chrome and Firefox) support 10.9+.

**Comment by coolynx** [comment]
@larrysalibra macOS 10.12 was the first version where all new features was just an integration in iOS because it was build using iOS team, since OS X team was dismissed.

http://www.macworld.co.uk/review/mac-software/macos-sierra-vs-mac-osx-el-capitan-comparison-review-3642607/

And it is more demanding on resources. If you have an older mac and do not need iOS integration then you actually do not need the latest macOS.

https://www.theverge.com/2016/12/21/14037686/apple-macbook-macos-focus-mobile-features-ios

**Comment by jackzampolin** [comment]
We have decided to go with the MacOS version support scheme described by @larrysalibra above for the next few releases. Closing.

**Comment by travisdetert** [comment]
I'm also running El Capitan on my macbook pro from 2009 (I know), but it is locked to El Capitan and no further.  I am actively working on a Blockstack application on other machines, but I would prefer to continue to be able to run this on El Capitan as well.
