### ISSUE TITLE
create a step-by-step on-boarding flow

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#476]
![1 1 onbording](https://cloud.githubusercontent.com/assets/994646/26084341/59860c66-39a9-11e7-8dd1-efb2f4a290c2.jpg)
![1 2 onbording](https://cloud.githubusercontent.com/assets/994646/26084340/5984894a-39a9-11e7-90e7-e592f97145c1.jpg)
![1 3 onbording](https://cloud.githubusercontent.com/assets/994646/26084337/54953ccc-39a9-11e7-923e-8871d6c7c42e.jpg)
![1 4 onbording](https://cloud.githubusercontent.com/assets/994646/26084339/59840862-39a9-11e7-9fb1-75a5a4c8230b.jpg)
![1 5 onbording](https://cloud.githubusercontent.com/assets/994646/26084342/5988c9d8-39a9-11e7-8ca0-b25f3f9244b8.jpg)

**Comment by shea256** [comment]
@guylepage3 I just used a template and built out 5 screens for the on-boarding flow.

I'll let you take it from here and put real design work into it ;)

@larrysalibra Tagging you on this as well for it to be built out.

Please comment.

**Comment by guylepage3** [comment]
Ok. cool.. Looks good! 👍

**Comment by MitchTalmadge** [comment]
This looks really well done! I love it

**Comment by guylepage3** [comment]
@shea256 can you post your final screens here with text in plain format when you're done? please and thank you. 😄

**Comment by shea256** [comment]
Yes will do.

**Comment by larrysalibra** [comment]
@shea256 can I go ahead and do a rough implementation of these?

**Comment by shea256** [comment]
Sure thing. Uploading now.

**Comment by shea256** [comment]
## 1.
![1 1 onbording](https://cloud.githubusercontent.com/assets/994646/26161844/13d82a50-3af3-11e7-82f3-976ab969c976.jpg)
## 2.
![1 2 onbording](https://cloud.githubusercontent.com/assets/994646/26161846/13e18550-3af3-11e7-8cf7-d2153f631ace.jpg)
## 3.
![1 3 onbording](https://cloud.githubusercontent.com/assets/994646/26161849/14962df2-3af3-11e7-9837-91ffef80bbb2.jpg)
## 4.
![1 4 onbording](https://cloud.githubusercontent.com/assets/994646/26161845/13dfd2d2-3af3-11e7-9bae-ccb2a882888b.jpg)
## 5.
![1 5 onbording](https://cloud.githubusercontent.com/assets/994646/26161847/13e91536-3af3-11e7-8eee-2aa2bce65c3d.jpg)

**Comment by shea256** [comment]
@larrysalibra Here are the 4 screens.

**Comment by larrysalibra** [comment]
@shea256 @guylepage3 these are implemented in https://github.com/blockstack/blockstack-portal/tree/v0.9 

email backup doesn't do anything yet.

**Comment by larrysalibra** [comment]
Done & ship. Nice job on the quick turn around on this @shea256 & @guylepage3
