### ISSUE TITLE
Backup core wallet

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#477]
@jcnelson  GET`http://localhost:6270/v1/wallet/keys` returns a JSON object with private keys among other things.  Is this object all we need to back up to allow a user to restore their core wallet?

**Comment by jcnelson** [comment]
No, this only returns the private keys and addresses.  Do you need to get the full wallet?  I can add `GET /v1/wallet/backup` as an endpoint.

**Comment by larrysalibra** [comment]
@jcnelson sorry for the late reply. are the private keys enough to restore the wallet? if our time frame to moving towards wallet only in the portal (no core wallet) is pretty short, maybe we could skip this?

**Comment by jcnelson** [comment]
yes, they are sufficient, but you'll need to remember the right order of private keys in order to reconstruct the multisig scriptSig.

**Comment by jackzampolin** [comment]
I'm closing this as it seems to be from a prior design iteration.
