### ISSUE TITLE
create post-on-boarding tooltips

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#485]
## 1.
![2 1 tooltip](https://cloud.githubusercontent.com/assets/994646/26162100/cb1709de-3af3-11e7-8894-da8f90ae2e3b.jpg)
## 2.
![2 2 tooltip](https://cloud.githubusercontent.com/assets/994646/26162101/cb169c38-3af3-11e7-8e7d-448110892c4b.jpg)
## 3.
![2 3 tooltip](https://cloud.githubusercontent.com/assets/994646/26162104/cb1b7d48-3af3-11e7-8923-bfc150f6d208.jpg)
## 4.
![2 4 tooltip](https://cloud.githubusercontent.com/assets/994646/26162105/cb1c310c-3af3-11e7-807c-f246cde70b4a.jpg)
## 5.
![2 5 tooltip](https://cloud.githubusercontent.com/assets/994646/26162103/cb1b00a2-3af3-11e7-8851-a3ed33807d9a.jpg)
## 6.
![2 6 tooltip](https://cloud.githubusercontent.com/assets/994646/26162102/cb198984-3af3-11e7-8cf3-19638da0f145.jpg)

**Comment by shea256** [comment]
@guylepage3 @larrysalibra Take a look at these tooltips. The first 5 correspond to each of the 5 apps. The sixth is the profiles app again.

@larrysalibra Also had the idea of putting a (1) icon next to each app to indicate to the user that they need to enter the app to complete a task.

**Comment by larrysalibra** [comment]
> @larrysalibra Also had the idea of putting a (1) icon next to each app to indicate to the user that they need to enter the app to complete a task.

like this -->

<img width="160" alt="screen shot 2017-05-17 at 11 30 19 am" src="https://cloud.githubusercontent.com/assets/597182/26162276/4c6f8c2c-3af4-11e7-8102-244ecfe71e75.png">

<img width="177" alt="screen shot 2017-05-17 at 11 30 25 am" src="https://cloud.githubusercontent.com/assets/597182/26162280/4fbb2dd2-3af4-11e7-88de-fc56ac978546.png">

**Comment by guylepage3** [comment]
I feel just a simple notification icon will do just fine. Better than a numerical notification icon. Also, we should consider doing something what GitHub does in their header when notifying users. We could place ours in the status bar.
<img width="192" alt="screenshot 2017-05-17 11 48 13" src="https://cloud.githubusercontent.com/assets/1711854/26163143/b9d449f4-3af6-11e7-85a8-dfde6cf045de.png">

**Comment by guylepage3** [comment]
But obviously use a red dot instead of blue.

**Comment by jackzampolin** [comment]
Closing as this looks to have been merged in.
