### ISSUE TITLE
Implement new status bar, tool tips, etc

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#489]

**Comment by guylepage3** [comment]
broke this up into multiple issues

- [#484: redesign status bar (based on new home screen status bar](https://github.com/blockstack/blockstack-portal/issues/484)
- [#491: ui build of redesigned v3 status bar](https://github.com/blockstack/blockstack-portal/issues/491)
- [#490: Status Bar Documentation v3(https://github.com/blockstack/blockstack-portal/issues/490)

**Comment by larrysalibra** [comment]
@guylepage3 this is an issue for me to remember to make the status bar work :-) Is there a better name I should use?

**Comment by larrysalibra** [comment]
I've written the logic to generate the values for the progress bar. Once @guylepage3 's design is done, I will come back around and hook up the status bar.
