### ISSUE TITLE
Profile image won't update when uploaded

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#494]
After uploading my profile image and clicking "Save and view profile", it didn't update or save.

![screen shot 2017-05-21 at 9 02 21 pm](https://cloud.githubusercontent.com/assets/5605552/26288963/fc21b7a4-3e68-11e7-972c-ee7b20d200d7.png)
![screen shot 2017-05-21 at 9 02 26 pm](https://cloud.githubusercontent.com/assets/5605552/26288964/fc23d8e0-3e68-11e7-898d-8533823994ff.png)

**Comment by larrysalibra** [comment]
Thanks for reporting this @pstan26

**Comment by jackzampolin** [comment]
This has been fixed in recent versions. Closing as stale
