### ISSUE TITLE
Make tool to transfer pre-release wallet names to new wallet format

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#498]

**Comment by larrysalibra** [comment]
idea: in the future we add an word (or something) to the 12 word phrase that’s a version value
and based on that we can calculate keys accordingly

**Comment by larrysalibra** [comment]
@kantai is working on this here: https://github.com/kantai/blockstack-transfer-service

adding this to 0.10.0 project to track progress.

**Comment by larrysalibra** [comment]
@kantai finished the core pieces of this: implementing the blockstack wire protocol in javascript. We'll need to put some engineering effort into integrating this into the browser and creating the subsidy api endpoint.

**Comment by wbobeirne** [comment]
Closing as stale.
