### ISSUE TITLE
onclick and hover ability for notification indicator / tooltip in status bar

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#499]
There should be the ability for users to either hover over the padded area on and around the notification indicator in the status bar. As well as click on the padded notification indicator to view the tooltip.

Having said that, a very important item about the tooltip is that we will need the tooltip to disappear if the user clicks anywhere outside of the tooltip div. otherwise it's very difficult to understand how to make that tooltip go away.

There should be the ability to click and have the tooltip stay open as well as just hover

This would provide two states for the user which is a better ux.

**Comment by larrysalibra** [comment]
I'm going to enable the built-in hover and click methods and we can tune the ux later.

**Comment by larrysalibra** [comment]
Hover didn't work. It wouldn't stay open once mouse leaves the overlay.

**Comment by guylepage3** [comment]
yeah. @larrysalibra i'm sure we can find a better component out there that will significantly reduce the workload on this.

**Comment by larrysalibra** [comment]
We no longer have this component.
