### ISSUE TITLE
Name registration failed because of failed NAME_TRANSFER step

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#504]
Reported by @thunderrabbit on slack

> I submitted my username request for thunderrabbit.id about 20 hours ago https://blockchain.info/address/3AXaax3H6PfDdu76oTwKMTDVMoKUJBfo3k  As suggested by jude, I restarted blockstack (about an hour ago), but the final transaction still has not gone through.

It appears NAME_TRANSFER operation was not broadcast.

Probably related to: https://github.com/blockstack/blockstack-core/issues/418

**Comment by larrysalibra** [comment]
Additional info from @thunderrabbit:

> other data is that I never turned off my computer since the registration and my internet connection is usually pretty solid.

**Comment by thunderrabbit** [comment]
Also, I am running ethereum and doge nodes, which I guess should not have affected, but could have??

**Comment by thunderrabbit** [comment]
I did leave my computer idle, so maybe it fell asleep before all the transactions could go through.

**Comment by jcnelson** [comment]
Hey @thunderrabbit, I think I've found the problem:

```
info	2017-05-24 23:16:47.951697 -0400	Blockstack	blockchain.py	org.blockstack.core	Tx b23c43abcff1dabf1809f82f7881d3a7d3b214d9c632cd9871b32e8dfdc70682 has 96 confirmations
info	2017-05-24 23:16:47.957991 -0400	Blockstack	registrar.py	org.blockstack.core	Transfer thunderrabbit.id to 14A96SQ2a9iFr7yvPQLBhn6h6LCLC9wpMg
info	2017-05-24 23:16:49.801180 -0400	Blockstack	scripts.py	org.blockstack.core	3AXaax3H6PfDdu76oTwKMTDVMoKUJBfo3k will subsidize 5500 (ops) + 26500 (dust) (32000)  satoshi
default	2017-05-24 23:16:58.318008 -0400	Blockstack	nameops.py	org.blockstack.core	Guessing that owner address 31mGefi2Dj3HEg4CXToJosAu1fMqF7DSKh requires 2 signatures
info	2017-05-24 23:16:58.325249 -0400	Blockstack	blockchain.py	org.blockstack.core	Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/thunderrabbit/Library/Application Support/Blockstack/config/client.ini)
info	2017-05-24 23:16:58.651869 -0400	Blockstack	nameops.py	org.blockstack.core	transfer tx 1093 bytes, 345528 satoshis txfee
info	2017-05-24 23:16:58.661285 -0400	Blockstack	nameops.py	org.blockstack.core	dust_fee is 26500
info	2017-05-24 23:16:58.669934 -0400	Blockstack	nameops.py	org.blockstack.core	Additional dust fee: 26500
error	2017-05-24 23:16:58.681236 -0400	Blockstack	nameops.py	org.blockstack.core	Failed to check transfer: Address 3AXaax3H6PfDdu76oTwKMTDVMoKUJBfo3k does not have enough balance (need 372028, have 109313).
error	2017-05-24 23:16:58.690545 -0400	Blockstack	nameops.py	org.blockstack.core	Error transferring: thunderrabbit.id
error	2017-05-24 23:16:58.702223 -0400	Blockstack	PortalLogServer	org.blockstack.mac	Error trying to process portal log: The operation couldn’t be completed. (Blockstack.PortalLogServer.LogEventDecoderError error 1.)
error	2017-05-24 23:16:58.711945 -0400	Blockstack	registrar.py	org.blockstack.core	Failed to transfer thunderrabbit.id to 14A96SQ2a9iFr7yvPQLBhn6h6LCLC9wpMg: Failed to broadcast transfer transaction: Address 3AXaax3H6PfDdu76oTwKMTDVMoKUJBfo3k does not have enough balance (need 372028, have 109313).
```

The Core node was correctly trying (and re-trying) to send the final `NAME_TRANSFER` transaction, but it ran out of BTC before it could do so.  Specifically, it needs 372028 satoshi, but your address only has 109313.  If you send it a little bit more BTC and wait for a bit, the Core node will automatically re-try the operation (it checks every 5 minutes).

In the mean time, we're working on a fix going forward to remove the need for the final `NAME_TRANSFER` step.  Thank you again for reporting this issue!

**Comment by thunderrabbit** [comment]
Thank you so much for finding this.   Shall I create a ticket like "Inform user if not enough BTC in wallet?"

There is also a sub-issue of the wallet informing me the price for thunderrabbit.id would be 0.008 BTC, but my 0.01 BTC was not enough to cover it.

**Comment by jcnelson** [comment]
Hi @thunderrabbit, opening a separate issue would be great!

What I suspect is that the transaction fees increased while your name was in the process of being registered.  The fee estimation algorithm calculates the satoshis-per-byte transaction fee at the time you register the name, meaning that if Bitcoin encounters a "fee event," it's possible that the required fees exceed the amount of Bitcoin you deposited initially.

We slightly overestimate fees today in order to account for this, but all the recent Bitcoin activity has exceeded even this estimation.  We'll also take a look at this, in addition to removing the last `NAME_TRANSFER` step.

**Comment by thunderrabbit** [comment]
I added 0.03 BTC, and the balance has shown up in my Blockstack wallet.  I waited 10 minutes, then restarted Blockstack (and waited 45 minutes), but it still has apparently not sent the final transaction.

**Comment by localjo** [comment]
I think I might also be experiencing a similar issue. I added 0.01 BTC to my account and tried to register localjo.id but it's been several days and I'm not able to access that profile anywhere. If I try to register it again, it says it's been registered. So it seems like the registration process might have started, but didn't complete.

**Comment by localjo** [comment]
Looks like I'm missing `NAME_TRANSFER`; https://explorer.blockstack.org/name/localjo.id

**Comment by thunderrabbit** [comment]
There are multiple `api_endpoint.log` files in my `Blockstack/config` directory.  The active file is `api_endpoint.log` and older files have a numeric suffix, (e.g. `api_endpoint.log.1495671344`)

The second to most recent file, `api_endpoint.log.1495671344`, has many instances of this string `Address <address> does not have enough balance (need <nnnnnn>, have 109313).`

(with slightly different values for what is needed)

Those messages are repeated through the entire file.

The most recent log file, `api_endpoint.log`, does not have any such lines, nor even any references to `thunderrabbit.id`

**Comment by oso4** [comment]
My name registration was finally successful, but the remaining bitcoin isn't showing up in my wallet - it says I have 0.00 BTC, but the transaction says otherwise:
[https://blockchain.info/address/3MP8eFA9FSXdaxiKoZb9jR5jcyQLhgcad3](https://blockchain.info/address/3MP8eFA9FSXdaxiKoZb9jR5jcyQLhgcad3)

Not sure what's going on. My profile the blockstack portal doesn't reflect that I have a .id, and actually forces me to restore my account every time I restart my computer. I'm thinking that's not normal. Full of problems for me over here.

**Comment by larrysalibra** [comment]
@thunderrabbit I looked at the second set of logs you sent me and it doesn't appear that the `registrar` continued trying to transfer your name 

```
default	2017-05-24 23:37:03.226434 -0400	Blockstack	registrar.py	org.blockstack.core	Transfer failed: Not all names transferred
error	2017-05-24 23:37:14.508351 -0400	Blockstack	registrar.py	org.blockstack.core	Failed to transfer thunderrabbit.id to 14A96SQ2a9iFr7yvPQLBhn6h6LCLC9wpMg: Failed to broadcast transfer transaction: Address 3AXaax3H6PfDdu76oTwKMTDVMoKUJBfo3k does not have enough balance (need 374233, have 109313).
default	2017-05-24 23:37:14.513345 -0400	Blockstack	registrar.py	org.blockstack.core	Transfer failed: Not all names transferred
info	2017-05-25 21:54:51.069435 -0400	Blockstack	registrar.py	org.blockstack.core	Cleaning all queues in /Users/thunderrabbit/Library/Application Support/Blockstack/config/queues.db
info	2017-05-25 21:54:51.109782 -0400	Blockstack	registrar.py	org.blockstack.core	Sleep for 300
info	2017-05-25 21:54:51.118610 -0400	Blockstack	registrar.py	org.blockstack.core	register all pending preorders in /Users/thunderrabbit/Library/Application Support/Blockstack/config/queues.db
info	2017-05-25 21:54:51.124288 -0400	Blockstack	registrar.py	org.blockstack.core	put zonefile hashes for registered names in /Users/thunderrabbit/Library/Application Support/Blockstack/config/queues.db
info	2017-05-25 21:54:51.129784 -0400	Blockstack	registrar.py	org.blockstack.core	replicate all pending zone files and profiles for updates /Users/thunderrabbit/Library/Application Support/Blockstack/config/queues.db
info	2017-05-25 21:54:51.135229 -0400	Blockstack	registrar.py	org.blockstack.core	transfer all names in /Users/thunderrabbit/Library/Application Support/Blockstack/config/queues.db
info	2017-05-25 21:54:51.143832 -0400	Blockstack	registrar.py	org.blockstack.core	replicate all pending zone files for name imports in /Users/thunderrabbit/Library/Application Support/Blockstack/config/queues.db
info	2017-05-25 21:54:51.149049 -0400	Blockstack	registrar.py	org.blockstack.core	clean out other confirmed operations
info	2017-05-25 21:59:52.130006 -0400	Blockstack	registrar.py	org.blockstack.core	Cleaning all queues in /Users/thunderrabbit/Library/Application Support/Blockstack/config/queues.db

```


I'll share the logs with @jcnelson and see if he has any insight.

**Comment by jcnelson** [comment]
If it's not too much trouble, can you post your `queues.db` file from `/Users/thunderrabbig/Library/Application Support/Blockstack/config/queues.db`?  That'll help us track down what went wrong.  There's nothing sensitive in it; it only records public information about ongoing name operations.  I'm trying to figure out why the registrar didn't resume trying to transfer your name.

**Comment by thunderrabbit** [comment]
It looks like a binary file, so I posted it to Larry via Dropbox

**Comment by larrysalibra** [comment]
I helped @thunderrabbit transfer his name to the browser manually. 

We also discovered a problem with zone file generation: https://github.com/blockstack/blockstack.js/issues/215

**Comment by localjo** [comment]
Can anyone tell me what steps I can take to transfer my name registration to the browser manually?

**Comment by larrysalibra** [comment]
@localjo the best instructions we have at the moment are here -> https://github.com/blockstack/blockstack-browser/blob/9b32ee8e2e033e46c8eba0ea6322553c374de21e/docs/manual-core-to-browser-migration.md

keep in mind that while your name will show up in the browser, it won't immediately be useful because we don't have support for updating zone files yet #88

**Comment by larrysalibra** [comment]
As of v0.11, we use a 3 step registration process that skips the `NAME_TRANSFER` step because browser provides the owner address private key directly to core so that there is no need to transfer the name. As a result, this issue shouldn't arise again.
