### ISSUE TITLE
macOS: insecure update error dialog upon installing latest Blockstack version (0.9?)

### ISSUE THREAD

**Issue by rubinovitz** [blockstack/blockstack-browser#505]
Dialog attached below. The install seemed to go fine, but a few hours later I got this alert (and I assume it's referring to Blockstack as that's all I've updated on Mac recently).

<img width="413" alt="screen shot 2017-05-25 at 6 33 10 pm" src="https://cloud.githubusercontent.com/assets/1807895/26474052/d6266e20-417c-11e7-8170-c95ec5bfaea9.png">

**Comment by larrysalibra** [comment]
@rubinovitz Thanks so much for reporting this! I had a similar problem while running the 0.9 version before pushing it to the update server and assumed it was related. That it's still appearing after the update has been pushed to the update server tells me there's another problem. I'll investigate.

**Comment by rubinovitz** [comment]
Update on update: I think the original install did not go through because I was just asked to update again. 
<img width="619" alt="screen shot 2017-05-25 at 7 33 23 pm" src="https://cloud.githubusercontent.com/assets/1807895/26474784/1c8eb60c-4181-11e7-9fdf-60f2b7699a9f.png">

**Comment by shea256** [comment]
Hey @rubinovitz after you installed the second time, does the problem persist?

**Comment by rubinovitz** [comment]
@shea256 Hi, it looks like I do have 0.9.0 installed and I have not received the insecure update error again, so I believe so (I cannot remember if I opted to install the update again, but I assume so).

**Comment by larrysalibra** [comment]
I haven't seen this problem again. I'm going to close it out, please re-open if it happens again. Thanks again @rubinovitz for reporting this!
