### ISSUE TITLE
Inform user if BTC balance is too low to complete a transaction

### ISSUE THREAD

**Issue by thunderrabbit** [blockstack/blockstack-browser#506]
Issue #504 was due to insufficient funds in my wallet.  Opening a ticket could have been avoided if Blockstack had informed me that I needed to add more BTC to complete the transaction.

### Details

The log included an error message

    error	2017-05-24 23:16:58.711945 -0400	Blockstack	registrar.py	org.blockstack.core	Failed to transfer thunderrabbit.id to 14A96SQ2a9iFr7yvPQLBhn6h6LCLC9wpMg: Failed to broadcast transfer transaction: Address 3AXaax3H6PfDdu76oTwKMTDVMoKUJBfo3k does not have enough balance (need 372028, have 109313).

which was not indicated anywhere in the web interface (http://localhost:8888/profiles).

### Motivation

#504 may have been due to [BTC price fluctuating](https://github.com/blockstack/blockstack-browser/issues/504#issuecomment-304146823), and it may be solved if we [remove the need for the final NAME_TRANSFER step](https://github.com/blockstack/blockstack-browser/issues/504#issuecomment-304040502), ...

but certainly as the system grows, there will be other reasons the lack of BTC in a wallet could be causing unexpected behavior.

**Comment by shea256** [comment]
Yes good call @thunderrabbit and thanks for linking these two issues.

**Comment by matheusml** [comment]
What's the current pattern for warning users of this kind of error @guylepage3 ?
Are we using a toastr?

**Comment by jackzampolin** [comment]
This has been implemented. Closing this issue.
