### ISSUE TITLE
resolve issue with sidebar on storage app

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#507]
Resolve issue with sidebar on storage app.

<img width="769" alt="screenshot 2017-05-28 15 09 41" src="https://cloud.githubusercontent.com/assets/1711854/26531476/c34a7a16-43b7-11e7-8f27-c70caff1cdfd.png">

**Comment by jackzampolin** [comment]
This has been fixed in current releases. Closing as stale.
