### ISSUE TITLE
design on-boarding screens

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#514]
Design new on-boarding screens for the browser based up current content.

<img width="550" alt="screenshot 2017-05-21 15 07 06" src="https://cloud.githubusercontent.com/assets/1711854/26601611/84cd1eb8-454e-11e7-9a9e-7a3d0cbacc89.png">
<img width="566" alt="screenshot 2017-05-21 15 07 14" src="https://cloud.githubusercontent.com/assets/1711854/26601609/84cc8d04-454e-11e7-8c89-f04359529ffd.png">
<img width="576" alt="screenshot 2017-05-21 15 07 24" src="https://cloud.githubusercontent.com/assets/1711854/26601610/84ccb054-454e-11e7-88e0-264e88fdec1c.png">
<img width="561" alt="screenshot 2017-05-21 15 07 38" src="https://cloud.githubusercontent.com/assets/1711854/26601612/84cee8c4-454e-11e7-9bb5-0e3e6a00fa83.png">
<img width="567" alt="screenshot 2017-05-24 17 22 47" src="https://cloud.githubusercontent.com/assets/1711854/26601613/84d12d1e-454e-11e7-8d79-78e40912fe7e.png">

**Comment by guylepage3** [comment]
Additional screen views that appear when user does not have their core node running.

<img width="596" alt="screenshot 2017-06-20 08 14 24" src="https://user-images.githubusercontent.com/1711854/27339320-7e7b180a-55a5-11e7-97b1-96abfca74dab.png">
<img width="714" alt="screenshot 2017-06-20 08 21 26" src="https://user-images.githubusercontent.com/1711854/27339321-7e7e7b44-55a5-11e7-8b08-8b65c474279b.png">

**Comment by guylepage3** [comment]
![on-boarding-01 2x](https://user-images.githubusercontent.com/1711854/27400730-0127c354-568f-11e7-8923-c1a2e85e770a.png)
![on-boarding-02 2x](https://user-images.githubusercontent.com/1711854/27400731-0128f666-568f-11e7-837e-81cee9e1c279.png)

**Comment by shea256** [comment]
The dots seem a little strange and distracting in there.

**Comment by guylepage3** [comment]
![on-boarding-01 2x](https://user-images.githubusercontent.com/1711854/27407599-008d9596-56a7-11e7-9c14-861971995e15.png)
![on-boarding-02 2x](https://user-images.githubusercontent.com/1711854/27407601-0094e580-56a7-11e7-86a4-b447e3d699a0.png)
![on-boarding-03 2x](https://user-images.githubusercontent.com/1711854/27407603-0098540e-56a7-11e7-8684-1155d7d46f58.png)
![on-boarding-04 2x](https://user-images.githubusercontent.com/1711854/27407602-0095bf82-56a7-11e7-8868-aeb8b213ebee.png)
![on-boarding-05 2x](https://user-images.githubusercontent.com/1711854/27407604-009cab94-56a7-11e7-9594-5aa8273ec48b.png)
![on-boarding-06 2x](https://user-images.githubusercontent.com/1711854/27407600-009505a6-56a7-11e7-9313-3b6e58370f12.png)
![on-boarding-07 2x](https://user-images.githubusercontent.com/1711854/27407605-009e8b94-56a7-11e7-9d2e-db346339d0f9.png)

**Comment by guylepage3** [comment]
![on-boarding-08 2x](https://user-images.githubusercontent.com/1711854/27408948-fc2c1530-56ac-11e7-8561-3acd4d8ac02c.png)

**Comment by shea256** [comment]
@guylepage3 Awesome thanks for sharing these. Thinking through this a bit now.

**Comment by guylepage3** [comment]
@shea256 based upon our discussion..

I feel as though this is pretty clean.. Thoughts?

![on-boarding-09 2x](https://user-images.githubusercontent.com/1711854/27495741-2bc31788-5821-11e7-9d1f-c8bd0c796c55.png)

**Comment by shea256** [comment]
@guylepage3 Can we get rid of that outside outline of the dots? Would just the dots work?

Also how does the white one look?

**Comment by guylepage3** [comment]
>Can we get rid of that outside outline of the dots?

@shea256, sorry. I don't see an outside white outline anywhere. Can you explain where that is located exactly?

>how does the white one look?

Will show you in a few minutes.

**Comment by guylepage3** [comment]
![on-boarding-10 2x](https://user-images.githubusercontent.com/1711854/27511367-fb3ed302-58ef-11e7-90db-756bb3aeef61.png)

**Comment by guylepage3** [comment]
![on-boarding-10 2x](https://user-images.githubusercontent.com/1711854/27511374-20737ea2-58f0-11e7-9163-8214308b6fa0.png)

**Comment by shea256** [comment]
@guylepage3 I really like that last one, the white one ^

**Comment by shea256** [comment]
With the status bar above, of course.

**Comment by guylepage3** [comment]
![on-boarding-10 2x](https://user-images.githubusercontent.com/1711854/27554134-670a4922-5a7b-11e7-84f6-882feeb04541.png)

**Comment by shea256** [comment]
nice!

**Comment by guylepage3** [comment]
pinning... https://github.com/blockstack/blockstack-browser/issues/534

**Comment by guylepage3** [comment]
@larrysalibra @shea256 did we decide that we are going to go with the stand alone webkit window for the browser? Please confirm as soon as possible as I will need to quickly add in the navigational items into the status bar.

**Comment by guylepage3** [comment]
![on-boarding-11 2x](https://user-images.githubusercontent.com/1711854/28339759-32dfdfc4-6bdb-11e7-8915-918bc2728231.png)

**Comment by shea256** [comment]
Nice!

**Comment by shea256** [comment]
Also can we prep for the transition to the new layout by using these options in the navbar?

Apps | Me | Money | Settings

**Comment by guylepage3** [comment]
![on-boarding-12 2x](https://user-images.githubusercontent.com/1711854/28341879-84d67bc8-6be3-11e7-8692-63a1410d37ba.png)

**Comment by guylepage3** [comment]
@shea256 can we talk about this.. I really feel as though we should pull in imagery into the on-boarding and give the user the feeling that this is their new desktop. even go so far as to add the imagery onto the background of the home screen.

**Comment by guylepage3** [comment]
This is my new desktop.. Blockstack is my desktop. My OS.

**Comment by guylepage3** [comment]
Maybe even let users set their own "home screen background image"

**Comment by larrysalibra** [comment]
> Maybe even let users set their own "home screen background image"

Let's revisit this after the summit - at the moment, let's hold off on more features.

> I really feel as though we should pull in imagery into the on-boarding and give the user the feeling that this is their new desktop. even go so far as to add the imagery onto the background of the home screen.

Use your best judgement. Looks good to me!

**Comment by guylepage3** [comment]
>let's hold off on more features

Yeah. agreed.

>Use your best judgement. Looks good to me!

👍

**Comment by guylepage3** [comment]
implementing. closing this issue

**Comment by guylepage3** [comment]
![browser-00a-onboarding 2x](https://user-images.githubusercontent.com/1711854/28388074-70db7a1c-6c9f-11e7-86d7-e1ab6b5732b8.png)
![browser-20a-onboarding-pair 2x](https://user-images.githubusercontent.com/1711854/28388073-70da70f4-6c9f-11e7-940a-138b7da9e541.png)
![browser-21a-onboarding-api-password 2x](https://user-images.githubusercontent.com/1711854/28388075-70df1b72-6c9f-11e7-97e5-9a7e5b95ac6d.png)

**Comment by guylepage3** [comment]
![browser-25a-onboarding-new-internet 2x](https://user-images.githubusercontent.com/1711854/28471174-3bd162e8-6e0a-11e7-98ef-9602709b05fe.png)
![browser-26a-onboarding-data 2x](https://user-images.githubusercontent.com/1711854/28471173-3bcb2338-6e0a-11e7-83e9-e4bdb1679435.png)
