### ISSUE TITLE
list the to-do list app on the home screen

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#515]

**Comment by larrysalibra** [comment]
can you create @guylepage3 an icon for this?

**Comment by guylepage3** [comment]
@larrysalibra. Yes. I'll create an issue for the app icon and peg it to this issue

**Comment by guylepage3** [comment]
App icon design issue https://github.com/blockstack/blockstack-browser/issues/554

**Comment by guylepage3** [comment]
![app-icon-todo-list 2x](https://user-images.githubusercontent.com/1711854/28272548-d5d1c178-6ad9-11e7-944c-cd5b4c8d2b5e.png)
