### ISSUE TITLE
Provide a better estimate of how much bitcoin to deposit

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#517]
Right now we estimate 0.01 bitcoins, however as bitcoin becomes more popular, the fees continue to increase. See this thread: https://forum.blockstack.org/t/help-unable-to-register-username-in-blockstack/1114/2?u=larry

**Comment by wica128** [comment]
Hi,

> Right now we estimate 0.01 bitcoins, 
It is was even fluctuating.  around the 0.008 and 0.01.
A link to explain this would be nice.

And it would be nice if it shows the transfer fee.

**Comment by rdempsey** [comment]
FYI I was unable to register until I viewed some of your troubleshooting answers and saw this in my console:

```
2017-06-04T14:27:18.055-0400 ERROR profiles/store/registration/actions.js: register failed.
Address <my-address> does not have enough balance (need 1357358, have 1000000).
```

**Comment by jackzampolin** [comment]
This is taken care of by the current name purchasing flow. Closing.
