### ISSUE TITLE
Developer UX Improvment

### ISSUE THREAD

**Issue by jcalfee** [blockstack/blockstack-browser#519]
So I built for the web.  Now what?
`https://github.com/blockstack/blockstack-browser#building-for-the-web`

I took a guess, but this open an empty page and I don't see any console errors:
```bash
firefox build/index.html
```

This may be a good place to mention or link to the configuration of the blockstack-core server.  I am running a docker container which puts the server under a different IP address.

**Comment by jcalfee** [comment]
Nevermind .. I need `npm run dev` and the other linux section .. thanks..

**Comment by larrysalibra** [comment]
@jcalfee glad you figured this out. 

> This may be a good place to mention or link to the configuration of the blockstack-core server. I am running a docker container which puts the server under a different IP address.

I created issue #520 to add documentation for pointing the browser at a remote core node.

Thank you for your feedback! Let us know if we can make anything more clear!

**Comment by jcalfee** [comment]
Well I kind of ran out of time.  Do you have something that explains this: Do you have a public blockstack server to connect this web interface too or why this is still a bad idea?  If users know this it should be easier for them to guide their efforts.

**Comment by larrysalibra** [comment]
> Do you have a public blockstack server to connect this web interface too or why this is still a bad idea?

You need to trust the core api server you're using because it needs your private keys to spend your bitcoin and perform name operations. This is why it should be run locally.
