### ISSUE TITLE
Add an app version number in local storage

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#521]
We can use this to prompt users that they need to upgrade storage format.

**Comment by matheusml** [comment]
@larrysalibra could you please provide more info on this?

**Comment by guylepage3** [comment]
@larrysalibra are we adding this into `v0.12`?

**Comment by jackzampolin** [comment]
This would likely be implemented in the [`SettingsReducer`](https://github.com/blockstack/blockstack-browser/blob/develop/app/js/account/store/settings/actions.js#L16)

**Comment by larrysalibra** [comment]
I'm working on this in the current state refactoring #562.

**Comment by larrysalibra** [comment]
The version number is set here: https://github.com/blockstack/blockstack-browser/commit/8958b1fba8b819828dbe6bfa3d77783a723ebf4e#diff-4de39683f4e124d810b6fe65d4ca0737R36

and is stored in localStorage in a separate item: https://github.com/blockstack/blockstack-browser/commit/3cbad51257aba1464e71d1d1af81ecc805d6a163#diff-27f24f8a13363c8441d079f37c6e00b0R66
