### ISSUE TITLE
hanging "loading addresses..."

### ISSUE THREAD

**Issue by ryanckulp** [blockstack/blockstack-browser#523]
prior to connecting a Storage provider, /wallet/receive:

<img width="568" alt="blockstack-wallet-loading-addresses" src="https://cloud.githubusercontent.com/assets/3083888/26803075/e5785662-4a10-11e7-8a1e-db81fa43d385.png">

after connecting Dropbox, revisiting page shows an address. not sure if these are related.

**Comment by larrysalibra** [comment]
Thanks for reporting! Which operating system and browser are you using?

**Comment by ryanckulp** [comment]
@larrysalibra thanks,

Chrome Version 58.0.3029.110 (64-bit)
macOS Sierra, Version 10.12.5

**Comment by kaushan** [comment]
Same here on Safari Version 10.1.1 MacOS Sierra 10.12.5

**Comment by matheusml** [comment]
Same here on Linux Mint 18.1, Latest Chrome.

Here's the console:

![](http://i.imgur.com/KTjTLjf.png)

**Comment by jackzampolin** [comment]
This has been fixed in the latest builds. Closing.
