### ISSUE TITLE
Update browser to include core zero confirmation fixes

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#526]
code is in: https://github.com/blockstack/blockstack-core/tree/rc-0.14.2-portal
use commit: https://github.com/blockstack/blockstack-core/commit/bbb4a5b3fe6d77451f7dd834d5f61219f60f8dda

**Comment by shea256** [comment]
@larrysalibra I'm having this issue with 1 confirmation. So it's not just a zero confirmation bug.

**Comment by larrysalibra** [comment]
I'm re-opening this because we were informed that the fix wasn't actually included in core until the rc-0.14.3 branch:
https://github.com/blockstack/blockstack-core/pull/479

**Comment by larrysalibra** [comment]
This was already shipped.
