### ISSUE TITLE
Names disappear for users upgrading from 0.9.0 to 0.9.1

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#527]
Reported by @shea256 and slack user monst.

**Comment by larrysalibra** [comment]
monst reports that using chrome, upgrading from 0.9.0 to 0.9.1 causes the state of the browser to totally reset as if it had never been run before:

![screen shot 2017-06-06 at 11 01 48 am](https://user-images.githubusercontent.com/597182/26836480-f287b90e-4aa8-11e7-9dfa-7f6f8f236a1b.png)

**Comment by jackzampolin** [comment]
Fixed in the latest versions. Closing as stale.
