### ISSUE TITLE
Make project work with npm 5

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#531]
After upgrading to npm 5, our dependencies and tests seem broken. I'm to push off investigating this to another day and instead stick to npm 4.

**Comment by matheusml** [comment]
Maybe this is related #588

**Comment by larrysalibra** [comment]
Thanks @matheusml ! I've also added engines to package.json with the versions we support: https://github.com/blockstack/blockstack-browser/commit/11976a5de386b8ec715beb74faf7212d4222a1a7
