### ISSUE TITLE
Importing onename ID

### ISSUE THREAD

**Issue by vmatekole** [blockstack/blockstack-browser#536]
I tried to register 'vmatekole' on Blockstack, forgetting I already did on onename back in 2014. 

Here is the associated bitcoin address for vmatekole – https://blockchain.info/address/1FVmrdzouHy512KPXstHDbv3UC39KhkP2J

When I go to Settings (on onenname) to transfer the ID to — https://blockchain.info/address/169utkgPB4ZSnnH6NH6qhQ3BVyXbZyRG71. A POST request to one https://onename/api/username/transfer is made — very worryingly my password is sent into the body — it seems the process of auth for transfer is being done server-side, why?

No recent transactions are seen on either address. Can someone shed some light?

**Comment by vmatekole** [comment]
Any update on this issue?

**Comment by guylepage3** [comment]
hey @vmatekole, this is something we're throwing into the roadmap.
