### ISSUE TITLE
Use integer form of the first 31 bits of a hash's byte sequence instead of hashcode

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#538]
Calculate `int-31` as the the integer form of the first 31 bits of a byte sequence instead of the hashcode.

**Comment by jcnelson** [comment]
I thought more about this regarding using a hashcode versus a 31-bit slice of a cryptographic hash.  Because the search space of 2**31 is so small, it doesn't matter how secure the hash function is.  If it's easier to use the hashcode algorithm instead of upgrading it, I'm all for it.
