### ISSUE TITLE
Refactor keychain code into library

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#539]
Our keychain code should have a clean interface similar to `blockstack-keychains`. I've started this in `account-utils`, but we should move this out into separate files and/or a separate library.

**Comment by jackzampolin** [comment]
Looks like [this is implemented](https://github.com/blockstack/blockstack-browser/blob/develop/app/js/utils/account-utils.js#L128-L129)? Can we close this issue?

**Comment by larrysalibra** [comment]
No, it hasn't. 

We'll need to eventually extract all of this logic and put it into blockstack.js.

**Comment by wbobeirne** [comment]
Closing as stale, other issues have taken the place of this in blockstack.js
