### ISSUE TITLE
ux issue: pairing screen opens a new tab upon execution

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#540]
There is an odd action that takes place that confuses me as to what just happened.

This issue occurs when the user has deleted their account and/or the user uses incognito mode. The user executes the requested...

>Please pair your browser with Blockstack. To pair your default browser with Blockstack, click on the Blockstack icon in your menu bar and then click on Home.

Seen here:
<img width="1246" alt="screenshot 2017-06-20 10 55 00" src="https://user-images.githubusercontent.com/1711854/27339857-ee186554-55a6-11e7-9365-7d5f36afa51b.png">

Then a new tab opens to...
<img width="1248" alt="screenshot 2017-06-20 10 55 28" src="https://user-images.githubusercontent.com/1711854/27339880-fd3a6ad2-55a6-11e7-98dd-69f1bac9c16f.png">

while the initial tab remains open. Not only is this a bit awkward, but it's also a bit confusing to the user. 
1. Ok. What just happened?
2. Did I successfully pair to Blockstack?

**Comment by larrysalibra** [comment]
I’m pretty sure there’s nothing we can do about it. It’s how the browser handles a request by the operating system to open a page. It by default opens pages in new tabs. There’s no way that I know of to change that behavior.

My solution would be to run browser portal in a separate app window and avoid the whole browser pairing situation in the first place.

Another solution that might allow us to avoid “pairing” in the future is to have portal set the core api password based on a determistically calculated key from the keychain and making the Core node storage subsystem multi-tenant. Each key pair would get its own storage system.

Open to other suggestions as well.

Don’t think we’ll get to this in this sprint. Moving to backlog.

**Comment by guylepage3** [comment]
>My solution would be to run browser portal in a separate app window and avoid the whole browser pairing situation in the first place.

I have liked this idea ever since you first proposed it to @shea256. This is something we should seriously consider. Seems as though it solves a lot of issues as well. Definitely solves a few UX issues which are critical for the browser to take off.

>Don’t think we’ll get to this in this sprint. Moving to backlog.

👍 cool.

**Comment by ted24** [comment]
I've met the same problem. So how can login into my acc now?

**Comment by larrysalibra** [comment]
We're planning to move to a native app window so this won't be an issue.
