### ISSUE TITLE
Helping users whose registrations paused before TRANSFER

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#558]
User's whose registration fails before the `TRANSFER` step are in an unfortunate situation that can only be resolved with the command line.

To help those users out, we want to be able to figure out their owner address and then give them a command on the command line to run.

I think @larrysalibra helped a couple users out with this last week -- if you could post the steps you took, we'd be able to help those users out while you are offline.

For right now, I'm telling those users to back up the `~/Library/Application\ Support/Blockstack/` as that's the most important for ensuring that their core wallet doesn't vanish on them.

**Comment by larrysalibra** [comment]
I’ve been pointing people to this thread:

https://blockstack.slackarchive.io/support/page-61

I’ll make a document for it.

**Comment by larrysalibra** [comment]
@kantai Here you go! https://github.com/blockstack/blockstack-browser/blob/9b32ee8e2e033e46c8eba0ea6322553c374de21e/docs/manual-core-to-browser-migration.md
