### ISSUE TITLE
Login to the Forum with Blockstack ID

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#561]
We spent a whole sprint hooking up `sign in with Blockstack` to the Forum. Now that we have the forum live in the Blockstack Browser we don't showcase this "aha" experience.

Clicking on this:
![screen shot 2017-06-27 at 1 03 16 am](https://user-images.githubusercontent.com/5605552/27571559-a0953c0c-5ad4-11e7-84a4-254453c4cdcd.png)

brings me to the forum without a handoff in the sign-in process. You just see the forum homepage:
![screen shot 2017-06-27 at 1 03 02 am](https://user-images.githubusercontent.com/5605552/27571750-d6c4caf8-5ad5-11e7-9aed-fbf1d95f1516.png)

...what should happen instead is you're brought to a `Sign in with Blockstack` action being automatically executed on the forum bringing you immediately here (sign-in didn't work here, similar to [Hello Blockstack error](https://github.com/blockstack/blockstack-browser/issues/547)):
![screen shot 2017-06-27 at 1 06 25 am](https://user-images.githubusercontent.com/5605552/27571623-f9137146-5ad4-11e7-98a3-58e0519531f4.png)

In this case you could skip over this modal too..
![screen shot 2017-06-27 at 1 06 11 am](https://user-images.githubusercontent.com/5605552/27571683-56af5e3c-5ad5-11e7-86b8-2214edbe9b14.png)

******

As a side note, I actually tried `signing in with Blockstack`, and couldn't:
![screen shot 2017-06-27 at 1 06 25 am](https://user-images.githubusercontent.com/5605552/27571705-7ed1a65e-5ad5-11e7-92d8-67a8b428fb4c.png)
![screen shot 2017-06-27 at 1 07 47 am](https://user-images.githubusercontent.com/5605552/27571704-7ed0bbd6-5ad5-11e7-8b9c-22288277839a.png)
![screen shot 2017-06-27 at 1 08 21 am](https://user-images.githubusercontent.com/5605552/27571703-7ed088b4-5ad5-11e7-8d76-2f0b25fb90e8.png)

**Comment by larrysalibra** [comment]
Thanks for finding this @pstan26 .

Great idea to have it automatically log in. We don't have a provision to allow external apps to ask an app to be logged in. Apps need to make the request themselves to be logged in. We could define a conventional way to do this for apps that want to support.

Want to open a feature request issue for this?

For the forum in particular, we could link from the browser to the forum using this link: http://forum.blockstack.org/auth/blockstack - which would start the blockstack authentication process. The downside is that it'd make users have to log in every time instead of just the first time.

---

I've verified that I can't log in either. 

Our ruby libraries are unable to decode our authentication responses.
```
(blockstack) Callback phase initiated.
(blockstack) Authentication failure! invalid_auth_response: Blockstack::InvalidAuthResponse, Unable to decode JWT

Blockstack::InvalidAuthResponse (Unable to decode JWT):
  blockstack (0.5.9) lib/blockstack.rb:79:in `rescue in verify_auth_response'
  blockstack (0.5.9) lib/blockstack.rb:44:in `verify_auth_response'
  /Users/larry/git/omniauth-blockstack/lib/omniauth/strategies/blockstack.rb:71:in `callback_phase'
  omniauth (1.4.2) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.4.2) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.4.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.4.2) lib/omniauth/builder.rb:63:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.13) lib/active_record/migration.rb:373:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.13) lib/active_support/callbacks.rb:373:in `_run__1766841012064838309__call__callbacks'
  activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
  /Users/larry/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/larry/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/larry/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.5ms)
  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.9ms)
  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.8ms)
  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (33.7ms)
```

**Comment by larrysalibra** [comment]
I opened an issue on the ruby library here: https://github.com/blockstack/blockstack-ruby/issues/1

**Comment by larrysalibra** [comment]
Please open an issue on https://github.com/blockstack/discourse-blockstack if you're still having an issue with forum sign on.
