### ISSUE TITLE
Create a state update process

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#562]
We have a lot of users experiencing issues that are most likely caused by stale state as the schema of our state changes between pre-releases.

There are some packages we could adopt to migrate state with each version:
https://www.npmjs.com/package/redux-persist
https://github.com/wildlifela/redux-persist-migrate

Another, simpler option would be to run what is essentially an account restore on each update:

The state we'd need to preserve is:

1. the encrypted mnemonic
2. api settings
3. dropbox token
4. the index of the next unused name address

**Comment by larrysalibra** [comment]
larry [8:31 PM] 
we really should only persist a few settings, the user's encrypted secret, and our cached identity keys

**Comment by jackzampolin** [comment]
Related to: https://github.com/blockstack/blockstack-browser/issues/521

**Comment by larrysalibra** [comment]
Now that we've refactored name state, I'm going to work on this next.

**Comment by larrysalibra** [comment]
I think the better way to handle this medium term is to use https://www.npmjs.com/package/redux-persist which allows us to write migrations between state versions - this appears to require changing the format of how data is stored in localStorage. I'm hesitant to do that right now given our time constraints and lack of experience with this library.

Instead, I'm adding a version number to the state tree. We manually increment the version number if we make a breaking change to the persisted state. If the version number is older than the current version, users will be prompted to enter their password to finish upgrading Blockstack. By entering their password, we can re-generate the state using the current structure from their secret.

<img width="532" alt="screen shot 2017-10-15 at 9 55 26 pm" src="https://user-images.githubusercontent.com/597182/31585417-980a5dd0-b1f3-11e7-9518-9ae0b25a9d0d.png">

**Comment by GinaAbrams** [comment]
closing this as it seems to be done - let me know if I'm wrong!
