### ISSUE TITLE
design a new button for profile creation

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#563]
Create a new button for profile creation

<img width="268" alt="screenshot 2017-06-27 12 45 30" src="https://user-images.githubusercontent.com/1711854/27599728-b1e282fe-5b37-11e7-85bf-dbabe33babda.png">

**Comment by guylepage3** [comment]
<img width="891" alt="screenshot 2017-06-27 13 21 51" src="https://user-images.githubusercontent.com/1711854/27600971-9f47c588-5b3b-11e7-8414-80465a64edf1.png">

**Comment by pstan26** [comment]
Too funny that you essentially predicted Silicon Valley HBO show with
having added Thomas Middleditch in here before season 4 started. Prescient.

**Comment by guylepage3** [comment]
Lmao.. So weird. Lol. 🙈

**Comment by pstan26** [comment]
This create button is disabled fyi (likely not your problem). Adding this to a new github issue.

**Comment by guylepage3** [comment]
@pstan26 Actually, yes that would be my issue. Thank you for letting me know sir. Can you create an issue for that and assign it to me? Thanks.

**Comment by guylepage3** [comment]
complete.

**Comment by pstan26** [comment]
Looks like you already found it! :-)

**Comment by guylepage3** [comment]
@pstan26 i think this is a separate issue.
