### ISSUE TITLE
"+ Create" profile button in profiles app in browser not clickable

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#567]
@larrysalibra 

When I hover over the blue "+ create" button, the pointer turns into a circle with a cross though it, indicating that you can't click on it. Was able to create a profile for the throwaway account I had (great experience compared to previous ones!)

![screen shot 2017-06-27 at 3 10 05 pm](https://user-images.githubusercontent.com/5605552/27605479-dbb5c2fe-5b4a-11e7-8181-79e0d30199e3.png)

**Comment by pstan26** [comment]
flow I went through:
![image](https://user-images.githubusercontent.com/5605552/27605660-52c7f592-5b4b-11e7-8f67-8cd11d8d293b.png)

**Comment by guylepage3** [comment]
@pstan26 What version of the browser are you running?

**Comment by pstan26** [comment]
0.10.0

**Comment by guylepage3** [comment]
Hm. I am unable to recreate that. I'm going to have to pass this one off to @larrysalibra.

**Comment by pstan26** [comment]
k thanks

**Comment by larrysalibra** [comment]
I'm not able to immediately reproduce this error either.

Does it happen if you delete your account and restore? We don't currently upgrade state between versions.  (See #562) This might happen if your browser only has 2 identity addresses generated. 

Starting with the consensus release (v0.9.0), we pre generate 9 identity addresses and don't let users create additional ones. The reason for this is that creating additional addresses requires that the user enter their password to decrypt their backup key so that we can generate the new addresses and we don't have a user interface mechanism for doing this at the moment.

**Comment by pstan26** [comment]
Is the process of deleting to just delete blockstack and re-download 0.10.0?

**Comment by larrysalibra** [comment]
No. You actually don’t need to delete/uninstall blockstack. All state is stored in your web browser (chrome, etc) so you can try it out in incognito. You can also delete your account in the Blockstack Account app and then restore your account with your backup phrase.

**Comment by pstan26** [comment]
Sure thing, do instructions exist for restoring the account with my backup
phrase?

**Comment by larrysalibra** [comment]
@pstan26 click the “restore account” link on our onboarding screens. there aren’t any instructions as far as I know.

**Comment by guylepage3** [comment]
>Sure thing, do instructions exist for restoring the account with my backup phrase?

No. We need to make the experience as user friendly as possible anyway. A great test for user flow is to not create instructions and therefore forcing the team to create a better flow and more intuitive product for the user.

**Comment by larrysalibra** [comment]
I can't reproduce this. Please re-open if it happens again!

**Comment by pstan26** [comment]
Downloaded the latest 0.11.0 and can't click "+create" button. Reopening this issue

**Comment by larrysalibra** [comment]
@pstan26 

You'll need to clear your local storage:

`localStorage.clear()` in the javascript console while the browser is open

**Comment by pstan26** [comment]
I did that and I just lost my username and didn't have a backup.
Terrrrrrrific.

**Comment by larrysalibra** [comment]
> I did that and I just lost my username and didn't have a backup.

If you opted in to the encrypted email back up, your inbox should have an encrypted copy of your backup phrase which can be unlocked with the upcoming transfer tool and used to recover your names.

**Comment by pstan26** [comment]
Ok I have that from registering docusign.id 7 days ago. This will also
apply to my pstanley.id i registered a few months ago as well? Will wait
for the transfer tool

**Comment by larrysalibra** [comment]
Yes. See #619
