### ISSUE TITLE
design update to profile view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#569]
Quickly update the design of the profile view so that it's a little friendlier.

<img width="1250" alt="screenshot 2017-06-27 16 08 30" src="https://user-images.githubusercontent.com/1711854/27607724-e0db8d2e-5b52-11e7-8ad8-b268d13e5434.png">

**Comment by guylepage3** [comment]
![browser-15b-profile-desktop 2x](https://user-images.githubusercontent.com/1711854/27608721-7e6324fa-5b56-11e7-8c76-2e17f80d9f31.png)

**Comment by guylepage3** [comment]
@shea256 proposing to move forward with this layout as a quick improvement from the dark version we have to date as we won't have time to execute more layouts. will swoop back around before summit if there's time. how does that sound?

**Comment by shea256** [comment]
👍

**Comment by guylepage3** [comment]
complete. closing issue.
