### ISSUE TITLE
Dropbox upload fails if user hasn't verified email

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#571]
Dropbox won't allow use to create shared links if the user hasn't verified the email of their account.

This doesn't happen immediately after creating a new account but after about 24 hours.

On the browser it shows up as "There was a problem submitting your registration."

@jcnelson how do you handle these types of errors at the Gaia level?

Ideally we would be able to give users actionable feed as to how they can resolve the problem with their dropbox. However this will quickly become very complicated as there are likely a large number of reasons that dropbox requests could fail: out of space, payment failed, account "freeze", etc.

```
{ status: 409,
  error: 
   { error_summary: 'email_not_verified/..',
     error: { '.tag': 'email_not_verified' } },
  response: 
   { req: 
      { _query: [],
        method: 'POST',
        url: 'https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings',
        header: [Object],
        _header: [Object],
        _callbacks: [Object],
        _data: [Object],
        xhr: {},
        _callback: [Function: responseHandler],
        _timeout: 0 },
     xhr: {},
     text: '{"error_summary": "email_not_verified/..", "error": {".tag": "email_not_verified"}}',
     statusText: 'Conflict',
     statusCode: 409,
     status: 409,
     statusType: 4,
     info: false,
     ok: false,
     clientError: true,
     serverError: false,
     error: 
      { [Error: cannot POST https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings (409)]
        status: 409,
        method: 'POST',
        url: 'https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings' },
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     notFound: false,
     forbidden: false,
     headers: { 'content-type': 'application/json' },
     header: { 'content-type': 'application/json' },
     type: 'application/json',
     body: { error_summary: 'email_not_verified/..', error: [Object] } } }
```

**Comment by jay-hwang** [comment]
I had this same issue with the same error message. After some digging, I found that I apparently I had two separate Dropbox accounts. One was synced to my computer, and the other was logged in on Dropbox's site. The account logged in on Dropbox's site hadn't been verified yet. I logged out of that account and logged in with the account synced to my computer and all is good now.

**Comment by larrysalibra** [comment]
We can't really do anything about this until we have more useful error responses from core. The tracking issue is for that is here: https://github.com/blockstack/blockstack-core/issues/422

**Comment by jackzampolin** [comment]
We are moving away from dropbox for storage. Closing this issue.
