### ISSUE TITLE
Social proofs should marked untrusted unless verified

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#573]
One of the things we talked about in the security review is that unverified social profiles should be marked as “untrusted” or “broken” - perhaps with a red color? Otherwise it’s easy to trick people into thinking that I’m you by adding your twitter to my profile and not verifying it.

**Comment by pstan26** [comment]
That is a small audience of people with verified social media accounts. Why
not just make the links clickable and let people see for themselves? Some
app will get built on our platform that verifies these someday anyways.

**Comment by shea256** [comment]
@pstan26 Larry is referring to how my Facebook, Twitter and GitHub accounts are verifiably linked to my blockchain ID here: https://onename.com/ryan

**Comment by pstan26** [comment]
Oh I see. Yea that makes sense. Maybe a soft grey *no* sign like this:
http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons-256/flat-gray-floral-icons-signs/091581-flat-gray-floral-icon-signs-nosign1.png

**Comment by guylepage3** [comment]
https://invis.io/VHCDGCEJ3#/241118423_browser-15b-Profile-Desktop

**Comment by pstan26** [comment]
Don't see any social proofs, is that what you were trying to show Guy? I
like the UI however

**Comment by jackzampolin** [comment]
This has been implemented in the latest version. Closing as stale.

**Comment by larrysalibra** [comment]
I don't think they currently show up as obviously, "broken", just not verified. We were discussing this yesterday in the frontend meeting.

Will let @yknl verify.

**Comment by larrysalibra** [comment]
This shipped
