### ISSUE TITLE
Address generation logic should format address based on network

### ISSUE THREAD

**Issue by scott-martin** [blockstack/blockstack-browser#574]
According to @shea256, "all address generation logic should detect the network it's on and format addresses accordingly."

When creating an account in regtest mode, there are 9 profile addresses that are pregenerated (js/account/store/account/actions.js:26). All of these addresses start with a "1", according to @shea256 this is because bitcoin mainnet addresses use the version byte "1". The problem surfaces when trying to log in to my account from an app I'm building - it fails due to the address in the jwt and the address coming from the api lookup not matching.

**Comment by larrysalibra** [comment]
Thank you for pointing this out @scott-martin !

**Comment by shea256** [comment]
Thanks for reporting this @scott-martin!

**Comment by larrysalibra** [comment]
To fill in more information about this: The way regtest mode currently works with core is it converts from bitcoin mainnet addresses to regtest addresses. ( @jcnelson please correct me if I'm wrong). This is how we've been able to use our javascript libraries & browser in regtest mode without any changes.

The one api call I've seen that doesn't do that is the name look up call `/v1/names/saturday.id` which returns the regtest address:

```JSON
{"status": "registered", "zonefile": "$ORIGIN saturday.id\n$TTL 3600\n_http._tcp URI 10 1 \"https://www.dropbox.com/s/y0fon2xxd71oiz3/profile.json?dl=1\"\n", "expire_block": 53044, "blockchain": "bitcoin", "last_txid": "3b05e7fe05e83457edc38128df36e871758c639819f67419f16b8ef35bd68a69", "address": "mh2i2ia3Gk15Dos6mAtiRxdFU1QZczQ3My", "zonefile_hash": "4a0bfc7d1c73f3b8c14544de35f9c022eb4a4da1"}
```

**Comment by scott-martin** [comment]
That's the call that ends up failing the signIn request using blockstack.js. So maybe the solution is to fix that name lookup call.

**Comment by jcnelson** [comment]
@scott-martin The Browser currently has no knowledge of whether or not it is connected to testnet or regtest, since as @larrysalibra mentions Core automatically translates addresses when it interacts with the blockchain.

If the problem you're having is specifically caused by `GET /v1/names/:name` returning a testnet-formatted address, would a viable solution be having Core simply converting any address it sends back to callers into a mainnet address?

**Comment by larrysalibra** [comment]
@jcnelson that would be an excellent solution for the moment!

**Comment by kantai** [comment]
Okay, as of blockstack-core@a9547a8d738de8801506d070f4b0870b80a8ba95, `GET /v1/names/:name` converts the address.

**Comment by larrysalibra** [comment]
Beautiful! Look forward to trying this out! Thanks @kantai

**Comment by larrysalibra** [comment]
This checks out for me!
