### ISSUE TITLE
Use of developer console on Firefox starts eating up RAM

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-browser#577]
Opening the developer console in Firefox (on Archlinux) and then refreshing the dashboard starts filling up the RAM quickly. After some debugging I guess it comes from the "debugger" tab.

Chromium on Archlinux works without problems. This problem exists on my laptop (same setup) too.

**Comment by guylepage3** [comment]
@larrysalibra @shea256 is this issue to be `backlog` or are we throwing it in to `v0.12`?

**Comment by larrysalibra** [comment]
I haven't seen this issue on Firefox on macOS or other browsers.

It seems to me if refreshing a web page on firefox causes firefox's debugger tab to use up a lot of memory that that is a bug with firefox. The debugger should be freeing resources used by the previous instance of the page.

thoughts @vsund ?

**Comment by vsund** [comment]
It freezes also when I only go on "Profiles" without opening the debugger tab. It's on both of my devices and their share a quite similar setup (Firefox on Archlinux, Chromium works without these problems).

Any idea how to debug this issue in Firefox?

**Comment by larrysalibra** [comment]
I haven't been able to replicate this on my firefox. This is probably a problem that should be reported to mozilla or archlinux.

**Comment by vsund** [comment]
Ah sorry, I forgot about this issue, this got fixed due to some changes in Blockstack Browser, Firefox or ArchLinux. In the end: I'm not experiencing this issue anymore 🎉

**Comment by vsund** [comment]
Ah sorry, I forgot about this issue, this got fixed due to some changes in Blockstack Browser, Firefox or ArchLinux. In the end: I'm not experiencing this issue anymore 🎉
