### ISSUE TITLE
restored account and blockstack ids are not there

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#580]
I went through the Restore Account process and it seemed to be successful. But my Blockstack IDs did not appear in the Profiles app when I went into the app. 

I waited 20 minutes, launched the Profiles app again and my Blockstack IDs are still not there.

<img width="1249" alt="screenshot 2017-06-30 09 04 33" src="https://user-images.githubusercontent.com/1711854/27736721-64c0fb8e-5d73-11e7-83af-73a8fd461d4e.png">

**Comment by larrysalibra** [comment]
@guylepage3 when did you buy your blockchain ids? 

If it was before 0.10, they won't be there until you migrate them.

**Comment by larrysalibra** [comment]
Waiting for feedback on this.

**Comment by guylepage3** [comment]
this issue has been resolved. what was happening was a long delay when the profile was restored. @kantai thought it probably was a caching issue in my browser.

Have tried to replicate the issue a few times to no avail.
