### ISSUE TITLE
Logging disparity between api_endpoint.log and the macOS log

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#582]
I got two logs from Ryan yesterday for debugging zero confs.
1. from the macOS logging (here)[https://github.com/blockstack/blockstack-browser/#logging], then filtered by 'blockstack' 
2. manually obtained api_endpoint.log from `~/Library/Application..`  -- the first log did not contain the information from the 2nd.

```
aaron@cornelius $ wc -l blockstack-core-logs-ryan-jun-30-657pm.txt 
494 blockstack-core-logs-ryan-jun-30-657pm.txt
aaron@cornelius $ wc -l blockstack-core-logs-ryan-jun-30-657pm-api_endpoint.txt 
5491 blockstack-core-logs-ryan-jun-30-657pm-api_endpoint.txt
``` 

I suspect we followed the instructions wrong, or that filtering by 'blockstack' was too aggressive? If so, we should figure out a way to make an automatic filter that works better.

**Comment by larrysalibra** [comment]
@kantai did you filter by the Blockstack process? if you’re typing in the search box, that means typing “process: Blockstack” (without quotes)

Only entering the word “blockstack” won’t do this.

**Comment by kantai** [comment]
Yep -- that was probably the issue -- we just entered the word "blockstack." Should we include "process: Blockstack" in the instructions (https://github.com/blockstack/blockstack-browser/#logging) ?

**Comment by larrysalibra** [comment]
Yes, let’s do that.

**Comment by larrysalibra** [comment]
@kantai updated instructions.
