### ISSUE TITLE
backup profile & account process review

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#583]
### Backup Blockstack Browser Account & Blockstack ID process review

1. **Backup Profile/Account** — As a user I want to save my "names" as I will be deleting my Blockstack App
    1. **Home Screen** — I opened my Blockstack App, which then opened my Chrome browser and I landed on the "Home Screen" — I am most concerned with backing up my profiles so therefore I on the "Profiles" app.
        - **Question**: Why are these apps? Should these Blockstack apps be one consistent brand?
            We created them as separate "looking" apps to give the user the impression that there are a few apps already built on Blockstack. But I feel that this has not worked out very well as a) people have not tweeted out that there are apps built on Blockstack and b) we don't internally look at them like they are separate apps. If people thought they were "non-Blockstack apps" they would tweet about these "apps" that had already been built on Blockstack.
    2. **Profiles List view** — Where do I click to backup my profiles(s)? In this instance I only care about "one" of my profiles. I then click on the profile that I want to back up.
    3. 🚩 **Profile view** 🚩 — After viewing the Profile and clicking on all the links on the profile view it became clear that there was no backup and/or export feature inside the "Profile App" itself. — **Confusion** — After discovering that there is no way to backup or export my profile(s) from the Profiles App itself I became very confused. I would have either created a support ticket or gone to the forum or slack to find out if it was at all possible to backup and/or export my profile from the browser. 🚩
        - **Questions**
            - So the Blockstack Core Developers explained to me that users can only backup their user "Account" located in the "Account App." They cannot backup their individual profiles. All profiles are associated with a user "Account." — **Proposal** — to change the name of the "Profiles App" to "Accounts" where users can have multiple "Accounts" that contain their "Profiles" inside their Accounts. Then change the current "Accounts" app to "Settings."
    4. **Account App landing view** — After receiving help from the Blockstack Core Developers, I entered the "Account App." — Here I quickly found the "backup account" tab and clicked.
    5. **Backup Account view** — I see that there is a use for a password but I do not recall being told the importance of this password. I enter my password.
    6. **Backup phrase decrypted** — There is a green alert box stating "Backup phrase decrypted" and "Write down the backup phrase below and keep it safe. Anyone who has it will be able to regain access to your account." — There should be a better way to explain what's happening here — Also, I would like to have the ability to simply download my backup phrase. In doing so it saves the user from thinking of a file name and reduces the friction backup their phrase.
    7. **Created backup phrase text file** — I copied and pasted my backup phrase into a plain text file so that i may encrypt the backup file.
    8. **Encrypted file**

**Question**
- Should there be an option to send the user their back up phrase once they've entered their correct password?

**Comment by guylepage3** [comment]
**Proposal** — to change the name of the "Profiles App" to "Accounts" where users can have multiple "Accounts" that contain their "Profiles" inside their Accounts. Then change the current "Accounts" app to "Settings."

**Comment by guylepage3** [comment]
To go along with that proposal is that it seems to make much more sense to peg a "Wallet" to a "Profile" and not to an "Account." 

The reason I feel this is more intuitive is that I have multiple bank accounts. and they have profiles so users are already used to this.

**Comment by guylepage3** [comment]
**Proposal 2** —To go along with that proposal is that it seems to make much more sense to peg a "Wallet" to a "Profile" and not to an "Account." 

The reason I feel this is more intuitive is that I have multiple bank accounts. and they have profiles so users are already used to this.

**Comment by shea256** [comment]
> Proposal — to change the name of the "Profiles App" to "Accounts" where users can have multiple "Accounts" that contain their "Profiles" inside their Accounts. Then change the current "Accounts" app to "Settings."

@guylepage3 The way it's set up now is the user can create one account/keychain. Then for that account, the user can have many profiles. That's why we named them profiles.

**Comment by shea256** [comment]
> Proposal 2 —To go along with that proposal is that it seems to make much more sense to peg a "Wallet" to a "Profile" and not to an "Account."

I see your point but this is going to be more cumbersome for the user. Best to minimize complexity.

**Comment by shea256** [comment]
Remember earlier how we said we would hide the fact that you could create multiple profiles? I think that's a great move. We can give users a single default profile and make it big. Then only power users would be making more than one profile. I can show you what this would look like.

**Comment by larrysalibra** [comment]
+1 making multiple profiles a power user feature

**Comment by guylepage3** [comment]
closing issue
