### ISSUE TITLE
restore account & profiles process review (3 user flows)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#584]
Restore Blockstack Browser Account & Blockstack ID process review.

There are 3 flows to restore a users account & profiles.

1. **Restore Account (Path 1)** — Restore from on-boarding screens.
    1. **On-boarding screen 1 - Welcome** (Screenshot 2017-07-01 15.46.33.png) — I noticed that on the first on-boarding screen of the Blockstack App there was a "Restore Account" link. — Clicked the "Restore Account" link.
    2. **Restore Account on-boarding screen** (Screenshot 2017-07-01 15.47.15.png) — This screen could use a description of what and at what time in the user funnel did the user receive their "Backup phrase."
    3. **Email backup of keychain** (Screenshot 2017-07-01 15.51.13.png) — Should this happen here only? I did make a note in the backup account process review suggesting that we add the ability for users to send themselves an encrypted backup to their email. — When I entered my email address and clicked the "Yes" link the modal window disappeared and I was all of a sudden on the Home Screen. — It would be nice to see a confirmation message telling me that my backup was successfully sent to my email address.
    4. **Home Screen** — Shouldn't the user be taken to their restored account so that they may see that their account was successfully restored. Maybe take them to the "Profiles App List View" Where they can see their profiles? — Clicked on the "Profiles App" to see if my profiles are restored.
    5. **Profiles App List View** — It took roughly 5 seconds for my profile to appear.

2. **Restore Account (Path 2)** — Restore from on-boarding screens but passed the initial on-boarding screen 1.
    1. **On-boarding screen 1 - Welcome** (Screenshot 2017-07-01 15.46.33.png) — I DID NOT notice that on the first on-boarding screen of the Blockstack App there was a "Restore Account" link and clicked "Get Started"
    2. **Choose a password to encrypt keychain** — I realized that I do not want to create a new account but want to restore my account. Since I did not notice that there was a link to restore on the screen before, I am stuck. — A possible solution could be to have a link to go back and a link to "restore" on each on-boarding screen?
— User is stuck and has to quit app — 

3. **Restore Account (Path 3)** — Restore from on-boarding screens from encrypted "keychain" in email.
— Confusion — Is it a keychain? A Profile? An account that I am restoring? — We should make sure naming is consistent for searching in email and to limit confusion for the user. — I recall having my Blockstack backup phrase or keychain being sent to me at some point. 
    1. Email — Once I found the email, I opened it and, on first blush, I could not tell if it was actually sent by Blockstack as there was not any Blockstack branding. — Apply the Newsletter HTML/CSS to this email for quick brand improvement. — I decided to download the "blockstack-backup.txt" file. — Decryption instructions — Maybe there should be instructions on how to decrypt the backup?
    2. **blockstack-backup.txt** — When looking at the file contents I am unaware what type of encryption this is. Therefore, how do I decrypt it?
— User is stuck as they do not know how to decrypt the file. They do not even know what type of encryption it is. —

**Comment by guylepage3** [comment]
<img width="1247" alt="screenshot 2017-07-01 15 46 33" src="https://user-images.githubusercontent.com/1711854/27765772-d17c2242-5e88-11e7-8fb9-c2562f92c71c.png">
<img width="1246" alt="screenshot 2017-07-01 15 47 15" src="https://user-images.githubusercontent.com/1711854/27765771-d17b941c-5e88-11e7-971d-e62d1ebdd5a1.png">
<img width="1249" alt="screenshot 2017-07-01 15 51 13" src="https://user-images.githubusercontent.com/1711854/27765773-d17c8f66-5e88-11e7-9e68-20bc07a89b9c.png">

**Comment by guylepage3** [comment]
closing issue

**Comment by iamnathanwindsor** [comment]
Hi Guys-

I have the blockstack-backup.txt file, how do I decrypt it?

Thank you~

**Comment by guylepage3** [comment]
@iamnathanwindsor can you send a support request to support@blockstack.com? thank you. :)
