### ISSUE TITLE
design new status bar with browser utilities

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#587]
Quickly redesign the browser status bars with the new browser utilities, `Profiles`, `Storage`, `Wallet` & `Settings`.

**Comment by guylepage3** [comment]
New status bar design based upon requirements from browser call on Mon, Jul 3.

<img width="772" alt="screenshot 2017-07-06 08 34 59" src="https://user-images.githubusercontent.com/1711854/27911224-49d8ceb6-6226-11e7-809b-0dacadb4bf11.png">

**Comment by guylepage3** [comment]
@shea256 @larrysalibra what do you guys think of this status bar?

<img width="1597" alt="screenshot 2017-07-06 13 55 23" src="https://user-images.githubusercontent.com/1711854/27925475-d8a129e6-6252-11e7-9227-13feef2502c1.png">

**Comment by larrysalibra** [comment]
@guylepage3 how do the lights work?

**Comment by guylepage3** [comment]
hey @larry, there is a simple change in css. for different backgrounds. Already established and defined here for developers.
- https://github.com/blockstack/blockstack-browser/issues/490

**Comment by larrysalibra** [comment]
@guylepage3 Sorry about being unclear. I was asking from the user's perspective. What do they mean? Do they click on them? 

Are they intended to be progress bar? If so, would something that looks more like a progress bar be better?

**Comment by guylepage3** [comment]
hm.. @larrysalibra these are just new status bars. Like the current status bar we have. As we've discussed, we are pulling out the browser utility apps and building them into the status bar. just as we've discussed on our call on Monday.

**Comment by larrysalibra** [comment]
@guylepage3 ha! I know these are the new status bars.

I'm asking specifically about the red dots...are they intended to be a progress bar? As a user, I don't know why there are red dots there or what I'm supposed to do to them or about them. I also don't know what message they're trying to communicate. It's not obvious to me.

**Comment by guylepage3** [comment]
Gotcha. Yeah. We can add a line and numbers above them or go with a percentage status bar.

**Comment by guylepage3** [comment]
<img width="1564" alt="screenshot 2017-07-06 15 57 41" src="https://user-images.githubusercontent.com/1711854/27930241-e013be76-6263-11e7-935d-e79670469c31.png">

**Comment by shea256** [comment]
@guylepage3 Can we do the following?

1. Change "Account" to "Me" and make it link to the profiles app.
2. Remove storage and roll that app into the "Settings" app.
3. Remove the "Browser setup progress" bar.

**Comment by shea256** [comment]
Some of this may be confusing and not yet clear but I can expand on this with some UX screens and how everything will be working together.

**Comment by guylepage3** [comment]
@shea256. gotcha. making the changes now.

**Comment by guylepage3** [comment]
@shea256 can you explain why we are pulling storage it into settings?

**Comment by guylepage3** [comment]
closing issue
