### ISSUE TITLE
node-sass failing with node 8 when trying to setup the project

### ISSUE THREAD

**Issue by matheusml** [blockstack/blockstack-browser#588]
I was trying to setup the project with:
- Node 8
- npm 5

But I was getting this error:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

```

After reading about this error for a while, it seems using a node version <= 7. So I've downgraded it and it worked.

Should we add this info to the docs?

**Comment by larrysalibra** [comment]
Thanks to your pull request, @matheusml, this now works!

I also added `engines` to package.json to let everyone know which versions of npm and node we support.
