### ISSUE TITLE
Increase the number of decimal places for bitcoin balances

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#595]
The actual amount is often significantly off from the displayed amount because decimal places only go up to 3. The decimal places in the app should go up to at least 6 (potentially 8).

**Comment by shea256** [comment]
<img width="1138" alt="screen shot 2017-07-05 at 4 02 13 pm" src="https://user-images.githubusercontent.com/994646/27882719-bb84afd4-619b-11e7-9121-fc7b46c0a2ad.png">
<img width="1161" alt="screen shot 2017-07-05 at 4 02 30 pm" src="https://user-images.githubusercontent.com/994646/27882720-bb9528e6-619b-11e7-87a8-76d97b3a8267.png">

**Comment by larrysalibra** [comment]
<img width="400" alt="screen shot 2017-07-07 at 5 17 30 pm" src="https://user-images.githubusercontent.com/597182/27951653-3a383024-6338-11e7-89ea-942971cbd1a9.png">
<img width="306" alt="screen shot 2017-07-07 at 5 17 38 pm" src="https://user-images.githubusercontent.com/597182/27951655-3b70f638-6338-11e7-858f-e45aeed29f13.png">

Beautiful @matheusml! Thank you!
