### ISSUE TITLE
Add a QR code to the wallet receive tab to support mobile deposits

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#596]

**Comment by matheusml** [comment]
Are we already using a library that have this?

**Comment by larrysalibra** [comment]
@matheusml No, we aren't currently using a library since we don't have we don't currently have QR support. Want to take a stab at finding one and making a PR?

**Comment by shea256** [comment]
Awesome @matheusml, great to have you jumping in!

**Comment by larrysalibra** [comment]
Thanks! @matheusml

**Comment by matheusml** [comment]
Done!

![](https://s11.postimg.org/f60cp6mkj/image.png)

**Comment by guylepage3** [comment]
Awesome @matheusml 😄

**Comment by pstan26** [comment]
Woohoo! Nice going @matheusml <https://github.com/matheusml> !

**Comment by larrysalibra** [comment]
Thank you @matheusml! Your pull request was merged in #598
