### ISSUE TITLE
Can't sign in without username

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#601]
Sign in before buying a username is broken.

Underlying cause is blockstack-core requires a blockchain ID for version: 1 auth requests:

https://github.com/blockstack/blockstack.js/issues/230
https://github.com/blockstack/blockstack-core/issues/483

As far as I know, our requirement that users be able to sign in with just a profile hasn't changed.
Thoughts @jcnelson?

**Comment by jcnelson** [comment]
Sorry about that; will revert.

**Comment by jcnelson** [comment]
should be fixed now

**Comment by larrysalibra** [comment]
It's fixed for me. Will be in 0.11 browser build.

**Comment by larrysalibra** [comment]
While this will be in the v0.11, it's important to understand that storage won't work without a username. Here is the tracking issue for that problem: #609
