### ISSUE TITLE
Add password confirmation field when creating new account

### ISSUE THREAD

**Issue by jay-hwang** [blockstack/blockstack-browser#604]
I recently had to backup + delete my Blockstack account, but I couldn't enter the password correctly. I use the same 4/5 passwords for everything, so I'm guessing I made a typo when first creating my password.

There's only one password input field when creating a new account. I think it would be good to have a second 'password confirmation' input, so if someone makes a typo and the two passwords don't match, it throws an error.

**Comment by pstan26** [comment]
Good idea.

**Comment by matheusml** [comment]
I think we are heading to [passwordless](https://github.com/blockstack/blockstack-browser/issues/606).
What do you think, @larrysalibra ?

**Comment by larrysalibra** [comment]
Yes @matheusml. See #606 

Thanks @jay-hwang for filing this!

**Comment by larrysalibra** [comment]
We've added this back in #618 

> I use the same 4/5 passwords for everything, so I'm guessing I made a typo when first creating my password.

Also @jay-hwang let's talk about password managers :-)
