### ISSUE TITLE
Remove the password

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#606]
Removing the password improves the onboarding experience and doesn't really sacrifice security in that

1. We're already storing unencrypted private keys for the name owner address in localstorage to avoid having to ask for a password on each sign in
2. We assume that a user's localstorage is protect from access from other users or malicious apps on a machine by the operating system user account. 
3. We're going to stop running the browser on localhost and instead run it as an electron app or in a webkit app window which removes the threat of malicious apps accessing the localstorage via localhost same origin

**Comment by shea256** [comment]
The alternatives to model our account protection model after [1Password](https://1password.com/) or [Exodus](https://www.exodus.io/).

Before we move forward with any of these models, we should get sign off from some security professionals.

I do have concerns about irreversible losses of funds and/or identities.

**Comment by larrysalibra** [comment]
@shea256 

Various thoughts on this:

* I find it annoying to enter a password on app start up. Operating systems that provide secure secret stores that are unlocked when the OS authenticates the user - when app developers opt out of that, it compromises user experience. If all app developers on macOS or iOS, for example, followed developers' best practice rules, users would only really need to remember one password and have the rest stored in the Keychain. 

* Entering a password for an app is acceptable on web because password managers integrate well with websites, but a pain on native apps in that password manager integration is hit and miss. (this changes in iOS 11 for what it's worth - not sure about macOS or other platforms) I find looking up passwords in password managers in order to copy and paste it a poor experience.

* I don't want to have to enter a password every time I use blockstack to sign into an app. In fact, I think our current sign in process is a worse experience than the existing web after initial sign in:

Blockstack experience

1. Click Sign in with Blockstack
2. Redirect to Browser
3. Click Approve
4. Redirect back to app

Existing web experience
1. Click sign in (user name and password are auto filled on page load by password manager)

Perhaps we can have something like an option to automatically sign me in to this app in the future and a mechanism for apps to check get an auth request signed via an AJAX request without a redirect and only do the redirect on initial sign in.

* I would expect an app to provide additional confirmation prompts and/or request a password or touch id verification when sending large amounts of money or making irrevocable changes to my name.

* For the average user, we expect that Blockstack will always be running. If a password is requested at start up and the blockstack keychain is always in an "unlocked" state, you're not really getting much benefit over reading the secret from the operating system secret store which is unlocked when the user logs in to her computer.  

* I'm not sure the comparison to currency wallets makes a lot of sense. Few people buy or sell crypto currencies from a wallet like Exodus on a daily basis. Those that want to trade send their funds to a centralized exchanged and buy and sell there. There's not an expectation that you're going to leave your Exodus wallet open and always running. People (hopefully!) will be signing in to Blockstack apps through the day.

---

What if we do something like this:

1. No password by default
2. Store seed in operating system secrets store. (on macOS & iOS this means only the signed app that stored the secret can read it)
3. Offer the ability to add a password after money is sent or a name has been ordered. This could happen right after the backup procedure.
4. If user adds a password, use that password to encrypt the secret and store the encrypted secret in the operating system secrets store.


(above assumes we switch to a native app format of some sort with the current code running electron or webkit)

**Comment by larrysalibra** [comment]
What I've suggested above, no password by default, optional password/touch id is what copay does:

![img_4160](https://user-images.githubusercontent.com/597182/28137519-26278d9a-6780-11e7-9ee5-7489d92ecbb0.PNG)
![img_4161](https://user-images.githubusercontent.com/597182/28137527-2ea30968-6780-11e7-8f01-c60902fc0419.PNG)

**Comment by shea256** [comment]
> What if we do something like this:
> 1. No password by default
> 2. Store seed in operating system secrets store. (on macOS & iOS this means only the signed app that stored the secret can read it)
> 3. Offer the ability to add a password after money is sent or a name has been ordered. This could happen right after the backup procedure.
> 4. If user adds a password, use that password to encrypt the secret and store the encrypted secret in the operating system secrets store.

I really like this. I would also only encrypt the master secret and the child branches that pertain to name operations and bitcoin withdrawals. Profile signing and authentication should never require the password. If these keys are ever compromised, the user can just rotate them with a name update operation.

I would also prioritize adding hardware support (w/ devices like Trezor), as this alleviates the need for passwords.

**Comment by shea256** [comment]
I would also communicate in the on-boarding process that we're not going to ask the user to set a password until later, however we can give them the option to override this and set a password right away.

Also, if the word key (12-word phrase) ever starts out as being un-encrypted and then later becomes encrypted, we have to ensure that the Redux history gets cleared.

Also, we should consider whether we're adding an additional step for users to download a backup PDF with an encrypted copy of their word key (12-word phrase). This would require the user to set a password early on but it wouldn't necessarily be used to lock the copy in localStorage.

**Comment by guylepage3** [comment]
>I would also communicate in the on-boarding process that we're not going to ask the user to set a password until later, however we can give them the option to override this and set a password right away.

Maybe we should simplify this and just make it so that a **password "is" required for all users** or a **password "is not" required for all users**.

**Comment by larrysalibra** [comment]
We've decided to go with password for everyone.
