### ISSUE TITLE
Setting owner key from browser results in registrations with wrong address

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#607]
It looks like the issue I referenced at the end of blockstack-core issue #487 (the address being registered to by core is wrong), is that browser is expecting a compressed bitcoin address, while core is registering with an uncompressed address.

This is because the private key string passed to core needs `01` suffix indicating that it should get a compressed public key (see WIF format here: [https://en.bitcoin.it/wiki/Wallet_import_format]).

Anyways, I have a patch which fixes this issue, and has been tested in regtest. Creating PR now.

**Comment by larrysalibra** [comment]
Fixed in `v.0.11` Thank you @kantai for figuring this out!
