### ISSUE TITLE
Withdraw only allows integer amounts of bitcoin

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#612]
The withdraw interface on the browser will only allow whole bitcoin withdrawals. 

![integer-withdraw](https://user-images.githubusercontent.com/1153552/28093992-440fe500-6668-11e7-8fe7-bfd9d73313b0.png)

This was tested on browser commit 13fc5e646c906d41ed9fc1491699752ee0be7554

**Comment by larrysalibra** [comment]
Fixed thanks to @matheusml 's pull request #615 

Thanks again for reporting this @kantai
