### ISSUE TITLE
Username pending for 24 hours

### ISSUE THREAD

**Issue by jay-hwang** [blockstack/blockstack-browser#620]
The first couple usernames I bought took a few hours to finish pending, but the most recent one took about 24 hours. Anyone else get this issue? 

If it's a common problem, is there a way to even out the average pending time? It might not be the best first impression if a user can't gain full accessibility to Blockstack apps for a whole day after taking out a mortgage to pay for their username.

**Comment by larrysalibra** [comment]
It shouldn't take 24 hours. 

The last name I bought with 0.11 took a bit over 1 hour from clicking register to pending going away. Can you share a link to the explorer for the name you ordered that took 24 hours? I'd like to see if it took that long to confirm transactions or if you're experiencing a bug with the browser.

**Comment by icidasset** [comment]
Same here, after 4 days it still says "profile being processed".
Do I have to connect it with Blockstack to get rid of this message?
(I also don't know how to do this)

https://onename.com/icidasset

Related question: How do I restore profiles in the Blockstack browser? Can I use the "key" that was sent to me via email?

**Comment by jay-hwang** [comment]
@larrysalibra Do you mean this link? http://localhost:8888/profiles/ithiel.id/local

**Comment by larrysalibra** [comment]
@jay-hwang this link https://explorer.blockstack.org/name/ithiel.id - it looks like registration went through smoothly and didn't get stuck. However, it also appears that the registration was done on v0.10 and not v0.11. We speeded up registration on v0.11 by removing the NAME_TRANSFER step and sending out the other 3 transactions more quickly (few blocks between each).

@icidasset Best bet for onename is to email onename support. support@onename.com. It might be stuck in the spam filter.

Can't easily move it to the browser at this time, but you will be able to soon!

**Comment by larrysalibra** [comment]
@jay-hwang are you still having this issue?

**Comment by jay-hwang** [comment]
@larrysalibra negative. Closing
