### ISSUE TITLE
design new native macOS layout of browser

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#621]
We should schedule a time to update the layout of the app.

I'm currently experimenting with a few UX layouts.

Here's a preview of one set I've been working on:

## Tab 1

![blockstack - home 1](https://user-images.githubusercontent.com/994646/28217468-2adfdadc-6883-11e7-8384-c5ed28b91c3a.png)

## Tab 2

![blockstack - home 2](https://user-images.githubusercontent.com/994646/28217469-2ae2399e-6883-11e7-9ef6-e09e7f362673.png)

## Tab 3

![blockstack - home 3](https://user-images.githubusercontent.com/994646/28217471-2aece0b0-6883-11e7-81f1-839c55f22187.png)

## Tab 4

![blockstack - home 4](https://user-images.githubusercontent.com/994646/28217470-2ae3abee-6883-11e7-89d9-d32a0edb127b.png)

cc @guylepage3 @larrysalibra

**Comment by guylepage3** [comment]
@shea256, So there would just be a macOS menu bar app?

Would we eventually add a stand alone macOS app as well?

**Comment by shea256** [comment]
@guylepage3 Well this could either be a menu bar app or a standalone window like Copay.

<img width="411" alt="screen shot 2017-07-14 at 11 45 35 am" src="https://user-images.githubusercontent.com/994646/28219488-27c6f11c-688a-11e7-8ad1-0e8a4831e58b.png">

**Comment by shea256** [comment]
I mentioned to @larrysalibra that I think it greatly simplifies the interface

With the current layout, it's 2 clicks to view your profile and 3 clicks to edit it.

With this update, it's 1 click to view your profile, 2 to edit it.

**Comment by matheusml** [comment]
Wow! this is awesome!

**Comment by guylepage3** [comment]
we can re-use some old designs from old products that we abandoned..

![1 profile d10 edit profile](https://user-images.githubusercontent.com/1711854/28235338-f25e45ac-68d9-11e7-950b-927304f8eeb1.png)

**Comment by guylepage3** [comment]
Very excited to go down this "mobile" route.

**Comment by shea256** [comment]
@guylepage3 Yeah we should def build off of that. Those designs are pretty high quality.

**Comment by shea256** [comment]
Here's a new iteration on this layout that I worked on Friday and yesterday:

![blockstack - home 1](https://user-images.githubusercontent.com/994646/28251447-2fa9b74e-6a4b-11e7-93e9-da6d2447bac0.png)
-
![blockstack - home 2](https://user-images.githubusercontent.com/994646/28251450-2fb0d9e8-6a4b-11e7-8b80-91e916aac33b.png)
-
![blockstack - home 3](https://user-images.githubusercontent.com/994646/28251446-2f8d9fa0-6a4b-11e7-9df3-308de350420e.png)
-
![blockstack - home 3b](https://user-images.githubusercontent.com/994646/28251448-2fada43a-6a4b-11e7-98c2-7aa9af7038d8.png)
-
![blockstack - home 4](https://user-images.githubusercontent.com/994646/28251449-2faf78dc-6a4b-11e7-8ff2-2d063771d961.png)

**Comment by guylepage3** [comment]
@shea256 how does a user discover someone else's profile in the new browser? should there be a search capability or will we be pushing for an external resource such as Onename.com?

**Comment by guylepage3** [comment]
@shea256 

1. **Profile** - How often will users want to navigate to their profile?
1. **Main focus of app to determine best UX/feel** - Do we want users to focus on their profile? People are vane and love to look at themselves. Keybase does this very well. Although, the #1 focus for us is apps. So having said that, if we take a look at iOS, they've done a wonderful job of removing all navigation and focus on apps themselves with the exception of those in the dock along the bottom of the home screen.
1. **Navigation** - One other thing I've been playing around with is the navigation at the top instead of the bottom. It's extremely cumbersome to click on the Blockstack icon in the macOS menu bar, then bring my cursor down 650px to the navigation. I want to click and then click to navigate.

**Comment by guylepage3** [comment]
Here are some **Home Screen** design options I've been thinking about. Will post layouts as they get more finalized.
- Layout similar to iOS
- Layout with apps as list items
- Layout with search bar and list below search

**Comment by guylepage3** [comment]
Here are some **Home Screen** design options I've been thinking about. Will post layouts as they get more finalized.
- Layout similar to iOS
- Layout with apps as list items
- Layout with search bar and list below search

The biggest thing I've been struggling with with the new browser is discoverability of apps. Discoverability of any content for that matter. Keybase does a bad job of this in their desktop app. They got lazy and just listed out all the people you're following below the identity portion of the app. It is looking more and more clear to me though that have a search bar of some kind is a quick and easy way to search for content, apps and/or profiles. Having app icons everywhere works with your thumb on iOS but not very well at all when it comes to desktop.

**Comment by shea256** [comment]
@guylepage3 Reading through this in a bit, sorry for the delay.

**Comment by shea256** [comment]
> @shea256 how does a user discover someone else's profile in the new browser? should there be a search capability or will we be pushing for an external resource such as Onename.com?

@guylepage3 Ah yes, there will be a search feature.

> Profile - How often will users want to navigate to their profile?

Fairly often.

> Main focus of app to determine best UX/feel - Do we want users to focus on their profile? People are vane and love to look at themselves. Keybase does this very well. Although, the #1 focus for us is apps. So having said that, if we take a look at iOS, they've done a wonderful job of removing all navigation and focus on apps themselves with the exception of those in the dock along the bottom of the home screen.

Users should focus on their profile a moderate amount. In the beginning, users will go to their profile semi-frequently. They will be adding new verifications and other items to their profile. That said, over time they will need to update their profile less.

One important thing to note is that we should think of this as an identity product. This entire app that we're building is somewhat a browser, somewhat an "identity wallet." As in, it's the thing you take with you when you log in to apps.

> Navigation - One other thing I've been playing around with is the navigation at the top instead of the bottom. It's extremely cumbersome to click on the Blockstack icon in the macOS menu bar, then bring my cursor down 650px to the navigation. I want to click and then click to navigate.

Makes sense to me. Would love to see it. And on mobile this would be flipped I imagine?

**Comment by shea256** [comment]
https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-320087379

OK cool would love to see these when they're ready. And I'll think about this.

**Comment by larrysalibra** [comment]
I like the direction this is going.

**Comment by guylepage3** [comment]
@shea256 as commented in Slack #design channel yesterday, Fri, Aug 4, 2017

_Guy Lepage [4:16 PM]_ 
hey @ryanshea here's the latest browser design
- Click here to view the project `Browser v0.13 (macOS)` https://invis.io/N8CWO5ZJ9#/247226608_desktop

**Viewing instructions**
- to view click on the menubar..
- there are only home screens and profile views at this point
- in order to jump to the next set of "home & profile" screens, there is an invisible button on the bottom of each of the browser windows
- when you have a minute, i'll walk you through the layouts.

**Comment by shea256** [comment]
This is the authorization screen for Civic:

![f250bb4a-6047-48e3-b342-03eaba0a299d](https://user-images.githubusercontent.com/994646/29141310-b27d1dc2-7d1b-11e7-8555-c0a95d5ed644.PNG)

**Comment by shea256** [comment]
This is the authorization screen for Civic

<img src="https://user-images.githubusercontent.com/994646/29141330-ced5854a-7d1b-11e7-891d-fd8ff2c045de.PNG" width="350px" />

**Comment by guylepage3** [comment]
@shea256 can you explain how auth will work exactly in the new browser?

**Comment by guylepage3** [comment]
**Browser designs**
- Mon–Wed (Sketch design files)
- Home screen (keep as is on blockstack.com)
- Wallet (Receive)
    - Send
- Me (Landing)
    - Avatar
    - Avatar settings
- Settings
- (Review) of on-boarding screens

**Comment by guylepage3** [comment]
![browser-macos-30-homescreen-d16 2x](https://user-images.githubusercontent.com/1711854/29775503-6363bdce-8bd3-11e7-82a0-1a16c3aaf279.png)
![browser-macos-40a-profile-d16 2x](https://user-images.githubusercontent.com/1711854/29775518-6d7e0c9c-8bd3-11e7-88fb-0ac7fbc58715.png)
![browser-macos-40b-profile-d16 2x](https://user-images.githubusercontent.com/1711854/29775517-6d7acffa-8bd3-11e7-9fb5-81ba34772014.png)
![browser-macos-41-profileedit-d16 2x](https://user-images.githubusercontent.com/1711854/29775520-6d7ea3e6-8bd3-11e7-8da7-d2c8a339cb95.png)
![browser-macos-42-profileedit-basicinfo-d16 2x](https://user-images.githubusercontent.com/1711854/29775519-6d7ea1ca-8bd3-11e7-93ab-764e21ddde86.png)
![browser-macos-43-profileedit-photo-d16 2x](https://user-images.githubusercontent.com/1711854/29775521-6d81e8da-8bd3-11e7-8885-0f4a031d86cf.png)
![browser-macos-44a-profileedit-social-d16 2x](https://user-images.githubusercontent.com/1711854/29775522-6d82c2e6-8bd3-11e7-8cbd-9cedc126933b.png)
![browser-macos-44b-profileedit-social-d16 2x](https://user-images.githubusercontent.com/1711854/29775523-6d8bc972-8bd3-11e7-9f42-3a40922b07b4.png)
![browser-macos-50-wallet-receive-d16 2x](https://user-images.githubusercontent.com/1711854/29775525-6d8e3ec8-8bd3-11e7-8797-72c9104c479f.png)

**Comment by shea256** [comment]
Awesome work on all this.

A few quick notes:

1. "Edit | Avatar | Other" is a bit confusing. When I first saw "other" I didn't know what that would be referring to. Something more clear would be "Edit | Main Avatar | Other Avatars" but that's unfortunately too long. Maybe there's another way to communicate these choices?
2. The "Receive | Wallet | Send" with the "Receive" below was confusing for me too. What if we make it like there are two sub-tabs (receive and send) and then you click between the two?
3. The address in the wallet looks too much like a button. It should look more like a field that copies an item to your clipboard.
4. In the photo uploading section, the term "Avatar image URL" should be changed to "Photo URL" so that we don't confuse people about what an "Avatar" means in our app.
5. We need to note to add text in the on-boarding process that tells users what an avatar is.
6. In the profile editing menu, the choice "Address" has a space in front of it like this: " Address" (just bothered me to see).
7. The verification text that needs to be copied looks too much like a button. Maybe dashed lines or some other color could help here.

**Comment by guylepage3** [comment]
1. Unfortunately we cannot use "Other Avatars" as there is not enough real estate. We will need to think of a better word. I thought "Other" would suffice for the time being since we are extremely crunched on time.
2. Could do in the next iteration. We already have a "design" solution for a tertiary tab system. Will add to the list of next iteration items
3. Can iterate on this as well.
4. Will do.
5. I would suggest that we not use the term Avatar on this iteration then or add that explanation on the next iteration.
6. This is in the design files only.
7. Will add this to the list of next iteration items as we should design out a clearly defined "copy to clipboard" style that is more intuitive for the user.

**Comment by larrysalibra** [comment]
1. How about Edit | Current | Other Avatars ?

**Comment by guylepage3** [comment]
Needs to be one word

**Comment by guylepage3** [comment]
New Home Screen view with search bar...

![browser-macos-30-homescreen-d16 2x](https://user-images.githubusercontent.com/1711854/29795696-54024f9c-8c1b-11e7-9630-528bd4cbd4dc.png)

**Comment by shea256** [comment]
"Edit | Current | Other" could work.

Other alternatives to "current" are "default" or "main".

**Comment by ryanshea** [comment]
I don't think you mean to include me, namespace collision - this is not the
Ryan Shea you are looking for.

**Comment by shea256** [comment]
@ryanshea Yes sorry looks like @guylepage3 got mixed up and accidentally tagged you. Feel free to mute this convo and we'll make sure not to tag you.

@guylepage3:

> 2. Could do in the next iteration. We already have a "design" solution for a tertiary tab system. Will add to the list of next iteration items

For something quicker, I'm thinking we just have "Send" and "Receive" and use a highlight color for the current one and leave the other one un-highlighted. What do you think?

> The address in the wallet looks too much like a button. It should look more like a field that copies an item to your clipboard.

>3. Can iterate on this as well.

For this, I would try removing the background color for the address. Could be a quick change. Similar to what Copay has. It's clear it's just text.

**Comment by shea256** [comment]
@guylepage3 Home screen looks great. Only thing is the navbar is in a different place than the other screens. Not a good experience. Would keep it in the same top spot to make navigation simple and smooth.

**Comment by guylepage3** [comment]
>For something quicker, I'm thinking we just have "Send" and "Receive" and use a highlight color for the current one and leave the other one un-highlighted. What do you think?

Yes. Will remove all Headline items across the board.

>For this, I would try removing the background color for the address. Could be a quick change. Similar to what Copay has. It's clear it's just text.

Sounds good but I feel we can do better. Will create a design issue for this.

>Only thing is the navbar is in a different place than the other screens.

So I thought about this as well but there are some more popular apps that are utilizing CSS transitions to move the navbar smoothly up to it's final resting place. 

The placement of the navbar & search bar allow for quicker visual navigation that would hopefully result in more use of by the user. Along with the resolution of css transitions, my thought was that when comparing the placement of the navbar vs the stronger visual placement the stronger visual seems to be something that wins.

But yes.. I will move it back to the top for simplicity and consistency.

**Comment by guylepage3** [comment]
Closing out this issue.

**Comment by yknl** [comment]
![browser-macos-44b-profileedit-social-d16](https://user-images.githubusercontent.com/29081231/29894297-dc7bc44c-8da2-11e7-8707-58adbbb715ea.png)
![browser-macos-44c-profileedit-social-d16](https://user-images.githubusercontent.com/29081231/29894299-dc90ae16-8da2-11e7-9788-c84d02b08bb9.png)
![browser-macos-44d-profileedit-social-d16](https://user-images.githubusercontent.com/29081231/29894298-dc81ac54-8da2-11e7-9a7b-ddb110f4202a.png)

**Comment by shea256** [comment]
Great work @yknl!

Here are my notes:

- Remove the "save and view profile" button.
- Remove the "delete" button.
- Replace the "x" button to close out the accordion and replace it with two buttons:.
  - A "^" button to close the accordion
  - A "trash" button to delete the item
- When the verify button is clicked, it should disappear and the accordion should be expanded. Once the instructions are shown, the "verify" button serves no function.

**Comment by guylepage3** [comment]
Thanks @ryanshea 

To clarify Ryan's comments @yknl

Screen 1:
- Remove the "save and view profile" button.
- Remove the "delete" button.

Screen 3: 
- Replace the "x" button to close out the accordion and replace it with two buttons:.
    - A "^" button to close the accordion
    - A "trash" button to delete the item
- When the verify button is clicked, it should disappear and the accordion should be expanded. Once the instructions are shown, the "verify" button serves no function.
    - Please remove the "verify" button.

----

Guy's comments;

Screen 2:
- There seems to be to much space for the "copy to clipboard" icon. We are in mobile view so we should try 
    - a) having the icon on the right smaller with very limited space 
    - b) coy to clipboard button below the text

Screen 3:
I would question whether we need a new "^" button to close the accordion. I personally may skip over that button as I have not seen it very often. the "x" close button means "close" close a window, close an accordion, close a sidebar, etc. it's quite universal

**Comment by guylepage3** [comment]
Additionally we should see a 4th screen of what a filled out account would look like.

**Comment by guylepage3** [comment]
And on Screen 1, we should also note that that screen the user has not yet filled out that account so the "twitter" bar would not be blue as a full blue bar means "verified"

**Comment by shea256** [comment]
> I would question whether we need a new "^" button to close the accordion. I personally may skip over that button as I have not seen it very often. the "x" close button means "close" close a window, close an accordion, close a sidebar, etc. it's quite universal

OK I think I would just be confused by a trash can next to an "x". That's why I was thinking of a carrot.

If you google "collapse accordion" you'll see this is a very common pattern.

<img width="1187" alt="screen shot 2017-08-30 at 6 04 23 pm" src="https://user-images.githubusercontent.com/994646/29897174-b129de9a-8dad-11e7-825f-5cd9d1df5837.png">

**Comment by larrysalibra** [comment]
Questions/Feedback:

* The "x" makes me think i'm deleting the account, not collapsing the accordion.
* What happens when I click the edit (pencil) button after the facebook proof is verified?
* Without the white check, it's not obvious to me that blue is verified. 
* If we add the "^" to indicate an expandable accordion, we can remove the pencil and replace it with the verified state icons. This makes it consistent with viewing the profiles of other users and clear whether or not your profile verification is successful.
* If this was actually on mobile, we'd probably want to use swipe left to delete, for desktop, a trash can makes sense.
<img width="424" alt="screen shot 2017-08-30 at 6 09 24 pm" src="https://user-images.githubusercontent.com/597182/29897335-6b329b1a-8dae-11e7-92fa-8b88360bc097.png">

**Comment by guylepage3** [comment]
@shea256 those are very old windows interface designs. not something i would model after. also those are the 2009 UI accordions. 

It's interesting.. Bootstrap recommends that the user click the link, in our case the bar to fold the accordion back up.

@larrysalibra let's not use mobile swiping on desktop.

**Comment by guylepage3** [comment]
<img width="1904" alt="screenshot 2017-08-30 18 23 11" src="https://user-images.githubusercontent.com/1711854/29897776-82d65d2c-8db0-11e7-9bdd-7ce8b05c3b49.png">

**Comment by shea256** [comment]
> The "x" makes me think i'm deleting the account, not collapsing the accordion.

Yes exactly this! We should avoid "x" in this case.

> Bootstrap recommends that the user click the link, in our case the bar to fold the accordion back up.

And yeah, bootstrap can do this for its main example because there's only one action in each state - to open and close the accordion. This changes when there's also a delete action. So there really should be two separate buttons for closing the collapse and deleting the item.

**Comment by yknl** [comment]
> When the verify button is clicked, it should disappear and the accordion should be expanded. Once the instructions are shown, the "verify" button serves no function.

I think the Verify button is still needed once the user posts to Facebook, we will need them to click on Verify in order to know when to check.

**Comment by guylepage3** [comment]
>I like the idea of the accordion caret, but I feel like having a trash can next to it would be confusing.

Agreed. A "Delete account" button would be better.

**Comment by guylepage3** [comment]
>The "x" makes me think i'm deleting the account, not collapsing the accordion.
>Yes exactly this! We should avoid "x" for this reason.

If one person thinks that, then yeah. let's us the "^" symbol.
