### ISSUE TITLE
TypeError while trying to Authenticate from Blockstack Forum

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#623]
Yesterday, pinoli reported in our slack that he was having difficulty authenticating. (Thanks for sending your log files Pinoli!)

The auth request string:

```
http://localhost:8888/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJqdGkiOiI0YTliM2U1ZS0zNTI5LTQ4OWMtOWYwNi04MmIzOWU4MjNkMjQiLCJpYXQiOjE1MDAwNTk4OTYsImV4cCI6MTUwMDA2MzQ5NiwiaXNzIjpudWxsLCJwdWJsaWNfa2V5cyI6W10sImRvbWFpbl9uYW1lIjoiZm9ydW0uYmxvY2tzdGFjay5vcmciLCJtYW5pZmVzdF91cmkiOiJodHRwczovL2ZvcnVtLmJsb2Nrc3RhY2sub3JnL2F1dGgvYmxvY2tzdGFjaz9tYW5pZmVzdD10cnVlIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9mb3J1bS5ibG9ja3N0YWNrLm9yZy9hdXRoL2Jsb2Nrc3RhY2svY2FsbGJhY2siLCJzY29wZXMiOltdfQ.
```

This corresponds to:

```
    {u'domain_name': u'forum.blockstack.org',
     u'exp': 1500063496,
     u'iat': 1500059896,
     u'iss': None,
     u'jti': u'4a9b3e5e-3529-489c-9f06-82b39e823d24',
     u'manifest_uri': u'https://forum.blockstack.org/auth/blockstack?manifest=true',
     u'public_keys': [],
     u'redirect_uri': u'https://forum.blockstack.org/auth/blockstack/callback',
     u'scopes': []}
```

His console had the following error:

```
TypeError: undefined is not an object (evaluating 'string.length') \{ [TypeError: undefined is not an object (evaluating 'string.length')]\
  line: 15603,\
  column: 15,\
  sourceURL: 'http://localhost:8888/js/main.js' \}\
decodeUnsafe@http://localhost:8888/js/main.js:15603:15\
decode@http://localhost:8888/js/main.js:15631:29\
decode@http://localhost:8888/js/main.js:37568:28\
fromBase58@http://localhost:8888/js/main.js:30169:34\
login@http://localhost:8888/js/main.js:3138:82\
login@[native code]\
invokeGuardedCallback@http://localhost:8888/js/main.js:103928:9\
executeDispatch@http://localhost:8888/js/main.js:97965:42\
executeDispatchesInOrder@http://localhost:8888/js/main.js:97985:22\
executeDispatchesAndRelease@http://localhost:8888/js/main.js:97396:46\
forEach@[native code]\
forEachAccumulated@http://localhost:8888/js/main.js:109316:16\
processEventQueue@http://localhost:8888/js/main.js:97607:25\
runEventQueueInBatch@http://localhost:8888/js/main.js:103995:35\
handleTopLevel@http://localhost:8888/js/main.js:104005:25\
```

**Comment by kantai** [comment]
Looking more into this, the culprit appears to be here:

`app/js/auth/components/AuthModal.js`

```
const appsNodeKey = this.props.identityKeypairs[0].appsNodeKey
const salt = this.props.identityKeypairs[0].salt
const appsNode = new AppsNode(HDNode.fromBase58(appsNodeKey), salt)
```

appsNodeKey is undefined

@larrysalibra -- any thoughts on how this can happen?

**Comment by larrysalibra** [comment]
Thanks for looking into this @kantai 

This key is pre-generated at account creation in current versions (this will change in 0.12) This error usually indicates the user upgraded from a previous version and didn't clear their browser storage. (see release notes: https://github.com/blockstack/blockstack-browser/releases/tag/v0.11.0)

Please let me know if this error still occurs after clear browser storage for the browser origin. (related to #562)

Also important to note forum sign in not working is a known issue: https://github.com/blockstack/blockstack-ruby/issues/1 and #561  

I'll work in some time to look at it Monday.

**Comment by pinoli** [comment]
hello everybody,
I just upgraded to [0.12.0](https://github.com/blockstack/blockstack-browser/releases/tag/v0.12.0) and the problem I ran into (not being able to approve apps) stopped. I now can successfully login in every app present on the Blockstack Home screen.

One thing though: before installing 0.12.0 I followed your suggestion to clear all browser data (reset local storage) and now my **Profiles** page doesn't show my registered username **pinoli.io**. It's like it disappeared. Do you have any ideas on how to recover it? It's weird because my BTC balance is correct, so it knows I made a tx with this wallet to register a username.

thanks for the help!

**Comment by larrysalibra** [comment]
@pinoli that's great to hear that sign in is now working for you!

We'll have a tool coming in the future to recover names from previous pre-release versions. In the meantime, make sure you keep the identity key (previously called back up phrase) in a safe place!
