### ISSUE TITLE
Mixed-content blocking prevents usage of storage on apps deployed with https

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#631]
Browsers block requests to content by that doesn't use https by default when a site is served over https. This includes requests to localhost.

This means that Blockstack apps deployed on https can't access the user's local core node to use storage.

<img width="1409" alt="screen shot 2017-07-19 at 4 21 47 am" src="https://user-images.githubusercontent.com/597182/28339979-ade44e3e-6c40-11e7-85de-6a4b73db48c6.png">
<img width="571" alt="screen shot 2017-07-19 at 4 21 37 am" src="https://user-images.githubusercontent.com/597182/28339992-b934f072-6c40-11e7-8749-2f90addbbd83.png">

**Comment by larrysalibra** [comment]
Some possible solutions:

* Serve apps without http (undesirable)
* Generate and install a self signed certificate for the core node on the user's computer

**Comment by larrysalibra** [comment]
@kantai in slack:

> browser extensions could also solve the problem, without requiring users to approve a new cert and modify /etc/hosts

**Comment by shea256** [comment]
This makes me frowny face. Are there any other options we have?

**Comment by kantai** [comment]
We should also bear in mind, that while addressing this problem, we should *also* address the potential issue raised during our security audit regarding pairing of Core <-> Browser (basically you want to establish that you both have a shared-secret without revealing the secret itself).

**Comment by shea256** [comment]
Does moving to a native window help at all?

**Comment by shea256** [comment]
Also what about the update where we add a DNS TLD to the OS?

**Comment by larrysalibra** [comment]
> Does moving to a native window help at all?

Potentially, if apps are also run in the native window. 
On macOS, when blockstack browser is running in a webview, we already have to override the transport security settings that prevent apple's APIs from talking to non-http URLs by enabling http communication with localhost so that we can load the browser: https://github.com/blockstack/blockstack-browser/commit/b1dd018882ef3a0dd95f3ff2523456ccbf8c792c#diff-92b0aed9d619d77d756c26eb3a51861dR42

We can potentially load insecure content - not 100% sure, would need to try it, but there's a method that makes it look like it might work: https://developer.apple.com/documentation/webkit/wkwebview/1415002-hasonlysecurecontent

If that doesn't work, another option is to have calls to `fetch` in blockstack.js be handled through native code when apps are run in our own native app window.

---

I assume something like this is probably possible in an electron app as well.

**Comment by satbam** [comment]
@larrysalibra @jackzampolin I am also running into this issue.

**Comment by patrickdevivo** [comment]
I'm encountering this as well when trying to use blockstack storage calls (`putFile` and `getFile`). I'm not sure of a good way to fix beyond anything suggested already

**Comment by cwackerfuss** [comment]
I'll add me name to the list here -- we're experiencing issues running on https and had to move over to an unsecured site to circumvent the mixed content errors.

**Comment by icidasset** [comment]
Could we use/do something like this? 🤔  https://github.com/cameronhunter/local-ssl-proxy

**Comment by larrysalibra** [comment]
This is solved with our new "direct to gaiahub" storage client library that allows apps to write directly to a gaia hub without proxying through a local core node. Apps can take advantage of this starting in blockstack.js 0.14.0 and can now enable https.

https://github.com/blockstack/blockstack.js/pull/314
