### ISSUE TITLE
Auto-generate profile

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#632]
Auto-generate first profile during on-boarding process.

**Comment by guylepage3** [comment]
>We'll also need a mechanism to allow users to make another profile this default profile.

Yes. see [#570: build new "create profile" button in profiles app](https://github.com/blockstack/blockstack-browser/issues/570)

**Comment by guylepage3** [comment]
@larrysalibra what was done here? i see #646 and we should not make others smaller but make them "profile list" items. there was an issue open for this.

**Comment by larrysalibra** [comment]
@guylepage3 A profile is now auto-generated during the on-boarding process. The user no longer needs to click the create button to create their first profile.

This issue was intended to be for implementing the auto-generation functionality. Apologies about the confusion!
