### ISSUE TITLE
Bullet points in profile list view on smaller devices

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#640]
Bullet points appear in profile list view when screen width is below 768px in chrome v59. Safari doesn't seem to have this issue.

![profile-list-bullets](https://user-images.githubusercontent.com/29081231/28434765-98b6a0f6-6d5e-11e7-8808-e7e9f2b76186.png)

**Comment by guylepage3** [comment]
Thanks for catching this one @yknl. :)

@estermer is this something you can tackle?

**Comment by estermer** [comment]
I can take a look at this one @guylepage3

**Comment by guylepage3** [comment]
awesome! thank you sir. you're a gentleman and a scholar. 👍

**Comment by larrysalibra** [comment]
Fixed by #656 - thanks again @yknl for reporting this!
