### ISSUE TITLE
Status bar is clickable and scrollable when modal is open

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#642]
Steps to reproduce:

* While in on-boarding process, click wallet icon
* Use trackpad to scroll over while mouse is over status bar

<img width="1438" alt="screen shot 2017-07-21 at 10 36 18 pm" src="https://user-images.githubusercontent.com/597182/28468448-961fc950-6e65-11e7-80fa-88c3891e606f.png">

@guylepage3 Can we a full screen overlay that's one z-index below the modal while the modal is displaying? That would also solve the problem of users clicking on the icons (if they click on the icons, the app will navigate to the page, changing the address bar and displaying the "< Home Screen" prompt.)

**Comment by guylepage3** [comment]
@larrysalibra, are you still seeing this issue?

**Comment by larrysalibra** [comment]
Yes.

**Comment by larrysalibra** [comment]
To see the issue, you have to first click on one of the icons in the status bar *before* trying to scroll.

**Comment by guylepage3** [comment]
taking a look at this now..

**Comment by guylepage3** [comment]
>@guylepage3 Can we a full screen overlay that's one z-index below the modal while the modal is displaying? That would also solve the problem of users clicking on the icons (if they click on the icons, the app will navigate to the page, changing the address bar and displaying the "< Home Screen" prompt.)

@larrysalibra that did not work as our modals do not have a `z-index` between the background and the modal div itself. but instead I repositioned the modal to be `top: 0;` and then positioned the background image `background-position: top 34px center;`

complete.
