### ISSUE TITLE
Blank space around links in on-boarding modal shouldn't be clickable

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#643]
From #534 
@shea256 wrote:
> Accidentally clicking outside the email page will cause it to close. Also if you click to the left or right of the "Skip" button the email page will close. Neither of these things should happen.

@guylepage3 this looks like it's because the `<a>` tags in the modal are set to `display: block`.

**Comment by guylepage3** [comment]
correct. will fix.

**Comment by larrysalibra** [comment]
This is still broken in `feature/redesign`

**Comment by larrysalibra** [comment]
Fixed

**Comment by jeffreyrufino** [comment]
How do you install the browser ?
