### ISSUE TITLE
Add default profile feature

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#644]
Provide a mechanism for users to use a different profile for sign in with blockstack when they are prompted to approve a sign in request and from the list of profiles screen.

---
Users currently can have multiple profiles, but we have hardcoded authentication to use the first profile. As such, there's no way to sign in to a blockstack app with anything but the first profile.

<img width="1180" alt="screen shot 2017-08-11 at 12 14 42 am" src="https://user-images.githubusercontent.com/597182/29180411-54f7a87e-7e2a-11e7-8983-3337826d3920.png">

We'd like to add a mechanism to set a profile as the default profile on the above screen. The default profile is the one that will be used for authentication unless they override the choice.

We'd also like to give users the ability to choose another profile at sign in approval in the screen below and indicate what profile they're using to sign into the app:

<img width="433" alt="screen shot 2017-08-11 at 12 15 42 am" src="https://user-images.githubusercontent.com/597182/29180717-374e3e9a-7e2b-11e7-986b-7992b178d383.png">

**Comment by amaurymartiny** [comment]
3 questions:

- There's already a `current` field in `profiles.identity` redux state, which I assume denotes the current active profile. It has duplicate data as one of the `localIdentities`, so would it be a good idea to replace this `current` object into a `currentDomainName` string? That string would map to the corresponding `localIdentities` item. (No big deal, we leave that maybe for another PR).
-  I thought this `current` field was the one used in the Sign In Request modal, but actually as you said Larry it's hardcoded to use the 1st profile. So my question is: where is the `current` object used?
- Would we want to add another `default` field in the state, or do I update the `current` field when user chooses his default profile (issue title is pretty confusing on this)?

---

On the 3rd question: UX-wise, the main difference I see is the following. On the "Sign In Request" modal (screenshot above):

- If we have both `default` and `current` fields, on this modal, it would always be the default profile that shows up first (can be overridden). 
- If we only have a `current` field like now, every time this modal shows up, current profile shows up. If user chooses another profile in this modal, the current profile will be updated everywhere (including in the user settings). Should probably change wording Default->Current in this case.

**Comment by larrysalibra** [comment]
@amaurymartiny I believe the the `current` object is used to display the `currently` viewed profile `ViewProfilePage`. I agree this is confusing - I changed to issue title to be "default". 

> There's already a current field in profiles.identity redux state, which I assume denotes the current active profile. It has duplicate data as one of the localIdentities, so would it be a good idea to replace this current object into a current string? That string would map to the corresponding localIdentities item. (No big deal, we leave that maybe for another PR).

I'm not sure what the thinking was behind the way the current and ViewProfilePage is implemented.  You also don't need to change that as part of this issue.

> I thought this current field was the one used in the Sign In Request modal, but actually as you said Larry it's hardcoded to use the 1st profile. So my question is: where is the current object used?

> Would we want to add another default field in the state, or do I update the current field when user chooses his default profile (issue title is pretty confusing on this)?

We'd want a default state that is separate from the `current` object.


---

> If we have both default and current fields, on this modal, it would always be the default profile that shows up first. User can then choose another one to be current.

I see two options (let me know if I'm missing any):

1. Changing the profile at sign in also changes the default
2. Changing the profile at sign in doesn't change the default, but just the profile used for that particular sign in. To change the default, one has to go back to the profiles page and pick a new default.

Which one do you think makes more sense?

**Comment by amaurymartiny** [comment]
Thanks for the explanations!

I think 2 makes more sense.

**Comment by larrysalibra** [comment]
Thanks to @amaurymartiny this is done and will ship in the next release.
