### ISSUE TITLE
Make first profile large, others smaller

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#646]
Split from #632 

Background: The first profile is now auto-generated - this is be the "main" or current profile. This should be large and the primary focus of the profiles page.

Other profiles should essentially just be a smaller list of names.

**Comment by guylepage3** [comment]
@larrysalibra This should not be an issue but this should be executed instead... https://github.com/blockstack/blockstack-browser/issues/635

**Comment by larrysalibra** [comment]
@guylepage3 sounds good to me. Apologies about the duplicate issue.
