### ISSUE TITLE
Password & Authentication modals should have transparent background

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#647]
Right now the enter password dialog when creating a new profile and the authentication dialogs have the same photo background as the on-boarding process modals.

I think this should be transparent so users don't lose their context.

Also, it seems like the authentication modal styles are a bit off.

**Comment by guylepage3** [comment]
agreed. we will need a secondary modal created.

@larrysalibra can you generate a new modal and i'll follow up?
