### ISSUE TITLE
Make modals work well on small screens

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#650]
See #534 comments

**Comment by guylepage3** [comment]
@larrysalibra can you expand on this issue? I'm not sure what you mean.

**Comment by larrysalibra** [comment]
@guylepage3 this was from a conversation you, ryan and I had. Someone mentioned that we needed to make the modals work well on smaller screens and I believe you said it was as simple as adding additional media queries.

**Comment by wbobeirne** [comment]
Closing as stale
