### ISSUE TITLE
Better icons in the on-boarding process

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#651]
@shea256 
> Use icons that more effectively embody the steps in the onboarding process.

**Comment by shea256** [comment]
The ones on these screens work really well:

<img width="284" alt="screen shot 2017-07-23 at 12 51 55 pm" src="https://user-images.githubusercontent.com/994646/28501247-c1037202-6fa5-11e7-9d7e-d4191f812be2.png">
<img width="269" alt="screen shot 2017-07-23 at 12 51 58 pm" src="https://user-images.githubusercontent.com/994646/28501246-c103718a-6fa5-11e7-849e-1bd13ff4eebc.png">
<img width="276" alt="screen shot 2017-07-23 at 12 52 02 pm" src="https://user-images.githubusercontent.com/994646/28501245-c0f7d4ec-6fa5-11e7-8b9c-87f03963595e.png">

Would suggest just using these for now. I can provide the files.

**Comment by guylepage3** [comment]
@shea256 do you have the vector versions of these?

**Comment by guylepage3** [comment]
Please provide better description for what "better" means. Thanks.

**Comment by guylepage3** [comment]
let's remove the background image and change the background color to `rgba(255, 255, 255, 0.95)`

**Comment by yknl** [comment]
Proposed new on-boarding icons, let me know your thoughts.

**New internet**
![image](https://user-images.githubusercontent.com/29081231/30671524-6902f514-9e35-11e7-968d-ca826e497e54.png)

**Alternate for new internet**
![image](https://user-images.githubusercontent.com/29081231/30671547-8f061c14-9e35-11e7-8c07-0e1eac92ae00.png)

**Data control**
![image](https://user-images.githubusercontent.com/29081231/30671580-bee7a1c8-9e35-11e7-881d-87beaf307499.png)

**New Identity**
![image](https://user-images.githubusercontent.com/29081231/30671745-901c77fa-9e36-11e7-9ebf-dda50d86d5b0.png)

**Comment by guylepage3** [comment]
Nice @yknl! Let's reduce the title font-size by 10% and increase the `line-height` by `2px`?

**Comment by yknl** [comment]
This is with title `font-size` reduced and `line-height` increased
![image](https://user-images.githubusercontent.com/29081231/30674013-26efff7c-9e45-11e7-946b-690d3626f412.png)

**Comment by larrysalibra** [comment]
Much better!

**Comment by guylepage3** [comment]
Looks great @yknl
