### ISSUE TITLE
list afia app on blockstack browser

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#652]
shea256
>I had a discussion with Patrick to see if we could get Afia listed as a Blockstack app.He's in contact with them now and they're moving on getting the logo prepared with @guylepage3. @pstan26 Feel free to log any other updates.

**Comment by guylepage3** [comment]
![afia-logo-large](https://user-images.githubusercontent.com/1711854/28523046-a4fa709e-7048-11e7-9e1f-a920968c6c5f.png)

**Comment by larrysalibra** [comment]
Finished this last week.
