### ISSUE TITLE
add casa and openbazaar icons on the home screen

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#657]
Add the Casa and Openbazaar icons on the home screen.

**Comment by guylepage3** [comment]
![app-icon-casa-1024x1024](https://user-images.githubusercontent.com/1711854/28632686-5baa57a2-71ff-11e7-81be-ed06ce5ff7e9.png)

**Comment by guylepage3** [comment]
![app-icon-openbazaar-1024x1024](https://user-images.githubusercontent.com/1711854/28632727-7d31f7d6-71ff-11e7-9220-0ad1ae68f63b.png)

**Comment by guylepage3** [comment]
@estermer, here are the icons to be added. 😄

**Comment by estermer** [comment]
are there particular links you would like these apps to go to @guylepage3 ?

**Comment by guylepage3** [comment]
@larrysalibra @shea256 do you guys have links for Casa & Openbazaar?

**Comment by estermer** [comment]
and since i am there adding links are there any for OR and Guild?

**Comment by larrysalibra** [comment]
Finished and shipped last week.
