### ISSUE TITLE
Nothing happens on "Register" click

### ISSUE THREAD

**Issue by obleft** [blockstack/blockstack-browser#659]
I've signed up for one name and want to sign up for another but when I select an available name and click "register", nothing happens.
<img width="563" alt="screen shot 2017-07-31 at 10 05 25 am" src="https://user-images.githubusercontent.com/12475863/28784282-8e256618-75d8-11e7-88be-5f47c94f9158.png">

**Comment by larrysalibra** [comment]
@obleft are you trying to register a second name immediately after registering the first one? I think I know what's wrong, just want to make sure I'm on the right track.

**Comment by larrysalibra** [comment]
And thank you very much for reporting this @obleft !

**Comment by obleft** [comment]
@larrysalibra yup, it started immediately upon registering the first name.

**Comment by jackzampolin** [comment]
Closing as stale.
