### ISSUE TITLE
URI request couldnt be completed

### ISSUE THREAD

**Issue by cusmith1** [blockstack/blockstack-browser#661]
I'm attempting to create an app with sign-in through blockstack and I'm getting an Invalid sign in request upon redirect to the blockstack portal. Everything seems to be working except for one error message:
>ERROR: auth/store/auth.js: loadAppManifest: error URI request couldn't be completed

I've tried it with versions 12.0, 11.1/11.0, and 9.1 of the portal and get the same error trace. All other messages are just the typical debug/info messages. (Sanity check passes, etc.)

My manifest file follows the same format as the auto-generated hello blockstack one with only the start url changed (im using a different port). My first thought was that it wasn't finding the manifest file, but typing the same path that's used for the generation of the authentication request opens the file correctly in different browsers. I've also tried altering the start url (different ports, no port, full url) to no avail.

The only thing else I can think of that's much different from the hello-blockstack tutorial is that I'm redirecting to the blockstack sign-in from an iframe rather than a main window.

Apologies for posting here rather than the forum but i haven't been able to create an account despite trying for over a week.

**Comment by larrysalibra** [comment]
@cusmith1 it sounds like the CORS headers on your manifest.json file aren't set to allow all requests.

configuring your server to return these headers for `manifest.json` and any linked assets (image, etcL should do the trick: https://github.com/blockstack/blockstack-todos/blob/master/_headers

**Comment by jackzampolin** [comment]
Closing as stale.
