### ISSUE TITLE
decide on a name for the 12-word phrase that users have to remember

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#665]
Currently some options are:

- backup phrase
- identity key
- word key
- wallet key
- security phrase

Each of these has pros and cons. I will provide more of my notes on this shortly and we can start a discussion.

**Comment by Daniel-Wang** [comment]
I like the name `backup phrase` because that's what you use to restore an account and `phrase` since it really is a phrase of human readable words, versus keys which are associated with hashes and long non-human readable strings.

**Comment by guylepage3** [comment]
>backup phrase

works for me. simple and easy to remember.

**Comment by jackzampolin** [comment]
We have decided on Backup Phrase. Closing.

**Comment by guylepage3** [comment]
@jackzampolin did we decide on "backup phrase?"

cc: @shea256 @larrysalibra @yknl

**Comment by larrysalibra** [comment]
No, we haven't decided. Thanks for pointing this out @guylepage3

**Comment by shea256** [comment]
Going through the on-boarding language again:

- On Blockstack you’ll find apps that give you control over your data...
- Blockstack has no 3rd parties: a __ key/phrase on your device gives you access.
- Choose a password to protect your __ key/phrase.
- [ Create __ key/phrase ]
- Write down your __ key/phrase for account recovery - don’t show it to anyone
- Re-enter your __ key/phrase to confirm you've kept it in a safe place

Gotta make sure that what we settle on makes sense in this entire context.

**Comment by larrysalibra** [comment]
@shea256 “Secret recovery phrase” or “recovery phrase” seem to be the two leading options.

**Comment by shea256** [comment]
For this reason, I'm leaning towards "security phrase".

**Comment by shea256** [comment]
> @shea256 “Secret recovery phrase” or “recovery phrase” seem to be the two leading options.

Yes, but the only issue I had was with the sentences above. For example:

"Blockstack has no 3rd parties: a recovery phrase on your device gives you access."

I'm confused about why a recovery phrase gives me access. It sounds like it's only useful for recovery. Rather, we should be positioning this phrase like it's something that's always useful when it's on your device.

**Comment by shea256** [comment]
That said, if we can change the copy for that sentence then "recovery phrase" works well.

**Comment by jackzampolin** [comment]
I think `recovery phrase` or `backup phrase` seem good. They both give people the idea that this phrase is import for account recovery and they shouldn't lose it.

**Comment by larrysalibra** [comment]
'Recovery phrase' also doesn't work on these screens:
- Choose a password to protect your __ key/phrase.
- [ Create __ key/phrase ]

It makes sense to create an identity key. It doesn't make sense to "create a recovery phrase". The phrase `recovery phrase` raises the question, what does this phrase recover?

Some options:
* wallet
* keychain
* account

I'm leaning towards keychain.

**Comment by shea256** [comment]
@larrysalibra Great point.

Resurfacing "security phrase" for exactly this reason.

Think about it for a minute.

And then replace it in each of the contexts above.

**Comment by larrysalibra** [comment]
@shea256 "security phrase" works in the situations above.

<img width="336" alt="screen shot 2017-10-25 at 3 03 04 am" src="https://user-images.githubusercontent.com/597182/31962799-239ac49a-b931-11e7-914c-0ec2caf310ab.png">

"Backup Security Phrase" works as well.

"Remove Security Phrase" doesn't work as well - but it's not horrible.

**Comment by shea256** [comment]
Ohhhh I see what you mean @larrysalibra.

"Create a keychain" ... "Backup your keychain phrase" ... "Delete your keychain" ... "Choose a password to encrypt your keychain" ... "A keychain on your device gives you access"

"Create an account" ... "Backup your account phrase" ... "Delete your account" ... "Choose a password to encrypt your account phrase" ... "An account phrase on your device gives you access"

**Comment by shea256** [comment]
That's making me think "keychain phrase".

**Comment by jackzampolin** [comment]
I like naming it a single word. The 12 word phrase _is_ your wallet in certain context and it it simplifies the mental model. I do like `keychain`

**Comment by shea256** [comment]
One of the big pieces of feedback from people was something like:

"This is a bunch of words. That's not a key."

**Comment by larrysalibra** [comment]
The value of having the word "phrase" is that people will know it's a bunch of words. Calling it "keychain" has the same problem as key.

"This is a bunch of words. That's not a keychain."

**Comment by shea256** [comment]
Yes it can't be just "keychain". It has to have "phrase" in it.

**Comment by shea256** [comment]
@jackzampolin you even described it as "The 12 word phrase". Case in point ;)

**Comment by shea256** [comment]
Let's move forward and lock in "keychain phrase" unless anyone has any other comments.

**Comment by larrysalibra** [comment]
Using "keychain phrase" and "keychain" - see screenshots below:
<img width="423" alt="screen shot 2017-10-25 at 11 14 44 pm" src="https://user-images.githubusercontent.com/597182/32007272-b072fdb0-b9db-11e7-88c2-19551b5df904.png">
<img width="437" alt="screen shot 2017-10-25 at 11 12 42 pm" src="https://user-images.githubusercontent.com/597182/32007273-b0a4075c-b9db-11e7-839e-214742d26c1b.png">
<img width="439" alt="screen shot 2017-10-25 at 11 11 16 pm" src="https://user-images.githubusercontent.com/597182/32007274-b0fd7bb6-b9db-11e7-8905-c39606647676.png">
<img width="430" alt="screen shot 2017-10-25 at 11 10 50 pm" src="https://user-images.githubusercontent.com/597182/32007275-b12499d0-b9db-11e7-8d36-d47153fe9024.png">
<img width="450" alt="screen shot 2017-10-25 at 11 06 12 pm" src="https://user-images.githubusercontent.com/597182/32007276-b15ef9b8-b9db-11e7-8b59-d0c93f754b5b.png">
<img width="461" alt="screen shot 2017-10-25 at 11 06 04 pm" src="https://user-images.githubusercontent.com/597182/32007277-b18cb772-b9db-11e7-8cd8-027f67ec84d9.png">
<img width="814" alt="screen shot 2017-10-25 at 11 19 55 pm" src="https://user-images.githubusercontent.com/597182/32007307-c3bc8db4-b9db-11e7-9db8-78f85198b9f0.png">
<img width="901" alt="screen shot 2017-10-25 at 11 20 06 pm" src="https://user-images.githubusercontent.com/597182/32007312-c6532286-b9db-11e7-83b4-9fe22051a743.png">
<img width="432" alt="screen shot 2017-10-25 at 11 22 50 pm" src="https://user-images.githubusercontent.com/597182/32007314-c91da6ee-b9db-11e7-9f4d-cefca2a9381f.png">
<img width="900" alt="screen shot 2017-10-25 at 11 28 42 pm" src="https://user-images.githubusercontent.com/597182/32007483-42916bf0-b9dc-11e7-8991-6fc9e7ca9419.png">
