### ISSUE TITLE
Implement new name registration process

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#669]
See design in #370

**Comment by larrysalibra** [comment]
<img width="658" alt="screen shot 2017-08-17 at 6 20 19 pm" src="https://user-images.githubusercontent.com/597182/29408525-29733d66-837b-11e7-80ab-1dfae0ae1be4.png">
<img width="803" alt="screen shot 2017-08-17 at 6 20 35 pm" src="https://user-images.githubusercontent.com/597182/29408530-2d82d7b8-837b-11e7-997a-6bfa9dc1fe44.png">
<img width="767" alt="screen shot 2017-08-17 at 6 20 49 pm" src="https://user-images.githubusercontent.com/597182/29408532-2f99f356-837b-11e7-911b-79d8e1e3c4cd.png">
<img width="718" alt="screen shot 2017-08-17 at 6 34 42 pm" src="https://user-images.githubusercontent.com/597182/29408536-316059e6-837b-11e7-988a-cc976539e351.png">

Payment detection still needs to be tested. I'm not sure how to do that on regtest (would need to have an empty core wallet to start and another wallet with regtest bitcoins in it to send to the core wallet and pay for the name). @kantai is this possible on regtest?

In the mean time, I will live dangerously and test with real bitcoins.

I've broken the status page off into a separate issue:  #685

**Comment by kantai** [comment]
Yep, this is possible -- the most straight forward way to do it is to use the bitcoind cli wallet.

```
$ bitcoin-cli -conf=/tmp/bitcoin-regtest/bitcoin.conf getnewaddress
moZhY5yNFVrbtmvGzHsKP5GDj8jnXrDv32

$ bitcoin-cli -conf=/tmp/bitcoin-regtest/bitcoin.conf setaccount moZhY5yNFVrbtmvGzHsKP5GDj8jnXrDv32 testing_account

$ bitcoin-cli -conf=/tmp/bitcoin-regtest/bitcoin.conf listaccounts
{
  "": 12710.01148715,
  "testing_account": 0
}
```

Then you can withdraw from the test wallet (which starts with like 50 BTC) from the browser, or from the CLI:

```
$ BLOCKSTACK_TESTNET=1 BLOCKSTACK_DEBUG=1 BLOCKSTACK_CLIENT_CONFIG=/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.portal_test_env/client/client.ini blockstack withdraw moZhY5yNFVrbtmvGzHsKP5GDj8jnXrDv32
{
    "status": true, 
    "success": true, 
    "transaction_hash": "ea8521c4c9ea88d1219bbe836c7a0d7d1454cb7f9c8172cc285e28135304614a"
}
```

Then, to send from the bitcoind wallet back to your wallet in browser:

```
$ bitcoin-cli -conf=/tmp/bitcoin-regtest/bitcoin.conf sendfrom testing_account mvF2KY1UbdopoomiB371epM99GTnzjSUfj 0.01
fe4f97b2cba2740dd22f106c85ee0ca4850c1ea2762c16ef3372352f2bdb0a37
```

(those new name registration screens look awesome, btw!)

**Comment by kantai** [comment]
This will require figuring out the corresponding testnet address for the browser wallet address -- you can do that from the blockstack virtualenv python (or use a different reencoding tool)

```
$ venv/python -c "import virtualchain as vc; print vc.address_reencode('124saANX9kaQ3HkWEyy3rvf13gnc1hVEFF', network='testnet')"
mgapsDTVxn1epQE7xYwRgqsKugPK1xTUBK
```

**Comment by larrysalibra** [comment]
thanks @kantai - those instructions really helped!

I got stuck at:
```
$ BLOCKSTACK_TESTNET=1 BLOCKSTACK_DEBUG=1 BLOCKSTACK_CLIENT_CONFIG=/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.portal_test_env/client/client.ini blockstack withdraw moZhY5yNFVrbtmvGzHsKP5GDj8jnXrDv32
```
with a prompt to `Enter wallet password:`. What's the password for the regtest mode wallet?

**Comment by kantai** [comment]
Oops -- sorry about leaving that out:

password should be `0123456789abcdef`

**Comment by jackzampolin** [comment]
This has been included in the latest release. Closing.
