### ISSUE TITLE
Create new profile hangs after 2 wrong passwords

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#670]
Entering password wrong twice leaves the create new profile modal in an unusable state:

<img width="449" alt="screen shot 2017-08-04 at 7 16 52 pm" src="https://user-images.githubusercontent.com/597182/28966573-8b8d8e02-7949-11e7-8383-871bcf43e4fa.png">

Thanks to @jackzampolin for reporting.

**Comment by sieut** [comment]
Hi @larrysalibra, I'd love to work on this issue if you haven't started on it yet

**Comment by sieut** [comment]
@larrysalibra I opened a PR for the issue https://github.com/blockstack/blockstack-browser/pull/682

**Comment by larrysalibra** [comment]
Thanks for taking care of this @sieut ! Very happy to have you as a contributor!
