### ISSUE TITLE
rogue sparkle blockstack process stays running after exit and blocks updates

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#673]

**Comment by shea256** [comment]
Here's the process I'm seeing:

> /Users/x/Library/Caches/org.blockstack.mac/org.sparkle-project.Sparkle/Autoupdate.app/Contents/MacOS/Autoupdate /Applications/Blockstack.app /Applications/Blockstack.app 2524 /Users/x/Library/Caches/org.blockstack.mac/org.sparkle-project.Sparkle/Blockstack

**Comment by shea256** [comment]
Here's the Blockstack dashboard version I see:

<img width="1197" alt="screen shot 2017-08-10 at 11 02 47 am" src="https://user-images.githubusercontent.com/994646/29177002-85937ffe-7dbb-11e7-88ba-c83e28d3028e.png">

**Comment by shea256** [comment]
DM'ing logs separately.

**Comment by larrysalibra** [comment]
@shea256 if you follow our normal instructions to generate logs and then open `system_logs.logarchive` and search for `sparkle` you should (eventually) seem some results that might give us info about what happened:

<img width="1389" alt="screen shot 2017-08-10 at 11 13 04 pm" src="https://user-images.githubusercontent.com/597182/29178466-3a671054-7e24-11e7-9d10-67048ec102eb.png">

**Comment by shea256** [comment]
OK this just automatically fixed itself. A new update modal popped up and I updated the app and we're all set now. So unfortunately we may have trouble getting to the bottom of this.

**Comment by jackzampolin** [comment]
Closing as stale. Please reopen if applicable.
