### ISSUE TITLE
Blockstack browser portal should recognize the OS it was installed on

### ISSUE THREAD

**Issue by dgsus** [blockstack/blockstack-browser#675]
after installing on linux and connecting on localhost:3000 it was asking me to link my blockstack by going to an OSX menu (home).

thx in advance!

**Comment by pstan26** [comment]
@jackzampolin was this the same issue Dan Trevino was having that he
mentioned?

**Comment by jackzampolin** [comment]
No it was not.

**Comment by jackzampolin** [comment]
We have added protocol handlers for Linux and Windows with the respective installers. Closing this issue as complete.
