### ISSUE TITLE
Use packaged version of nexe

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#677]
I'm currently using a global version of nexe as part of the mac build process. We should use a packaged version instead so that people aren't confused as to what version to install.

```
Vanquish:blockstack-browser larry$ nexe -v
1.1.2
Vanquish:blockstack-browser larry$ node -v
v6.10.1
```

Thanks to @yknl for raising this issue with me on slack.

**Comment by jackzampolin** [comment]
A couple of steps here:
- `npm install --save nexe`
- Patch these two files to point to the `node_modules` version of `nexe`
  * https://github.com/blockstack/blockstack-browser/blob/develop/gulp/tasks/compileBlockstackProxyForMac.js#L6
  * https://github.com/blockstack/blockstack-browser/blob/develop/gulp/tasks/compileCorsProxyForMac.js#L6

**Comment by larrysalibra** [comment]
would want to do `npm install --save-dev nexe` since we don't want that included in the app bundle for production, just for development.

**Comment by larrysalibra** [comment]
Thanks @dantrevino!
