### ISSUE TITLE
Set production subdomain or disable

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#686]
We'll need to set our production subdomain in the browser before the next release or disable subdomain support.

Currently I've hard coded `foo.id` and the regtest subdomain registrar endpoint.

Will also need a way to change registrar endpoints for regtest.

**Comment by kantai** [comment]
Looks like we are delaying subdomain support in browser for this sprint.

**Comment by larrysalibra** [comment]
Adding subdomains is now disabled.
