### ISSUE TITLE
Duplicate profile

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#687]
I'm seeing a duplicate profile. Need to investigate if a bug was introduced.

<img width="1166" alt="screen shot 2017-08-17 at 7 14 19 pm" src="https://user-images.githubusercontent.com/597182/29409776-5b5e97ee-8380-11e7-9f56-0605b86cd794.png">

**Comment by jackzampolin** [comment]
This is fixed in the current version. Closing.
