### ISSUE TITLE
Separate name registration search & results modal

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#689]
@guylepage3 had a meeting and decided to split the searching and results from the screen below into two separate views in the modal:

<img width="658" alt="screen shot 2017-08-17 at 6 20 19 pm" src="https://user-images.githubusercontent.com/597182/29414858-ab4918e8-8393-11e7-8ff3-932461d61d8b.png">

**Comment by larrysalibra** [comment]
@guylepage3 I separated search and results into separate modal "pages" as we discussed.
I extracted these into their own components so that they are easier to work with as well.

I also took a stab at simplifying the results screen. Please see the results below:

<img width="646" alt="screen shot 2017-08-18 at 6 02 13 pm" src="https://user-images.githubusercontent.com/597182/29457447-c8ccac54-844c-11e7-9888-725afacb4f7d.png">
<img width="636" alt="screen shot 2017-08-18 at 6 02 43 pm" src="https://user-images.githubusercontent.com/597182/29457451-ca421cb8-844c-11e7-9570-c2282dc1e2c2.png">

Would love your and @shea256 's feedback.

**Comment by guylepage3** [comment]
Nice work here @larrysalibra! 👍 I will be finishing this up today/tonight
