### ISSUE TITLE
The registered id disappeared

### ISSUE THREAD

**Issue by omaks** [blockstack/blockstack-browser#691]
@larrysalibra 
I registered moment.id. After that there was pending status but my username changed to moment.id. Then I changed my profile photo and went to go Guild app from home screen, clicked sign in and approve. And then the registered id is disappeared and there is no photo too. But the fee was taken from my wallet. Also if you try to register this id now, you'll see "moment.id has already been registered." but if you search moment.id, you'll see "No results found".

macOS Sierra, version 10.12.6
Safari, version 10.1.2 (12603.3.8)
Blockstack, version 0.13.0

**Comment by larrysalibra** [comment]
Thank you for the very detailed bug report @omaks !

It looks like we might be dealing with a couple issues here:

The first issue is that our explorer and search servers don't currently reflect updated name as quickly as our the browser does. This is something we can improve in the future. As of now, it `moment.id` along with your profile and picture are appearing the network for me. You can check it out on the explorer here: https://explorer.blockstack.org/name/moment.id

The second issue is that in the currently released version of the browser, we don't do a very good job of communicating what's going on during name registration and explaining what's happening after you submit the registration. We have some progress on that front that will ship on Monday (#669 #689) and hopefully will have a name registration status shipped ~2 weeks after that (#685)

A third issue is that we don't have a clearly communicated story for app developers as to what they should do during the period when a user has submitted a name registration and before the name registration has completed processing by the network. 

What happens now is that users logging in to apps with "pending" names send the name they are claiming to apps. Their profile (including photo) is also sent as part of the sign on process. Verification of their claimed name will fail until the network processes the name. Apps that choose to retrieve user profile information independently of what is claimed by the user (ie. the app does a look up on the name and tries to retrieve the profile (including photo)), will fail to retrieve the profile data until the name registration has been processed.

I'll open github issues about the first and third issues in a bit.  In the meantime, now that your name registration has been fully processed, can you try logging into an app again?

Thanks again for taking the time to submit this issue and your patience!

**Comment by omaks** [comment]
Thanks @larrysalibra for the detailed explanation!

Now I have two profiles: the first one is for which I registered moment.id and the second one is moment.id

I clicked to sign in for Guild app again and then I clicked to approve but nothing happened. The sign in request form was not disappeared. And it disappeared only when I clicked next to the form.

**Comment by jackzampolin** [comment]
This has been fixed in the latest versions of the browser and is a compound of a couple of different issues. If this is still a problem on the latest version please reopen this issue, otherwise closing as stale.
