### ISSUE TITLE
new developer mode macOS dropdown menu

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#699]
Now that we are going in the direction of a native macOS dropdown menu for the blockstack browser, how will developers jump into "developer mode?"

One way we could do this is by adding a "developer mode" option in settings.

**Comment by bmcqueen** [comment]
Yes, please.  I hit this one today.  I see nothing on "Option-click the Blockstack".

I guess updating the Readme with a workaround would be good enough.  I'll do that if somebody tells me the workaround.

**Comment by guylepage3** [comment]
@larrysalibra I'm pushing this into backlog as we do not have webkit in place as of yet. Might be something to consider for Sprint 0.17.
