### ISSUE TITLE
Sort social proof lists in consistent order

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#709]

**Comment by jackzampolin** [comment]
One way to accomplish this would be to sort them before they are set to the state in this file:

https://github.com/blockstack/blockstack-browser/blob/develop/app/js/profiles/store/identity/actions.js#L78-L79

**Comment by dashaxiong** [comment]
Hi @larrysalibra and @jackzampolin - I have made some progress on this by sorting the Social Proofs alphabetically. Is this sufficient? Screenshots below show the result of the change in the profile screen. 
Placeholders only:
![placeholders](https://user-images.githubusercontent.com/1290185/42983829-17e475c2-8c28-11e8-8ade-81c401d93512.png)
Filled Accounts and Placeholders:
![filledaccountsandplaceholders](https://user-images.githubusercontent.com/1290185/42983845-31d81ede-8c28-11e8-8861-0daa08d734de.png)
Filled Accounts, Placeholders, and Hidden Accounts:
![filledaccountsplaceholdersandhiddenaccounts](https://user-images.githubusercontent.com/1290185/42983853-3e0f2c7e-8c28-11e8-8ceb-9dc6672f9b04.png)

**Comment by larrysalibra** [comment]
Oh wow! Thanks for the pull request @dashaxiong ! - @jeffdomke who is now leading product for the browser would be the one to make the call on this.

**Comment by craigiansmith** [comment]
A revised PR is at #1634 :grin:

**Comment by larrysalibra** [comment]
Thanks @craigiansmith - I've asked @yknl to review your PR!
