### ISSUE TITLE
design new support button on Home Screen

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#710]
Design a new support button that will appear on the Home Screen and takes users to support.

**Comment by guylepage3** [comment]
out of scope for this sprint.. moving to https://github.com/orgs/blockstack/projects/8

**Comment by larrysalibra** [comment]
I think @yknl did this already. Please re-open if we need a new one!

**Comment by guylepage3** [comment]
We could use a new one but it's not important at the moment. Let's close this one out.
