### ISSUE TITLE
ui build typography from new browser design

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#714]
UI build typography of new browser design

Designs
- https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-325353544)

**Comment by guylepage3** [comment]
Attack hack plan..

Define and execute typography
- [ ] Within the latest sketch files, define `<h1-6>`tags, `lead` tags, `caption` and `<p> tags
- [ ] Build out `<h1-6>`tags, `lead` tags, `caption` and `<p> tags including margin/padding

**Comment by guylepage3** [comment]
complete
