### ISSUE TITLE
ui build new design forms

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#715]
UI build forms of new browser design

Designs
- https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-325353544)

**Comment by guylepage3** [comment]
Define all possible form styles.

DO NOT BUILD OUT EACH FORM STYLE. Just build what's needed today

- [ ] `default` forms
- [ ] `electric-blue` forms
- [ ] `light-blue` forms

**Comment by guylepage3** [comment]
complete.

<img width="702" alt="screenshot 2017-09-06 17 14 19" src="https://user-images.githubusercontent.com/1711854/30134907-d9d34f1a-9326-11e7-9546-a88792b96a9d.png">
