### ISSUE TITLE
ui build buttons of new browser design

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#717]
UI build buttons of new browser design

Designs
- https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-325353544)

**Comment by guylepage3** [comment]
Looks like Mark and team at Bootstrap have implemented some of the button items we recommended. Fits in nicely with our `.btn` styles. 😄 

https://getbootstrap.com/docs/4.0/components/buttons/

**Comment by guylepage3** [comment]
complete
