### ISSUE TITLE
move save + view profile button into individual social proofs

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#725]
Move the "save + view profile" button into individual social proofs and remove it from the edit profile view.

<img width="400" alt="screenshot 2017-09-05 15 15 03" src="https://user-images.githubusercontent.com/1711854/30079155-4b3647aa-924d-11e7-915c-e8d2b13c6e2e.png">

**Comment by yknl** [comment]
Should probably add a back button to go back to the profile once the Save + view profile button is removed.
