### ISSUE TITLE
Create secondary nav bar for new design

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#728]
Create secondary nav bar component that appears below the main nav

<img width="400" alt="/" src="https://user-images.githubusercontent.com/29081231/30087675-fa5998dc-926f-11e7-9235-a20f98d09896.png">

**Comment by guylepage3** [comment]
@yknl please use the `btn btn-link` button set for the secondary navbar. Also, keep in mind that we will not be having a "title" for each page as it gets confusing. Let's start building this out on the latest `develop` branch.

**Comment by guylepage3** [comment]
also, let's use the latest profile design.

![browser-macos-40a-profile-d16 2x](https://user-images.githubusercontent.com/1711854/30112562-c8f34dcc-92df-11e7-93d7-2556116d8171.png)
