### ISSUE TITLE
Improve account restoration process to automatically restore multiple names

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#729]
Currently, the account restoration process only restores the first identity address and name. We should search through a reasonable number of addresses and restore all of the addresses that have names at restoration time.

**Comment by vsund** [comment]
Trezor requires a wallet to be filled before you can add another one. Therefore they can check whether a wallet contains anything and only if proceed with the next one.
I think we could do something similar. E.g. if your profile contains an empty zone file you cannot create another one. When restoring then simply restore everything until the first unfilled profile appears.

**Comment by wbobeirne** [comment]
Closing this in favor of #1550 which has more recent discussion.
