### ISSUE TITLE
Live design All Avatars view

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#736]

**Comment by yknl** [comment]
Quick update to design for now
![image](https://user-images.githubusercontent.com/29081231/30282003-fb09664c-96e1-11e7-836c-b0b3b2ad412e.png)

**Comment by guylepage3** [comment]
@yknl Let's keep with the cards for now on the list view of all avatars. Let's just align things and change the colors of the links. That's too drastic of a change for something that will not be used very much. Also, we have much more pressing items to take care of before going that detailed on the avatar list view.

**Comment by guylepage3** [comment]
hey @yknl i'll take this one on. will be very quick for me to handle.

**Comment by guylepage3** [comment]
complete.
