### ISSUE TITLE
Blockstack todo broken while ID pending

### ISSUE THREAD

**Issue by dhealy05** [blockstack/blockstack-browser#737]
Signing in to Blockstack todo (both from home screen and the tutorial build) throws this error: 

core.blockstack.org/v1/names/guidebot.id Failed to load resource: the server responded with a status of 404 (NOT FOUND)

and redirects to the same Sign In screen. I am guessing this is because I registered my ID just before trying it so it is still "pending".

**Comment by jackzampolin** [comment]
We have changed this behavior in the latest release. You can now sign into apps without a name. If this is still an issue please reopen. Closing.
