### ISSUE TITLE
Status Bar Documentation v4

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#738]
Update status bar documentation as status bar has changed.

----

Reference:

**Status Bar Documentation**
[#344: Status Bar Documentation v2](https://github.com/blockstack/blockstack-portal/issues/344)

Based upon status bar redesign here:
- [#484: redesign status bar (based on new home screen status bar](https://github.com/blockstack/blockstack-portal/issues/484)

Originated from the design and ui build of the status bar in these to issues.
- [design return to home screen & app home standards](https://github.com/blockstack/blockstack-portal/issues/272)
- [ui build of the staus bar](https://github.com/blockstack/blockstack-portal/issues/340)

**Comment by larrysalibra** [comment]
Should this stay open?

**Comment by guylepage3** [comment]
@larrysalibra Let's leave this one open as this is something that is in the Design System list at the moment.

**Comment by wbobeirne** [comment]
As far as I can tell, the status bar isn't really a thing anymore. Closing.
