### ISSUE TITLE
add confirmation screen when removing account

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#744]
Add a confirmation screen that clearly communicates that the user's account is being deleted, that they need their backup phrase, etc.

<img width="668" alt="screenshot 2017-09-11 15 21 04" src="https://user-images.githubusercontent.com/1711854/30292638-f0b33542-9704-11e7-904f-e0f076ebb94f.png">

**Comment by kkomaz** [comment]
Will take a look into this 👍

**Comment by guylepage3** [comment]
completed by @kkomaz
