### ISSUE TITLE
Story: Remove payment key from core

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#749]
A user's payment key should not be stored in core but instead derived from the browser's 12 word backup phrase.

 issues:
- #730

**Comment by shea256** [comment]
Very excited to see this.

**Comment by larrysalibra** [comment]
This is done and merged into develop. It will be included in the next release.

See comments: https://github.com/blockstack/blockstack-browser/issues/730#issuecomment-333906533
