### ISSUE TITLE
Story: Windows app

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#750]
Users should be able to easily use Blockstack on Windows.

**Comment by kantai** [comment]
Alpha windows installer:

http://packages.blockstack.com/repositories/windows/BlockstackToolbox.exe

**Comment by larrysalibra** [comment]
We have windows app (yay!) - still need to make sure that the windows app gets included into our release process.

**Comment by kantai** [comment]
See issue #806 for including the windows app and the linux app into the release process.

**Comment by larrysalibra** [comment]
This is done and shipped in the v0.16.0 release. Please try it out! https://github.com/blockstack/blockstack-browser/releases/tag/v0.16.0

**Comment by shea256** [comment]
This is very exciting.

Let's make a note to update the install/downloads page @larrysalibra @guylepage3.

**Comment by guylepage3** [comment]
@shea256 Let me add that to the list for tomorrow's push of the site.
