### ISSUE TITLE
Story: multi-reader storage

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#752]
Issues:
- https://github.com/blockstack/blockstack-browser/pull/739

**Comment by larrysalibra** [comment]
We're dropping this until further notice.

**Comment by larrysalibra** [comment]
@kantai Is going to take a look at this today and make a final call

**Comment by shea256** [comment]
Update: we're making the final call on this today.

**Comment by larrysalibra** [comment]
Because of the large number of changes that multi-reader storage makes, we've decided to maintain multi-reader storage as a parallel branch until we're comfortable with merging it.

Related code is in`feature/multi-reader-storage` branches of the respective repositories:
https://github.com/blockstack/blockstack-storage-js/tree/feature/multi-reader-storage
https://github.com/blockstack/blockstack-browser/tree/feature/multi-reader-storage
https://github.com/blockstack/blockstack.js/tree/feature/multi-reader-storage
https://github.com/blockstack/blockstack-core/tree/feature/multi-reader-storage

I've made releases of our javascript libraries to npm to make it easier to test:
* blockstack-storage: v0.3.0-multi-reader-storage.alpha.1
* blockstack: v0.10.0-multi-reader-storage.alpha.1

Tests are currently not passing on the 3 javascript repos. Most of this is due to lint, some of this is due to automated tests that haven't been refactored or updated to take into account these changes.

While we're going to hold off on shipping this so that we can test it more, I encourage others to try it out.

@kantai do we need to change anything in your instructions on https://github.com/blockstack/blockstack-browser/pull/833#issue-261335039 to get this all up and running on docker with the new locations?

**Comment by muneeb-ali** [comment]
Great to have the ability to test this separately. 

+1 on hold the merge until a later release. The next release of the product should optimize for stability and code that has been running in the wild for a bit.

**Comment by larrysalibra** [comment]
Holding off on this until after the token distribution.

**Comment by randyl2004** [comment]
just out of curiosity; do we have any updates or an ETA on multi-reader storage or Gaia v2?
