### ISSUE TITLE
Replace existing icons within the default apps with custom ones

### ISSUE THREAD

**Issue by field2** [blockstack/blockstack-browser#757]
Design a custom icon set, built exclusively for Blockstack. This will improve visual consistency across demo/whitelabeled apps. I'll get started by posting screenshots of a few key app views with new icons replacing old ones.

**Comment by guylepage3** [comment]
This is awesome @field2. I'm really liking the cleanliness of the instagram and facebook iOS mobile app navbar icon designs...

We need to keep in mind that the icons need to be both outline as well as solid.

<img width="400" alt="ios-navbar-facebook" src="https://user-images.githubusercontent.com/1711854/30395866-a89ab252-9895-11e7-9530-5fdf4bb9e1e1.jpg">

<img width="400" alt="ios-navbar-instagram" src="https://user-images.githubusercontent.com/1711854/30395867-a8a09eba-9895-11e7-8249-798c70c3e3f7.jpg">

**Comment by field2** [comment]
Thanks for the reference, and I'm designing both outline and filled. I'd like to build on a 9-pixel base, so they'd be crisp (aligned to the pixel grid) at 9x9, 18x18, 27x27, etc. I'm finding 16 pixel base icons to be limiting, as they don't have a centered horizontal/vertical column and icons with components like + , - and X have to be designed off center. What do you think?

**Comment by guylepage3** [comment]
hey @field2 let's use one GitHub issue for the icons. In hind sight we should not have opened this issue until the icon set design has been defined. Closing this issue and moving comments here: https://github.com/blockstack/designs/issues/419
