### ISSUE TITLE
Add "create username" on default profile

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#768]
Add "create username" button between "view publicly" and "+ create" buttons on default profile

<img width="1035" alt="screenshot 2017-09-14 15 47 38" src="https://user-images.githubusercontent.com/1711854/30452905-31dde38e-9965-11e7-9f5d-6b6094146c78.png">

**Comment by yknl** [comment]
Would it make more sense to add a "create username" button/link near the owner address hash which is beneath the profile photo? 

As a new user, I think I might be confused what that string of random characters is. It might be helpful to add a (?) symbol beside it. When clicked, this can show a little help bubble explaining the hash and that they have the option to add a username.

**Comment by guylepage3** [comment]
@yknl the above looks good and makes sense. let's go with that. 👍
