### ISSUE TITLE
Icons on home screen need centering

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#775]
In a 392px x 650px webview, the icons aren't centered:

<img width="464" alt="screen shot 2017-09-15 at 6 07 28 pm" src="https://user-images.githubusercontent.com/597182/30479923-7e6f3ebe-9a41-11e7-9e6b-5e10ca2ff1fb.png">

**Comment by guylepage3** [comment]
Adding more detail in issue name. Thanks for the find @larrysalibra 😄

**Comment by guylepage3** [comment]
complete
