### ISSUE TITLE
missing "restore account" in settings

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#776]
Unable to restore my account as it is missing in the settings view.

System:
- Blockstack is running
- on branch `feature/redesign`

Is currently working on branch `develop`

<img width="474" alt="screenshot 2017-09-15 07 35 00" src="https://user-images.githubusercontent.com/1711854/30480611-938dd714-99e8-11e7-97d3-942df7363a24.png">

**Comment by larrysalibra** [comment]
To restore a different account:

1. Remove your account
2. Restore your account from the link in the on-boarding screen

**Comment by guylepage3** [comment]
@larrysalibra what is the reasoning we are doing it this way? was there an issue created for this?

**Comment by larrysalibra** [comment]
Can you think of a better name than "Remove Account" for this? 

Apple calls it "reset" on their phone.

1. reset your phone
2. restore phone from icloud/itunes backup

We could call it "Reset Browser"

**Comment by larrysalibra** [comment]
We changed it last sprint to fix the problems people were having with restoring their accounts. They need to go through the on-boarding process to set the browser state up properly.

**Comment by guylepage3** [comment]
@larrysalibra the user has a password that is associated with the "account" though. So I feel @shea256 got this right here. Unless we go the route of not having a password? Which would be a better experience.

**Comment by guylepage3** [comment]
>We changed it last sprint to fix the problems people were having with restoring their accounts. They need to go through the on-boarding process to set the browser state up properly.

Ahh.. Gotcha. are we killing the password then?

**Comment by larrysalibra** [comment]
> Ahh.. Gotcha. are we killing the password then?

We're not killing the password. They pick the password during on-boarding. It is used to encrypt their identity key in the browser. Nothing changes with that.


In the copy, I tried to make it clear why a user would want to remove their account -> that they can create a new account or restore another one after removing it. Happy to entertain any improvements in copy!

<img width="954" alt="screen shot 2017-09-15 at 6 44 39 pm" src="https://user-images.githubusercontent.com/597182/30480842-09567192-9a46-11e7-9f9d-c9ac192ee3b0.png">

**Comment by larrysalibra** [comment]
We can review the account removal and restoration process in the future and really optimize the experience. At the moment, given all of the things we have on our plate, I don't think it is a priority.

**Comment by guylepage3** [comment]
I feel that being able to restore one's account is pretty critical for confidence of the browser. I think we've discussed this a few times in our weekly meetings.

Naming however, is not so important at the moment. Let's use what we have been using for now. "Restore Account," then tackle the more important things and then come back to the verbiage.

I strongly feel that we should have a "Restore Account" process within the browser so that users do not feel trapped. It's quite difficult to explain to someone that they need to first delete their account and then restore from on-boarding. That's something that is hard to convey and have the user execute. It adds a ton of friction. 

As a user, I would consider dropping off at that point.

Thoughts?

**Comment by larrysalibra** [comment]
>  It's quite difficult to explain to someone that they need to first delete their account and then restore from on-boarding. That's something that is hard to convey and have the user execute. It adds a ton of friction.

It's the same process Apple uses for restoring your iPhone. Users are used to it.

1. Tap Reset
2. Tap Erase All Contents and Settings
3. Arrive back at beginning of on-boarding process
4. Tap "Restore iPhone from iTunes/iCloud backup.

**Comment by guylepage3** [comment]
@larrysalibra I just spoke with @shea256 about this issue. he explained to me what was happening and that syncing is coming in the future. I got it. We're really pushing users to not have to ever restore an account.

Definitely see that we will need to work on verbiage in the future for this. Do you have a future issue open for this?

**Comment by yknl** [comment]
I think this is more like merging the "Delete Account" and "Restore Account" into one single action. It makes sense to me but we should definitely be using verbiage closer to something like "Reset".

**Comment by guylepage3** [comment]
We're no longer going with a restore account in the settings area. closing issue.
