### ISSUE TITLE
allow form submission upon hitting "return/enter" key on all forms

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#778]
Allow form submission upon hitting "return/enter" key on all forms. 

See https://onename.com/login for an example.

**Comment by yknl** [comment]
@guylepage3 This feature has been implemented in e44e7a6c10a524fdbc92b33740525bf98cd1ab2b.
Let me know if you spot any forms where this doesn't work.

**Comment by guylepage3** [comment]
It's not working on quite a few @yknl. Such as the on-boarding screens.

**Comment by yknl** [comment]
That's strange, the on-boarding screen forms appear to be working for me on the latest of `feature/redesign` branch.

**Comment by guylepage3** [comment]
@yknl.. seems to be solved. closing issue. 👍
