### ISSUE TITLE
restore account does not seem to be working

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#779]
I have Blockstack running, entered my identity key and password and then clicked enter and nothing happened.

<img width="586" alt="screenshot 2017-09-15 08 37 46" src="https://user-images.githubusercontent.com/1711854/30482503-531d9bf2-99f1-11e7-875a-807a9f87dbbc.png">

**Comment by larrysalibra** [comment]
I'll take a look at this for you right now!

**Comment by larrysalibra** [comment]
@guylepage3 

I tried restore in both the `develop` and `feature/redesign` branches and I can't seem to replicate the problem. (restore works on my browsers for me)

Can you share the output in your javascript console? That might give us some clues as to what is happening.

**Comment by larrysalibra** [comment]
This works for both @yknl & me. Please open a new issue if it is still happening.
