### ISSUE TITLE
settings/storage blinks upon going from dropbox back to browser

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#781]
Noticed that there is a weird glitch that appears upon on-boarding...

When a user is on the Dropbox connect page and then clicks on the button to choose the Dropbox account that they would like to use for storage they are quickly taken to the Settings/Storage page for 3 milliseconds and bounce to the home screen.

Feels rather startling as a user.

**Comment by larrysalibra** [comment]
Since it looks like we are switching to the Gaia hubs and migrating away from dropbox, we're going to hold off on this for the moment.

**Comment by larrysalibra** [comment]
@guylepage3 I've taken a stab at addressing the blinking issue when connecting storage.

It's not 100% ideal, but I feel it's an improve. Let me know what you think!

Thanks again for reporting this!

**Comment by guylepage3** [comment]
Thanks @larrysalibra taking a look now

**Comment by guylepage3** [comment]
hm. no glitch but now i cannot move past the "App data is stored in the storage provider of your choice" screen..

<img width="1438" alt="screenshot 2017-10-04 15 55 09" src="https://user-images.githubusercontent.com/1711854/31196626-69893d8a-a91c-11e7-8691-e216970f5e0b.png">

**Issue:**
When I click "Choose your storage provider" and then "Dropbox" can then click "Personal", I get taken back to the "App data is stored in the storage provider of your choice" screen

**Comment by larrysalibra** [comment]
We're no longer using dropbox.
