### ISSUE TITLE
all long "digital keys" that breakage on social proofs require ellipsis & tooltip

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#784]
PGP key is too long and requires either ellipsis where that appears at a certain min-width with a tooltip hover state that shows the full PGP key when the user hovers over the shortened PGP key.

<img width="399" alt="screenshot 2017-09-15 15 21 21" src="https://user-images.githubusercontent.com/1711854/30500477-79ecf756-9a2c-11e7-8820-8da4a9b41b24.png">

**Comment by freethejazz** [comment]
The SocialAccountItem component deals with this issue in JavaScript currently (https://github.com/blockstack/blockstack-browser/blob/master/app/js/profiles/components/SocialAccountItem.js#L58).

There's a CSS only way of dealing with this issue as well, did you all explore that at all? Either way, my thought would be to create an ellipsized text component that takes a string length or pixel width and handles it for you. This would be something that could be backported for use within the SocialAccountItem and really anywhere else where long strings compete with horizontal space.

It would look something like:
`<Ellipsized maxLength={15} tooltip={true}>{props.potentiallyLongField}</Ellipsized>`
and via the js approach would render to something like:
`<span title="my full long property value that's too big">my full long pro...</span>`

How does that sound?

**Comment by yknl** [comment]
I think the issue with setting a `maxLength` is that the screen width can change depending on the platform the browser is being run on. Maybe a responsive css-based approach would be better.

**Comment by guylepage3** [comment]
@freethejazz @yknl let's definitely not use Javascript here. This is easily solvable with CSS. We are already doing this everywhere else. Let's keep with what we've been doing on the other social proofs.

```
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
```
