### ISSUE TITLE
Add additional profile functions

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#790]
In #789, we rearranged the profile tab to make it easier for users to understand. As of this we removed the "advanced" and "view publicly" options.

This issue is to discuss how we can add those back in in the future.

**Comment by larrysalibra** [comment]
One common method of adding secondary functions is through the use of the ellipsis or "more options" menu:

<img width="137" alt="screen shot 2017-09-18 at 11 29 37 am" src="https://user-images.githubusercontent.com/597182/30529666-e46a4d60-9c69-11e7-8441-2bd3c749dd99.png">
<img width="639" alt="screen shot 2017-09-18 at 12 02 07 pm" src="https://user-images.githubusercontent.com/597182/30529667-e6d0c854-9c69-11e7-92b2-6446191cffcc.png">

**Comment by guylepage3** [comment]
Definitely love the idea of hiding features away. Great user feedback here. Thank you. 😄

**Comment by larrysalibra** [comment]
As part of this we'll need to enable browser wallet key payment for the advanced functions which currently use the core wallet for payment.

**Comment by wbobeirne** [comment]
I don't think this interface exists as depicted anymore. Closing.
