### ISSUE TITLE
Documentation should reflect new project name

### ISSUE THREAD

**Issue by freethejazz** [blockstack/blockstack-browser#792]
In the README, there are a bunch of stale references to `blockstack-portal` when the repository at some point was renamed `blockstack-browser`. GitHub will do all the redirects properly, so the difference doesn't seem to have technical problems, but it is a reflection of out of date documentation. Out of date docs can be confusing to new users and generally "smells".

I'm happy to go through and make the updates if you all agree that this should be done.

**Comment by guylepage3** [comment]
hey @freethejazz.. good catch and yes. that would be awesome if you could go through it and do a pull request. we are just about to do a major release. could you pull from the `feature/redesign` branch? 😄

**Comment by freethejazz** [comment]
Will do @guylepage3. One question is regarding a reference in the code. My assumption is that this service's URL hasn't been updated, but I wanted to make sure: https://github.com/blockstack/blockstack-browser/blob/master/app/js/account/store/account/actions.js#L160

**Comment by guylepage3** [comment]
>One question is regarding a reference in the code. My assumption is that this service's URL hasn't been updated, but I wanted to make sure: https://github.com/blockstack/blockstack-browser/blob/master/app/js/account/store/account/actions.js#L160

Not sure.. cc: @larrysalibra @jcnelson @kantai

**Comment by larrysalibra** [comment]
Yes - that url should remain the same. Thanks @freethejazz @guylepage3 !

**Comment by freethejazz** [comment]
👍 In that case, the PR is ready to merge. Good luck on the rest of your prep work for the release, and I'm happy to help out on chores or front-end stuff if you need a hand.

**Comment by larrysalibra** [comment]
Closing this thanks to @freethejazz 's pull request which updated the old name references. This will ship in 0.16.
