### ISSUE TITLE
update tooltips

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#794]
Update tooltips to match design

<img width="502" alt="screenshot 2017-09-18 15 31 38" src="https://user-images.githubusercontent.com/1711854/30560637-8991ba46-9c86-11e7-8816-9a5d5a45eb09.png">

**Comment by guylepage3** [comment]
@kkomaz want to update the tool tips to match the layout below?

![browser-macos-40b-profile-d16 2x](https://user-images.githubusercontent.com/1711854/30564895-78114dc8-9c94-11e7-97e9-0c1def9dc3e6.png)

Sketch file is located here: https://github.com/blockstack/designs/blob/master/browser/browser-macOS-40-profile-d16.sketch

**Comment by kkomaz** [comment]
@guylepage3  Just so no one else starts on this...
https://github.com/blockstack/blockstack-browser/pull/800

**Comment by guylepage3** [comment]
Thanks @kkomaz 👍

**Comment by guylepage3** [comment]
complete. thanks again @kkomaz 😄
