### ISSUE TITLE
Review form input fields

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#801]
It's hard to see where you're supposed to type text:
<img width="1172" alt="screen shot 2017-09-19 at 6 59 56 pm" src="https://user-images.githubusercontent.com/597182/30589392-c885f532-9d6c-11e7-92c8-152294e9941a.png">

**Comment by kkomaz** [comment]
I can take a look at this @guylepage3

**Comment by guylepage3** [comment]
@kkomaz we will need to do some design thinking here as it will affect the entire app. How comfortable are you with designing in Sketch?

**Comment by kkomaz** [comment]
@guylepage3 

Probably need to pass on this one until design specs are created.  Not that comfortable with sketch.  😅

**Comment by guylepage3** [comment]
@kkomaz no worries.. if you see anything else you'd like to tackle, let @yknl or myself know. :)

**Comment by larrysalibra** [comment]
I'm still having trouble with the input fields.

They don't look obviously like input fields to me. This confused me when I was editing my description - I didn't really I was still in edit mode (because i clicked out of the input field and the border disappeared) and was confused when my edits were saved.

<img width="868" alt="screen shot 2017-10-28 at 11 35 35 pm" src="https://user-images.githubusercontent.com/597182/32136049-3e2411ba-bc3b-11e7-82a4-546e5e58c91f.png">

**Comment by guylepage3** [comment]
Thanks @larrysalibra. @yknl and I are working on UX/UI adjustments that will address this issue. Adding this as a note in the current UX/UI document. Closing issue
