### ISSUE TITLE
Search for username dialog button color 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#802]
Looks weird with a white button.
<img width="648" alt="screen shot 2017-09-19 at 6 58 19 pm" src="https://user-images.githubusercontent.com/597182/30589443-06fc1396-9d6d-11e7-8afe-eb2df4c3549d.png">

**Comment by kkomaz** [comment]
I can take a look at this @guylepage3   Let me know what color you're thinking.

**Comment by guylepage3** [comment]
@kkomaz sounds great... as a general rule of thumb we use `btn-primary btn-block` for our buttons.

**Comment by larrysalibra** [comment]
This was fixed.
