### ISSUE TITLE
review adding container to browser

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#803]
Settings menu should be centered like the edit profile menu:

<img width="1225" alt="screen shot 2017-09-19 at 7 03 44 pm" src="https://user-images.githubusercontent.com/597182/30589518-5bae5e6c-9d6d-11e7-9eaa-f91da04edeff.png">

**Comment by guylepage3** [comment]
where applicable, add a container to the browser for easier usage.

**Comment by kkomaz** [comment]
I can take a look at this @guylepage3.  I have an idea on how we should structure our html markdown to always make sure its centered

**Comment by guylepage3** [comment]
There are two sections to the browser that could use wrapping..

- [ ] Navbar - so that it is easier to access the navbar in a more condensed central place
- [ ] Initial containers

**Comment by guylepage3** [comment]
hey @kkomaz, i've already started on this one. but definitely feel free to look at the "daily standup" for more issues.

**Comment by kkomaz** [comment]
@guylepage3 

Gotcha.  Thanks for the heads up!  This is a good idea to confirm with you before starting 😄
