### ISSUE TITLE
New verifications UX

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#805]
Build out new social proof verifications UX

**Comment by shea256** [comment]
Here's a set of changes I'm proposing for the edit tab:

- Update the edit tab to be accordion-style, like the design found [here](https://github.com/blockstack/designs/blob/master/browser/browser-v0.16/browser-macOS-44b-profileEdit-social-d16%402x.png)
- Remove the address section for now
- Implement the same accordion feature for the keys as the social accounts. Make them blend into one another and simply consider them all the same type of thing.
- Put basic info at the top, with a single photo. Don't allow extra photos.

**Comment by shea256** [comment]
To be clear, this would mean that by simply clicking on the "edit" tab, you'd be right in the middle of being able to edit your name and upload a photo and set and verify social accounts. This would reduce navigation significantly.

**Comment by shea256** [comment]
That would make the edit page look something like this:

- First name
- Last name
- Bio
- Photo
- Twitter
- Facebook
- GitHub
- ...
- Bitcoin address
- Ethereum address
- SSH Key

**Comment by shea256** [comment]
Reminder that we're also removing the large "delete" button and popping it up as a trashcan. We're also removing "save & view profile" because that's no longer necessary. Data entry updates and then navigation will automatically save no matter what.

**Comment by yknl** [comment]
Design for the combined edit page as proposed by @shea256 
@guylepage3 please have a look and let me know if there are any design issues.

**Edit Profile**
![browser-macos-41a-profileedit-d16](https://user-images.githubusercontent.com/29081231/30938222-52b0df34-a3a7-11e7-8e9c-23b0f5c75953.png)

**Expanded verification instructions state**

![browser-macos-41b-profileedit-d16](https://user-images.githubusercontent.com/29081231/30938279-81417afc-a3a7-11e7-9717-725eb63f8566.png)

**Comment by shea256** [comment]
Oh that's soooo good! Great work @yknl! 😍

**Comment by guylepage3** [comment]
Looks great @yknl 😄

One thing is to ensure font sizes. I see some inconsistencies.

**Comment by GinaAbrams** [comment]
@yknl after FB is sorted out, could we change the Twitter verification browser pop-up to explicitly say the post has to be public? (Please feel free to point me to a different issue or ask me to make a new one if that helps)

**Comment by yknl** [comment]
@GinaAbrams I added a line about tweets having to be public to the verification screen. Can you also add this link to the forum FAQ in case people don't know how to make it public. https://support.twitter.com/articles/14016

**Comment by GinaAbrams** [comment]
yes will do thanks @yknl !!!

**Comment by larrysalibra** [comment]
This shipped.
