### ISSUE TITLE
Unable to sign in with Blockstack

### ISSUE THREAD

**Issue by jm-martinrocha** [blockstack/blockstack-browser#811]
Blockstack Api is running. Its password is correctly verified.
The wallet address and Balance is correctly charged into the browser.

But I cannot sign in with blockstack into any app. It says I dont have it installed.

I own an id (registered through blockstack CLI). It does not appear in the portal/browser (it only appears a default profile with a random name and no id).

What could be the problem?

Thank you,
Jose Martin

**Comment by larrysalibra** [comment]
the CLI has a separate wallet and is deprecated. You can’t log in to Blockstack apps with names in the CLI wallet.

You’ll have to transfer the name from your cli wallet to the browser. We’ll have something to help with this soon.

**Comment by jm-martinrocha** [comment]
Ok. I transfered the id from the adress in CLI to the adress of the default profile in the browser.

However, It created a new profile instead of asigning the id to the default profile. 

![selection_001](https://user-images.githubusercontent.com/32129499/30653639-e7e8b7c4-9e2b-11e7-9461-6a454d6a87cb.png)

And, does the 'Set as Default Profile' button works? becuase I click it and it does nothing (and there are no errors in the console).

**Comment by jackzampolin** [comment]
This has been fixed in the latest release. Please reopen if the issue persists. Closing.
