### ISSUE TITLE
UI build of photo upload design from browser redesign

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#814]
<img width="863" alt="screen shot 2017-09-21 at 4 32 42 pm" src="https://user-images.githubusercontent.com/597182/30686342-8c364530-9eea-11e7-9e15-91e17368001f.png">

**Comment by larrysalibra** [comment]
Slightly improved now: 
<img width="724" alt="screen shot 2017-09-21 at 8 58 24 pm" src="https://user-images.githubusercontent.com/597182/30696861-a5e86d62-9f0f-11e7-8bb6-b13ba60da4db.png">

**Comment by guylepage3** [comment]
@yknl can you apply our design for this to the photo edit layout as seen here:

<img width="400" alt="browser-macos-43-profileedit-photo-d16" src="https://user-images.githubusercontent.com/1711854/30697829-3b8b1aca-9eae-11e7-88b9-4d03367ee188.png">

**Comment by guylepage3** [comment]
But let's leave out the title "photo" of course. Thank you sir.

**Comment by jackzampolin** [comment]
This has been incorporated into the latest release. Closing
