### ISSUE TITLE
Wallet placeholders values look like real inputs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#815]
Wallet input placeholder are indistinguishable from real inputs.
For a second, I was worried that someone had hardcode a "send to" address in our code.

Placeholders:
<img width="769" alt="screen shot 2017-09-21 at 4 45 13 pm" src="https://user-images.githubusercontent.com/597182/30686954-61a30d24-9eec-11e7-9f68-5aed4d31c6ad.png">

In the below screenshot, I've changed the amount and it looks exactly the same as the placeholder above.
<img width="759" alt="screen shot 2017-09-21 at 4 45 55 pm" src="https://user-images.githubusercontent.com/597182/30686956-63b082ae-9eec-11e7-9e1c-7cd6937129ea.png">

**Comment by guylepage3** [comment]
Thanks for catching this one @larrysalibra

**Comment by guylepage3** [comment]
Hey @amintorres, do you want to post your latest here sir? 😄

**Comment by larrysalibra** [comment]
I removed the placeholders for the wallet in #854 as a temporary fix.

**Comment by guylepage3** [comment]
resolved with another issue. someone created a duplicate
