### ISSUE TITLE
Duplicate word in identity key

### ISSUE THREAD

**Issue by daviddahl** [blockstack/blockstack-browser#820]
As I worked on #622 I saw a single instance where a duplicate word was in the identity key. As I am unfamiliar with the tools / protocol of the identity key creation, I am unsure if that is actually bug. It would seem to reduce the complexity of the ID key, however.

If this is not a bug, I will have to handle the tap to confirm functionality, it currently assumes unique words ( in #810  )

**Comment by MidnightLightning** [comment]
The identity keys look like the "mnemonic key phrase" implementations [developed for Bitcoin](https://en.bitcoin.it/wiki/Mnemonic_phrase). If so, each word is simply representing an index in an array of 2,048 word possibilities. Each word is a random 1/2048, so it's possible a word would be repeated in the phrase, but it's unlikely to happen (if the first 11 words are picked and are unique, there's an 11/2048 chance the 12th word will match one of the first 11).
