### ISSUE TITLE
Improve Blockstack ID backup/restore UX and messaging

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#821]
Currently, profiles that don't have a registered username cannot be backed up and restored. This is not made clear to the user. 

Consider letting users know that they are also "saving their account" when registering a name.

**Comment by larrysalibra** [comment]
Made some notes as to how we can make it so blockchain ID data that doesn't have a username can be backed up and restored as part of some more general state clean up in #822. 

Thanks for bringing this up @yknl !!

**Comment by larrysalibra** [comment]
As long as users are using the default gaia hub, their info should be backed up and restored without a username.
