### ISSUE TITLE
Update design profile to look more like a card

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#826]
With the backlogging delay of, [#697: Update webkit native window to mobile size and look](https://github.com/blockstack/blockstack-browser/issues/697), the profile now does not resemble a card. This is a big problem that leaves the profile looking very open and unfinished.

**Solution:**
Update the layout to apply the **old 'white card' background** with a drop shadow as seen below. 

**NOTE:** Just the white background with the drop shadow.

![browser-40b-profile-desktop](https://user-images.githubusercontent.com/1711854/30745736-5165402e-9f75-11e7-9f56-a779bd106f94.png)

**Sketch file containing drop shadow rectangle style:** https://github.com/blockstack/designs/blob/master/browser/designs/_browser-old-versions/browser-v0.11.sketch

cc: @yknl @shea256  @larrysalibra

**Comment by wbobeirne** [comment]
Closing as stale
