### ISSUE TITLE
Windows 10 Install Successful with Docker However cannot access apps with Onename Exported id

### ISSUE THREAD

**Issue by imine4coin** [blockstack/blockstack-browser#827]
The windows Blockstack browser install went fine, however because I already had a id, imine4coin.id in Onename, I was able to export that to the browser id address.  The Onename id has some available coins but was never registered.

Now in the browser I don't see the coins associated with the name.  Nor do I have the ability in the browser to pay for the name registration.  Is the reason why I cannot access the apps that the name is not "officically" registered?  Or is it that the name has a different wallet id than what the browser is expecting?  What is the fix for this as I would really like to start learning how to develop apps on the platform.  But that is another Linux issue that is being worked.  
Thank you all for the feedback and for this platform.  It has great potential!
Robert

![username registration](https://user-images.githubusercontent.com/31987166/30812609-d5058bc0-a1d0-11e7-838c-cd35f22fc609.JPG)
![onename](https://user-images.githubusercontent.com/31987166/30812827-6d5a14a4-a1d1-11e7-831f-0432f4d07ff6.JPG)
![imine4coinzonefile](https://user-images.githubusercontent.com/31987166/30813339-cab847f0-a1d2-11e7-9409-e5c215a537ce.JPG)
![imine4coinhistory](https://user-images.githubusercontent.com/31987166/30813345-d0ae1b44-a1d2-11e7-8d14-e54e5cac7bc7.JPG)

**Comment by jackzampolin** [comment]
Please send an email to `support@blockstack.org` we can get this cleared up for you!

**Comment by imine4coin** [comment]
Email sent.  Thank you!
