### ISSUE TITLE
Test for lint as part of test suite

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#829]
Once upon a time in Issue #380, @shea256 asked us all to install eslint plugins in our editors to auto-display lint errors in our editors.

5 months later and we still have lots of lint hanging around our code.

I've added checking for lint as part of the tests that are run by circleCI on each commit. You can run these manually on your machine by running `npm run test`.

Since we don't have time to tackle lint all at once, I've configured `.eslintignore` to ignore lint in files that we've yet to clean up.

I will be cleaning up lint as I work on parts of the browser. I hope that you can help too! 

Once some files or a component are lint free, we can edit the `.eslintignore` file so that the newly lint free files are included in the automated checks.

cc @yknl @guylepage3 @shea256

**Comment by guylepage3** [comment]
Thank you for the reminder @larrysalibra. I am guilty of not linting. My apologies sir. Will add that to my workflow from now on. 👍
