### ISSUE TITLE
Test identity verifications in browser

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#831]
In order to test identity verifications in browser, all members of the Blockstack team should register their identities and go through the social proof verification process (Facebook, Twitter, LinkedIn, GitHub, HackerNews, Instagram). 

Tentatively scheduled for Thursday, Oct 5. This is dependent on the completion of new verifications UX in the browser.

@shea256 @muneeb-ali @larrysalibra @jcnelson @pstan26 @kantai @guylepage3 @jackzampolin @GinaAbrams

**Comment by wbobeirne** [comment]
Closing as stale
