### ISSUE TITLE
Auth Login Profile Selection UI Broken 

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#832]
In the latest version of Browser, when logging in to an app, I see no text in the dropdown menu.

![broken-login](https://user-images.githubusercontent.com/1153552/30940066-c673aafe-a3ad-11e7-8255-959b232a4ad1.png)

**Comment by yknl** [comment]
Doesn't seem to be an UI issue, just tested it out and I can see the list of profiles in the dropdown. The profiles might not have been fetched properly.

**Comment by xmakina** [comment]
![image](https://user-images.githubusercontent.com/1357791/30956257-a4ce7cf4-a42e-11e7-99a5-5d3d65ca8a72.png)
![image](https://user-images.githubusercontent.com/1357791/30956267-a9cd85b0-a42e-11e7-8f4a-4c5bf3daa615.png)

My profiles list in the dropdown, but I cannot choose it. It is there, but when clicked the main box doesn't fill with the chosen item. I cannot login by pressing approve. This issue continues if I have two profiles.

**Comment by kantai** [comment]
Just to clarify the issue we're seeing, @yknl, the drop-down displays text, but once a profile is selected, the "chosen profile" doesn't display. It is selected, and you are able to log into an app, but there's no text displayed. This happens for me in Chrome and Firefox, using the Linux launch scripts (those are built using docker containers, so the JS packages included by npm might be different -- I'll see if there's any CSS errors / JS errors)

**Comment by yknl** [comment]
@kantai I couldn't replicate it, I continue to see the name after selecting a profile. But I am getting some js errors in the console that might be related. I will investigate.

**Comment by kantai** [comment]
Offending CSS:

In `app.css:348 `
```CSS
.form-control {
    font-size: 0.875rem;
    font-weight: 400;
    color: #484848;
    /* padding: 1.0625rem 0.9375rem; */  <--- the offender
```

![broken-dropdown-1](https://user-images.githubusercontent.com/1153552/30968660-0b0b95de-a42e-11e7-92d9-41defe19f9c8.png)
![broken-dropdown-2](https://user-images.githubusercontent.com/1153552/30968661-0b0c9d3a-a42e-11e7-9817-76f4461ab5b8.png)

**Comment by jackzampolin** [comment]
This has been fixed in the latest version. Closing.
