### ISSUE TITLE
References to "localhost" broken when using Docker on Windows (through VirtualBox)

### ISSUE THREAD

**Issue by MidnightLightning** [blockstack/blockstack-browser#834]
When working with Docker on Windows, with VirtualBox as a back-end, Docker creates a virtual machine (boot2docker linux image) with its own IP address, and runs the Docker containers on that. However those ports are not mapped to the local (Windows) host machine. So references to `https://localhost` don't resolve properly to the running Blockstack tools. Instead, if in a Dockerized environment like that, they need to be able to be configured, to set the IP address of the running boot2docker VM (something like 192.168.99.100).

**Comment by jackzampolin** [comment]
@MidnightLightning Can you point out some specific places where this happens? @kantai

**Comment by MidnightLightning** [comment]
I downloaded the Windows installer from https://github.com/blockstack/blockstack-browser/releases and ran it. I already had Docker installed from my own development work, so just got all the shortcuts. Launching the shortcut gave a console window that spun up a Docker container, and walked me through setting a core data password. Upon finishing that process, it opened a browser window to `http://localhost:3000` (with the password I just entered set in the URL some way; I forget the exact fragment), which failed to load anything because there's nothing on `localhost:3000`. I manually changed the URL to `http://192.168.99.100:3000` and the Blockstack portal opened properly.

But then navigating around the interface didn't work well, and looking at the browser console I saw many errors as it tried to hit various ports on `localhost` unsuccessfully.

**Comment by kantai** [comment]
Okay -- our `start.sh` script attempts to set up a network bridge to the docker virtualmachine on ports `6270`, `8888`, and `1337` -- it seems like this is failing if the docker virtualmachine already existed. The offending lines of code are over in our packaging repo:

https://github.com/blockstack/packaging/blob/master/blockstack-toolbox-windows/windows/start.sh#L50

I'll work on this tomorrow -- should be easy enough to use vboxmanage to check if the port forwarding is set up on the virtualmachine, and if not, set it up.

Thanks for finding this!

**Comment by kantai** [comment]
I updated the v0.16.0 installer with a potential fix -- if you can try it out, let me know how it works out!

https://blockstack.blob.core.windows.net/packaging/windows-installer-v0.16.0.exe

**Comment by xmakina** [comment]
localhost:8888 opens on my win10 machine. I'm getting reset connection errors when trying to access anything on 6270 though

**Comment by kantai** [comment]
Hi @xmakina,

Can you open the "Docker Shell" shortcut that the Blockstack installer created and run the following command:

```bash
docker ps
```

Thanks!

**Comment by MidnightLightning** [comment]
@kantai I tried the 0.16.0 installer, and no dice; same situation. `docker ps` shows that the container is forwarding port 8888, but looking at the VirtualBox settings for the one running Boot2Docker machine, it only has an SSH port forwarded.

Though why the hyper-reliance on "localhost" being _the_ host for everything? Running the core Blockstack piece on your hardware is good, so you know and trust what it is, but it seems you're forcing the server/client relationship to always be within the same place? I as a developer have my main Windows workstation at home, but I also have a linux (CoreOS) box that is running 24/7, which is where I keep my Parity software running for Ethereum, my Bitcoin node for my local wallet, and my OpenBazaar server software to connect to from the client on my Windows workstation. In order to support other users seeing the content I generate with Blockstack (blogs, etc.), don't I need to keep my node on the network to "seed" that (to borrow a torrenting term)? By forcing me to need "localhost" to be where my core Blockstack server is running is really limiting my options as a user. Wouldn't it be more useful to follow a system where it tries localhost first as a default, but then if it can't connect, gives a "define your server address" sort of dialog, where you can save IPs/DNSs of trusted local Blockstack nodes to use?

**Comment by kantai** [comment]
@MidnightLightning -- I agree, we should make this more configurable -- we have an issue open here: #819 

That's weird about the networking setup though. Can you run the following from git's bash command shell?

(From `C:/Program Files (x86)/Git/bash.exe`):

```bash
if [ ! -z "$VBOX_MSI_INSTALL_PATH" ]; then
  VBOXMANAGE="${VBOX_MSI_INSTALL_PATH}VBoxManage.exe"
else
  VBOXMANAGE="${VBOX_INSTALL_PATH}VBoxManage.exe"
fi
VM=${DOCKER_MACHINE_NAME-default}

"${VBOXMANAGE}" showvminfo "${VM}" | grep NIC
```

**Comment by jackzampolin** [comment]
@MidnightLightning The reason we went with docker is so that you can host it elsewhere. If you would like more info on how to do that HMU in the Blockstack slack

**Comment by MidnightLightning** [comment]
@kantai 
```
$ "${VBOXMANAGE}" showvminfo "${VM}" | grep NIC
NIC 1:           MAC: 08002793069E, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 50450, guest ip = , guest port = 22
NIC 2:           MAC: 08002792DD5C, Attachment: Host-only Interface 'VirtualBox Host-Only Ethernet Adapter #2', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 3:           disabled
NIC 4:           disabled
NIC 5:           disabled
NIC 6:           disabled
NIC 7:           disabled
NIC 8:           disabled
```

**Comment by jordanvanbergen** [comment]
I have the same issue. Installed blockstack on Windows10 using the installation files blockstack provided. Everything is working but after starting BlockStack browser it opens an internet browser with localhost:8888 that won't work. If I change this to 192.168.99.100:8888 I see the BlockStack browser start page. 

But the rest isn't working as lot's of things are connected to localhost:xxxxx different portnumbers and all of them won't work. 

How do we get the localhost:xxxx from you local windows10 machine working to be able to fully use the BlockStack suite? I am now stuck as my wallet address won't show e.g. because of:

Failed to load resource: net::ERR_CONNECTION_REFUSED 
http://localhost:6270/v1/wallet/payment_address

**Comment by kantai** [comment]
Hi, @jordanvanbergen,
First, are you running with the latest release (v0.17.0)?

Second -- can you try running the following from git's bash command shell?

(From C:/Program Files (x86)/Git/bash.exe):

```bash
if [ ! -z "$VBOX_MSI_INSTALL_PATH" ]; then
  VBOXMANAGE="${VBOX_MSI_INSTALL_PATH}VBoxManage.exe"
else
  VBOXMANAGE="${VBOX_INSTALL_PATH}VBoxManage.exe"
fi
VM=${DOCKER_MACHINE_NAME-default}

"${VBOXMANAGE}" showvminfo "${VM}" | grep NIC | grep -q "name = core"
if [ $? -eq 1 ]; then
  "${VBOXMANAGE}" controlvm "${VM}" natpf1 core,tcp,localhost,6270,localhost,6270
fi
"${VBOXMANAGE}" showvminfo "${VM}" | grep NIC | grep -q "name = cors"
if [ $? -eq 1 ]; then
  "${VBOXMANAGE}" controlvm "${VM}" natpf1 cors,tcp,localhost,1337,localhost,1337
fi
"${VBOXMANAGE}" showvminfo "${VM}" | grep NIC | grep -q "name = browser"
if [ $? -eq 1 ]; then
  "${VBOXMANAGE}" controlvm "${VM}" natpf1 browser,tcp,localhost,8888,localhost,8888
fi
```

And afterwards, run 

```
"${VBOXMANAGE}" showvminfo "${VM}" | grep NIC
```

**Comment by jordanvanbergen** [comment]
I work during the day so I can only react to questions in the evening. Too bad but I can tell you my output is:

Vboxmanage.ext not found! I call the above from /User/Jordan/Git/Bash.exe

**Comment by jordanvanbergen** [comment]
Added virtualbox to the Path and now it works. This is the output:

NIC 1:           MAC: 0800270716AA, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = browser, protocol = tcp, host ip = localhost, host port = 8888, guest ip = localhost, guest port = 8888
NIC 1 Rule(1):   name = core, protocol = tcp, host ip = localhost, host port = 6270, guest ip = localhost, guest port = 6270
NIC 1 Rule(2):   name = cors, protocol = tcp, host ip = localhost, host port = 1337, guest ip = localhost, guest port = 1337
NIC 1 Rule(3):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 2099, guest ip = , guest port = 22
NIC 2:           MAC: 080027682007, Attachment: Host-only Interface 'VirtualBox Host-Only Ethernet Adapter #5', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 3:           disabled
NIC 4:           disabled
NIC 5:           disabled
NIC 6:           disabled
NIC 7:           disabled
NIC 8:           disabled

**Comment by jordanvanbergen** [comment]
While doing the above I got a firewall screen popup and said OKAY. Now http://localhost:8888/ is working! Will let you all know if the rest is working as well. So adding virtualbox to the PATH was needed so it seems to get it working and the firewall setup correct.

**Comment by jordanvanbergen** [comment]
Still no succes. Now I get:

Failed to load resource: net::ERR_SOCKET_NOT_CONNECTED
:6270/v1/wallet/payment_address 

So it changed from:

Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:6270/v1/wallet/payment_address

to 

Failed to load resource: net::ERR_SOCKET_NOT_CONNECTED
:6270/v1/wallet/payment_address 

but only this: Send at least 0.01 bitcoins to the address below to register a username. All username registrations use funds from your wallet.
Loading address...

And loading address doesn't disappear as the code can't get results due to Failed to load resource: net::ERR_SOCKET_NOT_CONNECTED

**Comment by jordanvanbergen** [comment]
Trying v0.17 now....... looks like installing and starting is working better than yesterday:

8147ed9f3210: Pull complete
adf24d70b9bf: Pull complete
08ac07a33362: Pull complete
7603a6b7bdde: Pull complete
f17c2b896e3d: Pull complete
def9d545d15c: Pull complete

Now let's see...... it's working! So with 0.17.x it's working now!

**Comment by jackzampolin** [comment]
This is awesome @kantai! Closing this issue.
