### ISSUE TITLE
Modify on-boarding screens to support Gaia hubs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#835]
As part of #824, I need to modify the on-boarding screens to support our new Gaia hubs.

**Comment by larrysalibra** [comment]
This is how it looks now:
<img width="446" alt="screen shot 2017-09-29 at 2 59 35 am" src="https://user-images.githubusercontent.com/597182/30985233-4c6fb282-a4c2-11e7-9ba4-286d5fdafdff.png">

We haven't reached a decision as to whether or not we will continue to support Dropbox going forward or if we will instead only support Gaia Hubs.

I'd like try to come to a decision in this issue.

To start the discussion, I've made two different versions of the main storage on-boarding screen:

## Option 1: Gaia Hubs-only

<img width="442" alt="screen shot 2017-09-29 at 2 48 36 am" src="https://user-images.githubusercontent.com/597182/30985482-d80c54b2-a4c2-11e7-992f-7c2c77ffe923.png">

Clicking on "Run my own Gaia Hub" would take you to a view that has a box where you can enter your Gaia Hub's address and a link to github with instructions on how to set up your own Gaia Hub. 

It could also have 1-click docker images for a few providers.

## Option 2: Gaia Hubs & Dropbox

<img width="430" alt="screen shot 2017-09-29 at 2 50 34 am" src="https://user-images.githubusercontent.com/597182/30985484-db3c513c-a4c2-11e7-8a96-249341542a69.png">

Clicking on "Choose another storage provider" would bring you to a list of buttons like we have now with "Connect Dropbox" as the first option.

---

## Analysis 

As I see it:

### Option 1: The Gaia Hubs-only direction:

**Pros:**
* simpler messaging: you need a gaia hub, pick your hub or run your own
* this is the direction we're likely moving
* avoids potentially breaking the ability to update profiles break when we remove the functionality in the future

**Cons:**
* For people who don't want to host their own, they have no real choice.

### Option 2: The Gaia Hub & Dropbox direction:

**Pros:**
* Gives all users a choice of hosting.
* Users who choose dropbox can actually see apps storing things in their dropbox

**Cons:**
* We have to support & test multiple code paths
* Users who choose dropbox will have a worse user experience
  * There's an annoying redirect with multi-step login and authorization
  * If they have the app installed & push notifications enabled, they'll get lots of notifications as apps write files
  * Slow writes
* We'll have to figure how to migrate dropbox users in the future or support indefinitely

---

I'm leaning towards Option 1. What does everyone else think?

**Comment by jcnelson** [comment]
I think if we go with Option 1, we need to have a blurb somewhere on how users can run their own Gaia hubs and configure theirs to store data to their Dropbox (or wherever).  IIRC the roadmap for Gaia hubs is that each hub is a "proxy" between your browser and the rest of your storage services.  We provide a Gaia hub for users to get started, but in the limit each user could have their own Gaia hub that takes care of the service-specific interfacing (i.e. Gaia hubs encapsulate the code complexity of linking your Dropbox account to your applications, so the browser doesn't have to do this).

**Comment by pstan26** [comment]
I think this depends on what the "setting up your own Gaia hub" process looks like. Will users like my mom know how to do that? If the short and long term user what experience will be better for them with if we steer them away from Dropbox then I feel that we should point them in that direction.

For that reason I'm leaning option 1 if it means less friction. If we proceed with that, there needs to be real focus on improving the copy. We are getting to a point where the user experience and expectations matter a lot.

**Comment by kantai** [comment]
I'm leaning towards Option 1 -- with an "advanced users" link to the gaia/hub repository, which would include instructions to spin up a node (should be pretty straight-forward to set up and configure) if someone would like to do that. Ultimately, even supporting Dropbox via the Gaia Hub seems burdensome, but that's a decision for another time, as currently, we only support S3 and Azure from the hub.

**Comment by muneeb-ali** [comment]
Would "Run my own Gaia Hub" still be an option under "Choose another storage provider"? 

I like having the option to use Dropbox there because it's the only working driver we have. I'm less concerned about migration later (it'd be a pain but we kinda need to do it anyway for apps/data on Dropbox right now plus we should be able to replicate data from place to another smoothly). I'm more concerned about people saying that "how is this decentralized". We already get this question for Gaia storage and without being able to display options like Run your own Gaia Hub, Connect Dropbox, Connect IPFS (greyed out), we're hiding a core feature of the system and the general audience might get confused about how this is decentralized or how we reduce cloud providers to "dumb drives" etc. 

So leaning towards option 2 with the addition that "Run your own Gaia Hub" should be an option there as well.

**Comment by larrysalibra** [comment]
@muneeb-ali 
> Would "Run my own Gaia Hub" still be an option under "Choose another storage provider"?

It could be.

**Comment by yknl** [comment]
Leaning slightly towards option 2. I like having the dropbox option because I feel more secure when I see my files are being stored in a place that I can control. Also seeing a list of other storage options reaffirms the decentralization theme for me.

I think if we were to go with option 1, we'd need really good messaging around what a Gaia Hub is. To the average user it may look like centralized storage which goes against the goal of decentralization.

**Comment by jcnelson** [comment]
> I'm more concerned about people saying that "how is this decentralized". We already get this question for Gaia storage and without being able to display options like Run your own Gaia Hub, Connect Dropbox, Connect IPFS (greyed out), we're hiding a core feature of the system and the general audience might get confused about how this is decentralized or how we reduce cloud providers to "dumb drives" etc.

Yeah, this is what I was getting at.  We can still claim that the system is decentralized if we can explain how a Gaia hub preserves the user's freedom to choose storage providers.  I think this is a precondition for Option 1.

The explanation doesn't have to be in the browser.  It could just be a URL called "what is a gaia hub?" that linked to a document in our github, for example.

**Comment by jackzampolin** [comment]
We also need to add an easy way for users to pull their data out of our gaia hub and migrate it to their own. 

I also like that linking to explanation of Gaia Hub. We need to spiff that documentation up significantly then...

**Comment by muneeb-ali** [comment]
> the other could pull the plug on my "free" account at any moment.

Really interesting to see the two perspectives on Dropbox. Which makes me think that maybe we should optimize for having __more options__. Different people have different preferences and reactions but if just display all options (hidden under a click-through) then we can cover more people and let them pick what they like (decentralization!). 

I fully understand that maintaining Dropbox will be a pain but we're not committing to this for long and if the option is hidden away then realistically most people are just going to pick the default/free option anyway.

**Comment by kantai** [comment]
> Different people have different preferences and reactions but if just display all options (hidden under a click-through) then we can cover more people and let them pick what they like (decentralization!).

I'm okay with this, and kind of sold on the "more options is better", so long as the options are hidden. The pains related to Dropbox are high, but not impossibly so (at worst, this is going to mean asking users to do zonefile updates if their dropbox url changes -- we _do_ have support for the zonefile update in browser).

**Comment by shea256** [comment]
I'm in the Gaia hubs only camp at this point but I can see both sides. I'll defer to you guys.

**Comment by shea256** [comment]
Here's a general preview of the storage selection page:

<img width="430" alt="30985484-db3c513c-a4c2-11e7-8a96-249341542a69" src="https://user-images.githubusercontent.com/994646/31130615-e0044fe2-a825-11e7-8e91-2e8f2c6274ce.png">

**Comment by shea256** [comment]
On-boarding screen:

- App data is stored in the storage provider of your choice
- Use default storage hub
- Choose another storage provider

Settings page:

- Default storage (free storage hub provided by Blockstack PBC)
- Dropbox
- IPFS

*Note: our storage migration feature will be included in a future version.*

**Comment by larrysalibra** [comment]
<img width="438" alt="screen shot 2017-10-04 at 6 29 40 pm" src="https://user-images.githubusercontent.com/597182/31171390-0e250f1c-a932-11e7-8e5e-2e026e76d822.png">
<img width="438" alt="screen shot 2017-10-04 at 6 29 49 pm" src="https://user-images.githubusercontent.com/597182/31171393-0f6e4ab4-a932-11e7-9b40-59d370b6cf55.png">
<img width="794" alt="screen shot 2017-10-04 at 6 37 42 pm" src="https://user-images.githubusercontent.com/597182/31171670-22361568-a933-11e7-9fb5-ab0f7b758e80.png">

**Comment by larrysalibra** [comment]
@shea256 thoughts ^^

**Comment by larrysalibra** [comment]
Potential improvements assuming we have time:

* Enable the self-hosted storage button and have it go to a page where one can set the gaia hub url and that provides the xpub for your keychain. This would also require development on gaia hubs and documentation to help people deploy.
* Integrating settings page & storage page (suggestions from @shea256 in #844)

**Comment by guylepage3** [comment]
Great job here @larrysalibra 😄

**Comment by kantai** [comment]
Closing this as this issue was resolved, and on-boarding screens have since changed anyways.
