### ISSUE TITLE
Issue with compiling browser with armhf - raspberry pi 3 852 error 404 'gulp-sourcemaps/map-sources' is not in the npm registry. 

### ISSUE THREAD

**Issue by henry158** [blockstack/blockstack-browser#837]
it seems to not be finding the correct packgae, unsure if it doesn't exist in the the repository for this platform..see attached pastebin.
http://termbin.com/ixyk

**Comment by larrysalibra** [comment]
from your pastebin:
```
2 info using npm@1.4.21
3 info using node@v4.8.2
```

Those versions of npm and nodejs are really old and not supported.

Please try Node v6 LTS & npm 5 - let us know if you're still having the problem.

**Comment by henry158** [comment]
`npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN bootstrap@4.0.0-beta requires a peer of jquery@>=3.0.0 but none was installed.
npm WARN bootstrap@4.0.0-beta requires a peer of popper.js@^1.11.0 but none was installed.
npm WARN react-dock@0.2.4 requires a peer of babel-runtime@^6.3.13 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})`

is the current error, not sure if that's old debian 9 related, nodejs for armhf related.

**Comment by henry158** [comment]
npm was holding onto some outdated packages in the directory, clearing it out and recloning fixed it. 

Thanks for being awesome

**Comment by larrysalibra** [comment]
@henry158 glad to hear it's working! Thanks for your patience!
