### ISSUE TITLE
0.0.0.0 is an invalid address

### ISSUE THREAD

**Issue by xmakina** [blockstack/blockstack-browser#838]
![image](https://user-images.githubusercontent.com/1357791/31030027-bee56990-a54b-11e7-9ecb-625ee6c17236.png)

After signing in to the Blockstack Todo App, no tasks can be saved and the console reports the above errors.

I've already done some preliminary investigations with the help of @kantai

**Comment by jackzampolin** [comment]
Looks like your PR got merged @xmakina Thanks! Closing this now.
