### ISSUE TITLE
Browser UX Review & Improvements

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#844]
I just went through the branch `feature/new-verifications-ux` and did a UX review.

Below are some items I came up with for improvements.

Let's start a discussion around them and see which ones we want to implement and which ones we want to drop.

### On-boarding / General (@larrysalibra)

1. Add a section or info icon that links to documentation. Include the following links: Tutorials, BlockstackJS docs, Core API docs, FAQ. #852 
2. Switch the tabs for the wallet and the profile. #848
3. Clean up the 404 page and center the text. #847

### Apps Tab (@larrysalibra)

1. Reorder the applications to the following: To-do list, Guild, Ongaku. #853 

### Wallet Tab (@larrysalibra) 

1. Remove the instruction text on the wallet tab. When users go to register a name, they will be given a payment prompt anyway. #854
2. Include text on the wallet tab that indicates that the numbers shown are the user’s “balance”. #854
3. Change the placeholder text on the send page of the wallet tab. Either no placeholder text should be used or the placeholder text should be obviously instructional and grayed out. #854

### Profiles Tab (@yknl)

1. Fix the error where the edit page does not load if the profile does not have name. #805
2. Re-enable photo uploading on the edit page. #805
3. Change all instances of “blockchain ID” to “Blockstack ID”. browser: #843 blockstack.js: https://github.com/blockstack/blockstack.js/issues/263 
4. Remove the “verify” button from the section where you can edit/prove an account. Instead, show the verification instructions after the user starts typing into the username field. #805
5. Remove the “+” from the “+create new id” button on the “more” page. #805
6. Include shadow social accounts for every social network that hasn’t been added to the user’s profile. #805
7. Make all unverified social accounts come up as clearly unverified. #841 
8. Clean up the design for the name purchase view. #856
9. On the name purchase view, change “cancel” to “back” and make sure it takes you back to the screen where you can search for a name. #856
10. Make the profile image clickable and enlargeable. #805

### Settings tab (@larrysalibra)

1. Change the “storage providers” page so that it’s more in line with choosing which Gaia hub you want to use. Consider combining it with the API settings page. https://github.com/blockstack/blockstack-browser/issues/835
2. Update the API settings page so that there’s a root url of the core node and all URL paths are defined in some standard. This can be something like “http://localhost:6270/v1/”. https://github.com/blockstack/blockstack-browser/issues/819

### Potential Improvements (@yknl)

1. Add the ability for a user to search for other people’s profiles. Maybe we can have the search bar open up a page on the explorer. #857

**Comment by shea256** [comment]
To-do's:

- Expand the Zendesk so it has the Blockstack brand
- Create a "Search" button in the browser that opens a search page in the explorer
- Landing page for the explorer that's specifically dedicated to search
- Update the explorer to use the search endpoint in core.blockstack.org

**Comment by shea256** [comment]
Name purchase view:

<img width="639" alt="screen shot 2017-10-02 at 4 44 05 pm" src="https://user-images.githubusercontent.com/994646/31130158-9dca550a-a824-11e7-8c9b-4a052e5413c2.png">

**Comment by shea256** [comment]
Comments from a recent user testing:

- Icons should have text
- Wallet icon looks like a camera, it wasn't clear it was a wallet
- App list icon should be a home screen

Observations of the user tester:

- Clicked to view the profile but didn't edit it because he didn't even see the edit tab
- Clicked around and explored settings a lot
- Was confused about what "backup account" is on the settings page

Questions asked:

- How do I get my app featured on this home page?
- How are you going to get me users?
- As a developer, how can I feel like I can contribute to this app directory and get it featured so I can get lots of users?

**Comment by shea256** [comment]
<img width="402" alt="screen shot 2017-10-03 at 11 05 12 am" src="https://user-images.githubusercontent.com/994646/31132432-c8313650-a82a-11e7-8ac3-6e50232e38ab.png">

**Comment by larrysalibra** [comment]
Clicking on the profile icon should send you to the edit profile page if it hasn't been edited before: https://github.com/blockstack/blockstack-browser/issues/849

**Comment by larrysalibra** [comment]
@shea256 

regarding the settings tab issues:

> Change the “storage providers” page so that it’s more in line with choosing which Gaia hub you want to use. Consider combining it with the API settings page. 

This is different than what we discussed yesterday. See #835 comments: https://github.com/blockstack/blockstack-browser/issues/835#issuecomment-334146682

> Update the API settings page so that there’s a root url of the core node and all URL paths are defined in some standard. This can be something like “http://localhost:6270/v1/”. #819 

This is something we've discussed for a while. It's a non-trivial amount of refactoring we can try to tackle this at the same time as making it so that the profile files of username-less Blockstack IDs are persisted to storage https://github.com/blockstack/blockstack-browser/issues/855 and state clean up https://github.com/blockstack/blockstack-browser/issues/562

**Comment by guylepage3** [comment]
@shea256 @larrysalibra can we close this one out?

**Comment by wbobeirne** [comment]
Closing as stale
