### ISSUE TITLE
Clean up 404 page

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#847]
Clean up the 404 page and center the text. from #844

**Comment by shea256** [comment]
404 page:

<img width="730" alt="screen shot 2017-10-03 at 10 22 00 am" src="https://user-images.githubusercontent.com/994646/31130195-b847cca0-a824-11e7-9ce3-f6cf0fc865d2.png">

**Comment by larrysalibra** [comment]
@guylepage3 I cleaned up the NotFoundPage component so that is a pure function and also did a rough clean up of the page until you have a chance to apply your design.

<img width="815" alt="screen shot 2017-10-04 at 8 07 55 pm" src="https://user-images.githubusercontent.com/597182/31174885-c8dd2d78-a93f-11e7-8624-4360ddb975de.png">

**Comment by guylepage3** [comment]
Yeah.. I will need to get to this tonight. Thanks @larrysalibra

**Comment by larrysalibra** [comment]
As we move to a native app, we shouldn't need a 404 page.
