### ISSUE TITLE
Go to edit profile on first profile visit

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#849]
As a new user with a new install of blockstack, clicking on the profile icon should go to the edit page. 
Once you've made an edit to your profile page, clicking on the profile icon should go to the view page.

**Comment by guylepage3** [comment]
Perfect. Here's what the view should look like...

<img width="400" alt="browser-macos-40c-profileedit-basicinfo-d16 2x" src="https://user-images.githubusercontent.com/1711854/31133620-11f30de2-a82e-11e7-9d86-af9d5e277196.png">

**Comment by shea256** [comment]
Should the "edit" view just always be the default page when going into the profile tab?

**Comment by yknl** [comment]
I think I would prefer to have a view of my profile as others see it. Also, since we're updating the profile as you type, it might be too easy to accidentally make changes to your profile.

**Comment by larrysalibra** [comment]
I agree with @yknl. Additionally, viewing profile by default is how it works on facebook, twitter, weibo, wechat, keybase. It's what users expect. Viewing my profile should let me see if I have any broken verifications. Eventually it could have other info like how many people follow me etc.

**Comment by guylepage3** [comment]
I feel as though landing on the edit view until I actually put in "some" credentials, is acceptable, but after that initial save, I would want to see my profile as others see it. Most people are vane and enjoy seeing themselves.

**Comment by larrysalibra** [comment]
@yknl Should be unblocked on this.
