### ISSUE TITLE
Add section with documentation links

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#852]
Add a section or info icon that links to documentation. Include the following links: Tutorials, BlockstackJS docs, Core API docs, FAQ.

From #844

**Comment by guylepage3** [comment]
Thanks for this @larrysalibra.. Can I get more context? Where exactly is this needed?

**Comment by larrysalibra** [comment]
@guylepage3 I’m not sure - on the call @shea256 explained it - and you gave some ideas. If I recall it was something about putting links outside the frame of the app over the background image or an intercom like icon that opens a list of links.

**Comment by guylepage3** [comment]
@larrysalibra Thank you for the context sir. Have scheduled this task into my list. Will be working on it tomorrow.

**Comment by larrysalibra** [comment]
we went with a support button that @yknl designed.
