### ISSUE TITLE
Wallet UX improvements

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#854]
From #844 

1. Remove the instruction text on the wallet tab. When users go to register a name, they will be given a payment prompt anyway.
2. Include text on the wallet tab that indicates that the numbers shown are the user’s “balance”.
3. Change the placeholder text on the send page of the wallet tab. Either no placeholder text should be used or the placeholder text should be obviously instructional and grayed out.

**Comment by larrysalibra** [comment]
For 3. I removed the placeholder text until #815 is resolved.
<img width="936" alt="screen shot 2017-10-04 at 8 25 32 pm" src="https://user-images.githubusercontent.com/597182/31175545-3677e4f2-a942-11e7-84a4-73bd6dab0401.png">
<img width="883" alt="screen shot 2017-10-04 at 8 25 40 pm" src="https://user-images.githubusercontent.com/597182/31175547-37aebb8e-a942-11e7-8d81-ada896eac8e0.png">

**Comment by shea256** [comment]
🔥

**Comment by guylepage3** [comment]
Looks great @larrysalibra 

We should figure out placeholder text as seen in issue https://github.com/blockstack/blockstack-browser/issues/815

@amintorres has been working on this..
