### ISSUE TITLE
Clean up the design for the name purchase view.

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#856]
![image](https://user-images.githubusercontent.com/29081231/31180467-b934d25c-a8ec-11e7-9a3f-779aa246e9d5.png)

**Comment by guylepage3** [comment]
@yknl can you provide screen shots on UI fixes for quick reference? Please and thank you sir. 😄

**Comment by yknl** [comment]
![image](https://user-images.githubusercontent.com/29081231/31402882-57c7e94a-adc5-11e7-9af9-5ae9c50d4a42.png)

![image](https://user-images.githubusercontent.com/29081231/31402920-805726aa-adc5-11e7-9137-ca7d571a7aae.png)

![image](https://user-images.githubusercontent.com/29081231/31402980-bb03c9d4-adc5-11e7-8da5-48cc93494d04.png)

![image](https://user-images.githubusercontent.com/29081231/31402992-c58a4284-adc5-11e7-979c-685066bce936.png)

**Comment by guylepage3** [comment]
Ok. Great work @yknl. We'll one-up this on the next redesign. 👍
