### ISSUE TITLE
Transfer name from onename

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#858]
Users will be transferring their names from onename to the browser in the coming weeks.

Users will have to provide the first (index 0) Blockstack ID profile from the browser wallet to the Onename "Export username" feature.

Onename will:
1. Create a profile file on the default gaia storage hub under that owner address
2. Store the profile and background images pointed to by the current profile to that file.
3. Transfer the name to the new owner address simultaneously updating the name to point at a zone file that includes the public url to the profile file in 1.

The browser should 
* display the name in the browser once the transaction confirms.
* allow users to edit the profile without having to do a new zone file update.
* detect that the profile file pointed to by the name isn't properly signed, read it in, sign it and write it back to the gaia hub.

We also need to make sure users are clear in that they will have to choose the default storage hub option for this to work.

Anything I'm missing @kantai?

**Comment by larrysalibra** [comment]
> Store the profile and background images pointed to by the current profile to that file.
Maybe we should only move the images that we're hosting in the onename s3 buckets over to gaia.

**Comment by kantai** [comment]
This looks good to me -- one thing to note is that the user needs some direction because the user flow needs to be something like:

1. Onename transfer interface directs user to install blockstack browser. Hint that they need to select the create new account option, rather than recovery, during onboarding, and select default storage provider.
2. User sets up browser and obtains address for the 1st account
3. User goes back to Onename and supplies address

>> Store the profile and background images pointed to by the current profile to that file.
> Maybe we should only move the images that we're hosting in the onename s3 buckets over to gaia.
Yeah, that's probably for the best -- no reason to copy other images over. We could even leave the images on the onename s3 buckets.

**Comment by jcnelson** [comment]
Earlier discussion: https://github.com/blockstack/blockstack-core/issues/278

**Comment by jcnelson** [comment]
One thing to consider in this process is that the user's profile will need to have the right signature---one that matches either the new owner key, or one that matches the `pubkey` `TXT` record.

When generating the new zone file, we need to insert the user's old public key so that profile resolution will continue to work once the transfer completes.

**Comment by kantai** [comment]
Just to tack on a note about using the `pubkey TXT` record -- we'd set the `pubkey TXT` record to the user's old public key on onename, and then when they update their profile in the browser, it would be signed by their new key. Because both public keys are "valid", the profile would correctly resolve both before it is signed by the browser _and_ after.

**Comment by larrysalibra** [comment]
is the pubkey TXT record a new thing? I'm pretty sure (not 100% sure though since i'm not in front of my computer) that our profile/zone file resolving logic in the browser doesn't know about that txt record and only uses the address record public key.

Couple questions

* Wouldn't this mean the old private key can always sign the profile unless the user issues a zone file update? If so, isn't this a security problem

* What's wrong with the profile failing to resolve until they save the file in the browser? This gives us an opportunity to prompt users to finish the transfer process and use the browser. We can make the browser automatically try to sign and save files for profiles that are in its gaia storage for one of its owner addresses.

**Comment by kantai** [comment]
It's not new -- my zonefile currently has it [ablankstein.id](https://core.blockstack.org/v1/names/ablankstein.id). But yes, this means the old private keys would be able to sign the profile. If you think it's okay to have the profile resolution fail until the transfer process finishes, that's fine with me.

**Comment by kantai** [comment]
Okay -- currently, when Onename transfers go through, they get a renew and zonefile update to something like:

```
$ORIGIN blankstein.id
$TTL 3600
_http._tcp URI 10 1 "https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/blankstein.id.json"
```

Where the hub is addressed to whatever address they are transferring to.

We can copy a profile over to that location easily enough from the backend (or even another process that is monitoring transfers), but the question is what should get copied there -- many transfers are old profile formats (or even profiles in zonefiles, like say `werner.id`). My thought is to copy over the resolved profile object -- the 'profile' attribute of (https://core.blockstack.org/v1/users/werner.id/)

**Comment by larrysalibra** [comment]
> copy over the resolved profile object
+1 This sounds great to me.

> https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/blankstein.id.json

I'm currently in the process of refactoring the browser so that there are no dependencies on having names.

Ideally, if we were storing each blockstack id's data in a separate gaia hub bucket based on that id's identity address (owner address), then when what i'd like to do is to store profiles in some place https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/profile.json where profile is what ever we want to call this file (profile/tokenfile/keyfile/etc).

Since we're data storing all of user's blockstack in the address bucket of the 0th blockstack id, that won't work.

Instead, what about naming the file based on the destination address?
If you're sending `ryan.id` to `15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx` 
it'd be `https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx.json`

If you're sending it to`1L9qgkHGqR6eY4kBVBvJHiL8d3iuY3Py9P`, it'd be `https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/1L9qgkHGqR6eY4kBVBvJHiL8d3iuY3Py9P.json`

Another option is to make a folder `https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/1L9qgkHGqR6eY4kBVBvJHiL8d3iuY3Py9P/profile.json`

Actually, if we use the folder option then we can upload photos into that folder as well.

Thoughts?

**Comment by kantai** [comment]
I see the issue with the name dependency, and like the folder solution. I kind of dislike the giant paths, though. To reduce the path size, we could index by account index?

```
https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/0/profile.json
https://gaia.blockstack.org/hub/15GAGiT2j2F1EzZrvjk3B8vBCfwVEzQaZx/1/profile.json
```

I don't feel strongly about it though, because it conveys less information about the owner address.

**Comment by larrysalibra** [comment]
@kantai I also don't like giant paths. Index works well since that's now how the browser looks up all things identity.

Let's go with what you suggested!

**Comment by kantai** [comment]
I'll switch the transfer service to use that URL now. That way, while the current browser won't post to that URL, the future ones will.

**Comment by kantai** [comment]
Okay, the transfer service is using that URL, and it's copying over resolved profiles. The JWTs are signed with a throwaway key. The copied over profile _won't_ resolve correctly -- the user has to go over to the browser and sign the JWT -- but this is the case no matter what.

**Comment by larrysalibra** [comment]
Transfers from onename have been working for a while.
