### ISSUE TITLE
Communicate length of name registration process

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#863]
We need to set reasonable expectations with regards to how long it will take name registration to complete. My mainnet test registration took roughly 1.5 hours. Since transactions don't always get picked up in the first block, they make take longer for some users. The vast majority of username registrations should be complete in 3 or 4 hours.

Part of #804

**Comment by larrysalibra** [comment]
I added this additional screen which is displayed after the user submits the name registration:

<img width="634" alt="screen shot 2017-10-06 at 11 51 29 pm" src="https://user-images.githubusercontent.com/597182/31286807-eb9a7f74-aaf1-11e7-8022-b63117c27795.png">

**Comment by shea256** [comment]
I'd just make it simple and pick one number. Safer is better so maybe 4 hours.

**Comment by larrysalibra** [comment]
@shea256 makes sense.
