### ISSUE TITLE
Clean up name pending behavior

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#864]
Names that aren't ready to use should show as pending.

Names that aren't ready to use should *not* be sent as part of the authentication process because apps will not be able to resolve them and authentication will fail.

Part of #804

**Comment by shea256** [comment]
Can we allow the user to sign in as the address in the meantime? This is a pretty critical window during which users will want to be able to sign into apps.

**Comment by larrysalibra** [comment]
> Can we allow the user to sign in as the address in the meantime? This is a pretty critical window during which users will want to be able to sign into apps.

With the above commit, the username is only sent in the authentication response if it's resolvable on the network.

**Comment by larrysalibra** [comment]
Blockstack IDs with pending usernames are now properly displayed and marked with a pending icon.

A Blockstack ID with a pending username does _**not**_ send the username during the sign in process - we do a look up of the name during sign in to make sure the name is resolvable.

<img width="554" alt="screen shot 2017-10-13 at 7 44 59 pm" src="https://user-images.githubusercontent.com/597182/31544766-0693a73a-b04f-11e7-8295-fe41c6ee674d.png">
<img width="554" alt="screen shot 2017-10-13 at 7 44 52 pm" src="https://user-images.githubusercontent.com/597182/31544768-06f7657c-b04f-11e7-9bd6-1dcd488615eb.png">

**Comment by larrysalibra** [comment]
I also updated the cards in all profile to always display the "identity address" and added tool tips to them.

**Comment by larrysalibra** [comment]
This has been merged into develop and will ship in the 0.18 release.
