### ISSUE TITLE
Prompt users to download Blockstack signed by Blockstack PBC

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#867]
In future builds starting from 0.18, the macOS app will be signed by Blockstack PBC instead of Appartisan Limited. Users will need to manually download the new version - sparkle will not install the update automatically because of the different Developer ID signature.

Let's create one last build in the 0.17.x series signed by Appartisan Limited that prompts users to download the updated version.

**Comment by shea256** [comment]
Apple still hasn't gotten back to us. I'll ping them again.

**Comment by larrysalibra** [comment]
Okay. Thanks for following up on this.

**Comment by larrysalibra** [comment]
This is still something we can do.
