### ISSUE TITLE
Default storage on-boarding flashes twice

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#875]

**Comment by alidcastano** [comment]
For me, it kept flashing and wouldn't let me continue to next step. Tried setting up dropbox instead but it would get hung up at the same point.

**Comment by larrysalibra** [comment]
Thanks @alidcastano. Hoping to work on this tomorrow!

**Comment by larrysalibra** [comment]
This should be fixed in the next release. Browser sync sort of masks the problem, so I'll need to test a production build before closing this out.
