### ISSUE TITLE
Add labels to navbar icons

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#876]

**Comment by guylepage3** [comment]
@yknl let's just put the text below the icons. `:hover` states will be solid icons. I'll provide those.

Pinning.. https://github.com/blockstack/blockstack-browser/issues/877

**Comment by guylepage3** [comment]
Designs are complete.. See here: [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)

**Comment by shea256** [comment]
Resurfacing this @yknl @larrysalibra.

**Comment by guylepage3** [comment]
@yknl can you provide a screen shot once this is built? Thank you sir.

**Comment by yknl** [comment]
@guylepage3 
![image](https://user-images.githubusercontent.com/29081231/31915315-019ec4e2-b81c-11e7-97bb-dfb9677ebb9f.png)

**Comment by guylepage3** [comment]
Awesome!!! What do you think about adding letter-spacing of 1px to the labels to make them more ligible?

**Comment by yknl** [comment]
I think we need to update the default color of the nav buttons as well since we're updating the secondary nav colors for better legibility.

![image](https://user-images.githubusercontent.com/29081231/31916208-8e586778-b81f-11e7-85a8-f1591f170f49.png)

**Comment by guylepage3** [comment]
Oh crikey!! I forgot to make the color switch. Thanks for pointing that out. Here's the blue that I've chosen

```
.ultramarine             {color: #004FFC;}
```

I'll update the active state icons for you @yknl

**Comment by guylepage3** [comment]
complete. closing issue
