### ISSUE TITLE
Place new Home and Wallet Icons

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#877]

**Comment by guylepage3** [comment]
https://paper.dropbox.com/doc/Frontend-2017-10-10-zOpyvVsO6YQWQXUPzj3yi

**Comment by guylepage3** [comment]
complete

**Comment by guylepage3** [comment]
<img width="731" alt="screenshot 2017-10-10 10 17 57" src="https://user-images.githubusercontent.com/1711854/31391364-4d747b6e-ada4-11e7-9e69-36db5cb2b159.png">
