### ISSUE TITLE
Show owner address even after adding username

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#881]

**Comment by guylepage3** [comment]
This should be tucked away in settings for better UX. No?

**Comment by larrysalibra** [comment]
I'm adding this as part of my state refactoring. 

I think it's fine to be visible on the profile just not super prominent

**Comment by larrysalibra** [comment]
Duplicate of #885 

This is what we have now:

<img width="554" alt="screen shot 2017-10-13 at 7 44 59 pm" src="https://user-images.githubusercontent.com/597182/31559589-b87761a6-b083-11e7-80d7-4b7dbef6a0c6.png">
<img width="558" alt="screen shot 2017-10-13 at 7 50 43 pm" src="https://user-images.githubusercontent.com/597182/31559591-bb04611c-b083-11e7-9223-88a0f50b9827.png">
