### ISSUE TITLE
Bitcoin address and username should be separate fields

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#885]
Still show the Bitcoin address after you have a username

**Comment by larrysalibra** [comment]
@yknl added this on the default ID page.
<img width="554" alt="screen shot 2017-10-13 at 7 44 59 pm" src="https://user-images.githubusercontent.com/597182/31559097-0787b1e4-b082-11e7-9f60-43993b7ed011.png">

I added this on the all IDs page:
<img width="558" alt="screen shot 2017-10-13 at 7 50 43 pm" src="https://user-images.githubusercontent.com/597182/31559090-0482c36c-b082-11e7-8194-986989ebf56d.png">
