### ISSUE TITLE
Add Windows Installation Instructions.

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#886]
Add installation instructions for windows. The windows install instructions are over in the [`packaging`](https://github.com/blockstack/packaging/tree/master/browser-core-docker) repository. Add a section in the README with this information.

**Comment by frankchen07** [comment]
I've taken a crack at this. Opened a pull request: https://github.com/blockstack/blockstack-browser/pull/1105

**Comment by Polcat000** [comment]
@jackzampolin Since #1105 was merged shouldn't that make #886 closed?

**Comment by moxiegirl** [comment]
@jackzampolin I'm closing this. I also have a detailed install/unininstall for Windows pending in a repo. Will be bringing it in later.

**Comment by moxiegirl** [comment]
I'll close this via my PR instead.

**Comment by moxiegirl** [comment]
Done. https://docs.blockstack.org/browser/browser-introduction.html
