### ISSUE TITLE
Add "DotPodcast" app to app store

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#887]
https://dotpodcast.co/
![dotpodcast app icon small](https://user-images.githubusercontent.com/5605552/31388082-daefdcb8-ad9a-11e7-9b8e-9f6ca3287f69.png)

You know what to do my friend. Thanks!

**Comment by pstan26** [comment]
cc @shea256

**Comment by guylepage3** [comment]
@yknl can i pass this off to you?

**Comment by yknl** [comment]
@guylepage3 yup, will add this in

**Comment by guylepage3** [comment]
thank you sir. removing it from my task list.

**Comment by yknl** [comment]
This has been added to the latest browser release.
