### ISSUE TITLE
Add tooltips to verifications views that say “Why am I doing this?”

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#893]
Add mouse over tool tips to the social proof verification views, or the trust level badge to explain why the user should verify their social proofs. 

Example:
![image](https://user-images.githubusercontent.com/29081231/31400998-71c144a0-adbf-11e7-8eb0-f81010b360ae.png)

**Comment by guylepage3** [comment]
@yknl let's keep with a consistent tool tip format for the design. can we see another option?

**Comment by yknl** [comment]
@guylepage3 we don't have a design for this yet. The shown tool tip example is from onename.

**Comment by guylepage3** [comment]
Hey @yknl. Yes we do. It our “tooltip” design. Please follow “roughly” that design. Let’s not stray from the current design until we do the next round of design together

**Comment by yknl** [comment]
@guylepage3 sorry I should've been more specific, the example shown is **not** the intended design. It is an example borrowed from one name to illustrate the purpose of the tooltip. Rest assured we will definitely be using something that follows our current tooltip design.

**Comment by guylepage3** [comment]
Oh.. ok. Can we see a rough layout of that? Or an applied UI build? Either or works. Just wanting to stay consistent

**Comment by guylepage3** [comment]
And thanks @yknl. Great work on this..

**Comment by larrysalibra** [comment]
Definitely need something to explain to users why they should verify social media accounts. Lots of confusion during the token sale about this from users.

**Comment by guylepage3** [comment]
This should be mocked up in InVision to show options on how we could handle this. I'll add this to my list.
