### ISSUE TITLE
redirectToSignIn should only redirect to URLs on the app origin

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#894]
Right now the following call redirects the user to a page on the app:

`blockstack.redirectToSignIn('/app')`

If the app is http://app.local, it should redirect back to http://app.local/app

**Comment by maxkreja** [comment]
Hi I would like to solve this issue. Would be kind if you could give me some directions to get started.

**Comment by larrysalibra** [comment]
This has been addressed in the blockstack.js repo
