### ISSUE TITLE
Add Studbits app to app store

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#896]
@guylepage3 

studbits.com

@alidcastano will be sending a 400x400 logo this week and will add it here. Thanks Alid!

**Comment by alidcastano** [comment]
Thanks, Patrick. Right now only an EARLY demo is live. I'll be hooking that up to Blockstack and creating the logo hopefully by the end of this week

**Comment by pstan26** [comment]
Great, we are looking forward and here to support, Alid.

**Comment by pstan26** [comment]
cc @shea256

**Comment by alidcastano** [comment]
Sorry for the delay with this. Turns out that I'm building Studbits as a desktop/web app using Electron. I was aiming to support Blockstack authentication/storage, but not sure how compatible this new approach will be with Blockstack's authentication/storage API.

**Comment by guylepage3** [comment]
No worries @alidcastano.. Will throw this in `backlog` for the time being. Let us know if anything changes. 😄

**Comment by cryptocracy** [comment]
@alidcastano ... I've been working on a side project to get trying to get Blockstack integrated into a Node-Red instance that is in an Electron
It currently lacks auth and storage api integration but perhaps this is a good starting point?
Here is the link to the repo: 
[https://github.com/cryptocracy/electron-node-red-blockstack](https://github.com/cryptocracy/electron-node-red-blockstack)

**Comment by pstan26** [comment]
@alidcastano are there specific features in Studbits that do not allow it to be implemented as a web app or desktop app?

**Comment by alidcastano** [comment]
The native constraints of desktop apps make Blockstack authentication more difficult.  (It's the only part of the prototype I couldn't port over sadly). I opened an issue (https://github.com/blockstack/blockstack.js/issues/270) to discuss it and see what could be done

**Comment by guylepage3** [comment]
@pstan26 @xanbots do we have the logo and link for Studbits?

**Comment by xanbots** [comment]
@guylepage3 I do not, @alidcastano can you drop it in the comments here? 512x512px - thanks!

**Comment by alidcastano** [comment]
Unfortunately, the direction of my app has changed. Please close this issue for now, and I'll open it back up if I end up offering support for Blockstack authentication, thanks!

**Comment by pstan26** [comment]
Which direction is it going in now? Interested!

**Comment by guylepage3** [comment]
closing this issue
