### ISSUE TITLE
Copy on /wallet/send-core is confusing

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#897]
The modal there requires your `blockstack api` password. It just says password. Being that there are a number `password`s in the blockstack browser, users may find this confusing. This can be fixed with documentation but we also might want to change the copy to `API Password`

**Comment by larrysalibra** [comment]
@jackzampolin that page doesn't do anything with the password field - you can enter whatever you want and it will still work. it's a hidden page only intended for developers
