### ISSUE TITLE
Inform users that they should not turn exit Blockstack during name registration

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#898]
Some users exit blockstack after submitting a name registration. 

This causes the registration transaction to fail to broadcast and their preorder to expire, costing them bitcoin without giving them a name.

https://forum.blockstack.org/t/paid-for-user-id-yesterday-btc-debited-but-not-available-when-i-login-today/1760/7?u=larry

**Comment by larrysalibra** [comment]
<img width="631" alt="screen shot 2017-10-12 at 5 24 05 pm" src="https://user-images.githubusercontent.com/597182/31489062-2bf2fee6-af72-11e7-845f-e6a7f5abbe94.png">

**Comment by guylepage3** [comment]
@larrysalibra this should be an `alert` box as it does not stand out. https://getbootstrap.com/docs/4.0/components/alerts/
