### ISSUE TITLE
Backup view look clean up

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#900]
This screen view some love:
<img width="815" alt="screen shot 2017-10-12 at 10 27 22 pm" src="https://user-images.githubusercontent.com/597182/31501351-9ae5b792-af9c-11e7-8b98-ce2c78835f00.png">

**Comment by larrysalibra** [comment]
The backup phrase in that screen shot isn't used for anything.

**Comment by yknl** [comment]
Cleaned up 
![account backup](https://user-images.githubusercontent.com/29081231/31570258-f242cb16-b04f-11e7-9180-a7c626183204.png)

**Comment by larrysalibra** [comment]
Looks much better. Thanks @yknl
