### ISSUE TITLE
Add "Send All" Feature to the Browser Wallet

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#903]
Currently, you have to specify an amount of BTC to send from the browser wallet to a given address. However, a frequent use scenario of the browser wallet is:

1. Send some money in to fund a registration
2. Complete registration
3. Send change out

For this use case, you'd want to be able to send "all funds" and have the wallet determine how much to allocate towards a TX fee. Blockstack core supports this, if you just leave out the "amount" property in the `POST /v1/wallet/balance` request -- (see here: https://blockstack.github.io/blockstack-core/#core-wallet-management-withdraw-payment-wallet-funds-post)

Most bitcoin wallets support a feature along these lines -- see Coinbase's interface for example.

**Comment by maxkreja** [comment]
I would like to pick this one up. It would be kind if you could point me in the correct direction so I know where to get started.

**Comment by AT1452** [comment]
Don't know if this project/issue is still active but I'm willing to take it up
