### ISSUE TITLE
Resolve tooltip UI

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#904]
@yknl we're close on the tooltip build to match the design but as stated on the pull request, https://github.com/blockstack/blockstack-browser/pull/800#issuecomment-336307615 we should really work hard to match the `triangle` height and width, `border-radius` and padding as seen below..

<img width="400" alt="browser-macos-40b-profile-d18 2x" src="https://user-images.githubusercontent.com/1711854/31523583-5daf5370-af82-11e7-81cb-b319c75119d6.png">

**Comment by guylepage3** [comment]
@yknl I'm going to add this to my list for today.

**Comment by wbobeirne** [comment]
Closing as stale
