### ISSUE TITLE
After Upgrade 0.17.1 still cannot send wallet amount from OneName Wallet to the Browser

### ISSUE THREAD

**Issue by imine4coin** [blockstack/blockstack-browser#905]
On Windows and trying to transfer OneName Wallet amount to New Blockstack Browser wallet.  However the follow error message appears.  Any suggestions as to the cause?
![image](https://user-images.githubusercontent.com/31987166/31531066-27254652-afaa-11e7-985f-a568da67b49c.png)

**Comment by larrysalibra** [comment]
@imine4coin I'm sorry that you're having this trouble. Can you email support@onename.com about this? Someone there should be able to help you.
