### ISSUE TITLE
Tool tips should appear over mouse

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#906]
Tool tips don't appear centered under the mouse pointer:

<img width="554" alt="screen shot 2017-10-13 at 7 49 14 pm" src="https://user-images.githubusercontent.com/597182/31544906-a6c6f734-b04f-11e7-9e87-13f8c53e5bc0.png">

**Comment by kkomaz** [comment]
I can probably take a look at this some time next week if it has not been addressed. 

@larrysalibra // @guylepage3

**Comment by larrysalibra** [comment]
Fixed thanks to @kkomaz !
