### ISSUE TITLE
Clean up id cards on all IDs page

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#907]
<img width="558" alt="screen shot 2017-10-13 at 7 50 43 pm" src="https://user-images.githubusercontent.com/597182/31544940-d352a460-b04f-11e7-920f-886667a7925e.png">

**Comment by guylepage3** [comment]
for the avatars can we please use 
```
<div class="d-flex align-items-center">...</div>
```
https://getbootstrap.com/docs/4.0/utilities/flex/#align-items

**Comment by guylepage3** [comment]
Hm.. there's an old card layout that we used for onename that will solve the layout issue on the design side.

**Comment by larrysalibra** [comment]
<img width="558" alt="screen shot 2017-10-13 at 7 50 43 pm" src="https://user-images.githubusercontent.com/597182/31552591-7e0b90b4-b06a-11e7-8caf-dc8d88687c24.png">

**Comment by guylepage3** [comment]
@larrysalibra @yknl can we check the font size of all the items in the "mini" card to have the same font-size as the ".id" name?
