### ISSUE TITLE
CORS Errors When Profile Page Tries to Verify Proofs

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#912]
Added some proofs (twitter + github) to my Browser profile (blankstein.id) -- the browser can't verify them because of CORS errors during the lookups on the `develop` branch.

![cors-failures-verifications](https://user-images.githubusercontent.com/1153552/31564642-ada1543c-b031-11e7-985c-36912115a2fc.png)

**Comment by yknl** [comment]
@kantai the twitter and github fetches should already be going through the CORS proxy. Can you confirm if your CORS proxy is working?

**Comment by larrysalibra** [comment]
I saw this problem too - it seems to show up when trying to fetch proof urls that don’t exist. Our CORS proxy may not return proper CORS headers if the URL it’s trying to fetch doesn’t exist or has an error.

**Comment by kantai** [comment]
The problem seems to be that the corsproxy doesn't want to use HTTPS --

![corsproxy-301](https://user-images.githubusercontent.com/1153552/31685332-9359a72e-b350-11e7-855a-a890593ee65f.png)

This is in v0.18.0 -- it seems like the nodejs corsproxy module doesn't support HTTPS, and the project is a little bit on the dormant side:

https://github.com/gr2m/CORS-Proxy/pull/38

**Comment by yknl** [comment]
This is weird, I use https proof urls and they seem to load through the CORS proxy and doesn't give out any console errors either. 

![image](https://user-images.githubusercontent.com/29081231/31686040-149ffa5c-b353-11e7-9c77-049ca70463da.png)

**Comment by kantai** [comment]
Can you check the network requests in the network console?

**Comment by kantai** [comment]
Aha -- this problem is in the Linux/Windows deployments, I think you are using `cors-https` and I'm not

**Comment by yknl** [comment]
ahh, I had no idea the Linux/Windows deployments used a different CORS proxy package.

**Comment by larrysalibra** [comment]
I forked corsproxy because it didn't support https https://www.npmjs.com/package/corsproxy-https

**Comment by kantai** [comment]
Yep -- if you merge the Dockerfile changes, it should fix the distribution of the corsproxy on Windows and Linux
