### ISSUE TITLE
Restore Account Phrase Entry Shouldn't Auto-complete

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#913]
The browser shouldn't store auto-complete data for the restore account phrase entry (this is a security problem).

I think setting the `autocomplete` attribute to false solves this:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete

**Comment by larrysalibra** [comment]
Thanks @kantai for reporting this! It's fixed and will be in the next release.
