### ISSUE TITLE
Mac Doesn't Save Data

### ISSUE THREAD

**Issue by shane1900** [blockstack/blockstack-browser#916]
Hi,

Newly installed on High Sierra.  It takes a very long time (several minutes to never) to open apps and when I am able to enter data such as in the to do list it never saves.  Hitting refresh starts over.  Any suggestions?

Thank you.

**Comment by larrysalibra** [comment]
Which storage provider are you using?

**Comment by shane1900** [comment]
Hi Larry.  The standard free.  In storage options I'm not able to click on any of the other options.

**Comment by shane1900** [comment]
I reinstalled and it's working a bit better but now http://localhost:8888/profiles doesn't appear, it's blank.  I was wanting to buy a username.  Storage providers still are all greyed out.

**Comment by wbobeirne** [comment]
That issue looks a lot like what happens in #1537, so I'm going to close this to consolidate on that one since it's reproducible.
