### ISSUE TITLE
Add checkboxes for email address input during onboarding

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#920]
Options:
(a) get account security notifications
(b) join the blockstack mailing list

**Comment by larrysalibra** [comment]
Implementing part (b) of this as we are going to optionally send emails to apps during sign in:

<img width="444" alt="screen shot 2017-10-30 at 6 53 45 pm" src="https://user-images.githubusercontent.com/597182/32167413-bffd80e0-bda3-11e7-8b54-8140c2b0e326.png">

**Comment by larrysalibra** [comment]
We've seen a number of users who are unhappy about being forced to enter email without an explanation of what it is used for. I've re-enabled the option to skip email entry.

**Comment by wbobeirne** [comment]
Closing this as stale, onboarding has changed a good bit since this was made and we don't have any security notifications built out.
