### ISSUE TITLE
Add a tooltip to explain what default storage is

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#923]
Problem: People are sometimes confused by what default storage means. They wonder where the data is being stored and are confused by the fact that we earlier told them that they are in control of their storage. If we're storing their data on a server somewhere, we need to explain to them why they're in control. It's because their data is signed and encrypted and eventually will be replicable across multiple cloud storage hubs. Which means data tampering and decryption and censorship are all invalid attack vectors.

Solution: Put a tooltip next to the “use default storage” button that explains what “default storage” is. Explain in this tooltip that their computer encrypts and signs all their data before backing it up to a server in the cloud. For simplicity, we connect them with a reliable server to provide the backups and online access. In the future, more will be available and they will be able to choose from multiple vendors across multiple geographies. Something like this.

**Comment by wbobeirne** [comment]
Closing as stale, the UI has changed since this was made.
