### ISSUE TITLE
User Testing Trial 2 - 2017-10-20

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-browser#925]
Not sure if we have an issue open for this already or not 😄

**Comment by larrysalibra** [comment]
How this go?

**Comment by pstan26** [comment]
Yea we have folks coming in this Friday 10/20 to do user testing. :-)

**Comment by larrysalibra** [comment]
Awesome! Looking forward to hearing their feedback.

**Comment by larrysalibra** [comment]
Going to close this. Please re-open if there's any feedback from user testing that should be documented here.
