### ISSUE TITLE
Update sign-in process UX

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#927]
Problem: Oftentimes the first thing user do when entering the browser is click on one of the apps, then login and get redirected back, then authorize the sign in request. When the users do this, they haven't yet visited their profile or edited their profile. Further, they haven't seen a bitcoin address at all. So when they hit the sign in screen, they see a Bitcoin address as their identifier and are confused. They expect to see their name there.

Solution: (a) Require the user to input their name in the on-boarding process (b) Show the user's name followed by the Bitcoin address or username in the profile selection window of the sign-in prompt.

**Comment by larrysalibra** [comment]
We should make sure to not show usernames that are still pending or show them in a way that indicates that they are pending in the select Blockstack ID dropdown during sign in.

**Comment by bodymindarts** [comment]
To clarify when signing in with an id that is still pending the login flow of the generated app (using the react version of https://github.com/blockstack/blockstack-app-generator) breaks silently.

**Comment by GinaAbrams** [comment]
@yknl any updates on this? 😄

**Comment by yknl** [comment]
@GinaAbrams This hasn't been completed yet.

**Comment by larrysalibra** [comment]
<img width="430" alt="screen shot 2017-10-31 at 7 56 18 pm" src="https://user-images.githubusercontent.com/597182/32222829-c286d028-be75-11e7-90e7-3260414366f9.png">
<img width="441" alt="screen shot 2017-10-31 at 7 57 09 pm" src="https://user-images.githubusercontent.com/597182/32222831-c3de8858-be75-11e7-8399-903dffc9c5d6.png">
