### ISSUE TITLE
Edit profile and verification updates

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#928]
Profile viewing

Problem: When the user goes to the profile page, he first clicks "add a username" and doesn't notice the edit panel.
Solution: Move the “add a username” from the “view profile” page to the “edit profile” page.

Problem: When the user goes to the profile page, the user doesn't have a feeling that this profile is theirs.
Solution: Add both name input and photo upload to the on-boarding process.

Problem: The bitcoin address on the profile is confusing for users. They think it's a Bitcoin address for payments and they don't know that the address is really the address that owns and secures their identity.
Solution: Consider using “ID-“ as the prefix for the identity address. This might be clearer than "b-".

Problem: When you read the trust level tooltip, it says "by verifying your social proofs". When I first read this I was a bit confused. The proofs aren't being verified. Rather the accounts are being verified using proofs.
Solution: Change the language in the trust level tooltip to say “Increase your trust level by verifying your social accounts”.

Profile editing

Problem: The verification instructions are currently incredibly confusing. This is the part that every user has the most trouble with. They typically go first to enter a username and then go to the "proof URL" field and then are either confused about what to do or they enter the URL to their profile there. They may then notice the instructions below but they have already been confused and wasted their time. Then, once they go to the instructions, they sometimes create the post but then they don't know what to do next. They're looking for where they should paste the proof URL. Then, once they have pasted the proof URL, they are trying to figure out how they can close the view or save the information.
Solution: Update the verification instructions to mirror the process we have developed for the Onename product. Order the components as follows: (1) Enter your username (2) Verification button or post creation instructions (3) Field for proof URL (4) Save/Close button.

Problem: Users don't know what to do when they are told to create a GitHub gist. They will often click to open the window but then they don't know what to type in the title field and the body field.
Solution: Change the instructions for GitHub from "Create a public gist with the following text." to the following steps: (1) "Copy the text below" / text field with verification text (2) Button: "Create a Gist" (3) "Paste the text in the description and body, then click 'create public gist'" (4) Copy the URL of the Gist and paste in the field below.

Problem: Profile viewing and editing is not clear to people.
Solution: Consider merging the “view profile” and “edit profile” pages.

Problem: If you click anywhere in the “increase your trust level” bar outside of the text box, nothing happens.
Solution: Make sure the full bar is clickable (instead of just the text).

**Comment by GinaAbrams** [comment]
@yknl any updates here? Can we close this out?

**Comment by yknl** [comment]
@GinaAbrams This is still being worked on

**Comment by yknl** [comment]
@shea256 @larrysalibra @guylepage3 Here is the proposed update to the profile view to address above mentioned problems. Let me know your thoughts!

- Iterating on @guylepage3's updated profile design.
- Fonts and colors with improved contrast
- No more blue highlight for verified social accounts to fix the jarring color transitions
- The identity address has "ID-" prefix
- **Edit** and **View** merged into a single view
- Clicking **Edit** activates edit mode and makes the profile fields and accounts editable
- Hovering over certain fields like Name and Bio will show a small edit icon beside it, clicking them will activate edit mode

![image](https://user-images.githubusercontent.com/29081231/31836371-11fe60de-b5a3-11e7-92aa-b86d3e2cd85a.png)

___

- If profile does not have a username, show **Add a username** in place of the username
![image](https://user-images.githubusercontent.com/29081231/31836851-ad7d965a-b5a4-11e7-9ba8-e926cc7ad242.png)

___

- Click **Edit** shows the **Save** button and hides the **More** button
- In edit mode, additional social account inputs are shown

![image](https://user-images.githubusercontent.com/29081231/31836645-07c397fa-b5a4-11e7-8410-df6fa8c8244a.png)

___

- Clicking on a social account in edit mode shows the proof instructions
- Proofs no longer autosave
- Proof instructions are similar to Onename.com instructions
- Other account lines fade to bring focus to the account being edited

![image](https://user-images.githubusercontent.com/29081231/31836848-a9c6ab50-b5a4-11e7-9b28-1fb3623025c9.png)

**Comment by shea256** [comment]
Awesome work @yknl! This is big improvement over the last version. Here are my comments:

> In edit mode, additional social account inputs are shown

Why not show the "prove your linkedin account" even if the user is in view mode? This would then activate edit mode.

> Other account lines fade to bring focus to the account being edited

I like this but there currently isn't enough contrast. To be clear on the last version with the blue background, what was particularly jarring was the fact that you would click on an item and then it would still have a white/gray background, and then only when you type in the username field would the blue background appear. That was the weird part. Further, the blue background would simply appear. I wonder if there's something closer to a traditional accordion, where there's a clear header component and outline.

**Comment by guylepage3** [comment]
Great job @yknl. 💥 

Soooo much better.. Love this iteration.. Heading more towards our overall neutral goal.

```
Product dictates the brand..
```

Really great work. One thing.. on my design i provided a 1440px width view for context (see example below). Could you provide one just so that i can understand sizing, etc. Thank you sir. 👍 

![team-item-v1 0 0 2x](https://user-images.githubusercontent.com/1711854/31837888-8668ce32-b5a8-11e7-95bf-d547e11884e6.png)

**Comment by larrysalibra** [comment]
I like the direction!

If you don't want to save? How do you exit out of the editing mode?

**Comment by shea256** [comment]
>If you don't want to save? How do you exit out of the editing mode?

Ah great point.

**Comment by larrysalibra** [comment]
I also sort of feel putting the instructions inline is a bit busy and distracting to the user. (not sure if this is related to the same contrast comment @shea256 mentioned) 

It make be less "busy" and clearer as a modal.

Click on "Prove your linked in a account" open a modal like we have on onename, complete the steps, save and close it.

Thoughts?

**Comment by shea256** [comment]
Here's an example of a collapsible element that is very clear:

![image3 png](https://user-images.githubusercontent.com/994646/31838435-d567798c-b5aa-11e7-9a95-a523ef5a723f.png)

**Comment by shea256** [comment]
> It make be less "busy" and clearer as a modal.
>
> Click on "Prove your linked in a account" open a modal like we have on onename, complete the steps, save and close it.

Yup @guylepage3 brought this up as well. I was concerned about the additional engineering requirements of changing this. Was also concerned about added friction in terms of editing.

But we could reopen this consideration if you two think it would be better.

**Comment by larrysalibra** [comment]
>  Was also concerned about added friction in terms of editing.
I don't think it adds additional friction to the editing process compared to an accordion collapsible element.

>  I was concerned about the additional engineering requirements of changing this.

@yknl is in a better position to make the call on this

**Comment by yknl** [comment]
> If you don't want to save? How do you exit out of the editing mode?

Good catch 😅 , added a cancel button on the right side.

> It make be less "busy" and clearer as a modal.

> Click on "Prove your linked in a account" open a modal like we have on onename, complete the steps, save and close it.

We can fade out the other lines even more and add some shadows to the account being edited like below.

![profile-edit-social](https://user-images.githubusercontent.com/29081231/31838755-3cd2105e-b5ac-11e7-9429-5084b15cb3f6.png)

**Comment by shea256** [comment]
>We can fade out the other lines even more and add some shadows to the account being edited like below.

That's interesting. Is even more of a contrast / outline possible? Maybe so it even starts to look more like a faux popup?

**Comment by shea256** [comment]
> Hovering over certain fields like Name and Bio will show a small edit icon beside it, clicking them will activate edit mode

Why not show these even if you're not hovering over the elements?

**Comment by shea256** [comment]
> We can fade out the other lines even more and add some shadows to the account being edited like below.

Yeah I'm just concerned that this still looks a little weird.

**Comment by yknl** [comment]
> That's interesting. Is even more of a contrast / outline possible? Maybe so it even starts to look more like a faux popup?

I think at this point we might as well just make it a modal.

**Comment by shea256** [comment]
> I think at this point we might as well just make it a modal.

OK that should be fine as long as it's simple.

**Comment by yknl** [comment]
One concern is how modals will look if we go to a native webkit view.

**Comment by larrysalibra** [comment]
> One concern is how modals will look if we go to a native webkit view.
Agree that's a concern, but I wouldn't worry about that today. we have a number of modals that will have to be addressed when we make that move.

**Comment by shea256** [comment]
> Agree that's a concern, but I wouldn't worry about that today. we have a number of modals that will have to be addressed when we make that move.

+1

**Comment by yknl** [comment]
> Really great work. One thing.. on my design i provided a 1440px width view for context (see example below). Could you provide one just so that i can understand sizing, etc. Thank you sir.

@guylepage3 for reference

![profile-edit-page](https://user-images.githubusercontent.com/29081231/31840693-79ba9e70-b5b4-11e7-974a-9d636764699d.png)

**Comment by guylepage3** [comment]
@yknl.. 💥 💥 💥 💥  😄 

Very very very nice sir.. 

Let's discuss `font-size` in our next design meeting. We're getting there.. 👍

**Comment by GinaAbrams** [comment]
@yknl can we close this? 😃

**Comment by yknl** [comment]
Hey, @GinaAbrams we're still working on this

**Comment by larrysalibra** [comment]
This shipped.
