### ISSUE TITLE
Fix backup account wording inconsistency in settings tab

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#929]
Problem: The "backup account" view in the settings panel has different wording than the rest of the app.
Solution: In the “backup account” settings panel, replace “backup phrase” with “recovery phrase”.

**Comment by cponeill** [comment]
Hey @yknl, I just wanted to confirm that it is only the text that needs to be changed and not anything hardcoded. If so then I will submit a PR.

**Comment by yknl** [comment]
Hey @cponeill, that is correct!

**Comment by cponeill** [comment]
That's great. I will submit a PR later today. Thank you for the quick reply @yknl.
