### ISSUE TITLE
Show user name after logging into the To Do List app

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#930]
Problem: When the user signs in, there isn't a clear indicator that the user is signed in as with their identity.
Solution: Show the user's name and photo just like in the Hello Blockstack app.

**Comment by GinaAbrams** [comment]
@yknl this is still "to do" as well correct?

**Comment by yknl** [comment]
Looks like @larrysalibra completed this
![image](https://user-images.githubusercontent.com/29081231/31836117-29bc935e-b5a2-11e7-8234-24ea5d4e381e.png)

**Comment by GinaAbrams** [comment]
Awesome thanks @yknl @larrysalibra
