### ISSUE TITLE
Blockstack Browser Issue Reporting

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-browser#931]
Create an easier way for users to report problems with the browser

**Comment by GinaAbrams** [comment]
@larrysalibra any update on this sprint deliverable?

**Comment by larrysalibra** [comment]
Nothing as of yet. Will plan to work on it after some UX improvements and transfer stuff.

**Comment by GinaAbrams** [comment]
@larrysalibra ping! Any updates? 😃

**Comment by wbobeirne** [comment]
Closing this as stale in favor of #1578.
