### ISSUE TITLE
Move the on-boarding process into a separate page

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#933]
The on-boarding process was implemented as a modal that sits in App - that the on-boarding component is mounted all the time. This causes a bunch of problems and lots of complexity as it essentially makes our on-boarding process global state.

Let's move this into a separate page that's only activated until certain conditions.

**Comment by larrysalibra** [comment]
This is technical debt we need to address sooner rather than later.

**Comment by guylepage3** [comment]
+1 on this. This will solve a lot of issues

**Comment by wbobeirne** [comment]
This is no longer the case.
