### ISSUE TITLE
Add "Souq" to app store

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#934]
http://beta.cryptocracy.io/

- [ ] @cryptocracy needs to add some more detail about what the app is.
- [ ] @cryptocracy needs to add a 400x400 logo here

**Comment by cryptocracy** [comment]
@pstan26 

> @cryptocracy needs to add some more detail about what the app is.

- I updated the http://beta.cryptocracy.io with a some additional app details, let me know your thoughts.

> @cryptocracy needs to add a 400x400 logo here

- Link: [https://github.com/cryptocracy/images/blob/master/400x400.png](https://github.com/cryptocracy/images/blob/master/400x400.png)

**Comment by guylepage3** [comment]
logo size required is.. 512 x 512.

**Comment by pstan26** [comment]
@guylepage3 thanks for update. cc @cryptocracy

**Comment by guylepage3** [comment]
On a side note... @cryptocracy what if you removed the torch from your logo and just had the flame? I feel it would be much stronger that way.. Something like this..

![souq](https://user-images.githubusercontent.com/1711854/31775139-c5f34daa-b4b5-11e7-8d04-318dec20b75f.png)

**Comment by guylepage3** [comment]
i’d even get rid of the blue now that i look at it..

![souq](https://user-images.githubusercontent.com/1711854/31775412-8d0925c2-b4b6-11e7-9fb7-59431b40522c.png)

**Comment by cryptocracy** [comment]
Ok I've cleaned it up some and resized it to the 512 x 512
![512x512](https://user-images.githubusercontent.com/5354826/31799703-95f1d0e6-b4f0-11e7-83e3-21e17731d4e6.png)

**Comment by pstan26** [comment]
Great! Can't wait to get it added.

**Comment by cryptocracy** [comment]
> Great! Can't wait to get it added.

Me too!

**Comment by pstan26** [comment]
Ping

**Comment by pstan26** [comment]
K cryotocracy updated his site and it looks nice, think we’re ready to add to the app store

**Comment by guylepage3** [comment]
@cryptocracy can i get your logo in 512 x 512 size?

**Comment by cryptocracy** [comment]
@guylepage3 
https://user-images.githubusercontent.com/5354826/31799703-95f1d0e6-b4f0-11e7-83e3-21e17731d4e6.png

**Comment by guylepage3** [comment]
Thank you sir. 👍

**Comment by guylepage3** [comment]
complete
