### ISSUE TITLE
Support for adding arbitrary accounts to Blockstack IDs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#938]
Presently, we limited the addition of social accounts to these types:

```
const accountTypes = [
  'twitter',
  'facebook',
  'linkedIn',
  'github',
  'instagram',
  'hackerNews',
  'bitcoin',
  'ethereum',
  'pgp',
  'ssh'
]
```

There are many service accounts - many widely used - that don't fit into these types. Wechat & Weibo
 are a couple of these that come to mind.

---
Additionally, the ability to add arbitrary account-identitfier pairs to the Blockstack ID's profile file allows developers of apps to make user's public app data opt-in discoverable by other users (users of that app or other apps) before we formalized this through multi-reader storage.

Apps could instruct users to manually add a custom account to their profile if they want their data to be accessible by other users of the app.

This makes multi-reader minimal viable product (MVP) apps possible with no other changes to our app platform.

Imagine alice.id and bob.id are using an app. Alice wants to see what Bob has shared in the app. She enters bob's username bob.id and the app performs the following process to find bob's data on the app.

1. It resolves `bob.id`'s profile.json file.
2. It searches through the list of accounts for the key it recognizes
3. It retrieves the value for that key which should be a URL point the the file written by bob's instance of the app.
4. It fetches the file at that URL and decode the data bob's app has stored in it.

Tagging @bodymindarts on this.

**Comment by larrysalibra** [comment]
Also tagging @shea256 and @yknl

**Comment by larrysalibra** [comment]
We've shipped multi-reader storage. I recall @yknl also added a feature for arbitrary accounts - did this ship @yknl ?

**Comment by yknl** [comment]
There's a pull request open for this change https://github.com/blockstack/blockstack-browser/pull/1104
Since we've implemented a different version of multi-reader storage, we may want to make some changes to the way we implemented this feature.
