### ISSUE TITLE
add a background image for the .dmg window

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#940]
Currently some users don't know what to do after they click on the .dmg. Many people don't know that they are supposed to drag the icon into the applications folder. This may seem obvious to developers but it's not obvious to many.

The solution here is to include a background image that indicates that the user has to drag the icon. This could be an arrow. Example incoming.

**Comment by shea256** [comment]
@larrysalibra @yknl tagging you on this.

**Comment by shea256** [comment]
![](http://operationproject.com/wp-content/uploads/2008/08/firefox-dmg.png)

**Comment by larrysalibra** [comment]
Related issue with instructions on how to implement this -> https://github.com/blockstack/blockstack-browser/issues/357
