### ISSUE TITLE
Transfer from Onename option

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#946]

**Comment by larrysalibra** [comment]
<img width="463" alt="screen shot 2017-10-23 at 10 58 48 pm" src="https://user-images.githubusercontent.com/597182/31896219-c931f492-b845-11e7-9b82-8117f0665408.png">
<img width="779" alt="screen shot 2017-10-23 at 10 59 38 pm" src="https://user-images.githubusercontent.com/597182/31896256-e2acc97e-b845-11e7-8c56-0c749db94e57.png">

**Comment by shea256** [comment]
@larrysalibra Can we close this issue? Has this been implemented?
