### ISSUE TITLE
[Question] Is the `npm` command required?

### ISSUE THREAD

**Issue by echosa** [blockstack/blockstack-browser#947]
I'm new to Blockstack, trying it out for the first time. The instructions say to download the desktop app _and_ clone the repo and run via `npm`. Is this necessary? I did that the first couple of times, but it didn't seem necessary. Right now, I only have the .app running (macOS) and Blockstack seems to still mostly be working fine (a bit slow, some pages/assets don't seem to load, but I imagine that's unrelated).

I also noticed that the npm command seems to force Chrome (hard-coded?) while the running .app correctly uses my default browser (Firefox Nightly, currently). So that was a bit confusing, as well, and part of the reason I decided to try not running `npm`.

I guess I'm just generally looking for clarification on using the Blockstack browser as a user, not so much a dev. If there's a better place for this than a GitHub issue, I'll be happy to ask there and close this issue.

**Comment by cwackerfuss-rl** [comment]
I'm not a blockstack developer, but I believe I can help.

If you're just running the Blockstack browser and not helping build it, you don't need to run the npm commands. Simply download your OS's package from this screen: https://github.com/blockstack/blockstack-browser/releases?mp=macos

That should be the only thing you have to do to install Blockstack on your machine!

**Comment by echosa** [comment]
Ah, cool. Thanks! That's what I was thinking, but wasn't sure. It also threw me for a loop that the "browser" is really just a menu icon that opens a tab in your default web browser, rather than being a full separate browser app itself, like TorBrowser and similar.

**Comment by cwackerfuss-rl** [comment]
@echosa Actually some folks on Twitter were just having that conversation today. @muneeb-ali was explaining that they can actually run the Blockstack services as a standalone browser (and DID in earlier iterations), but to facilitate easier adoption while it's still growing, Blockstack just runs in existing browsers.

**Comment by echosa** [comment]
Oh, cool. That's fair enough. Thanks for the answers! I'll close this issue now.
