### ISSUE TITLE
can the navbar be sticky?

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#951]
@guylepage3 @yknl Wanted to get your perspective on this.

This issue never really came up for me until we added a few more apps that pushed us to the point where the page height extended beyond the window height, requiring scrolling.

Seems like the navbar should stay fixed. Would be more intuitive.

**Comment by guylepage3** [comment]
@shea256 that's a very good point. 

Two other options

1. One alternative to a sticky nav is a hovering "Back to top" arrow button that we could place in the bottom right corner that appears only once the user has scrolled 50% of the initial viewport.
1. The other option, which is something I would rather execute, is a bottom sticky navbar that slides up from the bottom of the viewport as the user scrolls past 100% of the initial viewport.

Maybe @yknl has some alternatives to these.

**Comment by yknl** [comment]
I think a fixed top nav bar would work. We can add a border/shadow to the bar that appears when the scrolling offset is >0. We can mock this up to see how it will look. 

> One alternative to a sticky nav is a hovering "Back to top" arrow button that we could place in the bottom right corner that appears only once the user has scrolled 50% of the initial viewport.

Personally, I never found "Back to top" buttons very useful. It's the same amount of effort to click on the button as it is to hit the "Home" key on the keyboard. Plus having an always visible nav bar adds more context to the view.

> The other option, which is something I would rather execute, is a bottom sticky navbar that slides up from the bottom of the viewport as the user scrolls past 100% of the initial viewport.

This could be confusing, I think we should stick to just one nav bar, either fixed at the bottom or at the top.

**Comment by yknl** [comment]
A sticky nav bar was implemented

**Comment by guylepage3** [comment]
applied the `fixed-top` class as well as margin-top where needed.

See https://github.com/blockstack/blockstack-browser/commit/31caac80d67978db8aba1d84424ff0783ae12490
