### ISSUE TITLE
Add support for self-hosted gaia hubs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#953]
Places we'll need to modify:

* the transfer from onename link will need to load the gaiahub base url
* the advanced on-boarding screen
* storage settings screen

**Comment by shea256** [comment]
We could do something like:

- "Use hosted storage"
- "Self-host storage"

Would ideally like something that makes people have more of an aha moment with regards to owning their own data.

I have another idea with regards to this.

We don't ask users about their storage choice, but then once they're in the app we bug them to host their own Gaia node, which they can do on their own time.

Essentially, we indicate that the desired experience is self-hosting a Gaia node, but that we provide a temporary default option to help you get on-boarded.

Trying to think of other ways to frame this that make it clear that this is still a bring-your-own-storage network.

**Comment by larrysalibra** [comment]
As a quick change to the confusion of clicking on buttons that aren't enabled, i made this change:
<img width="903" alt="screen shot 2017-10-26 at 7 33 42 pm" src="https://user-images.githubusercontent.com/597182/32051335-cd10b380-ba86-11e7-8666-0cdd50bbc207.png">

**Comment by billxinli** [comment]
I assume this is still in progress.

As the "Connect Self-Hosted Storage"  and "URL for Gaia connection" are not working

<img width="768" alt="screen shot 2018-04-18 at 9 59 59 am" src="https://user-images.githubusercontent.com/1641464/38936831-bb5e43e0-42ef-11e8-9a9e-1745ea76e3df.png">
<img width="441" alt="screen shot 2018-04-18 at 9 59 52 am" src="https://user-images.githubusercontent.com/1641464/38936818-aaccffa8-42ef-11e8-8ef4-0bf9a53f76e3.png">
