### ISSUE TITLE
ask the user why they signed up for Blockstack at some point during the on-boarding process

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#957]
This is important to capture so we can get key insights about our users.

It can be surprising how useful and insightful this info can be.

**Comment by guylepage3** [comment]
Great idea to add a customer feedback pop-up. But this should be done a day or two after they've signed up. Something similar to the "Rate this App" iOS popup that we see on all apps. But this would be for the browser instead of apps.
