### ISSUE TITLE
Add transit encryption to application session JWT

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#958]
There's private information encoded in the JWT, which _should_ be encrypted using a transit key.

This shouldn't require any changes on the `blockstack-core` side (the jsonschema for the app session request should remain the same), but from the looks of it, will require updates of both the browser and `blockstack.js`

**Comment by larrysalibra** [comment]
Here's the issue for blockstack.js https://github.com/blockstack/blockstack.js/issues/276

**Comment by kantai** [comment]
This is implemented in the `feature/transit-encryption` branches of `blockstack.js` and `blockstack-browser`

It performs a hardcoded version check on the authentication request's payload. I've tested this with both browser and the todos application using the new `blockstack.js` -- I still need to test the other two configurations:

1. Browser with new features, auth request from old todos
2. Old browser, auth request from new todos

**Comment by kantai** [comment]
Tested with the three relevant configurations now -- authentication and storage work in all the cases.

**Comment by dominictarr** [comment]
there is also coreSession tokens - https://github.com/blockstack/blockstack.js/blob/master/src/auth/authSession.js#L35 this should really be done the same way as this, although having core never see the keys and just broadcast a transaction created in the app would be even better.
