### ISSUE TITLE
Insufficient and differing pricing shown when registering an ID

### ISSUE THREAD

**Issue by chadyj** [blockstack/blockstack-browser#961]
When registering an ID there are 2 different prices mentioned, which can cause user confusion. The price is also too low and can cause new users to transfer insufficient funds to their Blockstack wallet.

For example, when an ID is available the price is shown as `0.001331.`

![screen shot 2017-10-25 at 6 33 46 pm](https://user-images.githubusercontent.com/116099/32026630-3062cfec-b9b3-11e7-88b1-36b6aff38711.png)

However, after the ID is confirmed the price changes to `0.001`.

![screen shot 2017-10-25 at 6 36 32 pm](https://user-images.githubusercontent.com/116099/32026731-8d66f632-b9b3-11e7-93c6-93daa81259c4.png)

Different prices can cause user confusion, but worst is that if the wallet has `0.001` (as specified) then the transaction will silently fail because there is insufficient bitcoin.  

The console shows `ERROR profiles/store/registration/actions.js: register failed.
Address XXX does not have enough balance (need 133091, have 100000).`, but [no error is reported to the user](https://github.com/blockstack/blockstack-browser/issues/962).

On Slack [Larry caught the issue:](https://blockstack.slack.com/archives/C074LC7RC/p1508962373000370) `we were supposed to be rounding up to 0.002 but instead we were rounding to nearest`. 

This would prevent the problem as new users will transfer enough bitcoin, but I'd also suggest that  only 1 price be shown throughout the flow instead of 2 currently shown.

MacOS 10.13 and Browser version 0.18.3.

**Comment by larrysalibra** [comment]
@chadyj We fixed some rounding issues in a recent update. Let me know if you're still seeing this problem!
