### ISSUE TITLE
Add an edit icon (pencil) next to the profile image in the ID view

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#964]

**Comment by yknl** [comment]
This kind of breaks the design a little bit
![image](https://user-images.githubusercontent.com/29081231/32040652-90487870-b9ff-11e7-862b-57276ebd3f73.png)

**Comment by shea256** [comment]
What if clicking on the image opens a modal that has an edit button under the current image?

**Comment by shea256** [comment]
Also here's another example of this being done:

<img width="238" alt="screen shot 2017-10-26 at 3 44 26 am" src="https://user-images.githubusercontent.com/994646/32040832-0c850174-ba00-11e7-9b99-1766e1e06700.png">

**Comment by yknl** [comment]
Added a button to the photo modal
![image](https://user-images.githubusercontent.com/29081231/32041787-677bc83a-ba03-11e7-83c0-2572b135f58c.png)

**Comment by larrysalibra** [comment]
this shipped
