### ISSUE TITLE
suggestion to improve the copy of the email sign up screen

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#969]
Update the copy to simply:

```
Enter your email address:

Email address
[             ]

<Continue>
```

From this:

<img width="431" alt="screen shot 2017-10-26 at 12 47 43 pm" src="https://user-images.githubusercontent.com/994646/32065877-ffeffada-ba4b-11e7-8d2e-0a07635cd871.png">

**Comment by larrysalibra** [comment]
<img width="440" alt="screen shot 2017-10-30 at 7 12 10 pm" src="https://user-images.githubusercontent.com/597182/32168123-449c3e66-bda6-11e7-8ee3-e74cc568d663.png">

**Comment by larrysalibra** [comment]
Added the opt in to email list from #920

**Comment by larrysalibra** [comment]
Shipping this in v0.19.1 - please open a new issue if needs to change again.
