### ISSUE TITLE
Add in a full local proof checking system with a cache

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#97]

**Comment by larrysalibra** [comment]
I'm almost done with a `blockstack-proofs-js` library. That implements this. Will finish it up next week.

@shea256 do you want to register the `blockstack-proofs` npm package name?

**Comment by shea256** [comment]
Awesome! Why don't you just register it and add me as a collaborator?

**Comment by shea256** [comment]
Also, want to push it here? https://github.com/blockstack/blockstack-proofs-js

You should have access.

**Comment by shea256** [comment]
@larrysalibra You finished this one right?

**Comment by larrysalibra** [comment]
@shea256 left this issue open because still missing the caching part.

**Comment by shea256** [comment]
@larrysalibra OK do you think the cache is necessary for now? We could of course split this up into two issues and push the cache off.

**Comment by larrysalibra** [comment]
Moved local cache to issue #135
