### ISSUE TITLE
Github Verification Issue

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-browser#974]
Hey @yknl my github gist verification is not going through... 🤔

**Comment by yknl** [comment]
I will take a look, what's your Blockstack ID?

**Comment by GinaAbrams** [comment]
Thanks! ID is abramsgina

**Comment by yknl** [comment]
Looks like it went through:
https://explorer.blockstack.org/name/abramsgina.id

Are you seeing something different on the browser?

**Comment by GinaAbrams** [comment]
yes this is what I see: 
<img width="846" alt="screen shot 2017-10-27 at 11 56 48 am" src="https://user-images.githubusercontent.com/30627583/32113325-f4d04ebc-bb0d-11e7-84bf-6caece4b9f77.png">

**Comment by yknl** [comment]
@GinaAbrams can you take a screenshot of the browser console log after clicking on the IDs page?

**Comment by GinaAbrams** [comment]
Sure thing 
<img width="922" alt="screen shot 2017-10-27 at 1 39 46 pm" src="https://user-images.githubusercontent.com/30627583/32117459-6d944b4c-bb1c-11e7-800a-96cda4d51e56.png">

**Comment by yknl** [comment]
Fixed this issue in https://github.com/blockstack/blockstack.js/commit/12a996896dd0d2909cfef324543cce87d704d19f
