### ISSUE TITLE
move the "transfer username from onename" option into the name registration window

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#977]
Move this:

<img width="308" alt="screen shot 2017-10-27 at 4 47 23 pm" src="https://user-images.githubusercontent.com/994646/32124654-8ff4431c-bb36-11e7-9428-209d0394da3c.png">

So that it's an option in this window:

<img width="644" alt="screen shot 2017-10-27 at 4 47 32 pm" src="https://user-images.githubusercontent.com/994646/32124659-929710cc-bb36-11e7-8372-7ab58b73dbd0.png">

**Comment by rsolvang** [comment]
I just downloaded the "installer" for Linux and have followed the instructions on how to transfer my ID (https://blockstack.org/transfer-from-onename-to-browser.pdf). However, the three dots under "ID > More" is missing, so I can't complete the transfer. Considering I just got an email telling me I only have 11 days to do the transfer, this is a serious bug!

**Comment by kantai** [comment]
Hi @rsolvang -- sorry, the version of the script that was uploaded pointed to older versions of the Blockstack Browser. The script is now updated. You can re-download the script and run

```./Blockstack-for-Linux.sh pull```

to update your images.

**Comment by rsolvang** [comment]
Thanks for a quick reply, @kantai, it worked :+1:

**Comment by yknl** [comment]
Agreed, will prioritize this change.

**Comment by yknl** [comment]
Added transfer name from onename as option
![image](https://user-images.githubusercontent.com/29081231/32476548-04536974-c346-11e7-9a5b-83d47d8ba7b4.png)

**Comment by yknl** [comment]
![image](https://user-images.githubusercontent.com/29081231/32524649-caddd928-c3ee-11e7-8ed4-39b78981463d.png)
