### ISSUE TITLE
Re-enable validation of profile tokens (and integrate the new elliptic curve library to do so)

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#98]

**Comment by shea256** [comment]
@larrysalibra you took care of this one right?

**Comment by shea256** [comment]
@larrysalibra Just realized that this is still a pending issue.

Here's the line of code where this feature was temporarily disabled because of a compilation error with one of the libraries:

https://github.com/blockstack/blockstack-browser/blob/master/app/js/utils/profile-utils.js#L95

We can try re-enabling this feature and seeing if it goes through.

I'm moving this issue to the next milestone (v0.3.0).

**Comment by larrysalibra** [comment]
Seems to work!

I asked a related question that I had while testing this here -> https://forum.blockstack.org/t/why-do-profiles-have-decoded-tokens/659?u=larry

We should add tests for this (and many other things). Opened an issue to track that-> #161
