### ISSUE TITLE
Update primary navbar and be sticky

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#983]
Reference: [Browser UI/UX Oct 27](https://paper.dropbox.com/doc/Browser-UIUX-Oct-27-6S7A6BjsQNFBtOQ0DUCge)

----

- Navbar to become similar to http://instagram.com
      - ~~`max-width: 960px;`~~ to `max-width: 960px;`
      - Home button on left
      - ID, Wallet, Settings on the right

<img width="1440" alt="screenshot 2017-10-31 06 22 29" src="https://user-images.githubusercontent.com/1711854/32219250-ea5257fc-be03-11e7-8b56-34dc82554927.png">

**Comment by guylepage3** [comment]
changed the `max-width` to `960px` to match our Blockstack Design System Grid Container component.

```
/*  7. Grid containers */
/* blockstack.org uses two widths;
   1. Full container width 960px
   2. content width 760px
*/
.container-xs{max-width:440px;}
.container-sm{max-width:540px;}
.container-md{max-width:720px;}
.container-primary{max-width:760px;}
.container-lg{max-width:960px;}
.container-xl{max-width:1140px;}
```

**Comment by guylepage3** [comment]
https://github.com/blockstack/blockstack-browser/issues/983#issuecomment-340721050

**Comment by guylepage3** [comment]
Discovered issue with `.container-fluid` class. [#1002: The global full width container class has max-width definition](https://github.com/blockstack/blockstack-browser/issues/1002)
