### ISSUE TITLE
Update secondary navbar to use buttons only

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#984]
Reference: [Token Sale Registration Problems - Nov 2, 2017](https://paper.dropbox.com/doc/Token-Sale-Registration-Problems-Nov-2-2017-zTiYwuwVpYXOSJjpyICtR)

**Issue:**
- Users are having issues finding the "Edit, Save" buttons.

**Solution:**
- Change the links from `btn-link`'s to `btn btn-outline-* btn-pill`'s
- Move the buttons to a more logical place at eye level to where the majority of the "profile" content resides.
- Remove redundancy of pencil icon edit profile links to allow for less clutter and more focus on the main items of the profile. ie. profile content, level, buttons, etc.

**Comment by guylepage3** [comment]
working on this now.

**Comment by guylepage3** [comment]
@larrysalibra @yknl @shea256 

What do you guys think about this layout? Please provide feedback.

<img width="981" alt="screenshot 2017-11-02 14 12 30" src="https://user-images.githubusercontent.com/1711854/32342792-e66ccb10-bfd7-11e7-974e-b44aa9d0299a.png">

**Comment by yknl** [comment]
I think that makes it a lot more visible! We should go with this. One small thing is that we don't use the round pill buttons anywhere else, should we keep it to more rectangular buttons for consistency?

**Comment by guylepage3** [comment]
There are two new places that we are using "pill" buttons...
1. for items that are of less significance or that are not meant to be clickable. ie. the trust level bar.
2. for buttons that are of quaternary significance where we outline the button.

**Comment by guylepage3** [comment]
Trust level right now looks like a button. I keep trying to click on it.

**Comment by yknl** [comment]
Maybe the trust level bar should just be text or at most with an outline

**Comment by guylepage3** [comment]
complete.
