### ISSUE TITLE
Update the account deletion process so that it doesn’t require a password and local storage is cleared but make sure to include a confirmation

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#989]

**Comment by larrysalibra** [comment]
<img width="565" alt="screen shot 2017-10-31 at 6 04 32 pm" src="https://user-images.githubusercontent.com/597182/32219005-b51390d8-be67-11e7-956c-dd5f4e415a69.png">
<img width="627" alt="screen shot 2017-10-31 at 6 04 48 pm" src="https://user-images.githubusercontent.com/597182/32219012-b7445478-be67-11e7-9064-3c162a7e3bb8.png">

<img width="496" alt="screen shot 2017-10-31 at 6 18 46 pm" src="https://user-images.githubusercontent.com/597182/32219085-fbb5ddf2-be67-11e7-9901-ab6c0efe5f5b.png">
