### ISSUE TITLE
Add in a profile completion bar that is shown only on the profile view

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#990]

**Comment by larrysalibra** [comment]
<img width="818" alt="screen shot 2017-10-31 at 5 09 04 pm" src="https://user-images.githubusercontent.com/597182/32215898-4ac75aec-be5e-11e7-9b30-a92c567b3683.png">

Awesome work on this @yknl - are we calling these profiles or Blockstack IDs? Or is this your Blockstack ID profile? :-D

**Comment by guylepage3** [comment]
Very nice! :)

**Comment by yknl** [comment]
I think ID completion sound a little weird. Open to any suggestions.

**Comment by larrysalibra** [comment]
How about removing "Profile Completion" and just keeping the sentence below the progress bar?

"Complete your Blockstack ID by adding..."

**Comment by larrysalibra** [comment]
<img width="839" alt="screen shot 2017-10-31 at 10 48 52 pm" src="https://user-images.githubusercontent.com/597182/32230371-fc552828-be8d-11e7-8fe6-6f34309cb9ad.png">

**Comment by guylepage3** [comment]
@larrysalibra @yknl we should have “active descriptions” for the profile completion bar
I’m never going to read that sentence below the progress bar

<img width="1438" alt="screenshot 2017-10-31 10 51 04" src="https://user-images.githubusercontent.com/1711854/32230761-3ebf2204-be2a-11e7-9c26-b567e1563a1c.png">

**Comment by larrysalibra** [comment]
Done and shipping in v0.19.1. 

@guylepage3 great suggestion! - can you open a new issue for the changes? We can address them in a future iteration.
