### ISSUE TITLE
Instagram verifications only work when I include "www."

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#994]
I tried verifying with the following URL but the verification wasn't picked up:

https://instagram.com/p/Ba5AGfoFi7U/

Then I changed it to the web URL and it worked:

https://www.instagram.com/p/Ba5AGfoFi7U/

**Comment by yknl** [comment]
This is an issue with blockstack.js, we will need to add the instagram.com domain to the list of allowed domains.
