### ISSUE TITLE
Facebook verification throws a strange error

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#995]
<img width="397" alt="screen shot 2017-10-30 at 7 36 17 pm" src="https://user-images.githubusercontent.com/994646/32200764-aa92c4b2-bda9-11e7-9cd8-f422c6aba622.png">

**Comment by pstan26** [comment]
<img width="893" alt="screen shot 2017-10-31 at 12 41 50 am" src="https://user-images.githubusercontent.com/5605552/32207756-6daf7f56-bdd4-11e7-921a-423375bedb63.png">

safe to put my strange error in here too? :-)

**Comment by yknl** [comment]
Looks like it's because we haven't published the Facebook app.

**Comment by shea256** [comment]
@yknl OK what do we need to do with regards to the Facebook app? Is there something you're waiting on me for there?

**Comment by jdkanani** [comment]
@yknl @shea256 Just switch mode in settings. You don't have to wait for any approval from Facebook.

**Comment by yknl** [comment]
Thanks for the tip @jdkanani, turns out it was both switching the app out of development and a missing link param in the feed dialog url.

**Comment by jdkanani** [comment]
@yknl Great.
