### ISSUE TITLE
My photo upload isn't working for all ID's not owned by the first address

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#998]
<img width="376" alt="screen shot 2017-10-30 at 8 55 58 pm" src="https://user-images.githubusercontent.com/994646/32202707-e12368be-bdb4-11e7-9e0b-63bf6b08bdd1.png">

**Comment by shea256** [comment]
OK so I tried this again and it went through.

@kantai maybe it was a server issue?

**Comment by larrysalibra** [comment]
@shea256 the console log screenshot you provided is a problem verifying your facebook proof - the proof url doesn't exist - don't see anything in the log about uploading photos.

If you have this problem again, can you provide more of the log?

To save a console log in Chrome:
Right click and choose "save as"
<img width="343" alt="screen shot 2017-10-31 at 6 07 26 pm" src="https://user-images.githubusercontent.com/597182/32218647-95d309d4-be66-11e7-81ac-003984e1bdae.png">

In Safari, select the log entries you'd like to export and "save selection"

<img width="398" alt="screen shot 2017-10-31 at 6 08 34 pm" src="https://user-images.githubusercontent.com/597182/32218674-a98e0398-be66-11e7-8990-19f418b79bce.png">

In Firefox, you'll have to select the log entries and copy them to a text editor to save the log.

**Comment by larrysalibra** [comment]
Please re-open if you're still having this issue!
