### ISSUE TITLE
Error while verifying twitter account

### ISSUE THREAD

**Issue by jdkanani** [blockstack/blockstack-browser#999]
I am getting following JS error for twitter verification:

<img width="744" alt="screen shot 2017-10-31 at 10 32 42 am" src="https://user-images.githubusercontent.com/1692593/32208939-b93b33c8-be2b-11e7-9bcd-26fab28acc08.png">

**Comment by yknl** [comment]
@jdkanani you may have included the "@" in the twitter username field. You should leave that out for the verification to work properly.

**Comment by jdkanani** [comment]
Ah! fixed.

**Comment by shea256** [comment]
Tagging this as a related issue: #972
